// ES Module exports for ai_review roast format
export const titles = [
  "Incident Report: Frozen Prompt",
  "Failed to compile: Layers",
  "Failed to compile: Query",
  "Model conflict detected",
  "Incident Report: Dense Layers",
  "The Inference tragedy",
  "Incident Report: Pre-trained Dataset",
  "Failed to compile: Prompt",
  "The Prompt tragedy",
  "Dataset conflict detected",
  "Dataset Not Found",
  "Failed to compile: Weight",
  "Incident Report: Pre-trained Tensor",
  "Overfit GPU Error",
  "NullPointerDatasetException",
  "Absolute Pre-trained architecture",
  "Query Not Found",
  "Absolute Dense architecture",
  "Absolute Biased architecture",
  "Incident Report: Biased GPU",
  "Critical GPU failure",
  "Absolute Overfit architecture",
  "Incident Report: Dense Query",
  "Absolute Hallucinated architecture",
  "Dense Tensor Error",
  "Critical Inference failure",
  "The Tensor tragedy",
  "Hallucinated Weight Error",
  "Dense Weight Error",
  "Biased GPU Loop",
  "Frozen Tensor Loop",
  "The GPU tragedy",
  "Incident Report: Dense Inference",
  "The Query tragedy",
  "The Dataset tragedy",
  "Critical Prompt failure",
  "Failed to compile: Tensor",
  "NullPointerTokenException",
  "Incident Report: Biased Model",
  "Token conflict detected",
  "Frozen Dataset Error",
  "Biased Dataset Error",
  "Overfit Dataset Error",
  "Critical Dataset failure",
  "Cold-start Weight Error",
  "Critical Tensor failure",
  "Critical Query failure",
  "The Layers tragedy",
  "Incident Report: Hallucinated Tensor",
  "Hallucinated Inference Loop",
  "Incident Report: Cold-start GPU",
  "Model Not Found",
  "GPU conflict detected",
  "Incident Report: Dense Weight",
  "Critical Layers failure",
  "Layers Not Found",
  "NullPointerPromptException",
  "Absolute Frozen architecture",
  "Incident Report: Overfit Token",
  "Hallucinated Model Loop",
  "Weight Not Found",
  "NullPointerQueryException",
  "Frozen Query Error",
  "Dense Dataset Loop",
  "Incident Report: Dense Model",
  "NullPointerTensorException",
  "Incident Report: Cold-start Weight",
  "Incident Report: Pre-trained GPU",
  "Dense Inference Loop",
  "Failed to compile: Model",
  "NullPointerLayersException",
  "Absolute Custom architecture",
  "Frozen Inference Loop",
  "Incident Report: Dense Dataset",
  "Custom Query Error",
  "Layers conflict detected",
  "Custom Inference Loop",
  "Token Not Found",
  "Pre-trained GPU Error",
  "Failed to compile: GPU",
  "Incident Report: Custom Model",
  "Cold-start Layers Loop",
  "Critical Token failure",
  "The Weight tragedy",
  "Failed to compile: Dataset",
  "Frozen Model Loop",
  "Custom Model Error",
  "Biased Query Error",
  "Frozen Weight Error",
  "Incident Report: Overfit Query",
  "Cold-start Query Error",
  "Frozen Prompt Loop",
  "Frozen Prompt Error",
  "Custom Prompt Error",
  "Incident Report: Hallucinated Prompt",
  "NullPointerGPUException",
  "Custom Prompt Loop",
  "Frozen Layers Loop",
  "Pre-trained Layers Error",
  "Biased Inference Loop"
];

export const openings = [
  "Warning: System flagged an attempt to loaded frozen layers on a single local GPU.",
  "Warning: System flagged an attempt to trained weight model halting token generation.",
  "Alert: The candidate spent three months trying to compiled prompt dataset halting token generation.",
  "Scanning candidate profile for custom prompts...",
  "We checked the history and found a custom weight log.",
  "We checked the history and found a overfit weight log.",
  "Alert: The candidate spent three months trying to triggered cold-start delay exhausting system VRAM.",
  "Warning: System flagged an attempt to compiled prompt dataset returning generic outputs.",
  "The team has initiated audit for the candidate's token setup.",
  "Alert: The candidate spent three months trying to ran inference query halting token generation.",
  "Initial evaluation shows the developer decided to compiled prompt dataset exhausting system VRAM.",
  "We checked the history and found a custom tensor log.",
  "Recruiters reported a case of frozen token design.",
  "We checked the history and found a frozen dataset log.",
  "Recruiters reported a case of biased layers design.",
  "Scanning candidate profile for cold-start querys...",
  "Recruiters reported a case of custom GPU design.",
  "Recruiters reported a case of cold-start dataset design.",
  "Recruiters reported a case of dense weight design.",
  "We checked the history and found a cold-start weight log.",
  "Recruiters reported a case of pre-trained inference design.",
  "A review was filed regarding a biased inference.",
  "A review was filed regarding a hallucinated dataset.",
  "A review was filed regarding a cold-start prompt.",
  "A review was filed regarding a cold-start GPU.",
  "We checked the history and found a frozen tensor log.",
  "Alert: The candidate spent three months trying to trained weight model on a single local GPU.",
  "Recruiters reported a case of pre-trained token design.",
  "Alert: The candidate spent three months trying to loaded frozen layers exhausting system VRAM.",
  "Initial evaluation shows the developer decided to loaded frozen layers on a single local GPU.",
  "Alert: The candidate spent three months trying to compiled prompt dataset with high perplexity.",
  "A review was filed regarding a overfit tensor.",
  "Warning: System flagged an attempt to compiled prompt dataset on a single local GPU.",
  "A review was filed regarding a biased GPU.",
  "Scanning candidate profile for dense inferences...",
  "Initial evaluation shows the developer decided to compiled prompt dataset returning generic outputs.",
  "Warning: System flagged an attempt to compiled prompt dataset with high perplexity.",
  "Recruiters reported a case of overfit query design.",
  "Recruiters reported a case of dense dataset design.",
  "Scanning candidate profile for overfit prompts...",
  "Scanning candidate profile for hallucinated GPUs...",
  "Warning: System flagged an attempt to ran inference query halting token generation.",
  "Alert: The candidate spent three months trying to compiled prompt dataset exhausting system VRAM.",
  "Initial evaluation shows the developer decided to loaded frozen layers halting token generation.",
  "Initial evaluation shows the developer decided to trained weight model exhausting system VRAM.",
  "Initial evaluation shows the developer decided to ran inference query exhausting system VRAM.",
  "Recruiters reported a case of hallucinated GPU design.",
  "A review was filed regarding a hallucinated layers.",
  "We checked the history and found a overfit GPU log.",
  "A review was filed regarding a frozen model.",
  "We checked the history and found a frozen query log.",
  "Initial evaluation shows the developer decided to ran inference query returning generic outputs.",
  "Recruiters reported a case of hallucinated prompt design.",
  "Scanning candidate profile for frozen models...",
  "Warning: System flagged an attempt to trained weight model with high perplexity.",
  "We checked the history and found a biased GPU log.",
  "A review was filed regarding a dense layers.",
  "Warning: System flagged an attempt to ran inference query on a single local GPU.",
  "Initial evaluation shows the developer decided to loaded frozen layers with high perplexity.",
  "Initial evaluation shows the developer decided to triggered cold-start delay exhausting system VRAM.",
  "We checked the history and found a biased tensor log.",
  "A review was filed regarding a biased model.",
  "A review was filed regarding a dense dataset.",
  "Initial evaluation shows the developer decided to ran inference query on a single local GPU.",
  "Alert: The candidate spent three months trying to trained weight model with high perplexity.",
  "Scanning candidate profile for custom inferences...",
  "Initial evaluation shows the developer decided to compiled prompt dataset on a single local GPU.",
  "Alert: The candidate spent three months trying to loaded frozen layers returning generic outputs.",
  "Warning: System flagged an attempt to loaded frozen layers halting token generation.",
  "Alert: The candidate spent three months trying to trained weight model exhausting system VRAM.",
  "Initial evaluation shows the developer decided to triggered cold-start delay returning generic outputs.",
  "We checked the history and found a overfit model log.",
  "Alert: The candidate spent three months trying to triggered cold-start delay on a single local GPU.",
  "We checked the history and found a custom token log.",
  "Recruiters reported a case of overfit inference design.",
  "A review was filed regarding a biased dataset.",
  "Alert: The candidate spent three months trying to loaded frozen layers on a single local GPU.",
  "A review was filed regarding a overfit model.",
  "Scanning candidate profile for frozen tokens...",
  "Recruiters reported a case of hallucinated query design.",
  "Scanning candidate profile for hallucinated tensors...",
  "A review was filed regarding a pre-trained model.",
  "Alert: The candidate spent three months trying to compiled prompt dataset on a single local GPU.",
  "Recruiters reported a case of pre-trained model design.",
  "Recruiters reported a case of hallucinated layers design.",
  "Warning: System flagged an attempt to trained weight model exhausting system VRAM.",
  "Scanning candidate profile for biased prompts...",
  "A review was filed regarding a pre-trained weight.",
  "Initial evaluation shows the developer decided to triggered cold-start delay with high perplexity.",
  "Recruiters reported a case of dense prompt design."
];

export const findings = [
  "Obtained {{certification}} which apparently teaches how to ran inference query returning generic outputs.",
  "{{education}} is listed, but they still managed to deploy a frozen GPU to production.",
  "The candidate claims {{framework}} experience, but their repository is just a dense clone that has been abandoned.",
  "Obtained {{certification}} which apparently teaches how to loaded frozen layers halting token generation.",
  "{{candidateName}} has spent three weeks optimizing a model while completely ignoring {{missingSection}}.",
  "{{github}} contains more overfit GPUs than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a dense layers.",
  "{{education}} is listed, but they still managed to deploy a cold-start prompt to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ran inference query exhausting system VRAM.",
  "{{achievement}} was highlighted, but the git logs show they only managed to trained weight model on a single local GPU.",
  "Failed to configure {{project}} because {{candidateName}} decided to ran inference query on a single local GPU.",
  "{{achievement}} was highlighted, but the git logs show they only managed to loaded frozen layers returning generic outputs.",
  "Listed {{skill}} as a primary competency, but the evidence points to a cold-start tensor.",
  "Failed to configure {{project}} because {{candidateName}} decided to compiled prompt dataset exhausting system VRAM.",
  "Listed {{skill}} as a primary competency, but the evidence points to a custom layers.",
  "A security audit on {{github}} detected a plain-text database password inside a biased tensor.",
  "For {{experience}}, the primary contribution was writing a hallucinated config for a tensor.",
  "{{education}} is listed, but they still managed to deploy a hallucinated inference to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to trained weight model halting token generation.",
  "For {{experience}}, the primary contribution was writing a overfit config for a dataset.",
  "Obtained {{certification}} which apparently teaches how to triggered cold-start delay exhausting system VRAM.",
  "While debugging {{project}}, we found a custom logic loop related to {{language}} features.",
  "{{github}} contains more biased datasets than original code.",
  "{{github}} contains more frozen prompts than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to loaded frozen layers exhausting system VRAM.",
  "{{github}} contains more overfit datasets than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ran inference query exhausting system VRAM.",
  "Failed to configure {{project}} because {{candidateName}} decided to loaded frozen layers with high perplexity.",
  "While debugging {{project}}, we found a pre-trained logic loop related to {{language}} features.",
  "Obtained {{certification}} which apparently teaches how to loaded frozen layers on a single local GPU.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ran inference query with high perplexity.",
  "{{github}} contains more custom tensors than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to loaded frozen layers with high perplexity.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to triggered cold-start delay on a single local GPU.",
  "Failed to configure {{project}} because {{candidateName}} decided to loaded frozen layers on a single local GPU.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ran inference query halting token generation.",
  "{{github}} contains more pre-trained layerss than original code.",
  "For {{experience}}, the primary contribution was writing a biased config for a GPU.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to loaded frozen layers on a single local GPU.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to triggered cold-start delay exhausting system VRAM.",
  "Obtained {{certification}} which apparently teaches how to ran inference query exhausting system VRAM.",
  "For {{experience}}, the primary contribution was writing a pre-trained config for a dataset.",
  "Listed {{skill}} as a primary competency, but the evidence points to a biased weight.",
  "Failed to configure {{project}} because {{candidateName}} decided to compiled prompt dataset halting token generation.",
  "Obtained {{certification}} which apparently teaches how to loaded frozen layers returning generic outputs.",
  "{{education}} is listed, but they still managed to deploy a overfit query to production.",
  "{{education}} is listed, but they still managed to deploy a custom dataset to production.",
  "A security audit on {{github}} detected a plain-text database password inside a overfit inference.",
  "{{achievement}} was highlighted, but the git logs show they only managed to compiled prompt dataset exhausting system VRAM.",
  "A security audit on {{github}} detected a plain-text database password inside a cold-start GPU.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to trained weight model returning generic outputs.",
  "{{achievement}} was highlighted, but the git logs show they only managed to trained weight model exhausting system VRAM.",
  "Failed to configure {{project}} because {{candidateName}} decided to trained weight model returning generic outputs.",
  "Failed to configure {{project}} because {{candidateName}} decided to loaded frozen layers returning generic outputs.",
  "{{achievement}} was highlighted, but the git logs show they only managed to triggered cold-start delay returning generic outputs.",
  "A security audit on {{github}} detected a plain-text database password inside a hallucinated token.",
  "Listed {{skill}} as a primary competency, but the evidence points to a overfit query.",
  "{{github}} contains more biased prompts than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ran inference query halting token generation.",
  "Listed {{skill}} as a primary competency, but the evidence points to a dense dataset.",
  "For {{experience}}, the primary contribution was writing a frozen config for a inference.",
  "{{github}} contains more custom models than original code.",
  "{{github}} contains more frozen inferences than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to compiled prompt dataset returning generic outputs.",
  "{{github}} contains more frozen weights than original code.",
  "{{github}} contains more frozen tokens than original code.",
  "For {{experience}}, the primary contribution was writing a cold-start config for a model.",
  "{{github}} contains more biased weights than original code.",
  "{{github}} contains more custom prompts than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to triggered cold-start delay on a single local GPU.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ran inference query returning generic outputs.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to trained weight model on a single local GPU.",
  "{{github}} contains more dense GPUs than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a frozen GPU.",
  "A security audit on {{github}} detected a plain-text database password inside a pre-trained weight.",
  "{{github}} contains more biased models than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to loaded frozen layers exhausting system VRAM.",
  "{{achievement}} was highlighted, but the git logs show they only managed to loaded frozen layers halting token generation.",
  "Failed to configure {{project}} because {{candidateName}} decided to trained weight model exhausting system VRAM.",
  "While debugging {{project}}, we found a cold-start logic loop related to {{language}} features.",
  "{{education}} is listed, but they still managed to deploy a pre-trained inference to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to trained weight model with high perplexity.",
  "Obtained {{certification}} which apparently teaches how to compiled prompt dataset with high perplexity.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to trained weight model exhausting system VRAM.",
  "{{github}} contains more frozen GPUs than original code.",
  "{{github}} contains more cold-start tensors than original code.",
  "Obtained {{certification}} which apparently teaches how to triggered cold-start delay on a single local GPU.",
  "{{education}} is listed, but they still managed to deploy a dense tensor to production.",
  "Failed to configure {{project}} because {{candidateName}} decided to triggered cold-start delay halting token generation.",
  "A security audit on {{github}} detected a plain-text database password inside a custom query.",
  "{{achievement}} was highlighted, but the git logs show they only managed to triggered cold-start delay halting token generation.",
  "{{achievement}} was highlighted, but the git logs show they only managed to loaded frozen layers on a single local GPU.",
  "Listed {{skill}} as a primary competency, but the evidence points to a hallucinated tensor.",
  "For {{experience}}, the primary contribution was writing a custom config for a token.",
  "Obtained {{certification}} which apparently teaches how to trained weight model halting token generation.",
  "Obtained {{certification}} which apparently teaches how to ran inference query with high perplexity.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to triggered cold-start delay with high perplexity.",
  "Obtained {{certification}} which apparently teaches how to compiled prompt dataset halting token generation.",
  "{{github}} contains more hallucinated datasets than original code.",
  "Obtained {{certification}} which apparently teaches how to trained weight model with high perplexity.",
  "{{github}} contains more overfit querys than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to triggered cold-start delay returning generic outputs.",
  "Obtained {{certification}} which apparently teaches how to triggered cold-start delay halting token generation.",
  "Failed to configure {{project}} because {{candidateName}} decided to triggered cold-start delay on a single local GPU.",
  "Obtained {{certification}} which apparently teaches how to loaded frozen layers with high perplexity.",
  "Failed to configure {{project}} because {{candidateName}} decided to triggered cold-start delay with high perplexity.",
  "{{github}} contains more frozen layerss than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to triggered cold-start delay halting token generation.",
  "Obtained {{certification}} which apparently teaches how to compiled prompt dataset returning generic outputs.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ran inference query on a single local GPU.",
  "Obtained {{certification}} which apparently teaches how to triggered cold-start delay with high perplexity.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ran inference query returning generic outputs.",
  "{{github}} contains more frozen datasets than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to trained weight model halting token generation.",
  "Failed to configure {{project}} because {{candidateName}} decided to triggered cold-start delay exhausting system VRAM.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to compiled prompt dataset with high perplexity."
];

export const punchlines = [
  "Even Stack Overflow has marked this GPU as off-topic.",
  "A junior developer looked at the query and immediately went to touch grass.",
  "It did not optimize our process, but it did make the laptop fan spin like a jet engine.",
  "The documentation was so empty, I had to use it as a virtual sketchbook.",
  "The only thing memory-safe about this setup is that nobody has ever tried to run it.",
  "The compiler requested emotional support after reading the cold-start code.",
  "We would deploy it to production, but our SRE team deserves to sleep at night.",
  "The compiler requested emotional support after reading the dense code.",
  "Legend says this custom tensor is still running on localhost.",
  "Legend says this pre-trained tensor is still running on localhost.",
  "Legend says this hallucinated layers is still running on localhost.",
  "Legend says this overfit token is still running on localhost.",
  "The compiler requested emotional support after reading the pre-trained code.",
  "Legend says this custom token is still running on localhost.",
  "Legend says this custom dataset is still running on localhost.",
  "Legend says this dense weight is still running on localhost.",
  "Legend says this biased prompt is still running on localhost.",
  "Legend says this frozen token is still running on localhost.",
  "Legend says this custom model is still running on localhost.",
  "Legend says this cold-start layers is still running on localhost.",
  "Legend says this frozen dataset is still running on localhost.",
  "Legend says this overfit query is still running on localhost.",
  "Legend says this dense dataset is still running on localhost.",
  "Legend says this frozen tensor is still running on localhost.",
  "Legend says this overfit inference is still running on localhost.",
  "Legend says this biased model is still running on localhost.",
  "Legend says this hallucinated prompt is still running on localhost.",
  "Legend says this biased token is still running on localhost.",
  "Legend says this biased weight is still running on localhost.",
  "Legend says this overfit tensor is still running on localhost.",
  "Legend says this custom GPU is still running on localhost.",
  "Legend says this custom prompt is still running on localhost.",
  "Legend says this frozen model is still running on localhost.",
  "Legend says this overfit layers is still running on localhost.",
  "Legend says this frozen inference is still running on localhost.",
  "Legend says this frozen query is still running on localhost.",
  "Legend says this dense tensor is still running on localhost.",
  "Legend says this dense model is still running on localhost.",
  "Legend says this hallucinated dataset is still running on localhost.",
  "Legend says this hallucinated inference is still running on localhost.",
  "Legend says this dense layers is still running on localhost.",
  "Legend says this custom inference is still running on localhost.",
  "Legend says this dense inference is still running on localhost.",
  "Legend says this frozen prompt is still running on localhost.",
  "Legend says this dense token is still running on localhost.",
  "Legend says this biased dataset is still running on localhost.",
  "Legend says this frozen layers is still running on localhost.",
  "Legend says this biased GPU is still running on localhost.",
  "Legend says this hallucinated token is still running on localhost.",
  "Legend says this hallucinated query is still running on localhost.",
  "Legend says this dense query is still running on localhost.",
  "Legend says this frozen weight is still running on localhost.",
  "Legend says this custom weight is still running on localhost.",
  "Legend says this overfit dataset is still running on localhost.",
  "Legend says this overfit model is still running on localhost.",
  "Legend says this frozen GPU is still running on localhost.",
  "This is a classic example of a cold-start query disaster.",
  "This is a classic example of a biased dataset disaster.",
  "This is a classic example of a pre-trained prompt disaster.",
  "This is a classic example of a hallucinated query disaster.",
  "This is a classic example of a dense tensor disaster.",
  "This is a classic example of a frozen GPU disaster.",
  "This is a classic example of a custom prompt disaster.",
  "This is a classic example of a dense inference disaster.",
  "This is a classic example of a custom weight disaster.",
  "This is a classic example of a overfit inference disaster.",
  "This is a classic example of a cold-start token disaster.",
  "This is a classic example of a cold-start layers disaster.",
  "This is a classic example of a frozen token disaster.",
  "This is a classic example of a frozen layers disaster.",
  "This is a classic example of a hallucinated prompt disaster.",
  "This is a classic example of a hallucinated layers disaster.",
  "This is a classic example of a hallucinated token disaster.",
  "This is a classic example of a biased inference disaster.",
  "This is a classic example of a dense query disaster.",
  "This is a classic example of a pre-trained query disaster.",
  "This is a classic example of a custom GPU disaster.",
  "This is a classic example of a custom query disaster.",
  "This is a classic example of a frozen prompt disaster.",
  "This is a classic example of a hallucinated tensor disaster.",
  "This is a classic example of a frozen weight disaster.",
  "This is a classic example of a pre-trained dataset disaster.",
  "This is a classic example of a biased prompt disaster.",
  "This is a classic example of a biased layers disaster.",
  "This is a classic example of a cold-start weight disaster.",
  "This is a classic example of a overfit layers disaster.",
  "This is a classic example of a biased GPU disaster.",
  "This is a classic example of a cold-start tensor disaster.",
  "This is a classic example of a dense GPU disaster.",
  "This is a classic example of a cold-start inference disaster.",
  "This is a classic example of a overfit dataset disaster.",
  "This is a classic example of a frozen query disaster."
];

export const verdicts = [
  "PR triggered cold-start delay due to frozen implementation.",
  "Needs more commits and fewer explanations.",
  "Ship blocked by overfit check failures.",
  "PR trained weight model due to cold-start implementation.",
  "Return after touching actual production servers.",
  "Ship blocked by custom check failures.",
  "PR compiled prompt dataset due to biased implementation.",
  "Ship blocked by dense check failures.",
  "PR ran inference query due to custom implementation.",
  "Rejected on first principles of token organization.",
  "Closed as dense duplicate.",
  "Verdict: Prompt is completely unmergeable.",
  "Closed as overfit duplicate.",
  "Verdict: GPU is completely unmergeable.",
  "Verdict: Query is completely unmergeable.",
  "Request changes on the biased model.",
  "Rejected on first principles of dataset organization.",
  "Ship blocked by cold-start check failures.",
  "Request changes on the cold-start dataset.",
  "PR loaded frozen layers due to hallucinated implementation.",
  "Ship blocked by frozen check failures.",
  "Request changes on the biased dataset.",
  "Ship blocked by pre-trained check failures.",
  "PR ran inference query due to frozen implementation.",
  "Verdict: Layers is completely unmergeable.",
  "Rejected on first principles of inference organization.",
  "Ship blocked by hallucinated check failures.",
  "Ship blocked by biased check failures.",
  "Request changes on the frozen prompt.",
  "PR ran inference query due to dense implementation.",
  "PR triggered cold-start delay due to hallucinated implementation.",
  "PR compiled prompt dataset due to pre-trained implementation.",
  "Closed as pre-trained duplicate.",
  "Rejected on first principles of GPU organization.",
  "Closed as custom duplicate.",
  "Rejected on first principles of tensor organization.",
  "PR ran inference query due to hallucinated implementation.",
  "Request changes on the cold-start token.",
  "Rejected on first principles of weight organization.",
  "Closed as hallucinated duplicate.",
  "Request changes on the custom inference.",
  "Request changes on the dense GPU.",
  "PR compiled prompt dataset due to hallucinated implementation.",
  "Closed as biased duplicate.",
  "PR loaded frozen layers due to biased implementation.",
  "Closed as cold-start duplicate.",
  "Rejected on first principles of prompt organization.",
  "Verdict: Model is completely unmergeable.",
  "Request changes on the cold-start GPU.",
  "Verdict: Token is completely unmergeable.",
  "Verdict: Weight is completely unmergeable.",
  "Verdict: Tensor is completely unmergeable.",
  "PR loaded frozen layers due to custom implementation.",
  "Request changes on the pre-trained GPU.",
  "Request changes on the hallucinated prompt.",
  "Request changes on the hallucinated layers.",
  "Closed as frozen duplicate.",
  "PR trained weight model due to biased implementation.",
  "PR ran inference query due to overfit implementation.",
  "PR triggered cold-start delay due to custom implementation.",
  "PR loaded frozen layers due to cold-start implementation.",
  "Request changes on the pre-trained model.",
  "Request changes on the dense prompt.",
  "PR triggered cold-start delay due to overfit implementation.",
  "Request changes on the hallucinated query.",
  "PR loaded frozen layers due to dense implementation.",
  "Request changes on the overfit GPU.",
  "PR compiled prompt dataset due to dense implementation.",
  "Rejected on first principles of query organization.",
  "Request changes on the frozen weight.",
  "Rejected on first principles of layers organization.",
  "Request changes on the hallucinated dataset.",
  "PR trained weight model due to pre-trained implementation.",
  "PR compiled prompt dataset due to overfit implementation.",
  "PR compiled prompt dataset due to custom implementation.",
  "Verdict: Dataset is completely unmergeable.",
  "Rejected on first principles of model organization.",
  "PR trained weight model due to custom implementation.",
  "Request changes on the hallucinated tensor.",
  "Request changes on the hallucinated GPU.",
  "PR triggered cold-start delay due to biased implementation.",
  "Request changes on the frozen query.",
  "Request changes on the overfit prompt.",
  "PR trained weight model due to frozen implementation.",
  "Request changes on the cold-start prompt.",
  "Request changes on the hallucinated model.",
  "PR trained weight model due to overfit implementation.",
  "PR triggered cold-start delay due to dense implementation.",
  "Request changes on the dense tensor.",
  "PR ran inference query due to biased implementation.",
  "PR compiled prompt dataset due to cold-start implementation.",
  "Request changes on the hallucinated inference.",
  "Request changes on the custom GPU.",
  "Request changes on the custom dataset.",
  "Request changes on the dense inference.",
  "Request changes on the frozen GPU.",
  "Request changes on the cold-start model.",
  "Request changes on the custom token.",
  "Request changes on the cold-start weight."
];

export const easterEggs = [
  "FBI Investigation: Suspect was found deploying unencrypted overfit GPUs.",
  "Matrix Glitch: You copy-pasted a template and now the server believes it is a real founder.",
  "FBI Investigation: Suspect was found deploying unencrypted biased datasets.",
  "Dark Web Resume Auction: Current bid is $0.00, and the buyer is requesting a refund.",
  "Steam Achievement Unlocked: Successfully crashed a hello-world app on a $10,000 server.",
  "FBI Investigation: Suspect was found deploying unencrypted frozen weights.",
  "Gordon Ramsay Meltdown: 'This model is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This token is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This prompt is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This inference is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted hallucinated inferences.",
  "Elon Musk Tweet: 'Just deleted the entire tensor pipeline, was completely useless.'",
  "NASA Alert: Space mission aborted due to a minor GPU parsing error.",
  "Gordon Ramsay Meltdown: 'This weight is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This layers is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted custom prompts.",
  "Gordon Ramsay Meltdown: 'This query is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This tensor is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted pre-trained layerss.",
  "FBI Investigation: Suspect was found deploying unencrypted cold-start datasets.",
  "Gordon Ramsay Meltdown: 'This GPU is raw! It's absolutely raw!'"
];
