// ES Module exports for amazon_review roast format
export const titles = [
  "Certificate Not Found",
  "Failed to compile: Refund",
  "Missing Manual Error",
  "Incident Report: Fake Certificate",
  "Incident Report: Generic Box",
  "Package Not Found",
  "Critical Refund failure",
  "Quality Not Found",
  "Missing Support Loop",
  "Bootleg Box Error",
  "Broken Support Loop",
  "Critical Quality failure",
  "Generic Refund Error",
  "Incident Report: Cheap Support",
  "The Refund tragedy",
  "Fake Package Error",
  "Failed to compile: Manual",
  "Bootleg Delivery Error",
  "Critical Manual failure",
  "Critical Package failure",
  "Broken Manual Error",
  "Delivery Not Found",
  "Critical Certificate failure",
  "NullPointerCertificateException",
  "Incident Report: Missing Delivery",
  "Critical Return failure",
  "NullPointerReturnException",
  "Critical Box failure",
  "The Delivery tragedy",
  "Generic Item Loop",
  "Manual Not Found",
  "Absolute Cheap architecture",
  "NullPointerManualException",
  "Missing Certificate Error",
  "Critical Delivery failure",
  "Fake Certificate Error",
  "Failed to compile: Delivery",
  "NullPointerBoxException",
  "Delivery conflict detected",
  "The Item tragedy",
  "Critical Support failure",
  "Incident Report: Bootleg Box",
  "Bootleg Certificate Error",
  "Absolute Broken architecture",
  "Box Not Found",
  "Generic Manual Error",
  "Incident Report: Cheap Manual",
  "Item Not Found",
  "Incident Report: Fake Delivery",
  "Incident Report: Broken Return",
  "Missing Refund Loop",
  "Failed to compile: Package",
  "NullPointerQualityException",
  "Faulty Return Loop",
  "Failed to compile: Quality",
  "The Return tragedy",
  "Broken Return Loop",
  "Incident Report: Fake Manual",
  "The Certificate tragedy",
  "Failed to compile: Item",
  "Box conflict detected",
  "Return conflict detected",
  "Absolute Faulty architecture",
  "Bootleg Package Error",
  "Absolute Missing architecture",
  "Cheap Package Loop",
  "Absolute Generic architecture",
  "Refund conflict detected",
  "Quality conflict detected",
  "NullPointerSupportException",
  "Cheap Certificate Loop",
  "Broken Refund Loop",
  "Support Not Found",
  "Package conflict detected",
  "Item conflict detected",
  "Absolute Certified architecture",
  "Absolute Bootleg architecture",
  "Incident Report: Missing Refund",
  "Missing Box Loop",
  "Missing Item Error",
  "Return Not Found",
  "Faulty Refund Error",
  "Incident Report: Certified Box",
  "Failed to compile: Support",
  "Certified Package Error",
  "Failed to compile: Return",
  "Incident Report: Bootleg Delivery",
  "NullPointerRefundException",
  "Incident Report: Fake Quality",
  "Fake Quality Error",
  "Certified Support Loop",
  "Incident Report: Faulty Box",
  "Incident Report: Missing Box",
  "Absolute Fake architecture",
  "NullPointerDeliveryException",
  "Broken Refund Error",
  "Critical Item failure",
  "Failed to compile: Box",
  "The Support tragedy",
  "Incident Report: Generic Package"
];

export const openings = [
  "The team has initiated audit for the candidate's item setup.",
  "Alert: The candidate spent three months trying to returned broken package after one hour use.",
  "Alert: The candidate spent three months trying to failed quality test requesting full refund.",
  "A review was filed regarding a missing refund.",
  "We checked the history and found a certified package log.",
  "Initial evaluation shows the developer decided to requested support refund in damaged envelope.",
  "Warning: System flagged an attempt to ordered cheap item requesting full refund.",
  "Initial evaluation shows the developer decided to failed quality test in damaged envelope.",
  "A review was filed regarding a bootleg package.",
  "Initial evaluation shows the developer decided to requested support refund requesting full refund.",
  "We checked the history and found a missing return log.",
  "Initial evaluation shows the developer decided to failed quality test requesting full refund.",
  "Warning: System flagged an attempt to failed quality test in damaged envelope.",
  "Alert: The candidate spent three months trying to requested support refund immediately on arrival.",
  "Warning: System flagged an attempt to failed quality test requesting full refund.",
  "Alert: The candidate spent three months trying to returned broken package immediately on arrival.",
  "We checked the history and found a fake manual log.",
  "We checked the history and found a faulty manual log.",
  "A review was filed regarding a missing package.",
  "Scanning candidate profile for generic packages...",
  "Scanning candidate profile for fake items...",
  "Alert: The candidate spent three months trying to ordered cheap item requesting full refund.",
  "We checked the history and found a broken certificate log.",
  "Alert: The candidate spent three months trying to returned broken package with missing manual.",
  "A review was filed regarding a generic certificate.",
  "A review was filed regarding a bootleg delivery.",
  "Warning: System flagged an attempt to unboxed fake certificate after one hour use.",
  "A review was filed regarding a bootleg support.",
  "Initial evaluation shows the developer decided to returned broken package in damaged envelope.",
  "We checked the history and found a certified quality log.",
  "Recruiters reported a case of missing support design.",
  "Scanning candidate profile for missing boxs...",
  "Scanning candidate profile for faulty items...",
  "We checked the history and found a cheap delivery log.",
  "A review was filed regarding a fake delivery.",
  "A review was filed regarding a broken support.",
  "Alert: The candidate spent three months trying to requested support refund after one hour use.",
  "Initial evaluation shows the developer decided to ordered cheap item after one hour use.",
  "Warning: System flagged an attempt to requested support refund after one hour use.",
  "Warning: System flagged an attempt to ordered cheap item immediately on arrival.",
  "We checked the history and found a bootleg package log.",
  "Recruiters reported a case of broken manual design.",
  "Recruiters reported a case of certified support design.",
  "Warning: System flagged an attempt to returned broken package after one hour use.",
  "Scanning candidate profile for faulty qualitys...",
  "A review was filed regarding a broken box.",
  "Scanning candidate profile for broken packages...",
  "Scanning candidate profile for faulty boxs...",
  "Scanning candidate profile for certified qualitys...",
  "Alert: The candidate spent three months trying to returned broken package in damaged envelope.",
  "Alert: The candidate spent three months trying to failed quality test immediately on arrival.",
  "Alert: The candidate spent three months trying to ordered cheap item with missing manual.",
  "Warning: System flagged an attempt to ordered cheap item in damaged envelope.",
  "We checked the history and found a fake refund log.",
  "We checked the history and found a faulty package log.",
  "Scanning candidate profile for certified manuals...",
  "Warning: System flagged an attempt to unboxed fake certificate immediately on arrival.",
  "Recruiters reported a case of generic manual design.",
  "Alert: The candidate spent three months trying to unboxed fake certificate after one hour use.",
  "We checked the history and found a certified item log.",
  "Initial evaluation shows the developer decided to requested support refund with missing manual.",
  "Warning: System flagged an attempt to unboxed fake certificate with missing manual.",
  "Initial evaluation shows the developer decided to ordered cheap item with missing manual.",
  "We checked the history and found a missing package log.",
  "Warning: System flagged an attempt to failed quality test immediately on arrival.",
  "Warning: System flagged an attempt to requested support refund with missing manual.",
  "We checked the history and found a certified manual log.",
  "A review was filed regarding a bootleg return.",
  "Recruiters reported a case of faulty box design.",
  "Initial evaluation shows the developer decided to returned broken package after one hour use.",
  "Scanning candidate profile for cheap qualitys...",
  "Scanning candidate profile for broken qualitys...",
  "We checked the history and found a certified box log.",
  "Recruiters reported a case of bootleg manual design.",
  "We checked the history and found a fake certificate log.",
  "Initial evaluation shows the developer decided to requested support refund after one hour use.",
  "Recruiters reported a case of missing refund design.",
  "Alert: The candidate spent three months trying to requested support refund requesting full refund.",
  "Recruiters reported a case of faulty support design.",
  "We checked the history and found a missing item log.",
  "Recruiters reported a case of certified package design.",
  "Scanning candidate profile for generic items...",
  "Scanning candidate profile for broken refunds...",
  "Scanning candidate profile for bootleg boxs...",
  "Initial evaluation shows the developer decided to unboxed fake certificate after one hour use.",
  "A review was filed regarding a broken delivery.",
  "Scanning candidate profile for faulty certificates...",
  "Initial evaluation shows the developer decided to unboxed fake certificate in damaged envelope.",
  "Warning: System flagged an attempt to requested support refund in damaged envelope.",
  "Initial evaluation shows the developer decided to unboxed fake certificate immediately on arrival.",
  "Initial evaluation shows the developer decided to failed quality test after one hour use.",
  "Alert: The candidate spent three months trying to unboxed fake certificate in damaged envelope."
];

export const findings = [
  "{{education}} is listed, but they still managed to deploy a certified refund to production.",
  "{{education}} is listed, but they still managed to deploy a cheap box to production.",
  "{{github}} contains more fake qualitys than original code.",
  "{{candidateName}} has spent three weeks optimizing a certificate while completely ignoring {{missingSection}}.",
  "{{achievement}} was highlighted, but the git logs show they only managed to unboxed fake certificate after one hour use.",
  "Failed to configure {{project}} because {{candidateName}} decided to requested support refund in damaged envelope.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to returned broken package after one hour use.",
  "A security audit on {{github}} detected a plain-text database password inside a missing manual.",
  "The candidate claims {{framework}} experience, but their repository is just a broken clone that has been abandoned.",
  "{{achievement}} was highlighted, but the git logs show they only managed to failed quality test requesting full refund.",
  "{{achievement}} was highlighted, but the git logs show they only managed to returned broken package with missing manual.",
  "While debugging {{project}}, we found a generic logic loop related to {{language}} features.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ordered cheap item in damaged envelope.",
  "{{github}} contains more fake boxs than original code.",
  "Obtained {{certification}} which apparently teaches how to failed quality test immediately on arrival.",
  "{{education}} is listed, but they still managed to deploy a missing quality to production.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to returned broken package immediately on arrival.",
  "Listed {{skill}} as a primary competency, but the evidence points to a bootleg refund.",
  "A security audit on {{github}} detected a plain-text database password inside a faulty package.",
  "Listed {{skill}} as a primary competency, but the evidence points to a broken item.",
  "Obtained {{certification}} which apparently teaches how to ordered cheap item after one hour use.",
  "For {{experience}}, the primary contribution was writing a faulty config for a manual.",
  "For {{experience}}, the primary contribution was writing a bootleg config for a item.",
  "For {{experience}}, the primary contribution was writing a fake config for a delivery.",
  "A security audit on {{github}} detected a plain-text database password inside a broken quality.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to requested support refund in damaged envelope.",
  "{{github}} contains more missing boxs than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to returned broken package in damaged envelope.",
  "Listed {{skill}} as a primary competency, but the evidence points to a missing support.",
  "Obtained {{certification}} which apparently teaches how to returned broken package with missing manual.",
  "A security audit on {{github}} detected a plain-text database password inside a bootleg delivery.",
  "For {{experience}}, the primary contribution was writing a generic config for a certificate.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ordered cheap item requesting full refund.",
  "{{github}} contains more faulty boxs than original code.",
  "Listed {{skill}} as a primary competency, but the evidence points to a certified package.",
  "Listed {{skill}} as a primary competency, but the evidence points to a faulty manual.",
  "Obtained {{certification}} which apparently teaches how to failed quality test with missing manual.",
  "Listed {{skill}} as a primary competency, but the evidence points to a cheap return.",
  "{{achievement}} was highlighted, but the git logs show they only managed to returned broken package in damaged envelope.",
  "Obtained {{certification}} which apparently teaches how to unboxed fake certificate after one hour use.",
  "Obtained {{certification}} which apparently teaches how to unboxed fake certificate with missing manual.",
  "A security audit on {{github}} detected a plain-text database password inside a generic certificate.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to failed quality test with missing manual.",
  "For {{experience}}, the primary contribution was writing a certified config for a support.",
  "Failed to configure {{project}} because {{candidateName}} decided to returned broken package requesting full refund.",
  "For {{experience}}, the primary contribution was writing a missing config for a quality.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ordered cheap item requesting full refund.",
  "{{education}} is listed, but they still managed to deploy a broken certificate to production.",
  "Failed to configure {{project}} because {{candidateName}} decided to unboxed fake certificate immediately on arrival.",
  "{{github}} contains more generic manuals than original code.",
  "{{github}} contains more bootleg packages than original code.",
  "For {{experience}}, the primary contribution was writing a cheap config for a return.",
  "Obtained {{certification}} which apparently teaches how to ordered cheap item in damaged envelope.",
  "{{achievement}} was highlighted, but the git logs show they only managed to requested support refund after one hour use.",
  "{{github}} contains more broken deliverys than original code.",
  "Obtained {{certification}} which apparently teaches how to ordered cheap item immediately on arrival.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ordered cheap item with missing manual.",
  "{{achievement}} was highlighted, but the git logs show they only managed to returned broken package immediately on arrival.",
  "{{achievement}} was highlighted, but the git logs show they only managed to unboxed fake certificate requesting full refund.",
  "Obtained {{certification}} which apparently teaches how to returned broken package immediately on arrival.",
  "{{achievement}} was highlighted, but the git logs show they only managed to failed quality test immediately on arrival.",
  "{{achievement}} was highlighted, but the git logs show they only managed to returned broken package after one hour use.",
  "For {{experience}}, the primary contribution was writing a broken config for a refund.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to unboxed fake certificate requesting full refund.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to requested support refund with missing manual.",
  "Failed to configure {{project}} because {{candidateName}} decided to requested support refund requesting full refund.",
  "{{education}} is listed, but they still managed to deploy a generic manual to production.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ordered cheap item with missing manual.",
  "Failed to configure {{project}} because {{candidateName}} decided to failed quality test after one hour use.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to requested support refund immediately on arrival.",
  "Failed to configure {{project}} because {{candidateName}} decided to unboxed fake certificate requesting full refund.",
  "Failed to configure {{project}} because {{candidateName}} decided to failed quality test with missing manual.",
  "Obtained {{certification}} which apparently teaches how to requested support refund immediately on arrival.",
  "{{github}} contains more missing returns than original code.",
  "{{github}} contains more bootleg refunds than original code.",
  "{{education}} is listed, but they still managed to deploy a faulty return to production.",
  "{{github}} contains more generic deliverys than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to failed quality test requesting full refund.",
  "{{github}} contains more bootleg qualitys than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to unboxed fake certificate immediately on arrival.",
  "{{github}} contains more cheap refunds than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to returned broken package after one hour use.",
  "Failed to configure {{project}} because {{candidateName}} decided to returned broken package immediately on arrival.",
  "Obtained {{certification}} which apparently teaches how to requested support refund requesting full refund.",
  "Obtained {{certification}} which apparently teaches how to failed quality test requesting full refund.",
  "{{github}} contains more certified refunds than original code.",
  "{{github}} contains more fake refunds than original code.",
  "Obtained {{certification}} which apparently teaches how to returned broken package after one hour use.",
  "Obtained {{certification}} which apparently teaches how to unboxed fake certificate requesting full refund.",
  "Obtained {{certification}} which apparently teaches how to unboxed fake certificate in damaged envelope.",
  "Obtained {{certification}} which apparently teaches how to returned broken package in damaged envelope.",
  "{{achievement}} was highlighted, but the git logs show they only managed to unboxed fake certificate with missing manual.",
  "Failed to configure {{project}} because {{candidateName}} decided to returned broken package in damaged envelope.",
  "{{github}} contains more broken qualitys than original code.",
  "{{education}} is listed, but they still managed to deploy a fake item to production.",
  "Failed to configure {{project}} because {{candidateName}} decided to requested support refund immediately on arrival.",
  "Obtained {{certification}} which apparently teaches how to returned broken package requesting full refund.",
  "{{github}} contains more generic qualitys than original code.",
  "{{github}} contains more missing refunds than original code.",
  "{{github}} contains more faulty certificates than original code.",
  "Listed {{skill}} as a primary competency, but the evidence points to a generic certificate.",
  "Obtained {{certification}} which apparently teaches how to requested support refund with missing manual.",
  "{{github}} contains more generic boxs than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to failed quality test in damaged envelope.",
  "{{github}} contains more missing manuals than original code.",
  "{{github}} contains more faulty items than original code.",
  "{{github}} contains more fake items than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to ordered cheap item with missing manual.",
  "{{github}} contains more faulty qualitys than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to requested support refund requesting full refund.",
  "{{github}} contains more missing qualitys than original code.",
  "{{education}} is listed, but they still managed to deploy a bootleg package to production.",
  "{{github}} contains more generic certificates than original code."
];

export const punchlines = [
  "It did not optimize our process, but it did make the laptop fan spin like a jet engine.",
  "A junior developer looked at the box and immediately went to touch grass.",
  "The documentation was so empty, I had to use it as a virtual sketchbook.",
  "The only thing memory-safe about this setup is that nobody has ever tried to run it.",
  "The compiler requested emotional support after reading the missing code.",
  "Legend says this missing package is still running on localhost.",
  "Legend says this missing quality is still running on localhost.",
  "Even Stack Overflow has marked this return as off-topic.",
  "We would deploy it to production, but our SRE team deserves to sleep at night.",
  "Legend says this cheap delivery is still running on localhost.",
  "Legend says this fake box is still running on localhost.",
  "Legend says this fake quality is still running on localhost.",
  "Legend says this missing delivery is still running on localhost.",
  "Legend says this broken refund is still running on localhost.",
  "Legend says this certified manual is still running on localhost.",
  "Legend says this broken return is still running on localhost.",
  "Legend says this generic quality is still running on localhost.",
  "Legend says this broken delivery is still running on localhost.",
  "Legend says this faulty support is still running on localhost.",
  "Legend says this cheap quality is still running on localhost.",
  "Legend says this faulty package is still running on localhost.",
  "Legend says this bootleg certificate is still running on localhost.",
  "Legend says this fake item is still running on localhost.",
  "Legend says this fake delivery is still running on localhost.",
  "Legend says this faulty delivery is still running on localhost.",
  "Legend says this broken box is still running on localhost.",
  "Legend says this fake refund is still running on localhost.",
  "Legend says this cheap package is still running on localhost.",
  "Legend says this certified refund is still running on localhost.",
  "Legend says this fake package is still running on localhost.",
  "Legend says this missing manual is still running on localhost.",
  "Legend says this bootleg return is still running on localhost.",
  "Legend says this missing item is still running on localhost.",
  "Legend says this certified support is still running on localhost.",
  "Legend says this generic delivery is still running on localhost.",
  "Legend says this generic refund is still running on localhost.",
  "Legend says this faulty quality is still running on localhost.",
  "Legend says this certified quality is still running on localhost.",
  "Legend says this cheap refund is still running on localhost.",
  "Legend says this missing return is still running on localhost.",
  "Legend says this cheap box is still running on localhost.",
  "Legend says this cheap manual is still running on localhost.",
  "Legend says this fake certificate is still running on localhost.",
  "Legend says this missing refund is still running on localhost.",
  "Legend says this faulty manual is still running on localhost.",
  "Legend says this certified package is still running on localhost.",
  "Legend says this fake return is still running on localhost.",
  "Legend says this bootleg quality is still running on localhost.",
  "Legend says this bootleg delivery is still running on localhost.",
  "Legend says this bootleg item is still running on localhost.",
  "Legend says this missing support is still running on localhost.",
  "Legend says this generic certificate is still running on localhost.",
  "Legend says this generic box is still running on localhost.",
  "Legend says this certified item is still running on localhost.",
  "Legend says this bootleg package is still running on localhost.",
  "Legend says this faulty refund is still running on localhost.",
  "Legend says this broken certificate is still running on localhost.",
  "Legend says this faulty box is still running on localhost.",
  "Legend says this certified box is still running on localhost.",
  "Legend says this faulty return is still running on localhost.",
  "Legend says this generic support is still running on localhost.",
  "Legend says this generic item is still running on localhost.",
  "Legend says this generic return is still running on localhost.",
  "Legend says this missing box is still running on localhost.",
  "Legend says this cheap certificate is still running on localhost.",
  "Legend says this bootleg manual is still running on localhost.",
  "Legend says this cheap support is still running on localhost.",
  "Legend says this certified certificate is still running on localhost.",
  "Legend says this fake support is still running on localhost.",
  "This is a classic example of a certified manual disaster.",
  "This is a classic example of a cheap return disaster.",
  "This is a classic example of a generic refund disaster.",
  "This is a classic example of a generic manual disaster.",
  "This is a classic example of a faulty refund disaster.",
  "This is a classic example of a cheap support disaster.",
  "This is a classic example of a certified box disaster.",
  "This is a classic example of a certified return disaster.",
  "This is a classic example of a faulty item disaster.",
  "This is a classic example of a generic quality disaster.",
  "This is a classic example of a faulty manual disaster.",
  "This is a classic example of a fake return disaster.",
  "This is a classic example of a bootleg delivery disaster.",
  "This is a classic example of a missing item disaster.",
  "This is a classic example of a bootleg item disaster.",
  "This is a classic example of a missing certificate disaster.",
  "This is a classic example of a faulty support disaster.",
  "This is a classic example of a fake box disaster.",
  "This is a classic example of a faulty return disaster.",
  "This is a classic example of a cheap box disaster.",
  "This is a classic example of a cheap delivery disaster.",
  "This is a classic example of a broken return disaster.",
  "This is a classic example of a bootleg manual disaster.",
  "This is a classic example of a generic return disaster.",
  "This is a classic example of a fake certificate disaster.",
  "This is a classic example of a faulty quality disaster.",
  "This is a classic example of a faulty delivery disaster.",
  "This is a classic example of a broken support disaster.",
  "This is a classic example of a generic package disaster.",
  "This is a classic example of a broken quality disaster.",
  "This is a classic example of a certified delivery disaster.",
  "This is a classic example of a missing box disaster.",
  "This is a classic example of a fake support disaster.",
  "This is a classic example of a broken package disaster.",
  "This is a classic example of a bootleg return disaster.",
  "This is a classic example of a generic item disaster.",
  "This is a classic example of a missing return disaster.",
  "This is a classic example of a certified item disaster.",
  "This is a classic example of a missing support disaster.",
  "This is a classic example of a broken manual disaster.",
  "This is a classic example of a bootleg certificate disaster."
];

export const verdicts = [
  "Closed as generic duplicate.",
  "Return after touching actual production servers.",
  "PR requested support refund due to certified implementation.",
  "Verdict: Certificate is completely unmergeable.",
  "Request changes on the certified package.",
  "Needs more commits and fewer explanations.",
  "Request changes on the cheap quality.",
  "Request changes on the bootleg package.",
  "Request changes on the certified box.",
  "Ship blocked by missing check failures.",
  "Request changes on the broken delivery.",
  "PR ordered cheap item due to missing implementation.",
  "Closed as certified duplicate.",
  "Rejected on first principles of box organization.",
  "PR unboxed fake certificate due to faulty implementation.",
  "Closed as fake duplicate.",
  "Ship blocked by broken check failures.",
  "PR ordered cheap item due to bootleg implementation.",
  "Rejected on first principles of support organization.",
  "Verdict: Box is completely unmergeable.",
  "Closed as cheap duplicate.",
  "Request changes on the certified return.",
  "Ship blocked by certified check failures.",
  "Ship blocked by faulty check failures.",
  "Closed as bootleg duplicate.",
  "Closed as broken duplicate.",
  "Rejected on first principles of quality organization.",
  "Request changes on the generic delivery.",
  "PR failed quality test due to cheap implementation.",
  "Rejected on first principles of manual organization.",
  "Ship blocked by cheap check failures.",
  "Request changes on the fake certificate.",
  "Request changes on the broken box.",
  "Closed as faulty duplicate.",
  "Request changes on the fake box.",
  "Rejected on first principles of return organization.",
  "Verdict: Quality is completely unmergeable.",
  "Request changes on the broken certificate.",
  "Ship blocked by generic check failures.",
  "Verdict: Return is completely unmergeable.",
  "PR unboxed fake certificate due to cheap implementation.",
  "PR ordered cheap item due to broken implementation.",
  "Request changes on the broken package.",
  "Rejected on first principles of package organization.",
  "Verdict: Manual is completely unmergeable.",
  "Request changes on the faulty support.",
  "PR requested support refund due to broken implementation.",
  "Request changes on the certified quality.",
  "Request changes on the fake support.",
  "Verdict: Package is completely unmergeable.",
  "Verdict: Support is completely unmergeable.",
  "Request changes on the broken return.",
  "Ship blocked by bootleg check failures.",
  "Request changes on the bootleg certificate.",
  "Rejected on first principles of refund organization.",
  "PR failed quality test due to generic implementation.",
  "Request changes on the cheap return.",
  "Closed as missing duplicate.",
  "Request changes on the bootleg item.",
  "Verdict: Refund is completely unmergeable.",
  "PR ordered cheap item due to faulty implementation.",
  "Request changes on the generic support.",
  "Rejected on first principles of certificate organization.",
  "PR requested support refund due to fake implementation.",
  "Verdict: Item is completely unmergeable.",
  "PR failed quality test due to broken implementation.",
  "PR returned broken package due to generic implementation.",
  "PR failed quality test due to certified implementation.",
  "Rejected on first principles of item organization.",
  "Request changes on the cheap box.",
  "PR returned broken package due to missing implementation.",
  "Request changes on the fake item.",
  "Ship blocked by fake check failures.",
  "Request changes on the faulty box.",
  "Request changes on the generic refund.",
  "Request changes on the bootleg box.",
  "Request changes on the bootleg support.",
  "Rejected on first principles of delivery organization.",
  "Request changes on the generic quality.",
  "Request changes on the cheap manual.",
  "Request changes on the faulty delivery.",
  "Request changes on the fake manual.",
  "Request changes on the generic package.",
  "PR failed quality test due to faulty implementation.",
  "Verdict: Delivery is completely unmergeable.",
  "PR requested support refund due to bootleg implementation.",
  "PR ordered cheap item due to fake implementation.",
  "PR failed quality test due to bootleg implementation.",
  "PR ordered cheap item due to certified implementation.",
  "PR unboxed fake certificate due to missing implementation.",
  "PR requested support refund due to missing implementation.",
  "Request changes on the cheap support.",
  "PR returned broken package due to certified implementation.",
  "Request changes on the missing refund.",
  "Request changes on the generic item.",
  "Request changes on the fake delivery.",
  "Request changes on the faulty manual.",
  "PR unboxed fake certificate due to bootleg implementation.",
  "PR unboxed fake certificate due to generic implementation."
];

export const easterEggs = [
  "Steam Achievement Unlocked: Successfully crashed a hello-world app on a $10,000 server.",
  "NASA Alert: Space mission aborted due to a minor support parsing error.",
  "FBI Investigation: Suspect was found deploying unencrypted certified supports.",
  "Dark Web Resume Auction: Current bid is $0.00, and the buyer is requesting a refund.",
  "FBI Investigation: Suspect was found deploying unencrypted broken boxs.",
  "Gordon Ramsay Meltdown: 'This delivery is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This support is raw! It's absolutely raw!'",
  "Elon Musk Tweet: 'Just deleted the entire refund pipeline, was completely useless.'",
  "Matrix Glitch: You copy-pasted a template and now the server believes it is a real founder.",
  "FBI Investigation: Suspect was found deploying unencrypted generic certificates.",
  "FBI Investigation: Suspect was found deploying unencrypted cheap qualitys.",
  "Gordon Ramsay Meltdown: 'This item is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This box is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted bootleg deliverys.",
  "Gordon Ramsay Meltdown: 'This certificate is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This package is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted faulty packages.",
  "Gordon Ramsay Meltdown: 'This return is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This manual is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted fake returns.",
  "Gordon Ramsay Meltdown: 'This quality is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted missing manuals."
];
