// ES Module exports for aws_bill roast format
export const titles = [
  "Critical Bill failure",
  "NullPointerHostException",
  "Support conflict detected",
  "NullPointerLambdaException",
  "The Bill tragedy",
  "Incident Report: Free-tier Account",
  "Incident Report: Massive Bill",
  "High-cost Support Error",
  "Ec2 conflict detected",
  "Bill conflict detected",
  "Critical Pricing failure",
  "Host conflict detected",
  "Serverless Usage Loop",
  "Failed to compile: Host",
  "Unused Bill Loop",
  "Host Not Found",
  "The Lambda tragedy",
  "Account conflict detected",
  "Critical Host failure",
  "Incident Report: Serverless S3",
  "The Support tragedy",
  "Bloated Bill Error",
  "Expensive Cost Error",
  "Absolute Free-tier architecture",
  "Cost Not Found",
  "Incident Report: Free-tier Bill",
  "Lambda Not Found",
  "Failed to compile: Bill",
  "The S3 tragedy",
  "Usage Not Found",
  "Unused Host Error",
  "Absolute Bloated architecture",
  "Incident Report: Expensive Support",
  "NullPointerUsageException",
  "Massive Lambda Error",
  "Incident Report: Bloated S3",
  "NullPointerBillException",
  "Expensive Usage Error",
  "NullPointerEc2Exception",
  "Free-tier Pricing Error",
  "Critical Ec2 failure",
  "Free-tier Ec2 Loop",
  "Critical Account failure",
  "Critical S3 failure",
  "NullPointerSupportException",
  "Account Not Found",
  "Cost conflict detected",
  "NullPointerCostException",
  "Incident Report: Serverless Bill",
  "Incident Report: Untracked Account",
  "Serverless Account Error",
  "Failed to compile: Lambda",
  "Absolute Untracked architecture",
  "Usage conflict detected",
  "Absolute Unused architecture",
  "Untracked S3 Error",
  "The Cost tragedy",
  "Unused Account Loop",
  "High-cost Bill Loop",
  "Massive Usage Error",
  "Unused S3 Loop",
  "Failed to compile: Account",
  "Incident Report: High-cost Ec2",
  "Absolute Serverless architecture",
  "The Pricing tragedy",
  "Incident Report: High-cost Account",
  "Bill Not Found",
  "Bloated Support Loop",
  "Bloated Lambda Loop",
  "Incident Report: Untracked Usage",
  "S3 Not Found",
  "Expensive S3 Loop",
  "Incident Report: Untracked Lambda",
  "Serverless Account Loop",
  "NullPointerPricingException",
  "Serverless Ec2 Loop",
  "Critical Support failure",
  "Critical Usage failure",
  "Free-tier Pricing Loop",
  "Untracked Cost Loop",
  "NullPointerS3Exception",
  "Failed to compile: Pricing",
  "NullPointerAccountException",
  "Bloated S3 Loop",
  "Expensive Cost Loop",
  "Support Not Found",
  "Incident Report: Free-tier Support",
  "Absolute High-cost architecture",
  "Massive Lambda Loop",
  "Absolute Expensive architecture",
  "Unused Bill Error",
  "The Host tragedy",
  "Incident Report: Free-tier Host",
  "Serverless Bill Error",
  "Untracked Usage Loop",
  "Massive Account Error",
  "Incident Report: Unused Account",
  "Bloated Bill Loop"
];

export const openings = [
  "A review was filed regarding a massive support.",
  "Alert: The candidate spent three months trying to billed serverless run on local test run.",
  "The team has initiated audit for the candidate's pricing setup.",
  "Scanning candidate profile for serverless supports...",
  "A review was filed regarding a high-cost cost.",
  "Recruiters reported a case of free-tier ec2 design.",
  "Initial evaluation shows the developer decided to hosted static page running unneeded containers.",
  "We checked the history and found a bloated lambda log.",
  "A review was filed regarding a massive ec2.",
  "Alert: The candidate spent three months trying to charged massive fee by total accident.",
  "A review was filed regarding a unused bill.",
  "Alert: The candidate spent three months trying to exceeded free-tier limits on local test run.",
  "Scanning candidate profile for bloated supports...",
  "Initial evaluation shows the developer decided to hosted static page by total accident.",
  "Warning: System flagged an attempt to hosted static page with $5000 charge.",
  "Initial evaluation shows the developer decided to billed serverless run with $5000 charge.",
  "A review was filed regarding a free-tier account.",
  "Alert: The candidate spent three months trying to hosted static page with $5000 charge.",
  "Recruiters reported a case of free-tier support design.",
  "Alert: The candidate spent three months trying to alerted support team on local test run.",
  "Scanning candidate profile for bloated pricings...",
  "Recruiters reported a case of massive bill design.",
  "We checked the history and found a high-cost s3 log.",
  "Scanning candidate profile for unused hosts...",
  "Initial evaluation shows the developer decided to exceeded free-tier limits on local test run.",
  "Warning: System flagged an attempt to alerted support team by total accident.",
  "Alert: The candidate spent three months trying to billed serverless run running unneeded containers.",
  "Recruiters reported a case of high-cost account design.",
  "Scanning candidate profile for massive s3s...",
  "Scanning candidate profile for free-tier lambdas...",
  "Alert: The candidate spent three months trying to alerted support team by total accident.",
  "A review was filed regarding a untracked usage.",
  "Warning: System flagged an attempt to alerted support team running unneeded containers.",
  "Initial evaluation shows the developer decided to charged massive fee without price alerts.",
  "Alert: The candidate spent three months trying to billed serverless run without price alerts.",
  "Scanning candidate profile for unused usages...",
  "Warning: System flagged an attempt to exceeded free-tier limits with $5000 charge.",
  "Alert: The candidate spent three months trying to hosted static page without price alerts.",
  "A review was filed regarding a serverless cost.",
  "Alert: The candidate spent three months trying to charged massive fee with $5000 charge.",
  "A review was filed regarding a free-tier pricing.",
  "Recruiters reported a case of high-cost lambda design.",
  "Initial evaluation shows the developer decided to hosted static page without price alerts.",
  "Scanning candidate profile for serverless s3s...",
  "Recruiters reported a case of massive pricing design.",
  "Scanning candidate profile for high-cost bills...",
  "We checked the history and found a untracked bill log.",
  "A review was filed regarding a free-tier support.",
  "We checked the history and found a expensive s3 log.",
  "Initial evaluation shows the developer decided to exceeded free-tier limits with $5000 charge.",
  "A review was filed regarding a expensive lambda.",
  "A review was filed regarding a massive lambda.",
  "Recruiters reported a case of unused ec2 design.",
  "A review was filed regarding a bloated account.",
  "A review was filed regarding a serverless lambda.",
  "Warning: System flagged an attempt to charged massive fee running unneeded containers.",
  "Alert: The candidate spent three months trying to charged massive fee running unneeded containers.",
  "We checked the history and found a serverless lambda log.",
  "Warning: System flagged an attempt to charged massive fee by total accident.",
  "Warning: System flagged an attempt to alerted support team on local test run.",
  "Warning: System flagged an attempt to billed serverless run by total accident.",
  "Scanning candidate profile for massive hosts...",
  "We checked the history and found a unused pricing log.",
  "Initial evaluation shows the developer decided to billed serverless run running unneeded containers.",
  "Scanning candidate profile for expensive hosts...",
  "Recruiters reported a case of untracked lambda design.",
  "A review was filed regarding a expensive usage.",
  "A review was filed regarding a untracked cost.",
  "Initial evaluation shows the developer decided to billed serverless run by total accident.",
  "Warning: System flagged an attempt to charged massive fee without price alerts.",
  "Warning: System flagged an attempt to exceeded free-tier limits without price alerts.",
  "Recruiters reported a case of high-cost support design.",
  "Scanning candidate profile for serverless bills...",
  "Recruiters reported a case of expensive usage design.",
  "We checked the history and found a unused account log.",
  "Recruiters reported a case of bloated s3 design.",
  "Scanning candidate profile for untracked pricings...",
  "Scanning candidate profile for bloated bills...",
  "A review was filed regarding a serverless host.",
  "A review was filed regarding a untracked support.",
  "A review was filed regarding a free-tier host.",
  "Warning: System flagged an attempt to charged massive fee on local test run.",
  "Scanning candidate profile for high-cost pricings...",
  "Warning: System flagged an attempt to exceeded free-tier limits running unneeded containers.",
  "A review was filed regarding a unused cost.",
  "Scanning candidate profile for free-tier costs...",
  "Scanning candidate profile for high-cost hosts...",
  "Alert: The candidate spent three months trying to hosted static page running unneeded containers.",
  "Warning: System flagged an attempt to exceeded free-tier limits by total accident."
];

export const findings = [
  "{{github}} contains more bloated hosts than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a unused usage.",
  "The candidate claims {{framework}} experience, but their repository is just a free-tier clone that has been abandoned.",
  "Failed to configure {{project}} because {{candidateName}} decided to hosted static page by total accident.",
  "A security audit on {{github}} detected a plain-text database password inside a massive support.",
  "While debugging {{project}}, we found a massive logic loop related to {{language}} features.",
  "{{candidateName}} has spent three weeks optimizing a bill while completely ignoring {{missingSection}}.",
  "{{achievement}} was highlighted, but the git logs show they only managed to exceeded free-tier limits without price alerts.",
  "For {{experience}}, the primary contribution was writing a unused config for a ec2.",
  "Listed {{skill}} as a primary competency, but the evidence points to a untracked usage.",
  "{{education}} is listed, but they still managed to deploy a serverless ec2 to production.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to exceeded free-tier limits on local test run.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to alerted support team without price alerts.",
  "Obtained {{certification}} which apparently teaches how to exceeded free-tier limits running unneeded containers.",
  "Obtained {{certification}} which apparently teaches how to hosted static page with $5000 charge.",
  "Obtained {{certification}} which apparently teaches how to charged massive fee without price alerts.",
  "Failed to configure {{project}} because {{candidateName}} decided to exceeded free-tier limits with $5000 charge.",
  "Obtained {{certification}} which apparently teaches how to alerted support team running unneeded containers.",
  "{{github}} contains more massive ec2s than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a free-tier support.",
  "{{achievement}} was highlighted, but the git logs show they only managed to exceeded free-tier limits running unneeded containers.",
  "{{github}} contains more serverless costs than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to alerted support team running unneeded containers.",
  "Failed to configure {{project}} because {{candidateName}} decided to charged massive fee running unneeded containers.",
  "Failed to configure {{project}} because {{candidateName}} decided to alerted support team by total accident.",
  "For {{experience}}, the primary contribution was writing a untracked config for a pricing.",
  "Failed to configure {{project}} because {{candidateName}} decided to charged massive fee on local test run.",
  "{{github}} contains more untracked supports than original code.",
  "{{github}} contains more free-tier ec2s than original code.",
  "Listed {{skill}} as a primary competency, but the evidence points to a unused support.",
  "{{github}} contains more massive accounts than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to charged massive fee with $5000 charge.",
  "Obtained {{certification}} which apparently teaches how to hosted static page without price alerts.",
  "For {{experience}}, the primary contribution was writing a high-cost config for a usage.",
  "{{github}} contains more massive bills than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a expensive bill.",
  "Obtained {{certification}} which apparently teaches how to alerted support team without price alerts.",
  "Failed to configure {{project}} because {{candidateName}} decided to alerted support team running unneeded containers.",
  "Obtained {{certification}} which apparently teaches how to billed serverless run with $5000 charge.",
  "The candidate claims {{framework}} experience, but their repository is just a high-cost clone that has been abandoned.",
  "Listed {{skill}} as a primary competency, but the evidence points to a serverless bill.",
  "For {{experience}}, the primary contribution was writing a serverless config for a host.",
  "{{education}} is listed, but they still managed to deploy a bloated support to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to charged massive fee on local test run.",
  "{{education}} is listed, but they still managed to deploy a massive pricing to production.",
  "Listed {{skill}} as a primary competency, but the evidence points to a bloated host.",
  "{{achievement}} was highlighted, but the git logs show they only managed to hosted static page without price alerts.",
  "A security audit on {{github}} detected a plain-text database password inside a untracked cost.",
  "While debugging {{project}}, we found a free-tier logic loop related to {{language}} features.",
  "A security audit on {{github}} detected a plain-text database password inside a high-cost bill.",
  "{{education}} is listed, but they still managed to deploy a expensive usage to production.",
  "{{education}} is listed, but they still managed to deploy a free-tier support to production.",
  "Obtained {{certification}} which apparently teaches how to exceeded free-tier limits with $5000 charge.",
  "A security audit on {{github}} detected a plain-text database password inside a bloated pricing.",
  "{{github}} contains more serverless bills than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to hosted static page running unneeded containers.",
  "{{education}} is listed, but they still managed to deploy a high-cost lambda to production.",
  "Failed to configure {{project}} because {{candidateName}} decided to exceeded free-tier limits on local test run.",
  "{{github}} contains more expensive s3s than original code.",
  "Obtained {{certification}} which apparently teaches how to charged massive fee on local test run.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to hosted static page on local test run.",
  "{{education}} is listed, but they still managed to deploy a untracked s3 to production.",
  "Listed {{skill}} as a primary competency, but the evidence points to a high-cost usage.",
  "Obtained {{certification}} which apparently teaches how to billed serverless run on local test run.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to billed serverless run on local test run.",
  "Failed to configure {{project}} because {{candidateName}} decided to hosted static page with $5000 charge.",
  "{{achievement}} was highlighted, but the git logs show they only managed to billed serverless run without price alerts.",
  "{{achievement}} was highlighted, but the git logs show they only managed to exceeded free-tier limits with $5000 charge.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to hosted static page with $5000 charge.",
  "For {{experience}}, the primary contribution was writing a free-tier config for a cost.",
  "For {{experience}}, the primary contribution was writing a expensive config for a s3.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to alerted support team by total accident.",
  "Failed to configure {{project}} because {{candidateName}} decided to billed serverless run on local test run.",
  "Listed {{skill}} as a primary competency, but the evidence points to a free-tier ec2.",
  "{{github}} contains more expensive hosts than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to billed serverless run with $5000 charge.",
  "{{github}} contains more expensive bills than original code.",
  "{{github}} contains more untracked accounts than original code.",
  "{{github}} contains more unused bills than original code.",
  "Listed {{skill}} as a primary competency, but the evidence points to a massive s3.",
  "Obtained {{certification}} which apparently teaches how to alerted support team by total accident.",
  "{{github}} contains more unused s3s than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to hosted static page on local test run.",
  "Listed {{skill}} as a primary competency, but the evidence points to a expensive account.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to hosted static page by total accident.",
  "Failed to configure {{project}} because {{candidateName}} decided to alerted support team with $5000 charge.",
  "Failed to configure {{project}} because {{candidateName}} decided to exceeded free-tier limits running unneeded containers.",
  "Obtained {{certification}} which apparently teaches how to exceeded free-tier limits on local test run.",
  "Failed to configure {{project}} because {{candidateName}} decided to charged massive fee without price alerts.",
  "{{achievement}} was highlighted, but the git logs show they only managed to charged massive fee running unneeded containers.",
  "Obtained {{certification}} which apparently teaches how to hosted static page by total accident.",
  "Obtained {{certification}} which apparently teaches how to exceeded free-tier limits without price alerts.",
  "Obtained {{certification}} which apparently teaches how to charged massive fee running unneeded containers.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to alerted support team with $5000 charge.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to exceeded free-tier limits by total accident.",
  "{{github}} contains more bloated costs than original code.",
  "Obtained {{certification}} which apparently teaches how to hosted static page on local test run.",
  "Obtained {{certification}} which apparently teaches how to alerted support team on local test run.",
  "{{github}} contains more massive costs than original code.",
  "For {{experience}}, the primary contribution was writing a bloated config for a cost.",
  "{{achievement}} was highlighted, but the git logs show they only managed to hosted static page with $5000 charge.",
  "{{github}} contains more high-cost supports than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to alerted support team on local test run.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to billed serverless run without price alerts.",
  "{{github}} contains more unused supports than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to exceeded free-tier limits by total accident.",
  "{{achievement}} was highlighted, but the git logs show they only managed to alerted support team with $5000 charge.",
  "{{achievement}} was highlighted, but the git logs show they only managed to hosted static page running unneeded containers.",
  "{{achievement}} was highlighted, but the git logs show they only managed to alerted support team on local test run.",
  "Obtained {{certification}} which apparently teaches how to billed serverless run running unneeded containers.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to alerted support team on local test run."
];

export const punchlines = [
  "The documentation was so empty, I had to use it as a virtual sketchbook.",
  "The compiler requested emotional support after reading the serverless code.",
  "Legend says this massive bill is still running on localhost.",
  "Legend says this free-tier ec2 is still running on localhost.",
  "It did not optimize our process, but it did make the laptop fan spin like a jet engine.",
  "The only thing memory-safe about this setup is that nobody has ever tried to run it.",
  "The compiler requested emotional support after reading the free-tier code.",
  "Even Stack Overflow has marked this usage as off-topic.",
  "We would deploy it to production, but our SRE team deserves to sleep at night.",
  "Legend says this bloated support is still running on localhost.",
  "A junior developer looked at the usage and immediately went to touch grass.",
  "Legend says this high-cost host is still running on localhost.",
  "Legend says this bloated ec2 is still running on localhost.",
  "Legend says this bloated lambda is still running on localhost.",
  "Legend says this bloated account is still running on localhost.",
  "Legend says this untracked cost is still running on localhost.",
  "Legend says this untracked support is still running on localhost.",
  "Legend says this expensive s3 is still running on localhost.",
  "Legend says this unused support is still running on localhost.",
  "The compiler requested emotional support after reading the high-cost code.",
  "Legend says this untracked host is still running on localhost.",
  "Legend says this serverless usage is still running on localhost.",
  "Legend says this bloated pricing is still running on localhost.",
  "Legend says this unused bill is still running on localhost.",
  "Legend says this serverless lambda is still running on localhost.",
  "Legend says this massive ec2 is still running on localhost.",
  "Legend says this bloated cost is still running on localhost.",
  "Legend says this serverless account is still running on localhost.",
  "Legend says this untracked pricing is still running on localhost.",
  "Legend says this unused lambda is still running on localhost.",
  "Legend says this bloated bill is still running on localhost.",
  "Legend says this untracked ec2 is still running on localhost.",
  "Legend says this bloated host is still running on localhost.",
  "Legend says this massive host is still running on localhost.",
  "Legend says this unused ec2 is still running on localhost.",
  "Legend says this massive support is still running on localhost.",
  "Legend says this massive account is still running on localhost.",
  "Legend says this serverless cost is still running on localhost.",
  "Legend says this massive lambda is still running on localhost.",
  "Legend says this untracked lambda is still running on localhost.",
  "Legend says this bloated usage is still running on localhost.",
  "Legend says this massive cost is still running on localhost.",
  "Legend says this unused usage is still running on localhost.",
  "Legend says this unused cost is still running on localhost.",
  "Legend says this untracked account is still running on localhost.",
  "Legend says this massive pricing is still running on localhost.",
  "This is a classic example of a serverless s3 disaster.",
  "This is a classic example of a massive host disaster.",
  "This is a classic example of a free-tier lambda disaster.",
  "This is a classic example of a untracked ec2 disaster.",
  "This is a classic example of a massive bill disaster.",
  "This is a classic example of a massive lambda disaster.",
  "This is a classic example of a massive usage disaster.",
  "This is a classic example of a high-cost cost disaster.",
  "This is a classic example of a untracked host disaster.",
  "This is a classic example of a expensive account disaster.",
  "This is a classic example of a unused support disaster.",
  "This is a classic example of a unused lambda disaster.",
  "This is a classic example of a free-tier bill disaster.",
  "This is a classic example of a bloated lambda disaster.",
  "This is a classic example of a bloated cost disaster.",
  "This is a classic example of a massive pricing disaster.",
  "This is a classic example of a unused ec2 disaster.",
  "This is a classic example of a free-tier cost disaster.",
  "This is a classic example of a expensive pricing disaster.",
  "This is a classic example of a expensive support disaster.",
  "This is a classic example of a massive ec2 disaster.",
  "This is a classic example of a bloated support disaster."
];

export const verdicts = [
  "Needs more commits and fewer explanations.",
  "Request changes on the bloated lambda.",
  "Request changes on the expensive bill.",
  "Return after touching actual production servers.",
  "Request changes on the high-cost cost.",
  "Request changes on the bloated cost.",
  "Verdict: Support is completely unmergeable.",
  "Verdict: Cost is completely unmergeable.",
  "PR billed serverless run due to expensive implementation.",
  "Verdict: Usage is completely unmergeable.",
  "Ship blocked by untracked check failures.",
  "Rejected on first principles of pricing organization.",
  "Verdict: S3 is completely unmergeable.",
  "PR charged massive fee due to high-cost implementation.",
  "Ship blocked by expensive check failures.",
  "Closed as unused duplicate.",
  "Ship blocked by serverless check failures.",
  "PR alerted support team due to high-cost implementation.",
  "Closed as high-cost duplicate.",
  "Verdict: Pricing is completely unmergeable.",
  "Rejected on first principles of ec2 organization.",
  "Ship blocked by high-cost check failures.",
  "PR exceeded free-tier limits due to untracked implementation.",
  "Rejected on first principles of lambda organization.",
  "Rejected on first principles of support organization.",
  "Rejected on first principles of host organization.",
  "Closed as untracked duplicate.",
  "PR alerted support team due to untracked implementation.",
  "PR alerted support team due to bloated implementation.",
  "Verdict: Lambda is completely unmergeable.",
  "Request changes on the massive lambda.",
  "Verdict: Host is completely unmergeable.",
  "Verdict: Account is completely unmergeable.",
  "Ship blocked by massive check failures.",
  "PR billed serverless run due to free-tier implementation.",
  "PR billed serverless run due to unused implementation.",
  "Request changes on the expensive host.",
  "Rejected on first principles of cost organization.",
  "Ship blocked by bloated check failures.",
  "Request changes on the serverless pricing.",
  "Request changes on the expensive ec2.",
  "Request changes on the bloated ec2.",
  "Request changes on the untracked s3.",
  "Closed as serverless duplicate.",
  "Rejected on first principles of bill organization.",
  "Closed as massive duplicate.",
  "Ship blocked by free-tier check failures.",
  "PR hosted static page due to unused implementation.",
  "Rejected on first principles of usage organization.",
  "Closed as expensive duplicate.",
  "Verdict: Ec2 is completely unmergeable.",
  "Request changes on the bloated host.",
  "PR hosted static page due to serverless implementation.",
  "Closed as bloated duplicate.",
  "Closed as free-tier duplicate.",
  "Request changes on the bloated account.",
  "Request changes on the unused s3.",
  "PR hosted static page due to high-cost implementation.",
  "Request changes on the free-tier lambda.",
  "Request changes on the expensive lambda.",
  "PR hosted static page due to expensive implementation.",
  "Verdict: Bill is completely unmergeable.",
  "PR charged massive fee due to untracked implementation.",
  "Request changes on the free-tier pricing.",
  "Ship blocked by unused check failures.",
  "PR alerted support team due to free-tier implementation.",
  "PR hosted static page due to bloated implementation.",
  "Rejected on first principles of account organization.",
  "PR exceeded free-tier limits due to massive implementation.",
  "Request changes on the massive ec2.",
  "Request changes on the free-tier host.",
  "Request changes on the free-tier cost.",
  "PR hosted static page due to massive implementation.",
  "PR alerted support team due to expensive implementation.",
  "Request changes on the massive host.",
  "PR exceeded free-tier limits due to expensive implementation.",
  "PR exceeded free-tier limits due to unused implementation.",
  "PR exceeded free-tier limits due to serverless implementation.",
  "PR charged massive fee due to bloated implementation.",
  "PR exceeded free-tier limits due to high-cost implementation.",
  "PR alerted support team due to serverless implementation.",
  "Request changes on the serverless support."
];

export const easterEggs = [
  "Steam Achievement Unlocked: Successfully crashed a hello-world app on a $10,000 server.",
  "Gordon Ramsay Meltdown: 'This usage is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted bloated costs.",
  "NASA Alert: Space mission aborted due to a minor pricing parsing error.",
  "Elon Musk Tweet: 'Just deleted the entire cost pipeline, was completely useless.'",
  "FBI Investigation: Suspect was found deploying unencrypted untracked lambdas.",
  "Matrix Glitch: You copy-pasted a template and now the server believes it is a real founder.",
  "Dark Web Resume Auction: Current bid is $0.00, and the buyer is requesting a refund.",
  "Gordon Ramsay Meltdown: 'This lambda is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This host is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This bill is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted expensive s3s.",
  "Gordon Ramsay Meltdown: 'This ec2 is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted free-tier usages.",
  "Gordon Ramsay Meltdown: 'This cost is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This account is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted massive usages.",
  "Gordon Ramsay Meltdown: 'This support is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted unused bills.",
  "Gordon Ramsay Meltdown: 'This pricing is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted high-cost ec2s."
];
