// ES Module exports for clippy_dialog roast format
export const titles = [
  "Word Not Found",
  "Suggestion Not Found",
  "Incident Report: Helper-level Warning",
  "The Clippy tragedy",
  "Failed to compile: Clippy",
  "Critical Doc failure",
  "Suggestion conflict detected",
  "Incident Report: Administrative Assistant",
  "Unused Doc Error",
  "Helper-level Word Loop",
  "Failed to compile: Doc",
  "Clippy Not Found",
  "Incident Report: Legacy Dialog",
  "Helper-level Doc Loop",
  "Annoying Office Loop",
  "The Advice tragedy",
  "Unused Advice Loop",
  "Word conflict detected",
  "Administrative Office Error",
  "Unused Suggestion Loop",
  "Failed to compile: Office",
  "Failed to compile: Advice",
  "Absolute Paperclip architecture",
  "The Assistant tragedy",
  "Absolute Legacy architecture",
  "NullPointerWordException",
  "Critical Suggestion failure",
  "Annoying Advice Loop",
  "Paperclip Doc Error",
  "Incident Report: Annoying Clippy",
  "Assistant Not Found",
  "Critical Word failure",
  "The Word tragedy",
  "Legacy Warning Error",
  "Incident Report: Helper-level Assistant",
  "Critical Assistant failure",
  "Failed to compile: Suggestion",
  "Absolute Helper-level architecture",
  "Doc conflict detected",
  "Unused Advice Error",
  "Legacy Advice Error",
  "NullPointerClippyException",
  "NullPointerAdviceException",
  "Absolute Annoying architecture",
  "Legacy Office Loop",
  "Failed to compile: Warning",
  "The Doc tragedy",
  "Obsolete Warning Error",
  "Incident Report: Helper-level Doc",
  "NullPointerOfficeException",
  "Failed to compile: Word",
  "Assistant conflict detected",
  "The Support tragedy",
  "Annoying Dialog Error",
  "The Dialog tragedy",
  "Obsolete Office Loop",
  "Basic Warning Error",
  "Advice conflict detected",
  "Absolute Administrative architecture",
  "Paperclip Warning Loop",
  "Dialog conflict detected",
  "Unused Clippy Error",
  "Failed to compile: Support",
  "Clippy conflict detected",
  "NullPointerSuggestionException",
  "Failed to compile: Dialog",
  "NullPointerAssistantException",
  "Helper-level Warning Loop",
  "Doc Not Found",
  "Advice Not Found",
  "Critical Support failure",
  "Legacy Clippy Loop",
  "Critical Warning failure",
  "Annoying Suggestion Error",
  "Incident Report: Annoying Word",
  "Unused Word Error",
  "Basic Office Loop",
  "Obsolete Word Error",
  "Dialog Not Found",
  "Incident Report: Basic Office",
  "Incident Report: Unused Clippy",
  "Office conflict detected",
  "The Warning tragedy",
  "Incident Report: Annoying Suggestion",
  "Annoying Clippy Error",
  "Absolute Unused architecture",
  "Critical Clippy failure",
  "Critical Advice failure",
  "Incident Report: Administrative Support",
  "Annoying Doc Loop",
  "Critical Dialog failure",
  "Unused Office Error",
  "The Suggestion tragedy",
  "Helper-level Clippy Loop",
  "NullPointerDocException",
  "Legacy Dialog Error",
  "Incident Report: Unused Assistant",
  "Incident Report: Legacy Support",
  "Administrative Support Error",
  "Absolute Basic architecture"
];

export const openings = [
  "Initial evaluation shows the developer decided to suggested basic advice to bypass template.",
  "Scanning candidate profile for helper-level docs...",
  "Warning: System flagged an attempt to suggested basic advice to bypass template.",
  "A review was filed regarding a unused office.",
  "Scanning candidate profile for basic docs...",
  "Alert: The candidate spent three months trying to clicked warning dialog that nobody requested.",
  "A review was filed regarding a obsolete Word.",
  "Warning: System flagged an attempt to ignored office helper in legacy doc file.",
  "Alert: The candidate spent three months trying to suggested basic advice in legacy doc file.",
  "Recruiters reported a case of helper-level suggestion design.",
  "A review was filed regarding a helper-level clippy.",
  "A review was filed regarding a annoying Word.",
  "A review was filed regarding a helper-level suggestion.",
  "Warning: System flagged an attempt to suggested basic advice that nobody requested.",
  "Alert: The candidate spent three months trying to prompted clippy assistant to bypass template.",
  "The team has initiated audit for the candidate's suggestion setup.",
  "We checked the history and found a legacy support log.",
  "Recruiters reported a case of unused suggestion design.",
  "Alert: The candidate spent three months trying to prompted clippy assistant in legacy doc file.",
  "We checked the history and found a administrative office log.",
  "Warning: System flagged an attempt to ignored office helper that nobody requested.",
  "We checked the history and found a annoying clippy log.",
  "A review was filed regarding a helper-level support.",
  "A review was filed regarding a unused warning.",
  "Recruiters reported a case of obsolete Word design.",
  "Recruiters reported a case of unused assistant design.",
  "Warning: System flagged an attempt to clicked warning dialog in legacy doc file.",
  "Recruiters reported a case of administrative support design.",
  "A review was filed regarding a helper-level dialog.",
  "Initial evaluation shows the developer decided to clicked warning dialog with useless comments.",
  "Scanning candidate profile for basic suggestions...",
  "We checked the history and found a administrative warning log.",
  "We checked the history and found a annoying suggestion log.",
  "A review was filed regarding a obsolete clippy.",
  "Scanning candidate profile for paperclip advices...",
  "We checked the history and found a annoying advice log.",
  "Initial evaluation shows the developer decided to clicked warning dialog that nobody requested.",
  "A review was filed regarding a annoying dialog.",
  "Alert: The candidate spent three months trying to suggested basic advice to bypass template.",
  "Initial evaluation shows the developer decided to prompted clippy assistant during typing run.",
  "Initial evaluation shows the developer decided to suggested basic advice that nobody requested.",
  "Recruiters reported a case of administrative advice design.",
  "We checked the history and found a annoying support log.",
  "Recruiters reported a case of helper-level clippy design.",
  "Warning: System flagged an attempt to searched Word support during typing run.",
  "Warning: System flagged an attempt to suggested basic advice in legacy doc file.",
  "Initial evaluation shows the developer decided to ignored office helper with useless comments.",
  "Warning: System flagged an attempt to searched Word support to bypass template.",
  "Initial evaluation shows the developer decided to searched Word support in legacy doc file.",
  "Scanning candidate profile for obsolete suggestions...",
  "A review was filed regarding a obsolete office.",
  "Alert: The candidate spent three months trying to suggested basic advice that nobody requested.",
  "A review was filed regarding a basic doc.",
  "Alert: The candidate spent three months trying to clicked warning dialog with useless comments.",
  "We checked the history and found a obsolete doc log.",
  "Initial evaluation shows the developer decided to suggested basic advice during typing run.",
  "A review was filed regarding a unused Word.",
  "Scanning candidate profile for unused dialogs...",
  "Initial evaluation shows the developer decided to clicked warning dialog during typing run.",
  "Recruiters reported a case of annoying advice design.",
  "Scanning candidate profile for helper-level Words...",
  "A review was filed regarding a legacy suggestion.",
  "Alert: The candidate spent three months trying to prompted clippy assistant during typing run.",
  "We checked the history and found a paperclip suggestion log.",
  "Scanning candidate profile for legacy assistants...",
  "Scanning candidate profile for basic Words...",
  "Initial evaluation shows the developer decided to suggested basic advice with useless comments.",
  "Warning: System flagged an attempt to ignored office helper during typing run.",
  "Initial evaluation shows the developer decided to prompted clippy assistant that nobody requested.",
  "Initial evaluation shows the developer decided to suggested basic advice in legacy doc file.",
  "Scanning candidate profile for annoying dialogs...",
  "Alert: The candidate spent three months trying to suggested basic advice during typing run.",
  "A review was filed regarding a helper-level doc.",
  "Recruiters reported a case of annoying Word design.",
  "Warning: System flagged an attempt to searched Word support with useless comments.",
  "Alert: The candidate spent three months trying to suggested basic advice with useless comments.",
  "We checked the history and found a annoying warning log.",
  "Initial evaluation shows the developer decided to clicked warning dialog in legacy doc file.",
  "Alert: The candidate spent three months trying to prompted clippy assistant that nobody requested.",
  "Recruiters reported a case of legacy doc design.",
  "Alert: The candidate spent three months trying to searched Word support to bypass template.",
  "A review was filed regarding a administrative Word.",
  "Recruiters reported a case of basic warning design.",
  "Scanning candidate profile for unused offices...",
  "Initial evaluation shows the developer decided to prompted clippy assistant in legacy doc file.",
  "A review was filed regarding a legacy advice.",
  "A review was filed regarding a basic office.",
  "We checked the history and found a obsolete assistant log.",
  "Initial evaluation shows the developer decided to prompted clippy assistant with useless comments.",
  "Initial evaluation shows the developer decided to searched Word support that nobody requested.",
  "A review was filed regarding a administrative warning.",
  "Initial evaluation shows the developer decided to prompted clippy assistant to bypass template.",
  "We checked the history and found a obsolete support log.",
  "Recruiters reported a case of basic dialog design."
];

export const findings = [
  "{{github}} contains more helper-level dialogs than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a obsolete assistant.",
  "{{github}} contains more legacy dialogs than original code.",
  "Obtained {{certification}} which apparently teaches how to suggested basic advice during typing run.",
  "Failed to configure {{project}} because {{candidateName}} decided to prompted clippy assistant during typing run.",
  "Listed {{skill}} as a primary competency, but the evidence points to a annoying advice.",
  "While debugging {{project}}, we found a legacy logic loop related to {{language}} features.",
  "Obtained {{certification}} which apparently teaches how to ignored office helper during typing run.",
  "{{candidateName}} has spent three weeks optimizing a Word while completely ignoring {{missingSection}}.",
  "{{achievement}} was highlighted, but the git logs show they only managed to clicked warning dialog that nobody requested.",
  "The candidate claims {{framework}} experience, but their repository is just a legacy clone that has been abandoned.",
  "Failed to configure {{project}} because {{candidateName}} decided to prompted clippy assistant with useless comments.",
  "{{education}} is listed, but they still managed to deploy a administrative support to production.",
  "Obtained {{certification}} which apparently teaches how to clicked warning dialog during typing run.",
  "Failed to configure {{project}} because {{candidateName}} decided to clicked warning dialog in legacy doc file.",
  "{{github}} contains more annoying assistants than original code.",
  "For {{experience}}, the primary contribution was writing a helper-level config for a advice.",
  "{{github}} contains more paperclip Words than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to suggested basic advice that nobody requested.",
  "Failed to configure {{project}} because {{candidateName}} decided to suggested basic advice to bypass template.",
  "For {{experience}}, the primary contribution was writing a paperclip config for a doc.",
  "{{education}} is listed, but they still managed to deploy a annoying office to production.",
  "{{education}} is listed, but they still managed to deploy a paperclip warning to production.",
  "Listed {{skill}} as a primary competency, but the evidence points to a helper-level dialog.",
  "A security audit on {{github}} detected a plain-text database password inside a paperclip Word.",
  "{{github}} contains more administrative assistants than original code.",
  "Obtained {{certification}} which apparently teaches how to searched Word support to bypass template.",
  "{{education}} is listed, but they still managed to deploy a legacy suggestion to production.",
  "A security audit on {{github}} detected a plain-text database password inside a helper-level office.",
  "{{github}} contains more basic assistants than original code.",
  "Obtained {{certification}} which apparently teaches how to suggested basic advice that nobody requested.",
  "Failed to configure {{project}} because {{candidateName}} decided to ignored office helper to bypass template.",
  "Obtained {{certification}} which apparently teaches how to suggested basic advice with useless comments.",
  "For {{experience}}, the primary contribution was writing a administrative config for a Word.",
  "{{achievement}} was highlighted, but the git logs show they only managed to prompted clippy assistant that nobody requested.",
  "{{achievement}} was highlighted, but the git logs show they only managed to suggested basic advice during typing run.",
  "{{github}} contains more administrative dialogs than original code.",
  "Obtained {{certification}} which apparently teaches how to ignored office helper in legacy doc file.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to prompted clippy assistant during typing run.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to prompted clippy assistant to bypass template.",
  "{{github}} contains more obsolete warnings than original code.",
  "Obtained {{certification}} which apparently teaches how to searched Word support that nobody requested.",
  "Failed to configure {{project}} because {{candidateName}} decided to searched Word support in legacy doc file.",
  "For {{experience}}, the primary contribution was writing a obsolete config for a suggestion.",
  "Listed {{skill}} as a primary competency, but the evidence points to a paperclip warning.",
  "For {{experience}}, the primary contribution was writing a annoying config for a office.",
  "{{github}} contains more unused assistants than original code.",
  "For {{experience}}, the primary contribution was writing a unused config for a warning.",
  "{{achievement}} was highlighted, but the git logs show they only managed to prompted clippy assistant with useless comments.",
  "{{github}} contains more annoying warnings than original code.",
  "{{education}} is listed, but they still managed to deploy a obsolete doc to production.",
  "Listed {{skill}} as a primary competency, but the evidence points to a legacy suggestion.",
  "Obtained {{certification}} which apparently teaches how to prompted clippy assistant in legacy doc file.",
  "{{achievement}} was highlighted, but the git logs show they only managed to suggested basic advice in legacy doc file.",
  "Failed to configure {{project}} because {{candidateName}} decided to suggested basic advice with useless comments.",
  "{{achievement}} was highlighted, but the git logs show they only managed to searched Word support in legacy doc file.",
  "{{github}} contains more legacy clippys than original code.",
  "{{github}} contains more annoying suggestions than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to prompted clippy assistant in legacy doc file.",
  "{{github}} contains more obsolete suggestions than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to clicked warning dialog during typing run.",
  "{{achievement}} was highlighted, but the git logs show they only managed to suggested basic advice to bypass template.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to searched Word support to bypass template.",
  "{{github}} contains more administrative warnings than original code.",
  "{{education}} is listed, but they still managed to deploy a unused dialog to production.",
  "{{github}} contains more annoying docs than original code.",
  "{{github}} contains more unused offices than original code.",
  "{{github}} contains more basic offices than original code.",
  "{{github}} contains more basic warnings than original code.",
  "{{github}} contains more administrative suggestions than original code.",
  "For {{experience}}, the primary contribution was writing a legacy config for a assistant.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to searched Word support with useless comments.",
  "{{github}} contains more administrative clippys than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ignored office helper to bypass template.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to suggested basic advice to bypass template.",
  "Failed to configure {{project}} because {{candidateName}} decided to prompted clippy assistant that nobody requested.",
  "A security audit on {{github}} detected a plain-text database password inside a basic suggestion.",
  "Obtained {{certification}} which apparently teaches how to ignored office helper with useless comments.",
  "{{achievement}} was highlighted, but the git logs show they only managed to searched Word support during typing run.",
  "{{github}} contains more obsolete docs than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ignored office helper with useless comments.",
  "Failed to configure {{project}} because {{candidateName}} decided to ignored office helper that nobody requested.",
  "Obtained {{certification}} which apparently teaches how to prompted clippy assistant that nobody requested.",
  "{{github}} contains more basic supports than original code.",
  "{{github}} contains more legacy docs than original code.",
  "{{education}} is listed, but they still managed to deploy a helper-level Word to production.",
  "Listed {{skill}} as a primary competency, but the evidence points to a administrative clippy.",
  "Listed {{skill}} as a primary competency, but the evidence points to a unused assistant.",
  "Obtained {{certification}} which apparently teaches how to searched Word support with useless comments.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ignored office helper in legacy doc file.",
  "{{github}} contains more annoying clippys than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to clicked warning dialog with useless comments.",
  "Failed to configure {{project}} because {{candidateName}} decided to ignored office helper in legacy doc file.",
  "{{github}} contains more annoying advices than original code.",
  "While debugging {{project}}, we found a helper-level logic loop related to {{language}} features.",
  "Failed to configure {{project}} because {{candidateName}} decided to searched Word support that nobody requested.",
  "Obtained {{certification}} which apparently teaches how to clicked warning dialog in legacy doc file.",
  "Failed to configure {{project}} because {{candidateName}} decided to suggested basic advice in legacy doc file.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ignored office helper that nobody requested.",
  "{{github}} contains more paperclip docs than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to clicked warning dialog in legacy doc file.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ignored office helper to bypass template.",
  "{{achievement}} was highlighted, but the git logs show they only managed to searched Word support that nobody requested.",
  "Obtained {{certification}} which apparently teaches how to clicked warning dialog that nobody requested.",
  "Failed to configure {{project}} because {{candidateName}} decided to suggested basic advice that nobody requested.",
  "{{education}} is listed, but they still managed to deploy a basic assistant to production.",
  "Obtained {{certification}} which apparently teaches how to prompted clippy assistant during typing run.",
  "A security audit on {{github}} detected a plain-text database password inside a unused warning.",
  "Obtained {{certification}} which apparently teaches how to prompted clippy assistant with useless comments.",
  "{{github}} contains more legacy Words than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a legacy advice.",
  "{{achievement}} was highlighted, but the git logs show they only managed to clicked warning dialog to bypass template.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ignored office helper with useless comments.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ignored office helper in legacy doc file.",
  "Listed {{skill}} as a primary competency, but the evidence points to a obsolete support.",
  "Obtained {{certification}} which apparently teaches how to clicked warning dialog with useless comments.",
  "{{github}} contains more paperclip clippys than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to suggested basic advice in legacy doc file.",
  "{{github}} contains more legacy suggestions than original code.",
  "For {{experience}}, the primary contribution was writing a basic config for a advice.",
  "Obtained {{certification}} which apparently teaches how to ignored office helper to bypass template."
];

export const punchlines = [
  "The only thing memory-safe about this setup is that nobody has ever tried to run it.",
  "It did not optimize our process, but it did make the laptop fan spin like a jet engine.",
  "Legend says this administrative Word is still running on localhost.",
  "Even Stack Overflow has marked this office as off-topic.",
  "Legend says this legacy dialog is still running on localhost.",
  "The compiler requested emotional support after reading the paperclip code.",
  "We would deploy it to production, but our SRE team deserves to sleep at night.",
  "A junior developer looked at the clippy and immediately went to touch grass.",
  "The documentation was so empty, I had to use it as a virtual sketchbook.",
  "Legend says this basic clippy is still running on localhost.",
  "Legend says this administrative advice is still running on localhost.",
  "Legend says this annoying Word is still running on localhost.",
  "The compiler requested emotional support after reading the helper-level code.",
  "Legend says this obsolete office is still running on localhost.",
  "Legend says this legacy suggestion is still running on localhost.",
  "Legend says this helper-level Word is still running on localhost.",
  "Legend says this basic warning is still running on localhost.",
  "Legend says this obsolete warning is still running on localhost.",
  "Legend says this legacy Word is still running on localhost.",
  "Legend says this administrative warning is still running on localhost.",
  "Legend says this unused advice is still running on localhost.",
  "Legend says this paperclip doc is still running on localhost.",
  "Legend says this administrative assistant is still running on localhost.",
  "Legend says this unused clippy is still running on localhost.",
  "Legend says this obsolete Word is still running on localhost.",
  "Legend says this legacy advice is still running on localhost.",
  "Legend says this annoying dialog is still running on localhost.",
  "Legend says this annoying suggestion is still running on localhost.",
  "Legend says this paperclip office is still running on localhost.",
  "Legend says this unused office is still running on localhost.",
  "Legend says this basic support is still running on localhost.",
  "Legend says this obsolete advice is still running on localhost.",
  "Legend says this unused warning is still running on localhost.",
  "Legend says this legacy doc is still running on localhost.",
  "Legend says this legacy clippy is still running on localhost.",
  "Legend says this basic office is still running on localhost.",
  "Legend says this unused Word is still running on localhost.",
  "Legend says this annoying support is still running on localhost.",
  "Legend says this annoying warning is still running on localhost.",
  "Legend says this basic Word is still running on localhost.",
  "Legend says this basic advice is still running on localhost.",
  "Legend says this basic assistant is still running on localhost.",
  "Legend says this paperclip dialog is still running on localhost.",
  "Legend says this annoying office is still running on localhost.",
  "Legend says this annoying assistant is still running on localhost.",
  "Legend says this unused dialog is still running on localhost.",
  "Legend says this paperclip Word is still running on localhost.",
  "Legend says this paperclip assistant is still running on localhost.",
  "Legend says this administrative office is still running on localhost.",
  "Legend says this unused support is still running on localhost.",
  "Legend says this paperclip support is still running on localhost.",
  "Legend says this administrative support is still running on localhost.",
  "Legend says this unused doc is still running on localhost.",
  "Legend says this obsolete dialog is still running on localhost.",
  "Legend says this administrative suggestion is still running on localhost.",
  "Legend says this administrative clippy is still running on localhost.",
  "Legend says this obsolete clippy is still running on localhost.",
  "Legend says this legacy assistant is still running on localhost.",
  "Legend says this paperclip suggestion is still running on localhost.",
  "Legend says this basic suggestion is still running on localhost.",
  "Legend says this obsolete support is still running on localhost.",
  "Legend says this unused suggestion is still running on localhost.",
  "This is a classic example of a obsolete warning disaster.",
  "This is a classic example of a helper-level warning disaster.",
  "This is a classic example of a basic clippy disaster.",
  "This is a classic example of a unused advice disaster.",
  "This is a classic example of a obsolete assistant disaster.",
  "This is a classic example of a obsolete support disaster.",
  "This is a classic example of a unused doc disaster.",
  "This is a classic example of a annoying office disaster.",
  "This is a classic example of a legacy suggestion disaster.",
  "This is a classic example of a administrative Word disaster.",
  "This is a classic example of a paperclip support disaster.",
  "This is a classic example of a unused assistant disaster.",
  "This is a classic example of a obsolete office disaster.",
  "This is a classic example of a helper-level assistant disaster.",
  "This is a classic example of a paperclip assistant disaster.",
  "This is a classic example of a unused Word disaster.",
  "This is a classic example of a obsolete Word disaster.",
  "This is a classic example of a unused suggestion disaster.",
  "This is a classic example of a legacy clippy disaster.",
  "This is a classic example of a obsolete advice disaster.",
  "This is a classic example of a administrative warning disaster.",
  "This is a classic example of a legacy support disaster.",
  "This is a classic example of a administrative suggestion disaster.",
  "This is a classic example of a basic support disaster.",
  "This is a classic example of a basic doc disaster.",
  "This is a classic example of a annoying dialog disaster.",
  "This is a classic example of a paperclip clippy disaster.",
  "This is a classic example of a basic dialog disaster.",
  "This is a classic example of a basic advice disaster.",
  "This is a classic example of a obsolete dialog disaster.",
  "This is a classic example of a unused support disaster.",
  "This is a classic example of a obsolete doc disaster.",
  "This is a classic example of a administrative advice disaster.",
  "This is a classic example of a obsolete suggestion disaster."
];

export const verdicts = [
  "Needs more commits and fewer explanations.",
  "Rejected on first principles of advice organization.",
  "Return after touching actual production servers.",
  "Ship blocked by paperclip check failures.",
  "Closed as annoying duplicate.",
  "Verdict: Doc is completely unmergeable.",
  "Verdict: Support is completely unmergeable.",
  "PR prompted clippy assistant due to paperclip implementation.",
  "PR clicked warning dialog due to administrative implementation.",
  "Verdict: Warning is completely unmergeable.",
  "Rejected on first principles of support organization.",
  "Ship blocked by unused check failures.",
  "Verdict: Office is completely unmergeable.",
  "Closed as administrative duplicate.",
  "Verdict: Suggestion is completely unmergeable.",
  "Closed as obsolete duplicate.",
  "Ship blocked by obsolete check failures.",
  "PR prompted clippy assistant due to helper-level implementation.",
  "PR clicked warning dialog due to annoying implementation.",
  "Verdict: Assistant is completely unmergeable.",
  "Rejected on first principles of assistant organization.",
  "PR prompted clippy assistant due to administrative implementation.",
  "Rejected on first principles of clippy organization.",
  "Ship blocked by administrative check failures.",
  "Verdict: Dialog is completely unmergeable.",
  "PR ignored office helper due to legacy implementation.",
  "Rejected on first principles of Word organization.",
  "Closed as helper-level duplicate.",
  "Rejected on first principles of dialog organization.",
  "Rejected on first principles of suggestion organization.",
  "Closed as unused duplicate.",
  "PR ignored office helper due to obsolete implementation.",
  "Ship blocked by basic check failures.",
  "Request changes on the administrative Word.",
  "Ship blocked by helper-level check failures.",
  "Closed as legacy duplicate.",
  "Request changes on the unused support.",
  "Verdict: Clippy is completely unmergeable.",
  "Request changes on the unused suggestion.",
  "Verdict: Word is completely unmergeable.",
  "Ship blocked by legacy check failures.",
  "PR searched Word support due to paperclip implementation.",
  "Request changes on the basic advice.",
  "Request changes on the annoying advice.",
  "PR prompted clippy assistant due to unused implementation.",
  "Rejected on first principles of warning organization.",
  "Verdict: Advice is completely unmergeable.",
  "PR suggested basic advice due to annoying implementation.",
  "PR suggested basic advice due to administrative implementation.",
  "Request changes on the obsolete Word.",
  "Request changes on the unused advice.",
  "PR ignored office helper due to unused implementation.",
  "Rejected on first principles of office organization.",
  "Request changes on the legacy Word.",
  "PR suggested basic advice due to obsolete implementation.",
  "Ship blocked by annoying check failures.",
  "Request changes on the annoying support.",
  "Closed as paperclip duplicate.",
  "Request changes on the legacy assistant.",
  "Request changes on the administrative support.",
  "Request changes on the obsolete dialog.",
  "Request changes on the basic office.",
  "PR ignored office helper due to paperclip implementation.",
  "PR clicked warning dialog due to legacy implementation.",
  "Closed as basic duplicate.",
  "PR ignored office helper due to administrative implementation.",
  "Request changes on the annoying Word.",
  "Request changes on the helper-level dialog.",
  "Request changes on the administrative dialog.",
  "PR prompted clippy assistant due to legacy implementation.",
  "PR suggested basic advice due to paperclip implementation.",
  "Request changes on the basic clippy.",
  "PR searched Word support due to basic implementation.",
  "PR searched Word support due to legacy implementation.",
  "Request changes on the administrative doc.",
  "PR searched Word support due to unused implementation.",
  "Request changes on the annoying warning.",
  "Request changes on the obsolete clippy.",
  "Rejected on first principles of doc organization.",
  "Request changes on the unused assistant.",
  "Request changes on the helper-level clippy.",
  "Request changes on the administrative warning.",
  "PR searched Word support due to annoying implementation.",
  "PR prompted clippy assistant due to obsolete implementation.",
  "PR clicked warning dialog due to basic implementation.",
  "PR clicked warning dialog due to paperclip implementation.",
  "Request changes on the legacy warning.",
  "PR searched Word support due to obsolete implementation.",
  "PR ignored office helper due to basic implementation.",
  "PR suggested basic advice due to unused implementation.",
  "Request changes on the paperclip office.",
  "Request changes on the annoying suggestion.",
  "Request changes on the basic dialog.",
  "Request changes on the helper-level assistant.",
  "Request changes on the unused doc.",
  "Request changes on the unused clippy.",
  "Request changes on the obsolete warning.",
  "Request changes on the administrative assistant.",
  "Request changes on the helper-level warning."
];

export const easterEggs = [
  "Gordon Ramsay Meltdown: 'This warning is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted helper-level warnings.",
  "Elon Musk Tweet: 'Just deleted the entire clippy pipeline, was completely useless.'",
  "Gordon Ramsay Meltdown: 'This support is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted obsolete warnings.",
  "Matrix Glitch: You copy-pasted a template and now the server believes it is a real founder.",
  "FBI Investigation: Suspect was found deploying unencrypted legacy dialogs.",
  "Steam Achievement Unlocked: Successfully crashed a hello-world app on a $10,000 server.",
  "Gordon Ramsay Meltdown: 'This doc is raw! It's absolutely raw!'",
  "NASA Alert: Space mission aborted due to a minor advice parsing error.",
  "Dark Web Resume Auction: Current bid is $0.00, and the buyer is requesting a refund.",
  "Gordon Ramsay Meltdown: 'This office is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This dialog is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This Word is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This suggestion is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This assistant is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This clippy is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted annoying advices.",
  "Gordon Ramsay Meltdown: 'This advice is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted basic supports.",
  "FBI Investigation: Suspect was found deploying unencrypted administrative offices."
];
