// ES Module exports for corporate_pip roast format
export const titles = [
  "Poor Period Error",
  "Poor Manager Loop",
  "Critical Period Loop",
  "Absolute Poor architecture",
  "NullPointerPerformanceException",
  "Absolute Formal architecture",
  "Metrics conflict detected",
  "Employee conflict detected",
  "Critical Employee failure",
  "Critical Period failure",
  "Improvement-level Period Loop",
  "Incident Report: Sub-standard Metrics",
  "Failed to compile: Employee",
  "Formal Standard Loop",
  "Incident Report: Critical Plan",
  "Incident Report: Warning-level Warning",
  "NullPointerEmployeeException",
  "Period Not Found",
  "Critical Performance failure",
  "Incident Report: Improvement-level Plan",
  "Performance conflict detected",
  "Sub-standard Goal Error",
  "Absolute Sub-standard architecture",
  "Warning-level Plan Error",
  "The PIP tragedy",
  "Poor Goal Error",
  "Failed to compile: Manager",
  "Improvement-level Manager Loop",
  "Incident Report: Poor Manager",
  "Standard conflict detected",
  "Failed to compile: PIP",
  "Formal Manager Error",
  "The Plan tragedy",
  "Standard Not Found",
  "The Warning tragedy",
  "The Employee tragedy",
  "Incident Report: Improvement-level PIP",
  "Performance Not Found",
  "Formal Goal Error",
  "Failed to compile: Standard",
  "The Standard tragedy",
  "Critical Warning failure",
  "Absolute Critical architecture",
  "Critical Plan failure",
  "Absolute Warning-level architecture",
  "Absolute Deficient architecture",
  "Warning Not Found",
  "Failed to compile: Plan",
  "Average Metrics Error",
  "Deficient Employee Error",
  "NullPointerMetricsException",
  "Failed to compile: Goal",
  "NullPointerWarningException",
  "Incident Report: Poor Plan",
  "PIP Not Found",
  "Manager conflict detected",
  "Failed to compile: Metrics",
  "Critical Standard failure",
  "Average Warning Error",
  "NullPointerPIPException",
  "PIP conflict detected",
  "Employee Not Found",
  "NullPointerStandardException",
  "The Metrics tragedy",
  "Critical Metrics failure",
  "Critical Goal failure",
  "NullPointerGoalException",
  "Improvement-level Manager Error",
  "Formal Manager Loop",
  "Critical Manager Loop",
  "Average Performance Error",
  "Average Employee Loop",
  "Goal conflict detected",
  "Critical Manager failure",
  "Metrics Not Found",
  "Poor Manager Error",
  "Incident Report: Improvement-level Standard",
  "Warning-level Employee Loop",
  "Absolute Average architecture",
  "Warning-level Metrics Error",
  "Plan conflict detected",
  "Improvement-level Performance Loop",
  "The Performance tragedy",
  "Poor Employee Error",
  "Failed to compile: Performance",
  "The Manager tragedy",
  "Manager Not Found",
  "Warning conflict detected",
  "Incident Report: Formal Plan",
  "Incident Report: Critical Standard",
  "Deficient Goal Error",
  "Incident Report: Improvement-level Period",
  "Deficient Period Error",
  "Incident Report: Average Period",
  "Incident Report: Deficient Metrics",
  "NullPointerPlanException",
  "Critical PIP failure",
  "Formal Goal Loop"
];

export const openings = [
  "Scanning candidate profile for formal periods...",
  "The team has initiated audit for the candidate's PIP setup.",
  "A review was filed regarding a sub-standard goal.",
  "Initial evaluation shows the developer decided to evaluated poor metrics under close monitoring.",
  "Scanning candidate profile for improvement-level metricss...",
  "We checked the history and found a formal PIP log.",
  "Scanning candidate profile for formal standards...",
  "Alert: The candidate spent three months trying to evaluated poor metrics in 30 days.",
  "Recruiters reported a case of deficient metrics design.",
  "Warning: System flagged an attempt to placed on PIP due to failure.",
  "A review was filed regarding a critical period.",
  "Initial evaluation shows the developer decided to reviewed formal plan under close monitoring.",
  "Recruiters reported a case of deficient employee design.",
  "Warning: System flagged an attempt to placed on PIP without compensation.",
  "Alert: The candidate spent three months trying to evaluated poor metrics without compensation.",
  "We checked the history and found a poor PIP log.",
  "Recruiters reported a case of average period design.",
  "Recruiters reported a case of critical performance design.",
  "Recruiters reported a case of formal warning design.",
  "A review was filed regarding a critical manager.",
  "Scanning candidate profile for warning-level goals...",
  "A review was filed regarding a formal plan.",
  "Scanning candidate profile for critical periods...",
  "We checked the history and found a poor employee log.",
  "A review was filed regarding a improvement-level goal.",
  "A review was filed regarding a formal period.",
  "Warning: System flagged an attempt to reviewed formal plan due to failure.",
  "Warning: System flagged an attempt to evaluated poor metrics starting immediately.",
  "We checked the history and found a improvement-level PIP log.",
  "Recruiters reported a case of deficient plan design.",
  "A review was filed regarding a deficient metrics.",
  "Initial evaluation shows the developer decided to evaluated poor metrics in 30 days.",
  "Recruiters reported a case of average metrics design.",
  "Recruiters reported a case of poor metrics design.",
  "Alert: The candidate spent three months trying to reviewed formal plan without compensation.",
  "We checked the history and found a sub-standard plan log.",
  "We checked the history and found a critical metrics log.",
  "Scanning candidate profile for deficient PIPs...",
  "Warning: System flagged an attempt to warned deficient employee in 30 days.",
  "Recruiters reported a case of sub-standard standard design.",
  "Warning: System flagged an attempt to warned deficient employee under close monitoring.",
  "Recruiters reported a case of critical employee design.",
  "We checked the history and found a deficient performance log.",
  "We checked the history and found a critical goal log.",
  "Scanning candidate profile for sub-standard standards...",
  "A review was filed regarding a poor manager.",
  "Initial evaluation shows the developer decided to reviewed formal plan due to failure.",
  "Scanning candidate profile for deficient periods...",
  "Initial evaluation shows the developer decided to placed on PIP in 30 days.",
  "Initial evaluation shows the developer decided to warned deficient employee under close monitoring.",
  "Initial evaluation shows the developer decided to evaluated poor metrics starting immediately.",
  "A review was filed regarding a poor standard.",
  "Scanning candidate profile for average metricss...",
  "A review was filed regarding a deficient plan.",
  "Warning: System flagged an attempt to failed standard goal due to failure.",
  "Recruiters reported a case of average employee design.",
  "Initial evaluation shows the developer decided to placed on PIP without compensation.",
  "A review was filed regarding a warning-level manager.",
  "Initial evaluation shows the developer decided to failed standard goal under close monitoring.",
  "Alert: The candidate spent three months trying to failed standard goal starting immediately.",
  "A review was filed regarding a average PIP.",
  "Scanning candidate profile for average employees...",
  "Recruiters reported a case of poor standard design.",
  "Recruiters reported a case of improvement-level employee design.",
  "A review was filed regarding a average manager.",
  "A review was filed regarding a formal manager.",
  "Warning: System flagged an attempt to warned deficient employee due to failure.",
  "Scanning candidate profile for average performances...",
  "Scanning candidate profile for sub-standard employees...",
  "Scanning candidate profile for improvement-level standards...",
  "Warning: System flagged an attempt to placed on PIP under close monitoring.",
  "We checked the history and found a formal standard log.",
  "We checked the history and found a average plan log.",
  "Warning: System flagged an attempt to evaluated poor metrics without compensation.",
  "A review was filed regarding a average metrics.",
  "Initial evaluation shows the developer decided to warned deficient employee without compensation.",
  "Initial evaluation shows the developer decided to reviewed formal plan without compensation.",
  "A review was filed regarding a warning-level PIP.",
  "Initial evaluation shows the developer decided to warned deficient employee due to failure.",
  "Recruiters reported a case of formal performance design.",
  "A review was filed regarding a warning-level performance.",
  "A review was filed regarding a average warning."
];

export const findings = [
  "Obtained {{certification}} which apparently teaches how to placed on PIP under close monitoring.",
  "Obtained {{certification}} which apparently teaches how to placed on PIP starting immediately.",
  "Failed to configure {{project}} because {{candidateName}} decided to placed on PIP due to failure.",
  "While debugging {{project}}, we found a critical logic loop related to {{language}} features.",
  "Obtained {{certification}} which apparently teaches how to evaluated poor metrics due to failure.",
  "Obtained {{certification}} which apparently teaches how to evaluated poor metrics starting immediately.",
  "{{education}} is listed, but they still managed to deploy a deficient standard to production.",
  "A security audit on {{github}} detected a plain-text database password inside a formal period.",
  "Failed to configure {{project}} because {{candidateName}} decided to evaluated poor metrics due to failure.",
  "{{github}} contains more critical warnings than original code.",
  "{{github}} contains more improvement-level employees than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a improvement-level manager.",
  "{{achievement}} was highlighted, but the git logs show they only managed to placed on PIP starting immediately.",
  "Failed to configure {{project}} because {{candidateName}} decided to failed standard goal due to failure.",
  "{{candidateName}} has spent three weeks optimizing a warning while completely ignoring {{missingSection}}.",
  "The candidate claims {{framework}} experience, but their repository is just a sub-standard clone that has been abandoned.",
  "Listed {{skill}} as a primary competency, but the evidence points to a critical goal.",
  "For {{experience}}, the primary contribution was writing a deficient config for a standard.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to evaluated poor metrics due to failure.",
  "The candidate claims {{framework}} experience, but their repository is just a improvement-level clone that has been abandoned.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to warned deficient employee starting immediately.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to placed on PIP under close monitoring.",
  "Failed to configure {{project}} because {{candidateName}} decided to reviewed formal plan starting immediately.",
  "A security audit on {{github}} detected a plain-text database password inside a deficient manager.",
  "{{achievement}} was highlighted, but the git logs show they only managed to failed standard goal starting immediately.",
  "While debugging {{project}}, we found a sub-standard logic loop related to {{language}} features.",
  "Listed {{skill}} as a primary competency, but the evidence points to a sub-standard PIP.",
  "{{github}} contains more deficient plans than original code.",
  "Obtained {{certification}} which apparently teaches how to reviewed formal plan under close monitoring.",
  "Obtained {{certification}} which apparently teaches how to placed on PIP in 30 days.",
  "{{achievement}} was highlighted, but the git logs show they only managed to evaluated poor metrics without compensation.",
  "Obtained {{certification}} which apparently teaches how to reviewed formal plan in 30 days.",
  "Listed {{skill}} as a primary competency, but the evidence points to a poor plan.",
  "Obtained {{certification}} which apparently teaches how to evaluated poor metrics without compensation.",
  "For {{experience}}, the primary contribution was writing a average config for a PIP.",
  "Failed to configure {{project}} because {{candidateName}} decided to warned deficient employee under close monitoring.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to placed on PIP without compensation.",
  "Failed to configure {{project}} because {{candidateName}} decided to reviewed formal plan in 30 days.",
  "A security audit on {{github}} detected a plain-text database password inside a sub-standard plan.",
  "For {{experience}}, the primary contribution was writing a improvement-level config for a PIP.",
  "Listed {{skill}} as a primary competency, but the evidence points to a formal metrics.",
  "Failed to configure {{project}} because {{candidateName}} decided to reviewed formal plan under close monitoring.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to failed standard goal starting immediately.",
  "Failed to configure {{project}} because {{candidateName}} decided to reviewed formal plan due to failure.",
  "{{achievement}} was highlighted, but the git logs show they only managed to placed on PIP without compensation.",
  "{{achievement}} was highlighted, but the git logs show they only managed to placed on PIP due to failure.",
  "{{github}} contains more average managers than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to placed on PIP starting immediately.",
  "{{github}} contains more sub-standard performances than original code.",
  "{{github}} contains more deficient PIPs than original code.",
  "While debugging {{project}}, we found a improvement-level logic loop related to {{language}} features.",
  "Failed to configure {{project}} because {{candidateName}} decided to warned deficient employee due to failure.",
  "Failed to configure {{project}} because {{candidateName}} decided to failed standard goal without compensation.",
  "{{github}} contains more warning-level PIPs than original code.",
  "Obtained {{certification}} which apparently teaches how to warned deficient employee starting immediately.",
  "{{github}} contains more critical employees than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to warned deficient employee starting immediately.",
  "Failed to configure {{project}} because {{candidateName}} decided to failed standard goal under close monitoring.",
  "{{achievement}} was highlighted, but the git logs show they only managed to evaluated poor metrics starting immediately.",
  "{{education}} is listed, but they still managed to deploy a critical manager to production.",
  "Obtained {{certification}} which apparently teaches how to failed standard goal starting immediately.",
  "For {{experience}}, the primary contribution was writing a sub-standard config for a goal.",
  "{{education}} is listed, but they still managed to deploy a poor period to production.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to warned deficient employee without compensation.",
  "Failed to configure {{project}} because {{candidateName}} decided to evaluated poor metrics under close monitoring.",
  "For {{experience}}, the primary contribution was writing a critical config for a performance.",
  "{{github}} contains more deficient performances than original code.",
  "Obtained {{certification}} which apparently teaches how to reviewed formal plan without compensation.",
  "For {{experience}}, the primary contribution was writing a poor config for a goal.",
  "Listed {{skill}} as a primary competency, but the evidence points to a warning-level metrics.",
  "{{github}} contains more poor standards than original code.",
  "{{github}} contains more poor periods than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a critical goal.",
  "{{github}} contains more formal goals than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to warned deficient employee without compensation.",
  "Failed to configure {{project}} because {{candidateName}} decided to evaluated poor metrics in 30 days.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to warned deficient employee due to failure.",
  "{{education}} is listed, but they still managed to deploy a formal plan to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to failed standard goal without compensation.",
  "A security audit on {{github}} detected a plain-text database password inside a poor plan.",
  "{{education}} is listed, but they still managed to deploy a sub-standard metrics to production.",
  "Obtained {{certification}} which apparently teaches how to evaluated poor metrics in 30 days.",
  "{{github}} contains more formal periods than original code.",
  "{{github}} contains more critical standards than original code.",
  "Listed {{skill}} as a primary competency, but the evidence points to a improvement-level plan.",
  "Obtained {{certification}} which apparently teaches how to failed standard goal due to failure.",
  "Failed to configure {{project}} because {{candidateName}} decided to placed on PIP under close monitoring.",
  "Failed to configure {{project}} because {{candidateName}} decided to failed standard goal in 30 days.",
  "A security audit on {{github}} detected a plain-text database password inside a warning-level warning.",
  "Obtained {{certification}} which apparently teaches how to failed standard goal under close monitoring.",
  "For {{experience}}, the primary contribution was writing a formal config for a plan.",
  "Obtained {{certification}} which apparently teaches how to placed on PIP due to failure.",
  "Failed to configure {{project}} because {{candidateName}} decided to evaluated poor metrics without compensation.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to failed standard goal under close monitoring.",
  "{{github}} contains more critical managers than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to reviewed formal plan without compensation.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to failed standard goal due to failure.",
  "Obtained {{certification}} which apparently teaches how to reviewed formal plan due to failure.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to evaluated poor metrics starting immediately.",
  "{{education}} is listed, but they still managed to deploy a average employee to production.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to warned deficient employee under close monitoring.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to reviewed formal plan under close monitoring.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to reviewed formal plan in 30 days.",
  "{{github}} contains more deficient managers than original code.",
  "For {{experience}}, the primary contribution was writing a warning-level config for a warning.",
  "Obtained {{certification}} which apparently teaches how to placed on PIP without compensation.",
  "{{github}} contains more average goals than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to reviewed formal plan starting immediately.",
  "{{github}} contains more formal performances than original code.",
  "{{github}} contains more critical PIPs than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to warned deficient employee without compensation.",
  "{{achievement}} was highlighted, but the git logs show they only managed to failed standard goal under close monitoring.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to placed on PIP due to failure.",
  "{{achievement}} was highlighted, but the git logs show they only managed to evaluated poor metrics due to failure.",
  "Failed to configure {{project}} because {{candidateName}} decided to warned deficient employee starting immediately.",
  "{{achievement}} was highlighted, but the git logs show they only managed to failed standard goal due to failure."
];

export const punchlines = [
  "Even Stack Overflow has marked this warning as off-topic.",
  "It did not optimize our process, but it did make the laptop fan spin like a jet engine.",
  "Legend says this warning-level metrics is still running on localhost.",
  "A junior developer looked at the employee and immediately went to touch grass.",
  "We would deploy it to production, but our SRE team deserves to sleep at night.",
  "The only thing memory-safe about this setup is that nobody has ever tried to run it.",
  "The compiler requested emotional support after reading the deficient code.",
  "The compiler requested emotional support after reading the warning-level code.",
  "Legend says this average manager is still running on localhost.",
  "The documentation was so empty, I had to use it as a virtual sketchbook.",
  "Legend says this formal PIP is still running on localhost.",
  "Legend says this formal performance is still running on localhost.",
  "The compiler requested emotional support after reading the sub-standard code.",
  "Legend says this sub-standard goal is still running on localhost.",
  "Legend says this deficient standard is still running on localhost.",
  "Legend says this formal warning is still running on localhost.",
  "Legend says this deficient employee is still running on localhost.",
  "Legend says this improvement-level employee is still running on localhost.",
  "Legend says this poor employee is still running on localhost.",
  "Legend says this average goal is still running on localhost.",
  "Legend says this average period is still running on localhost.",
  "Legend says this formal metrics is still running on localhost.",
  "Legend says this critical goal is still running on localhost.",
  "Legend says this formal employee is still running on localhost.",
  "Legend says this average standard is still running on localhost.",
  "Legend says this formal manager is still running on localhost.",
  "Legend says this average employee is still running on localhost.",
  "Legend says this critical metrics is still running on localhost.",
  "Legend says this deficient goal is still running on localhost.",
  "Legend says this poor performance is still running on localhost.",
  "Legend says this average performance is still running on localhost.",
  "Legend says this critical PIP is still running on localhost.",
  "Legend says this critical standard is still running on localhost.",
  "Legend says this formal goal is still running on localhost.",
  "Legend says this deficient manager is still running on localhost.",
  "Legend says this critical warning is still running on localhost.",
  "Legend says this formal period is still running on localhost.",
  "Legend says this poor manager is still running on localhost.",
  "Legend says this critical performance is still running on localhost.",
  "Legend says this poor warning is still running on localhost.",
  "Legend says this formal plan is still running on localhost.",
  "Legend says this poor plan is still running on localhost.",
  "Legend says this deficient warning is still running on localhost.",
  "Legend says this critical period is still running on localhost.",
  "Legend says this deficient period is still running on localhost.",
  "Legend says this average plan is still running on localhost.",
  "Legend says this poor PIP is still running on localhost.",
  "Legend says this deficient plan is still running on localhost.",
  "Legend says this deficient PIP is still running on localhost.",
  "Legend says this poor goal is still running on localhost.",
  "Legend says this deficient metrics is still running on localhost.",
  "Legend says this average warning is still running on localhost.",
  "Legend says this formal standard is still running on localhost.",
  "This is a classic example of a deficient employee disaster.",
  "This is a classic example of a deficient standard disaster.",
  "This is a classic example of a critical employee disaster.",
  "This is a classic example of a improvement-level warning disaster.",
  "This is a classic example of a formal warning disaster.",
  "This is a classic example of a deficient period disaster.",
  "This is a classic example of a formal PIP disaster.",
  "This is a classic example of a formal plan disaster.",
  "This is a classic example of a formal performance disaster.",
  "This is a classic example of a poor standard disaster.",
  "This is a classic example of a poor PIP disaster.",
  "This is a classic example of a average warning disaster.",
  "This is a classic example of a sub-standard employee disaster.",
  "This is a classic example of a improvement-level employee disaster.",
  "This is a classic example of a warning-level PIP disaster.",
  "This is a classic example of a poor warning disaster.",
  "This is a classic example of a improvement-level performance disaster.",
  "This is a classic example of a critical manager disaster.",
  "This is a classic example of a critical metrics disaster.",
  "This is a classic example of a average goal disaster.",
  "This is a classic example of a critical standard disaster.",
  "This is a classic example of a poor employee disaster.",
  "This is a classic example of a critical PIP disaster.",
  "This is a classic example of a deficient manager disaster.",
  "This is a classic example of a sub-standard PIP disaster.",
  "This is a classic example of a warning-level performance disaster.",
  "This is a classic example of a improvement-level metrics disaster.",
  "This is a classic example of a warning-level plan disaster.",
  "This is a classic example of a critical goal disaster.",
  "This is a classic example of a average period disaster.",
  "This is a classic example of a sub-standard performance disaster.",
  "This is a classic example of a formal manager disaster.",
  "This is a classic example of a formal employee disaster.",
  "This is a classic example of a sub-standard warning disaster.",
  "This is a classic example of a deficient warning disaster.",
  "This is a classic example of a average plan disaster."
];

export const verdicts = [
  "Closed as average duplicate.",
  "Rejected on first principles of standard organization.",
  "Rejected on first principles of plan organization.",
  "Closed as warning-level duplicate.",
  "Verdict: Warning is completely unmergeable.",
  "Return after touching actual production servers.",
  "Verdict: Performance is completely unmergeable.",
  "PR reviewed formal plan due to poor implementation.",
  "Verdict: Manager is completely unmergeable.",
  "PR placed on PIP due to deficient implementation.",
  "Rejected on first principles of employee organization.",
  "Rejected on first principles of manager organization.",
  "Needs more commits and fewer explanations.",
  "Request changes on the formal goal.",
  "Verdict: Goal is completely unmergeable.",
  "Ship blocked by average check failures.",
  "PR failed standard goal due to average implementation.",
  "PR warned deficient employee due to improvement-level implementation.",
  "Ship blocked by warning-level check failures.",
  "Verdict: Plan is completely unmergeable.",
  "Rejected on first principles of performance organization.",
  "Ship blocked by sub-standard check failures.",
  "Closed as improvement-level duplicate.",
  "Request changes on the critical plan.",
  "Request changes on the average warning.",
  "Request changes on the average standard.",
  "Request changes on the average plan.",
  "Verdict: Period is completely unmergeable.",
  "PR evaluated poor metrics due to warning-level implementation.",
  "Closed as deficient duplicate.",
  "Closed as sub-standard duplicate.",
  "PR warned deficient employee due to average implementation.",
  "Ship blocked by deficient check failures.",
  "Ship blocked by poor check failures.",
  "Ship blocked by critical check failures.",
  "PR failed standard goal due to warning-level implementation.",
  "PR evaluated poor metrics due to average implementation.",
  "Rejected on first principles of PIP organization.",
  "Rejected on first principles of period organization.",
  "Request changes on the improvement-level standard.",
  "PR reviewed formal plan due to critical implementation.",
  "PR warned deficient employee due to formal implementation.",
  "Request changes on the warning-level goal.",
  "PR warned deficient employee due to warning-level implementation.",
  "Ship blocked by improvement-level check failures.",
  "Request changes on the sub-standard standard.",
  "Closed as poor duplicate.",
  "PR placed on PIP due to sub-standard implementation.",
  "Closed as formal duplicate.",
  "Request changes on the improvement-level goal.",
  "Verdict: Standard is completely unmergeable.",
  "PR warned deficient employee due to poor implementation.",
  "PR reviewed formal plan due to sub-standard implementation.",
  "PR reviewed formal plan due to warning-level implementation.",
  "PR evaluated poor metrics due to critical implementation.",
  "Verdict: PIP is completely unmergeable.",
  "Verdict: Metrics is completely unmergeable.",
  "Request changes on the formal standard.",
  "Request changes on the critical employee.",
  "Request changes on the deficient period.",
  "Request changes on the critical manager.",
  "Request changes on the average goal.",
  "Request changes on the critical standard.",
  "Request changes on the average performance.",
  "Request changes on the critical goal.",
  "Request changes on the critical period.",
  "Request changes on the formal metrics.",
  "PR failed standard goal due to poor implementation.",
  "Request changes on the improvement-level employee.",
  "Request changes on the deficient employee.",
  "PR placed on PIP due to average implementation.",
  "Request changes on the deficient performance.",
  "PR reviewed formal plan due to improvement-level implementation.",
  "Closed as critical duplicate.",
  "PR placed on PIP due to poor implementation.",
  "Request changes on the poor plan.",
  "PR failed standard goal due to critical implementation.",
  "Rejected on first principles of goal organization.",
  "Rejected on first principles of warning organization.",
  "Verdict: Employee is completely unmergeable.",
  "Request changes on the deficient PIP.",
  "Ship blocked by formal check failures.",
  "PR failed standard goal due to deficient implementation.",
  "Request changes on the formal employee.",
  "Request changes on the average PIP.",
  "Request changes on the poor performance.",
  "PR warned deficient employee due to critical implementation.",
  "Request changes on the average employee.",
  "Request changes on the critical metrics.",
  "PR reviewed formal plan due to deficient implementation.",
  "Request changes on the deficient standard.",
  "Request changes on the improvement-level metrics.",
  "PR placed on PIP due to warning-level implementation.",
  "Request changes on the average period.",
  "Request changes on the formal warning."
];

export const easterEggs = [
  "Matrix Glitch: You copy-pasted a template and now the server believes it is a real founder.",
  "Gordon Ramsay Meltdown: 'This warning is raw! It's absolutely raw!'",
  "NASA Alert: Space mission aborted due to a minor period parsing error.",
  "Elon Musk Tweet: 'Just deleted the entire employee pipeline, was completely useless.'",
  "Steam Achievement Unlocked: Successfully crashed a hello-world app on a $10,000 server.",
  "Dark Web Resume Auction: Current bid is $0.00, and the buyer is requesting a refund.",
  "Gordon Ramsay Meltdown: 'This plan is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted average goals.",
  "Gordon Ramsay Meltdown: 'This PIP is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This employee is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted deficient performances.",
  "FBI Investigation: Suspect was found deploying unencrypted critical employees.",
  "Gordon Ramsay Meltdown: 'This goal is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted sub-standard metricss.",
  "Gordon Ramsay Meltdown: 'This manager is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This performance is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted improvement-level performances.",
  "FBI Investigation: Suspect was found deploying unencrypted formal periods.",
  "Gordon Ramsay Meltdown: 'This period is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This standard is raw! It's absolutely raw!'"
];
