// ES Module exports for court_verdict roast format
export const titles = [
  "The Crime tragedy",
  "Critical Jury failure",
  "Suspicious Trial Error",
  "NullPointerTrialException",
  "Absolute Illegal architecture",
  "Incident Report: Illegal Sentence",
  "Stolen Verdict Error",
  "Faulty Trial Loop",
  "Incident Report: Faulty Trial",
  "Absolute Faulty architecture",
  "Guilty Codebase Loop",
  "Critical Crime failure",
  "Copy-pasted Crime Loop",
  "Stolen Judge Error",
  "Faulty Theft Error",
  "Copy-pasted Theft Error",
  "Incident Report: Illegal Trial",
  "The Evidence tragedy",
  "Load-bearing Theft Loop",
  "Failed to compile: Sentence",
  "Illegal Felony Error",
  "Codebase conflict detected",
  "Absolute Suspicious architecture",
  "Suspicious Evidence Error",
  "Incident Report: Illegal Evidence",
  "NullPointerCodebaseException",
  "The Verdict tragedy",
  "Incident Report: Stolen Sentence",
  "Incident Report: Guilty Trial",
  "Incident Report: Faulty Sentence",
  "Failed to compile: Jury",
  "Absolute Guilty architecture",
  "Critical Theft failure",
  "Critical Evidence failure",
  "NullPointerEvidenceException",
  "Sentence Not Found",
  "Failed to compile: Evidence",
  "Guilty Theft Error",
  "Critical Felony failure",
  "The Felony tragedy",
  "Faulty Theft Loop",
  "Load-bearing Codebase Loop",
  "Copy-pasted Sentence Loop",
  "Failed to compile: Judge",
  "NullPointerVerdictException",
  "Felony conflict detected",
  "Load-bearing Sentence Error",
  "Verdict Not Found",
  "Judge Not Found",
  "NullPointerTheftException",
  "Incident Report: Illegal Felony",
  "NullPointerJuryException",
  "Verdict conflict detected",
  "Theft conflict detected",
  "Critical Judge failure",
  "Failed to compile: Trial",
  "Load-bearing Trial Error",
  "Critical Trial failure",
  "The Codebase tragedy",
  "Failed to compile: Felony",
  "The Theft tragedy",
  "Absolute Unlawful architecture",
  "Stolen Crime Error",
  "Guilty Trial Loop",
  "Absolute Copy-pasted architecture",
  "Codebase Not Found",
  "Incident Report: Copy-pasted Verdict",
  "Felony Not Found",
  "Critical Verdict failure",
  "Unlawful Codebase Loop",
  "Copy-pasted Jury Error",
  "Stolen Sentence Error",
  "Absolute Load-bearing architecture",
  "Evidence conflict detected",
  "Crime Not Found",
  "Incident Report: Faulty Evidence",
  "Incident Report: Load-bearing Theft",
  "Suspicious Verdict Loop",
  "The Trial tragedy",
  "The Judge tragedy",
  "Incident Report: Unlawful Sentence",
  "Failed to compile: Codebase",
  "Crime conflict detected",
  "Illegal Codebase Error",
  "Incident Report: Load-bearing Evidence",
  "Incident Report: Copy-pasted Felony",
  "Incident Report: Suspicious Trial",
  "Critical Codebase failure",
  "Faulty Judge Loop",
  "Evidence Not Found",
  "Unlawful Sentence Loop",
  "Trial conflict detected",
  "Faulty Crime Loop",
  "Incident Report: Stolen Judge",
  "Jury Not Found",
  "Incident Report: Guilty Evidence",
  "Incident Report: Faulty Jury",
  "NullPointerCrimeException",
  "Faulty Crime Error",
  "Theft Not Found"
];

export const openings = [
  "Warning: System flagged an attempt to sentenced suspect developer to standard bootstrap tasks.",
  "Initial evaluation shows the developer decided to committed codebase theft on all felony counts.",
  "The team has initiated audit for the candidate's crime setup.",
  "Scanning candidate profile for faulty felonys...",
  "Recruiters reported a case of unlawful codebase design.",
  "We checked the history and found a stolen jury log.",
  "We checked the history and found a illegal theft log.",
  "Scanning candidate profile for stolen crimes...",
  "Initial evaluation shows the developer decided to convicted for duplicate code to standard bootstrap tasks.",
  "A review was filed regarding a suspicious verdict.",
  "We checked the history and found a guilty crime log.",
  "We checked the history and found a illegal verdict log.",
  "Recruiters reported a case of stolen judge design.",
  "Alert: The candidate spent three months trying to audited suspect commits without chance of parole.",
  "Initial evaluation shows the developer decided to audited suspect commits to standard bootstrap tasks.",
  "A review was filed regarding a suspicious judge.",
  "Scanning candidate profile for stolen verdicts...",
  "Recruiters reported a case of faulty codebase design.",
  "We checked the history and found a faulty verdict log.",
  "Scanning candidate profile for load-bearing verdicts...",
  "Scanning candidate profile for faulty jurys...",
  "Warning: System flagged an attempt to sentenced suspect developer with maximum sentence.",
  "We checked the history and found a copy-pasted trial log.",
  "We checked the history and found a suspicious verdict log.",
  "Recruiters reported a case of suspicious jury design.",
  "Alert: The candidate spent three months trying to audited suspect commits to lifetime of debugging.",
  "We checked the history and found a stolen sentence log.",
  "A review was filed regarding a load-bearing verdict.",
  "Alert: The candidate spent three months trying to reviewed case evidence with maximum sentence.",
  "Recruiters reported a case of stolen theft design.",
  "Recruiters reported a case of faulty crime design.",
  "Warning: System flagged an attempt to reviewed case evidence to standard bootstrap tasks.",
  "We checked the history and found a stolen trial log.",
  "Warning: System flagged an attempt to sentenced suspect developer without chance of parole.",
  "We checked the history and found a load-bearing judge log.",
  "Alert: The candidate spent three months trying to reviewed case evidence without chance of parole.",
  "Warning: System flagged an attempt to sentenced suspect developer to lifetime of debugging.",
  "Alert: The candidate spent three months trying to convicted for duplicate code on all felony counts.",
  "Recruiters reported a case of copy-pasted crime design.",
  "Scanning candidate profile for guilty trials...",
  "Initial evaluation shows the developer decided to convicted for duplicate code on all felony counts.",
  "Warning: System flagged an attempt to reviewed case evidence with maximum sentence.",
  "Scanning candidate profile for guilty jurys...",
  "Scanning candidate profile for stolen evidences...",
  "Initial evaluation shows the developer decided to convicted for duplicate code with maximum sentence.",
  "A review was filed regarding a load-bearing sentence.",
  "A review was filed regarding a guilty theft.",
  "We checked the history and found a guilty verdict log.",
  "Initial evaluation shows the developer decided to sentenced suspect developer on all felony counts.",
  "Warning: System flagged an attempt to convicted for duplicate code to lifetime of debugging.",
  "Initial evaluation shows the developer decided to reviewed case evidence to lifetime of debugging.",
  "We checked the history and found a faulty codebase log.",
  "Scanning candidate profile for unlawful jurys...",
  "Alert: The candidate spent three months trying to convicted for duplicate code with maximum sentence.",
  "We checked the history and found a suspicious sentence log.",
  "A review was filed regarding a guilty judge.",
  "Recruiters reported a case of copy-pasted codebase design.",
  "Recruiters reported a case of stolen evidence design.",
  "Scanning candidate profile for stolen trials...",
  "Warning: System flagged an attempt to reviewed case evidence without chance of parole.",
  "Recruiters reported a case of unlawful jury design.",
  "Warning: System flagged an attempt to committed codebase theft with maximum sentence.",
  "Warning: System flagged an attempt to audited suspect commits to lifetime of debugging.",
  "A review was filed regarding a guilty felony.",
  "Scanning candidate profile for faulty evidences...",
  "Scanning candidate profile for illegal judges...",
  "We checked the history and found a stolen codebase log.",
  "Initial evaluation shows the developer decided to reviewed case evidence with maximum sentence.",
  "Recruiters reported a case of unlawful felony design.",
  "A review was filed regarding a suspicious crime.",
  "Alert: The candidate spent three months trying to reviewed case evidence to lifetime of debugging.",
  "A review was filed regarding a stolen theft.",
  "Initial evaluation shows the developer decided to sentenced suspect developer to standard bootstrap tasks.",
  "Warning: System flagged an attempt to convicted for duplicate code without chance of parole.",
  "A review was filed regarding a faulty judge.",
  "We checked the history and found a guilty felony log.",
  "Scanning candidate profile for unlawful felonys...",
  "Alert: The candidate spent three months trying to committed codebase theft to standard bootstrap tasks.",
  "Scanning candidate profile for copy-pasted trials...",
  "Warning: System flagged an attempt to reviewed case evidence on all felony counts.",
  "Recruiters reported a case of illegal jury design.",
  "We checked the history and found a unlawful jury log.",
  "Recruiters reported a case of stolen trial design.",
  "Warning: System flagged an attempt to reviewed case evidence to lifetime of debugging.",
  "Alert: The candidate spent three months trying to audited suspect commits to standard bootstrap tasks.",
  "Recruiters reported a case of load-bearing theft design."
];

export const findings = [
  "Obtained {{certification}} which apparently teaches how to sentenced suspect developer without chance of parole.",
  "Failed to configure {{project}} because {{candidateName}} decided to audited suspect commits on all felony counts.",
  "Listed {{skill}} as a primary competency, but the evidence points to a suspicious felony.",
  "{{education}} is listed, but they still managed to deploy a illegal verdict to production.",
  "For {{experience}}, the primary contribution was writing a guilty config for a felony.",
  "The candidate claims {{framework}} experience, but their repository is just a stolen clone that has been abandoned.",
  "{{candidateName}} has spent three weeks optimizing a verdict while completely ignoring {{missingSection}}.",
  "{{github}} contains more load-bearing codebases than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a unlawful codebase.",
  "Listed {{skill}} as a primary competency, but the evidence points to a unlawful codebase.",
  "While debugging {{project}}, we found a guilty logic loop related to {{language}} features.",
  "Listed {{skill}} as a primary competency, but the evidence points to a load-bearing jury.",
  "Obtained {{certification}} which apparently teaches how to audited suspect commits to lifetime of debugging.",
  "Listed {{skill}} as a primary competency, but the evidence points to a illegal evidence.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to audited suspect commits to lifetime of debugging.",
  "{{achievement}} was highlighted, but the git logs show they only managed to convicted for duplicate code on all felony counts.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to sentenced suspect developer without chance of parole.",
  "Failed to configure {{project}} because {{candidateName}} decided to audited suspect commits with maximum sentence.",
  "{{github}} contains more copy-pasted evidences than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to committed codebase theft on all felony counts.",
  "A security audit on {{github}} detected a plain-text database password inside a stolen jury.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to reviewed case evidence with maximum sentence.",
  "{{education}} is listed, but they still managed to deploy a stolen crime to production.",
  "Obtained {{certification}} which apparently teaches how to reviewed case evidence with maximum sentence.",
  "A security audit on {{github}} detected a plain-text database password inside a load-bearing codebase.",
  "Listed {{skill}} as a primary competency, but the evidence points to a stolen theft.",
  "{{achievement}} was highlighted, but the git logs show they only managed to sentenced suspect developer with maximum sentence.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to audited suspect commits on all felony counts.",
  "{{github}} contains more illegal verdicts than original code.",
  "{{github}} contains more unlawful trials than original code.",
  "Obtained {{certification}} which apparently teaches how to committed codebase theft to standard bootstrap tasks.",
  "A security audit on {{github}} detected a plain-text database password inside a copy-pasted trial.",
  "Failed to configure {{project}} because {{candidateName}} decided to committed codebase theft without chance of parole.",
  "{{education}} is listed, but they still managed to deploy a copy-pasted crime to production.",
  "A security audit on {{github}} detected a plain-text database password inside a suspicious theft.",
  "For {{experience}}, the primary contribution was writing a unlawful config for a judge.",
  "Obtained {{certification}} which apparently teaches how to sentenced suspect developer to standard bootstrap tasks.",
  "Obtained {{certification}} which apparently teaches how to audited suspect commits on all felony counts.",
  "Failed to configure {{project}} because {{candidateName}} decided to sentenced suspect developer on all felony counts.",
  "A security audit on {{github}} detected a plain-text database password inside a faulty judge.",
  "{{github}} contains more unlawful thefts than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to committed codebase theft to standard bootstrap tasks.",
  "Failed to configure {{project}} because {{candidateName}} decided to convicted for duplicate code on all felony counts.",
  "{{education}} is listed, but they still managed to deploy a faulty judge to production.",
  "For {{experience}}, the primary contribution was writing a load-bearing config for a felony.",
  "A security audit on {{github}} detected a plain-text database password inside a guilty evidence.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to convicted for duplicate code without chance of parole.",
  "Listed {{skill}} as a primary competency, but the evidence points to a copy-pasted sentence.",
  "Failed to configure {{project}} because {{candidateName}} decided to convicted for duplicate code to lifetime of debugging.",
  "Obtained {{certification}} which apparently teaches how to committed codebase theft with maximum sentence.",
  "Failed to configure {{project}} because {{candidateName}} decided to sentenced suspect developer with maximum sentence.",
  "While debugging {{project}}, we found a copy-pasted logic loop related to {{language}} features.",
  "{{achievement}} was highlighted, but the git logs show they only managed to committed codebase theft without chance of parole.",
  "Obtained {{certification}} which apparently teaches how to convicted for duplicate code to standard bootstrap tasks.",
  "Obtained {{certification}} which apparently teaches how to reviewed case evidence on all felony counts.",
  "Listed {{skill}} as a primary competency, but the evidence points to a faulty trial.",
  "Failed to configure {{project}} because {{candidateName}} decided to reviewed case evidence with maximum sentence.",
  "For {{experience}}, the primary contribution was writing a copy-pasted config for a codebase.",
  "Failed to configure {{project}} because {{candidateName}} decided to convicted for duplicate code to standard bootstrap tasks.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to sentenced suspect developer on all felony counts.",
  "Obtained {{certification}} which apparently teaches how to audited suspect commits with maximum sentence.",
  "{{github}} contains more unlawful felonys than original code.",
  "{{github}} contains more illegal felonys than original code.",
  "{{github}} contains more suspicious verdicts than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to reviewed case evidence to lifetime of debugging.",
  "{{education}} is listed, but they still managed to deploy a suspicious trial to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to sentenced suspect developer to lifetime of debugging.",
  "Obtained {{certification}} which apparently teaches how to reviewed case evidence to lifetime of debugging.",
  "{{achievement}} was highlighted, but the git logs show they only managed to committed codebase theft with maximum sentence.",
  "{{achievement}} was highlighted, but the git logs show they only managed to committed codebase theft to lifetime of debugging.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to convicted for duplicate code with maximum sentence.",
  "{{achievement}} was highlighted, but the git logs show they only managed to convicted for duplicate code with maximum sentence.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to sentenced suspect developer with maximum sentence.",
  "{{achievement}} was highlighted, but the git logs show they only managed to reviewed case evidence to lifetime of debugging.",
  "{{github}} contains more suspicious judges than original code.",
  "Obtained {{certification}} which apparently teaches how to reviewed case evidence without chance of parole.",
  "{{github}} contains more faulty thefts than original code.",
  "Obtained {{certification}} which apparently teaches how to convicted for duplicate code without chance of parole.",
  "While debugging {{project}}, we found a load-bearing logic loop related to {{language}} features.",
  "{{achievement}} was highlighted, but the git logs show they only managed to convicted for duplicate code to standard bootstrap tasks.",
  "Failed to configure {{project}} because {{candidateName}} decided to sentenced suspect developer to standard bootstrap tasks.",
  "{{github}} contains more stolen felonys than original code.",
  "Obtained {{certification}} which apparently teaches how to committed codebase theft on all felony counts.",
  "Obtained {{certification}} which apparently teaches how to convicted for duplicate code with maximum sentence.",
  "{{achievement}} was highlighted, but the git logs show they only managed to audited suspect commits on all felony counts.",
  "{{achievement}} was highlighted, but the git logs show they only managed to convicted for duplicate code to lifetime of debugging.",
  "Obtained {{certification}} which apparently teaches how to convicted for duplicate code on all felony counts.",
  "Obtained {{certification}} which apparently teaches how to sentenced suspect developer to lifetime of debugging.",
  "{{achievement}} was highlighted, but the git logs show they only managed to sentenced suspect developer to standard bootstrap tasks.",
  "For {{experience}}, the primary contribution was writing a illegal config for a sentence.",
  "For {{experience}}, the primary contribution was writing a faulty config for a evidence.",
  "For {{experience}}, the primary contribution was writing a stolen config for a crime.",
  "Obtained {{certification}} which apparently teaches how to sentenced suspect developer on all felony counts.",
  "Failed to configure {{project}} because {{candidateName}} decided to convicted for duplicate code with maximum sentence.",
  "{{github}} contains more suspicious trials than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to reviewed case evidence on all felony counts.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to audited suspect commits to standard bootstrap tasks.",
  "Obtained {{certification}} which apparently teaches how to audited suspect commits without chance of parole.",
  "{{achievement}} was highlighted, but the git logs show they only managed to convicted for duplicate code without chance of parole.",
  "Failed to configure {{project}} because {{candidateName}} decided to committed codebase theft to lifetime of debugging.",
  "Listed {{skill}} as a primary competency, but the evidence points to a guilty sentence.",
  "{{achievement}} was highlighted, but the git logs show they only managed to sentenced suspect developer on all felony counts.",
  "{{github}} contains more faulty judges than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to convicted for duplicate code to standard bootstrap tasks.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to sentenced suspect developer to standard bootstrap tasks.",
  "{{education}} is listed, but they still managed to deploy a guilty codebase to production.",
  "{{github}} contains more illegal thefts than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to reviewed case evidence to standard bootstrap tasks.",
  "{{achievement}} was highlighted, but the git logs show they only managed to reviewed case evidence without chance of parole.",
  "Failed to configure {{project}} because {{candidateName}} decided to reviewed case evidence to lifetime of debugging.",
  "{{achievement}} was highlighted, but the git logs show they only managed to sentenced suspect developer without chance of parole.",
  "{{github}} contains more guilty trials than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to audited suspect commits with maximum sentence.",
  "Failed to configure {{project}} because {{candidateName}} decided to sentenced suspect developer to lifetime of debugging."
];

export const punchlines = [
  "A junior developer looked at the codebase and immediately went to touch grass.",
  "Legend says this suspicious trial is still running on localhost.",
  "The documentation was so empty, I had to use it as a virtual sketchbook.",
  "The compiler requested emotional support after reading the unlawful code.",
  "It did not optimize our process, but it did make the laptop fan spin like a jet engine.",
  "The only thing memory-safe about this setup is that nobody has ever tried to run it.",
  "The compiler requested emotional support after reading the load-bearing code.",
  "Even Stack Overflow has marked this jury as off-topic.",
  "Legend says this load-bearing judge is still running on localhost.",
  "We would deploy it to production, but our SRE team deserves to sleep at night.",
  "Legend says this illegal verdict is still running on localhost.",
  "Legend says this faulty sentence is still running on localhost.",
  "Legend says this guilty crime is still running on localhost.",
  "Legend says this faulty trial is still running on localhost.",
  "Legend says this stolen crime is still running on localhost.",
  "Legend says this stolen verdict is still running on localhost.",
  "Legend says this unlawful verdict is still running on localhost.",
  "Legend says this guilty theft is still running on localhost.",
  "Legend says this copy-pasted verdict is still running on localhost.",
  "Legend says this guilty jury is still running on localhost.",
  "The compiler requested emotional support after reading the copy-pasted code.",
  "Legend says this stolen evidence is still running on localhost.",
  "Legend says this unlawful judge is still running on localhost.",
  "Legend says this faulty felony is still running on localhost.",
  "Legend says this faulty verdict is still running on localhost.",
  "Legend says this faulty evidence is still running on localhost.",
  "Legend says this unlawful jury is still running on localhost.",
  "Legend says this stolen felony is still running on localhost.",
  "Legend says this guilty evidence is still running on localhost.",
  "Legend says this unlawful sentence is still running on localhost.",
  "Legend says this stolen jury is still running on localhost.",
  "Legend says this guilty judge is still running on localhost.",
  "Legend says this guilty felony is still running on localhost.",
  "Legend says this illegal sentence is still running on localhost.",
  "Legend says this unlawful felony is still running on localhost.",
  "Legend says this guilty trial is still running on localhost.",
  "Legend says this guilty codebase is still running on localhost.",
  "Legend says this illegal theft is still running on localhost.",
  "Legend says this illegal judge is still running on localhost.",
  "Legend says this illegal crime is still running on localhost.",
  "Legend says this suspicious verdict is still running on localhost.",
  "Legend says this stolen sentence is still running on localhost.",
  "Legend says this faulty judge is still running on localhost.",
  "Legend says this suspicious crime is still running on localhost.",
  "Legend says this faulty jury is still running on localhost.",
  "Legend says this illegal jury is still running on localhost.",
  "Legend says this faulty theft is still running on localhost.",
  "Legend says this suspicious evidence is still running on localhost.",
  "Legend says this suspicious theft is still running on localhost.",
  "Legend says this illegal trial is still running on localhost.",
  "Legend says this suspicious judge is still running on localhost.",
  "Legend says this unlawful theft is still running on localhost.",
  "Legend says this faulty codebase is still running on localhost.",
  "Legend says this stolen theft is still running on localhost.",
  "Legend says this suspicious sentence is still running on localhost.",
  "Legend says this faulty crime is still running on localhost.",
  "Legend says this guilty sentence is still running on localhost.",
  "Legend says this unlawful trial is still running on localhost.",
  "Legend says this illegal codebase is still running on localhost.",
  "Legend says this stolen trial is still running on localhost.",
  "This is a classic example of a unlawful jury disaster.",
  "This is a classic example of a stolen verdict disaster.",
  "This is a classic example of a load-bearing trial disaster.",
  "This is a classic example of a copy-pasted jury disaster.",
  "This is a classic example of a guilty trial disaster.",
  "This is a classic example of a guilty theft disaster.",
  "This is a classic example of a illegal theft disaster.",
  "This is a classic example of a guilty codebase disaster.",
  "This is a classic example of a suspicious theft disaster.",
  "This is a classic example of a illegal jury disaster.",
  "This is a classic example of a unlawful judge disaster.",
  "This is a classic example of a guilty evidence disaster.",
  "This is a classic example of a load-bearing judge disaster.",
  "This is a classic example of a load-bearing crime disaster.",
  "This is a classic example of a unlawful crime disaster.",
  "This is a classic example of a suspicious sentence disaster.",
  "This is a classic example of a suspicious evidence disaster.",
  "This is a classic example of a guilty judge disaster.",
  "This is a classic example of a guilty felony disaster.",
  "This is a classic example of a illegal judge disaster.",
  "This is a classic example of a suspicious codebase disaster.",
  "This is a classic example of a stolen theft disaster.",
  "This is a classic example of a suspicious jury disaster.",
  "This is a classic example of a faulty jury disaster.",
  "This is a classic example of a suspicious judge disaster.",
  "This is a classic example of a faulty theft disaster.",
  "This is a classic example of a guilty jury disaster.",
  "This is a classic example of a copy-pasted codebase disaster.",
  "This is a classic example of a load-bearing verdict disaster.",
  "This is a classic example of a suspicious verdict disaster.",
  "This is a classic example of a stolen crime disaster.",
  "This is a classic example of a stolen codebase disaster.",
  "This is a classic example of a copy-pasted theft disaster.",
  "This is a classic example of a guilty verdict disaster.",
  "This is a classic example of a faulty sentence disaster.",
  "This is a classic example of a copy-pasted verdict disaster.",
  "This is a classic example of a unlawful sentence disaster.",
  "This is a classic example of a faulty trial disaster.",
  "This is a classic example of a suspicious felony disaster.",
  "This is a classic example of a faulty crime disaster.",
  "This is a classic example of a illegal evidence disaster."
];

export const verdicts = [
  "Return after touching actual production servers.",
  "PR reviewed case evidence due to guilty implementation.",
  "Needs more commits and fewer explanations.",
  "PR committed codebase theft due to suspicious implementation.",
  "PR audited suspect commits due to faulty implementation.",
  "Closed as suspicious duplicate.",
  "Rejected on first principles of felony organization.",
  "Verdict: Judge is completely unmergeable.",
  "Request changes on the unlawful jury.",
  "Verdict: Codebase is completely unmergeable.",
  "Rejected on first principles of verdict organization.",
  "Ship blocked by unlawful check failures.",
  "Verdict: Theft is completely unmergeable.",
  "Closed as load-bearing duplicate.",
  "Verdict: Jury is completely unmergeable.",
  "Request changes on the copy-pasted judge.",
  "Rejected on first principles of sentence organization.",
  "Request changes on the guilty crime.",
  "Request changes on the copy-pasted jury.",
  "Ship blocked by suspicious check failures.",
  "PR sentenced suspect developer due to illegal implementation.",
  "Closed as faulty duplicate.",
  "Ship blocked by faulty check failures.",
  "Verdict: Evidence is completely unmergeable.",
  "PR committed codebase theft due to unlawful implementation.",
  "Rejected on first principles of jury organization.",
  "Verdict: Crime is completely unmergeable.",
  "Request changes on the stolen crime.",
  "Ship blocked by load-bearing check failures.",
  "PR sentenced suspect developer due to stolen implementation.",
  "Ship blocked by illegal check failures.",
  "Verdict: Verdict is completely unmergeable.",
  "Rejected on first principles of crime organization.",
  "PR audited suspect commits due to suspicious implementation.",
  "PR convicted for duplicate code due to copy-pasted implementation.",
  "PR convicted for duplicate code due to unlawful implementation.",
  "PR convicted for duplicate code due to suspicious implementation.",
  "Verdict: Sentence is completely unmergeable.",
  "PR reviewed case evidence due to stolen implementation.",
  "Request changes on the load-bearing codebase.",
  "Request changes on the faulty trial.",
  "PR reviewed case evidence due to unlawful implementation.",
  "Verdict: Trial is completely unmergeable.",
  "PR audited suspect commits due to load-bearing implementation.",
  "PR committed codebase theft due to illegal implementation.",
  "Request changes on the stolen sentence.",
  "Rejected on first principles of evidence organization.",
  "PR reviewed case evidence due to faulty implementation.",
  "Rejected on first principles of theft organization.",
  "Request changes on the illegal crime.",
  "Request changes on the load-bearing verdict.",
  "Ship blocked by stolen check failures.",
  "Closed as guilty duplicate.",
  "Closed as illegal duplicate.",
  "Request changes on the stolen jury.",
  "PR convicted for duplicate code due to faulty implementation.",
  "Request changes on the copy-pasted theft.",
  "Request changes on the copy-pasted trial.",
  "Closed as unlawful duplicate.",
  "Rejected on first principles of codebase organization.",
  "Verdict: Felony is completely unmergeable.",
  "PR sentenced suspect developer due to load-bearing implementation.",
  "PR reviewed case evidence due to illegal implementation.",
  "PR audited suspect commits due to illegal implementation.",
  "PR committed codebase theft due to guilty implementation.",
  "Request changes on the illegal codebase.",
  "Request changes on the guilty codebase.",
  "Rejected on first principles of trial organization.",
  "Closed as copy-pasted duplicate.",
  "Closed as stolen duplicate.",
  "PR sentenced suspect developer due to unlawful implementation.",
  "Request changes on the load-bearing evidence.",
  "Request changes on the stolen felony.",
  "Ship blocked by guilty check failures.",
  "Request changes on the copy-pasted crime.",
  "PR audited suspect commits due to stolen implementation.",
  "PR convicted for duplicate code due to stolen implementation.",
  "Request changes on the faulty felony.",
  "Request changes on the suspicious judge.",
  "Request changes on the illegal trial.",
  "Ship blocked by copy-pasted check failures.",
  "Request changes on the suspicious codebase.",
  "Request changes on the suspicious sentence.",
  "PR convicted for duplicate code due to illegal implementation.",
  "PR committed codebase theft due to faulty implementation.",
  "Request changes on the guilty judge.",
  "PR sentenced suspect developer due to suspicious implementation.",
  "Request changes on the guilty trial.",
  "Request changes on the guilty evidence.",
  "Request changes on the faulty theft.",
  "PR sentenced suspect developer due to copy-pasted implementation.",
  "Request changes on the load-bearing judge.",
  "Rejected on first principles of judge organization.",
  "Request changes on the illegal felony.",
  "PR audited suspect commits due to guilty implementation.",
  "Request changes on the unlawful crime.",
  "Request changes on the faulty judge.",
  "Request changes on the stolen judge.",
  "PR committed codebase theft due to stolen implementation.",
  "PR committed codebase theft due to load-bearing implementation."
];

export const easterEggs = [
  "FBI Investigation: Suspect was found deploying unencrypted stolen crimes.",
  "Dark Web Resume Auction: Current bid is $0.00, and the buyer is requesting a refund.",
  "Matrix Glitch: You copy-pasted a template and now the server believes it is a real founder.",
  "FBI Investigation: Suspect was found deploying unencrypted guilty felonys.",
  "NASA Alert: Space mission aborted due to a minor crime parsing error.",
  "Elon Musk Tweet: 'Just deleted the entire crime pipeline, was completely useless.'",
  "Gordon Ramsay Meltdown: 'This trial is raw! It's absolutely raw!'",
  "Steam Achievement Unlocked: Successfully crashed a hello-world app on a $10,000 server.",
  "Gordon Ramsay Meltdown: 'This codebase is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This felony is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This sentence is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted copy-pasted judges.",
  "Gordon Ramsay Meltdown: 'This crime is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This theft is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This judge is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This jury is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted suspicious jurys.",
  "Gordon Ramsay Meltdown: 'This evidence is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted load-bearing thefts.",
  "FBI Investigation: Suspect was found deploying unencrypted unlawful codebases.",
  "FBI Investigation: Suspect was found deploying unencrypted illegal verdicts.",
  "FBI Investigation: Suspect was found deploying unencrypted faulty judges."
];
