// ES Module exports for cscareerquestions roast format
export const titles = [
  "Career conflict detected",
  "NullPointerMarketException",
  "Intern Not Found",
  "NullPointerJob huntException",
  "Critical Mock failure",
  "Empty Job hunt Loop",
  "Absolute Boot camp architecture",
  "Resume conflict detected",
  "The Salary tragedy",
  "Critical Career failure",
  "Incident Report: Basic Application",
  "Failed to compile: Junior",
  "Entry-level Job hunt Error",
  "Fresh Mock Error",
  "Empty Career Error",
  "The Offer tragedy",
  "Fresh Resume Error",
  "Failed to compile: Intern",
  "Incident Report: Unprepared Offer",
  "Incident Report: Fresh Intern",
  "Incident Report: Basic Salary",
  "Job hunt Not Found",
  "NullPointerOfferException",
  "Incident Report: Entry-level Resume",
  "Fresh Salary Loop",
  "Unprepared Junior Loop",
  "Fresh Junior Error",
  "Offer Not Found",
  "Intern conflict detected",
  "Desperate Resume Loop",
  "Failed to compile: Offer",
  "Absolute Fresh architecture",
  "NullPointerMockException",
  "NullPointerJuniorException",
  "Incident Report: Empty Resume",
  "Critical Job hunt failure",
  "Empty Mock Loop",
  "Fresh Market Error",
  "The Intern tragedy",
  "NullPointerCareerException",
  "Failed to compile: Salary",
  "Salary Not Found",
  "Mock conflict detected",
  "Entry-level Offer Loop",
  "Resume Not Found",
  "Absolute Unprepared architecture",
  "Incident Report: Rejected Career",
  "Junior Not Found",
  "Absolute Desperate architecture",
  "Incident Report: Unprepared Job hunt",
  "Critical Offer failure",
  "Incident Report: Boot camp Career",
  "Absolute Empty architecture",
  "Rejected Resume Error",
  "Incident Report: Boot camp Job hunt",
  "Fresh Career Error",
  "The Junior tragedy",
  "The Mock tragedy",
  "Application conflict detected",
  "Absolute Entry-level architecture",
  "Mock Not Found",
  "Unprepared Job hunt Error",
  "The Career tragedy",
  "Market conflict detected",
  "Career Not Found",
  "Entry-level Offer Error",
  "Empty Resume Loop",
  "Junior conflict detected",
  "Entry-level Resume Error",
  "Critical Salary failure",
  "Failed to compile: Market",
  "Unprepared Job hunt Loop",
  "Incident Report: Fresh Salary",
  "Boot camp Application Error",
  "Critical Junior failure",
  "Incident Report: Basic Mock",
  "Failed to compile: Application",
  "The Application tragedy",
  "Rejected Intern Error",
  "Rejected Junior Error",
  "Basic Intern Error",
  "The Job hunt tragedy",
  "Absolute Basic architecture",
  "Boot camp Career Error",
  "Critical Market failure",
  "NullPointerSalaryException",
  "Market Not Found",
  "Boot camp Mock Error",
  "Incident Report: Desperate Application",
  "Incident Report: Desperate Offer",
  "Desperate Career Error",
  "Incident Report: Boot camp Market",
  "Absolute Rejected architecture",
  "NullPointerResumeException",
  "Fresh Application Error",
  "Application Not Found",
  "Fresh Intern Error",
  "Incident Report: Rejected Salary",
  "NullPointerInternException",
  "Unprepared Application Loop"
];

export const openings = [
  "A review was filed regarding a entry-level career.",
  "Warning: System flagged an attempt to posted resume review on reddit forum.",
  "Warning: System flagged an attempt to rejected candidate profile after boot camp end.",
  "The team has initiated audit for the candidate's salary setup.",
  "Alert: The candidate spent three months trying to applied to 500 jobs with 0 interviews.",
  "Alert: The candidate spent three months trying to posted resume review on reddit forum.",
  "A review was filed regarding a entry-level salary.",
  "Scanning candidate profile for boot camp salarys...",
  "Alert: The candidate spent three months trying to asked basic question without finding work.",
  "A review was filed regarding a boot camp salary.",
  "Recruiters reported a case of basic career design.",
  "Scanning candidate profile for fresh juniors...",
  "Warning: System flagged an attempt to applied to 500 jobs with 0 interviews.",
  "A review was filed regarding a unprepared resume.",
  "Warning: System flagged an attempt to rejected candidate profile in tough market.",
  "Scanning candidate profile for entry-level markets...",
  "We checked the history and found a unprepared junior log.",
  "Initial evaluation shows the developer decided to asked basic question in tough market.",
  "We checked the history and found a empty career log.",
  "Warning: System flagged an attempt to asked basic question without finding work.",
  "Warning: System flagged an attempt to posted resume review after boot camp end.",
  "We checked the history and found a desperate application log.",
  "A review was filed regarding a unprepared career.",
  "We checked the history and found a boot camp junior log.",
  "Initial evaluation shows the developer decided to complained about market on reddit forum.",
  "A review was filed regarding a fresh resume.",
  "Alert: The candidate spent three months trying to applied to 500 jobs on reddit forum.",
  "We checked the history and found a empty job hunt log.",
  "Initial evaluation shows the developer decided to applied to 500 jobs without finding work.",
  "Warning: System flagged an attempt to applied to 500 jobs after boot camp end.",
  "Recruiters reported a case of empty intern design.",
  "Initial evaluation shows the developer decided to rejected candidate profile after boot camp end.",
  "Initial evaluation shows the developer decided to applied to 500 jobs with 0 interviews.",
  "Recruiters reported a case of basic application design.",
  "The team has initiated audit for the candidate's job hunt setup.",
  "Initial evaluation shows the developer decided to complained about market after boot camp end.",
  "Initial evaluation shows the developer decided to applied to 500 jobs after boot camp end.",
  "Initial evaluation shows the developer decided to complained about market in tough market.",
  "Recruiters reported a case of fresh job hunt design.",
  "Recruiters reported a case of fresh resume design.",
  "Recruiters reported a case of desperate resume design.",
  "Scanning candidate profile for rejected job hunts...",
  "Alert: The candidate spent three months trying to rejected candidate profile on reddit forum.",
  "Initial evaluation shows the developer decided to rejected candidate profile in tough market.",
  "A review was filed regarding a basic offer.",
  "Alert: The candidate spent three months trying to asked basic question on reddit forum.",
  "Warning: System flagged an attempt to complained about market in tough market.",
  "Scanning candidate profile for entry-level careers...",
  "Recruiters reported a case of boot camp salary design.",
  "We checked the history and found a fresh market log.",
  "Alert: The candidate spent three months trying to rejected candidate profile with 0 interviews.",
  "Scanning candidate profile for rejected applications...",
  "Recruiters reported a case of basic offer design.",
  "Scanning candidate profile for boot camp job hunts...",
  "A review was filed regarding a rejected job hunt.",
  "We checked the history and found a boot camp job hunt log.",
  "Recruiters reported a case of boot camp offer design.",
  "Warning: System flagged an attempt to asked basic question in tough market.",
  "A review was filed regarding a boot camp market.",
  "Recruiters reported a case of rejected career design.",
  "We checked the history and found a fresh resume log.",
  "We checked the history and found a empty offer log.",
  "Recruiters reported a case of rejected salary design.",
  "Warning: System flagged an attempt to applied to 500 jobs in tough market.",
  "Scanning candidate profile for fresh resumes...",
  "Scanning candidate profile for empty salarys...",
  "We checked the history and found a rejected market log.",
  "We checked the history and found a basic salary log.",
  "Recruiters reported a case of empty junior design.",
  "We checked the history and found a basic mock log.",
  "Warning: System flagged an attempt to applied to 500 jobs without finding work.",
  "Scanning candidate profile for fresh interns...",
  "Warning: System flagged an attempt to asked basic question with 0 interviews.",
  "Initial evaluation shows the developer decided to posted resume review on reddit forum.",
  "Warning: System flagged an attempt to complained about market without finding work.",
  "A review was filed regarding a rejected junior.",
  "Warning: System flagged an attempt to complained about market after boot camp end.",
  "Scanning candidate profile for empty offers...",
  "We checked the history and found a unprepared intern log.",
  "Alert: The candidate spent three months trying to posted resume review without finding work.",
  "We checked the history and found a basic market log.",
  "A review was filed regarding a entry-level job hunt.",
  "Warning: System flagged an attempt to complained about market on reddit forum.",
  "We checked the history and found a entry-level offer log.",
  "Warning: System flagged an attempt to posted resume review without finding work.",
  "Alert: The candidate spent three months trying to rejected candidate profile without finding work.",
  "Alert: The candidate spent three months trying to applied to 500 jobs in tough market.",
  "We checked the history and found a unprepared salary log.",
  "Recruiters reported a case of basic salary design.",
  "Warning: System flagged an attempt to asked basic question after boot camp end.",
  "Scanning candidate profile for rejected offers...",
  "Recruiters reported a case of fresh intern design."
];

export const findings = [
  "Failed to configure {{project}} because {{candidateName}} decided to complained about market in tough market.",
  "{{candidateName}} has spent three weeks optimizing a offer while completely ignoring {{missingSection}}.",
  "{{education}} is listed, but they still managed to deploy a basic resume to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to rejected candidate profile after boot camp end.",
  "Listed {{skill}} as a primary competency, but the evidence points to a fresh salary.",
  "{{education}} is listed, but they still managed to deploy a rejected mock to production.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to applied to 500 jobs on reddit forum.",
  "For {{experience}}, the primary contribution was writing a boot camp config for a application.",
  "Failed to configure {{project}} because {{candidateName}} decided to complained about market with 0 interviews.",
  "{{github}} contains more entry-level salarys than original code.",
  "The candidate claims {{framework}} experience, but their repository is just a boot camp clone that has been abandoned.",
  "{{github}} contains more unprepared interns than original code.",
  "For {{experience}}, the primary contribution was writing a rejected config for a salary.",
  "Listed {{skill}} as a primary competency, but the evidence points to a desperate resume.",
  "Failed to configure {{project}} because {{candidateName}} decided to asked basic question after boot camp end.",
  "{{achievement}} was highlighted, but the git logs show they only managed to posted resume review on reddit forum.",
  "Obtained {{certification}} which apparently teaches how to asked basic question in tough market.",
  "Listed {{skill}} as a primary competency, but the evidence points to a rejected market.",
  "Obtained {{certification}} which apparently teaches how to posted resume review without finding work.",
  "{{github}} contains more rejected mocks than original code.",
  "While debugging {{project}}, we found a desperate logic loop related to {{language}} features.",
  "{{achievement}} was highlighted, but the git logs show they only managed to complained about market without finding work.",
  "{{education}} is listed, but they still managed to deploy a fresh career to production.",
  "Obtained {{certification}} which apparently teaches how to asked basic question on reddit forum.",
  "{{achievement}} was highlighted, but the git logs show they only managed to applied to 500 jobs after boot camp end.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to complained about market after boot camp end.",
  "Listed {{skill}} as a primary competency, but the evidence points to a unprepared mock.",
  "A security audit on {{github}} detected a plain-text database password inside a desperate resume.",
  "Obtained {{certification}} which apparently teaches how to posted resume review after boot camp end.",
  "For {{experience}}, the primary contribution was writing a unprepared config for a application.",
  "Failed to configure {{project}} because {{candidateName}} decided to complained about market without finding work.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to applied to 500 jobs after boot camp end.",
  "Obtained {{certification}} which apparently teaches how to applied to 500 jobs on reddit forum.",
  "{{education}} is listed, but they still managed to deploy a empty job hunt to production.",
  "Obtained {{certification}} which apparently teaches how to asked basic question after boot camp end.",
  "{{github}} contains more fresh juniors than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a basic application.",
  "Listed {{skill}} as a primary competency, but the evidence points to a boot camp market.",
  "{{education}} is listed, but they still managed to deploy a boot camp offer to production.",
  "Obtained {{certification}} which apparently teaches how to complained about market with 0 interviews.",
  "Failed to configure {{project}} because {{candidateName}} decided to posted resume review after boot camp end.",
  "For {{experience}}, the primary contribution was writing a desperate config for a intern.",
  "{{github}} contains more basic careers than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to posted resume review on reddit forum.",
  "For {{experience}}, the primary contribution was writing a entry-level config for a career.",
  "A security audit on {{github}} detected a plain-text database password inside a boot camp junior.",
  "For {{experience}}, the primary contribution was writing a basic config for a career.",
  "{{achievement}} was highlighted, but the git logs show they only managed to rejected candidate profile with 0 interviews.",
  "For {{experience}}, the primary contribution was writing a empty config for a junior.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to complained about market in tough market.",
  "While debugging {{project}}, we found a entry-level logic loop related to {{language}} features.",
  "Failed to configure {{project}} because {{candidateName}} decided to posted resume review without finding work.",
  "Obtained {{certification}} which apparently teaches how to applied to 500 jobs after boot camp end.",
  "Listed {{skill}} as a primary competency, but the evidence points to a empty career.",
  "{{github}} contains more unprepared applications than original code.",
  "{{github}} contains more desperate interns than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to rejected candidate profile on reddit forum.",
  "{{candidateName}} has spent three weeks optimizing a job hunt while completely ignoring {{missingSection}}.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to asked basic question on reddit forum.",
  "Failed to configure {{project}} because {{candidateName}} decided to applied to 500 jobs with 0 interviews.",
  "Failed to configure {{project}} because {{candidateName}} decided to asked basic question without finding work.",
  "{{education}} is listed, but they still managed to deploy a unprepared junior to production.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to posted resume review on reddit forum.",
  "{{github}} contains more basic salarys than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to applied to 500 jobs without finding work.",
  "{{achievement}} was highlighted, but the git logs show they only managed to asked basic question on reddit forum.",
  "A security audit on {{github}} detected a plain-text database password inside a entry-level salary.",
  "{{github}} contains more boot camp offers than original code.",
  "{{github}} contains more boot camp job hunts than original code.",
  "For {{experience}}, the primary contribution was writing a fresh config for a resume.",
  "A security audit on {{github}} detected a plain-text database password inside a unprepared offer.",
  "Failed to configure {{project}} because {{candidateName}} decided to rejected candidate profile in tough market.",
  "Obtained {{certification}} which apparently teaches how to posted resume review on reddit forum.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to applied to 500 jobs with 0 interviews.",
  "Listed {{skill}} as a primary competency, but the evidence points to a unprepared job hunt.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to asked basic question after boot camp end.",
  "A security audit on {{github}} detected a plain-text database password inside a basic job hunt.",
  "A security audit on {{github}} detected a plain-text database password inside a fresh market.",
  "{{github}} contains more empty juniors than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a boot camp job hunt.",
  "Obtained {{certification}} which apparently teaches how to rejected candidate profile on reddit forum.",
  "Failed to configure {{project}} because {{candidateName}} decided to applied to 500 jobs without finding work.",
  "{{education}} is listed, but they still managed to deploy a entry-level career to production.",
  "{{github}} contains more empty resumes than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a rejected career.",
  "Obtained {{certification}} which apparently teaches how to applied to 500 jobs with 0 interviews.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to asked basic question with 0 interviews.",
  "{{achievement}} was highlighted, but the git logs show they only managed to asked basic question in tough market.",
  "{{education}} is listed, but they still managed to deploy a empty market to production.",
  "Listed {{skill}} as a primary competency, but the evidence points to a entry-level market.",
  "The candidate claims {{framework}} experience, but their repository is just a entry-level clone that has been abandoned.",
  "{{github}} contains more rejected careers than original code.",
  "Obtained {{certification}} which apparently teaches how to complained about market in tough market.",
  "Obtained {{certification}} which apparently teaches how to complained about market after boot camp end.",
  "While debugging {{project}}, we found a boot camp logic loop related to {{language}} features.",
  "{{github}} contains more rejected job hunts than original code.",
  "{{github}} contains more fresh applications than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to posted resume review with 0 interviews.",
  "{{github}} contains more desperate resumes than original code.",
  "{{github}} contains more empty mocks than original code.",
  "{{github}} contains more basic resumes than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to applied to 500 jobs with 0 interviews.",
  "{{achievement}} was highlighted, but the git logs show they only managed to posted resume review in tough market.",
  "Failed to configure {{project}} because {{candidateName}} decided to applied to 500 jobs in tough market.",
  "Failed to configure {{project}} because {{candidateName}} decided to posted resume review in tough market.",
  "Failed to configure {{project}} because {{candidateName}} decided to complained about market on reddit forum.",
  "Obtained {{certification}} which apparently teaches how to rejected candidate profile without finding work.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to posted resume review without finding work.",
  "{{github}} contains more basic interns than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to applied to 500 jobs on reddit forum.",
  "Failed to configure {{project}} because {{candidateName}} decided to rejected candidate profile after boot camp end.",
  "Listed {{skill}} as a primary competency, but the evidence points to a basic offer.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to rejected candidate profile after boot camp end.",
  "Obtained {{certification}} which apparently teaches how to rejected candidate profile in tough market.",
  "Failed to configure {{project}} because {{candidateName}} decided to asked basic question on reddit forum.",
  "A security audit on {{github}} detected a plain-text database password inside a entry-level job hunt.",
  "{{github}} contains more basic offers than original code.",
  "{{github}} contains more desperate markets than original code.",
  "{{education}} is listed, but they still managed to deploy a entry-level job hunt to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to complained about market after boot camp end.",
  "For {{experience}}, the primary contribution was writing a rejected config for a job hunt.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to applied to 500 jobs without finding work.",
  "{{achievement}} was highlighted, but the git logs show they only managed to complained about market on reddit forum."
];

export const punchlines = [
  "Even Stack Overflow has marked this junior as off-topic.",
  "We would deploy it to production, but our SRE team deserves to sleep at night.",
  "The compiler requested emotional support after reading the fresh code.",
  "The documentation was so empty, I had to use it as a virtual sketchbook.",
  "The only thing memory-safe about this setup is that nobody has ever tried to run it.",
  "The compiler requested emotional support after reading the boot camp code.",
  "Legend says this unprepared job hunt is still running on localhost.",
  "It did not optimize our process, but it did make the laptop fan spin like a jet engine.",
  "Legend says this entry-level market is still running on localhost.",
  "A junior developer looked at the job hunt and immediately went to touch grass.",
  "The compiler requested emotional support after reading the entry-level code.",
  "A junior developer looked at the intern and immediately went to touch grass.",
  "Legend says this entry-level job hunt is still running on localhost.",
  "Legend says this boot camp resume is still running on localhost.",
  "Legend says this fresh intern is still running on localhost.",
  "Even Stack Overflow has marked this job hunt as off-topic.",
  "Legend says this basic salary is still running on localhost.",
  "Legend says this fresh junior is still running on localhost.",
  "Legend says this unprepared mock is still running on localhost.",
  "Legend says this empty application is still running on localhost.",
  "Legend says this basic junior is still running on localhost.",
  "Legend says this empty offer is still running on localhost.",
  "Legend says this desperate application is still running on localhost.",
  "Legend says this fresh salary is still running on localhost.",
  "Legend says this empty intern is still running on localhost.",
  "Legend says this desperate market is still running on localhost.",
  "Legend says this desperate salary is still running on localhost.",
  "Legend says this fresh market is still running on localhost.",
  "Legend says this desperate junior is still running on localhost.",
  "Legend says this rejected intern is still running on localhost.",
  "Legend says this rejected mock is still running on localhost.",
  "Legend says this rejected application is still running on localhost.",
  "Legend says this rejected salary is still running on localhost.",
  "Legend says this rejected junior is still running on localhost.",
  "Legend says this empty junior is still running on localhost.",
  "Legend says this empty salary is still running on localhost.",
  "Legend says this empty mock is still running on localhost.",
  "Legend says this fresh application is still running on localhost.",
  "Legend says this desperate resume is still running on localhost.",
  "Legend says this desperate intern is still running on localhost.",
  "Legend says this basic application is still running on localhost.",
  "Legend says this unprepared salary is still running on localhost.",
  "Legend says this desperate mock is still running on localhost.",
  "Legend says this unprepared resume is still running on localhost.",
  "Legend says this rejected market is still running on localhost.",
  "Legend says this desperate career is still running on localhost.",
  "Legend says this rejected career is still running on localhost.",
  "Legend says this desperate offer is still running on localhost.",
  "Legend says this fresh resume is still running on localhost.",
  "Legend says this basic career is still running on localhost.",
  "Legend says this basic intern is still running on localhost.",
  "Legend says this basic offer is still running on localhost.",
  "Legend says this unprepared junior is still running on localhost.",
  "This is a classic example of a empty offer disaster.",
  "This is a classic example of a boot camp mock disaster.",
  "This is a classic example of a basic mock disaster.",
  "This is a classic example of a entry-level application disaster.",
  "This is a classic example of a desperate mock disaster.",
  "This is a classic example of a entry-level resume disaster.",
  "This is a classic example of a empty mock disaster.",
  "This is a classic example of a empty market disaster.",
  "This is a classic example of a desperate application disaster.",
  "This is a classic example of a desperate market disaster.",
  "This is a classic example of a boot camp resume disaster.",
  "This is a classic example of a basic offer disaster.",
  "This is a classic example of a unprepared resume disaster.",
  "This is a classic example of a desperate junior disaster.",
  "This is a classic example of a empty job hunt disaster.",
  "This is a classic example of a fresh intern disaster.",
  "This is a classic example of a rejected job hunt disaster.",
  "This is a classic example of a unprepared career disaster.",
  "This is a classic example of a basic market disaster.",
  "This is a classic example of a rejected mock disaster.",
  "This is a classic example of a rejected career disaster.",
  "This is a classic example of a empty junior disaster.",
  "This is a classic example of a empty application disaster.",
  "This is a classic example of a boot camp salary disaster.",
  "This is a classic example of a unprepared job hunt disaster.",
  "This is a classic example of a fresh career disaster.",
  "This is a classic example of a entry-level job hunt disaster.",
  "This is a classic example of a fresh salary disaster.",
  "This is a classic example of a boot camp junior disaster.",
  "This is a classic example of a desperate job hunt disaster.",
  "This is a classic example of a boot camp career disaster.",
  "This is a classic example of a fresh resume disaster.",
  "This is a classic example of a rejected junior disaster.",
  "This is a classic example of a unprepared market disaster.",
  "This is a classic example of a unprepared offer disaster.",
  "This is a classic example of a rejected intern disaster.",
  "This is a classic example of a fresh application disaster.",
  "This is a classic example of a empty salary disaster.",
  "This is a classic example of a unprepared mock disaster.",
  "This is a classic example of a unprepared junior disaster.",
  "This is a classic example of a entry-level career disaster.",
  "This is a classic example of a basic intern disaster."
];

export const verdicts = [
  "Rejected on first principles of intern organization.",
  "Closed as rejected duplicate.",
  "PR asked basic question due to entry-level implementation.",
  "PR posted resume review due to basic implementation.",
  "Rejected on first principles of application organization.",
  "Return after touching actual production servers.",
  "Needs more commits and fewer explanations.",
  "Ship blocked by basic check failures.",
  "PR applied to 500 jobs due to desperate implementation.",
  "Verdict: Job hunt is completely unmergeable.",
  "Rejected on first principles of resume organization.",
  "Rejected on first principles of job hunt organization.",
  "PR applied to 500 jobs due to boot camp implementation.",
  "Closed as fresh duplicate.",
  "Verdict: Salary is completely unmergeable.",
  "Rejected on first principles of salary organization.",
  "PR asked basic question due to basic implementation.",
  "Verdict: Career is completely unmergeable.",
  "Request changes on the fresh junior.",
  "Verdict: Resume is completely unmergeable.",
  "PR complained about market due to unprepared implementation.",
  "Ship blocked by rejected check failures.",
  "Rejected on first principles of offer organization.",
  "Request changes on the fresh career.",
  "Closed as empty duplicate.",
  "Ship blocked by unprepared check failures.",
  "PR rejected candidate profile due to unprepared implementation.",
  "PR applied to 500 jobs due to entry-level implementation.",
  "Verdict: Market is completely unmergeable.",
  "Request changes on the unprepared mock.",
  "Ship blocked by desperate check failures.",
  "Verdict: Intern is completely unmergeable.",
  "Request changes on the desperate salary.",
  "Rejected on first principles of mock organization.",
  "Request changes on the basic mock.",
  "Closed as unprepared duplicate.",
  "Request changes on the unprepared intern.",
  "Verdict: Mock is completely unmergeable.",
  "Request changes on the boot camp career.",
  "Ship blocked by entry-level check failures.",
  "Rejected on first principles of career organization.",
  "Ship blocked by boot camp check failures.",
  "Request changes on the desperate market.",
  "Ship blocked by fresh check failures.",
  "Request changes on the desperate job hunt.",
  "Rejected on first principles of market organization.",
  "Closed as basic duplicate.",
  "PR posted resume review due to empty implementation.",
  "PR asked basic question due to boot camp implementation.",
  "PR rejected candidate profile due to entry-level implementation.",
  "Closed as desperate duplicate.",
  "Request changes on the desperate junior.",
  "Closed as entry-level duplicate.",
  "Request changes on the fresh intern.",
  "Request changes on the basic career.",
  "Request changes on the rejected career.",
  "Request changes on the basic salary.",
  "Verdict: Offer is completely unmergeable.",
  "Rejected on first principles of junior organization.",
  "Request changes on the unprepared market.",
  "Request changes on the desperate application.",
  "Closed as boot camp duplicate.",
  "Request changes on the empty intern.",
  "Request changes on the unprepared salary.",
  "Request changes on the fresh salary.",
  "Request changes on the fresh job hunt.",
  "Request changes on the unprepared junior.",
  "PR posted resume review due to desperate implementation.",
  "Request changes on the basic intern.",
  "PR rejected candidate profile due to empty implementation.",
  "PR complained about market due to boot camp implementation.",
  "PR complained about market due to fresh implementation.",
  "Request changes on the basic junior.",
  "PR posted resume review due to fresh implementation.",
  "PR complained about market due to basic implementation.",
  "Request changes on the rejected offer.",
  "PR posted resume review due to boot camp implementation.",
  "Request changes on the boot camp salary.",
  "Request changes on the entry-level application.",
  "PR complained about market due to entry-level implementation.",
  "PR complained about market due to empty implementation.",
  "Request changes on the entry-level salary.",
  "Request changes on the boot camp application.",
  "Ship blocked by empty check failures.",
  "Request changes on the empty salary.",
  "Request changes on the boot camp job hunt.",
  "Request changes on the unprepared job hunt.",
  "Verdict: Application is completely unmergeable.",
  "Request changes on the rejected application.",
  "Verdict: Junior is completely unmergeable.",
  "Request changes on the rejected intern.",
  "Request changes on the boot camp resume.",
  "Request changes on the boot camp market.",
  "PR applied to 500 jobs due to empty implementation."
];

export const easterEggs = [
  "FBI Investigation: Suspect was found deploying unencrypted fresh mocks.",
  "NASA Alert: Space mission aborted due to a minor mock parsing error.",
  "Gordon Ramsay Meltdown: 'This junior is raw! It's absolutely raw!'",
  "Matrix Glitch: You copy-pasted a template and now the server believes it is a real founder.",
  "Elon Musk Tweet: 'Just deleted the entire market pipeline, was completely useless.'",
  "FBI Investigation: Suspect was found deploying unencrypted entry-level markets.",
  "Gordon Ramsay Meltdown: 'This market is raw! It's absolutely raw!'",
  "Steam Achievement Unlocked: Successfully crashed a hello-world app on a $10,000 server.",
  "Gordon Ramsay Meltdown: 'This mock is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted empty job hunts.",
  "FBI Investigation: Suspect was found deploying unencrypted desperate careers.",
  "Gordon Ramsay Meltdown: 'This resume is raw! It's absolutely raw!'",
  "Dark Web Resume Auction: Current bid is $0.00, and the buyer is requesting a refund.",
  "Elon Musk Tweet: 'Just deleted the entire job hunt pipeline, was completely useless.'",
  "FBI Investigation: Suspect was found deploying unencrypted unprepared salarys.",
  "FBI Investigation: Suspect was found deploying unencrypted boot camp mocks.",
  "Gordon Ramsay Meltdown: 'This job hunt is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted basic interns.",
  "NASA Alert: Space mission aborted due to a minor job hunt parsing error.",
  "Gordon Ramsay Meltdown: 'This application is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This offer is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This intern is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted rejected resumes."
];
