// ES Module exports for database_deadlock roast format
export const titles = [
  "Critical Migration failure",
  "Deadlocked Transaction Loop",
  "Table Not Found",
  "Blocked Sql Error",
  "Heavy Query Loop",
  "Critical Database failure",
  "NullPointerDeadlockException",
  "Critical Sql failure",
  "Deadlocked Migration Loop",
  "Database-level Table Loop",
  "Raw Transaction Error",
  "The Sql tragedy",
  "Raw Postgres Error",
  "Absolute Blocked architecture",
  "NullPointerPostgresException",
  "Unindexed Deadlock Error",
  "Incident Report: Database-level Transaction",
  "Database Not Found",
  "Absolute Heavy architecture",
  "Incident Report: Deadlocked Migration",
  "Blocked Query Loop",
  "Deadlock conflict detected",
  "Failed to compile: Postgres",
  "NullPointerConnectionException",
  "Critical Transaction failure",
  "The Database tragedy",
  "Heavy Postgres Error",
  "Incident Report: Unindexed Migration",
  "Failed to compile: Connection",
  "Absolute Synchronous architecture",
  "The Deadlock tragedy",
  "Incident Report: Deadlocked Transaction",
  "Failed to compile: Database",
  "Incident Report: Blocked Migration",
  "Incident Report: Unindexed Transaction",
  "Query conflict detected",
  "Incident Report: Database-level Sql",
  "NullPointerSqlException",
  "The Postgres tragedy",
  "The Table tragedy",
  "Unindexed Query Loop",
  "Connection Not Found",
  "Absolute Database-level architecture",
  "Critical Lock failure",
  "Deadlock Not Found",
  "NullPointerTableException",
  "Deadlocked Deadlock Loop",
  "Incident Report: Locked Sql",
  "Incident Report: Blocked Sql",
  "Lock conflict detected",
  "Synchronous Connection Loop",
  "Incident Report: Synchronous Sql",
  "Failed to compile: Deadlock",
  "Sql conflict detected",
  "Incident Report: Unindexed Database",
  "Incident Report: Synchronous Migration",
  "Locked Lock Error",
  "The Connection tragedy",
  "NullPointerMigrationException",
  "Locked Lock Loop",
  "Incident Report: Raw Sql",
  "Raw Lock Loop",
  "Blocked Table Error",
  "Blocked Query Error",
  "Raw Deadlock Loop",
  "NullPointerDatabaseException",
  "Critical Table failure",
  "Postgres Not Found",
  "Synchronous Transaction Error",
  "Database-level Database Loop",
  "Heavy Migration Loop",
  "The Query tragedy",
  "Lock Not Found",
  "Absolute Locked architecture",
  "Failed to compile: Transaction",
  "Incident Report: Database-level Deadlock",
  "Table conflict detected",
  "Absolute Unindexed architecture",
  "Critical Postgres failure",
  "NullPointerTransactionException",
  "Critical Query failure",
  "Database-level Sql Error",
  "Transaction conflict detected",
  "Transaction Not Found",
  "Raw Transaction Loop",
  "Incident Report: Unindexed Sql",
  "Absolute Deadlocked architecture",
  "Migration conflict detected",
  "Locked Migration Loop",
  "Absolute Raw architecture",
  "The Lock tragedy",
  "Deadlocked Lock Loop",
  "Deadlocked Migration Error",
  "Deadlocked Query Loop",
  "Incident Report: Deadlocked Query",
  "Heavy Deadlock Loop",
  "NullPointerLockException",
  "Incident Report: Synchronous Connection",
  "Incident Report: Database-level Connection",
  "Failed to compile: Sql"
];

export const openings = [
  "Alert: The candidate spent three months trying to locked database table on first transaction.",
  "We checked the history and found a blocked sql log.",
  "A review was filed regarding a database-level transaction.",
  "We checked the history and found a blocked lock log.",
  "A review was filed regarding a deadlocked query.",
  "Initial evaluation shows the developer decided to locked database table restricting write access.",
  "A review was filed regarding a blocked transaction.",
  "We checked the history and found a unindexed connection log.",
  "A review was filed regarding a synchronous query.",
  "Scanning candidate profile for raw migrations...",
  "Scanning candidate profile for unindexed deadlocks...",
  "Scanning candidate profile for locked locks...",
  "Warning: System flagged an attempt to failed database migration causing system timeout.",
  "Alert: The candidate spent three months trying to blocked network connection on first transaction.",
  "The team has initiated audit for the candidate's deadlock setup.",
  "Scanning candidate profile for heavy migrations...",
  "A review was filed regarding a blocked lock.",
  "Recruiters reported a case of synchronous connection design.",
  "Recruiters reported a case of locked lock design.",
  "We checked the history and found a database-level transaction log.",
  "Recruiters reported a case of blocked migration design.",
  "We checked the history and found a synchronous database log.",
  "Warning: System flagged an attempt to locked database table restricting write access.",
  "Initial evaluation shows the developer decided to rolled back transaction during migration run.",
  "We checked the history and found a heavy deadlock log.",
  "A review was filed regarding a database-level deadlock.",
  "Warning: System flagged an attempt to failed database migration during migration run.",
  "A review was filed regarding a unindexed lock.",
  "Alert: The candidate spent three months trying to rolled back transaction during migration run.",
  "Warning: System flagged an attempt to locked database table during migration run.",
  "Scanning candidate profile for heavy querys...",
  "Initial evaluation shows the developer decided to locked database table during migration run.",
  "Initial evaluation shows the developer decided to locked database table without database index.",
  "Scanning candidate profile for raw transactions...",
  "Scanning candidate profile for deadlocked deadlocks...",
  "Alert: The candidate spent three months trying to executed slow query causing system timeout.",
  "Alert: The candidate spent three months trying to rolled back transaction without database index.",
  "A review was filed regarding a blocked table.",
  "A review was filed regarding a heavy migration.",
  "Initial evaluation shows the developer decided to failed database migration restricting write access.",
  "Initial evaluation shows the developer decided to executed slow query during migration run.",
  "Initial evaluation shows the developer decided to locked database table causing system timeout.",
  "We checked the history and found a synchronous deadlock log.",
  "Warning: System flagged an attempt to failed database migration restricting write access.",
  "Scanning candidate profile for unindexed querys...",
  "Recruiters reported a case of locked deadlock design.",
  "Scanning candidate profile for locked transactions...",
  "Initial evaluation shows the developer decided to executed slow query on first transaction.",
  "Initial evaluation shows the developer decided to locked database table on first transaction.",
  "Warning: System flagged an attempt to blocked network connection during migration run.",
  "Alert: The candidate spent three months trying to blocked network connection causing system timeout.",
  "Scanning candidate profile for blocked connections...",
  "Recruiters reported a case of deadlocked table design.",
  "Scanning candidate profile for raw databases...",
  "Warning: System flagged an attempt to executed slow query on first transaction.",
  "We checked the history and found a blocked database log.",
  "Initial evaluation shows the developer decided to rolled back transaction without database index.",
  "Alert: The candidate spent three months trying to locked database table without database index.",
  "Warning: System flagged an attempt to blocked network connection causing system timeout.",
  "Recruiters reported a case of unindexed postgres design.",
  "Alert: The candidate spent three months trying to rolled back transaction causing system timeout.",
  "Alert: The candidate spent three months trying to blocked network connection without database index.",
  "We checked the history and found a raw transaction log.",
  "Scanning candidate profile for database-level querys...",
  "A review was filed regarding a raw lock.",
  "Alert: The candidate spent three months trying to rolled back transaction restricting write access.",
  "Initial evaluation shows the developer decided to rolled back transaction restricting write access.",
  "Alert: The candidate spent three months trying to failed database migration restricting write access.",
  "We checked the history and found a blocked deadlock log.",
  "A review was filed regarding a deadlocked connection.",
  "We checked the history and found a raw connection log.",
  "A review was filed regarding a deadlocked deadlock.",
  "We checked the history and found a blocked migration log.",
  "Scanning candidate profile for blocked sqls...",
  "Scanning candidate profile for database-level migrations...",
  "Recruiters reported a case of unindexed sql design.",
  "We checked the history and found a locked query log.",
  "Initial evaluation shows the developer decided to failed database migration causing system timeout.",
  "Scanning candidate profile for locked sqls...",
  "Recruiters reported a case of blocked transaction design.",
  "A review was filed regarding a locked transaction.",
  "Initial evaluation shows the developer decided to executed slow query restricting write access.",
  "A review was filed regarding a deadlocked lock.",
  "Warning: System flagged an attempt to rolled back transaction restricting write access.",
  "Warning: System flagged an attempt to failed database migration on first transaction.",
  "A review was filed regarding a synchronous connection.",
  "Scanning candidate profile for raw tables...",
  "Recruiters reported a case of locked query design.",
  "We checked the history and found a locked database log.",
  "Warning: System flagged an attempt to locked database table without database index."
];

export const findings = [
  "The candidate claims {{framework}} experience, but their repository is just a raw clone that has been abandoned.",
  "A security audit on {{github}} detected a plain-text database password inside a blocked postgres.",
  "{{achievement}} was highlighted, but the git logs show they only managed to failed database migration without database index.",
  "For {{experience}}, the primary contribution was writing a database-level config for a sql.",
  "While debugging {{project}}, we found a blocked logic loop related to {{language}} features.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to blocked network connection causing system timeout.",
  "For {{experience}}, the primary contribution was writing a deadlocked config for a sql.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to rolled back transaction causing system timeout.",
  "{{candidateName}} has spent three weeks optimizing a lock while completely ignoring {{missingSection}}.",
  "A security audit on {{github}} detected a plain-text database password inside a deadlocked database.",
  "{{achievement}} was highlighted, but the git logs show they only managed to blocked network connection causing system timeout.",
  "Listed {{skill}} as a primary competency, but the evidence points to a unindexed postgres.",
  "Listed {{skill}} as a primary competency, but the evidence points to a blocked transaction.",
  "{{education}} is listed, but they still managed to deploy a raw table to production.",
  "{{github}} contains more locked migrations than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to locked database table causing system timeout.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to rolled back transaction without database index.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to rolled back transaction during migration run.",
  "{{achievement}} was highlighted, but the git logs show they only managed to executed slow query causing system timeout.",
  "{{education}} is listed, but they still managed to deploy a locked database to production.",
  "{{education}} is listed, but they still managed to deploy a synchronous transaction to production.",
  "Listed {{skill}} as a primary competency, but the evidence points to a synchronous sql.",
  "{{achievement}} was highlighted, but the git logs show they only managed to blocked network connection restricting write access.",
  "Listed {{skill}} as a primary competency, but the evidence points to a raw connection.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to locked database table on first transaction.",
  "{{achievement}} was highlighted, but the git logs show they only managed to executed slow query on first transaction.",
  "Failed to configure {{project}} because {{candidateName}} decided to locked database table causing system timeout.",
  "{{education}} is listed, but they still managed to deploy a blocked migration to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to rolled back transaction on first transaction.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to failed database migration during migration run.",
  "A security audit on {{github}} detected a plain-text database password inside a synchronous query.",
  "Failed to configure {{project}} because {{candidateName}} decided to executed slow query restricting write access.",
  "Listed {{skill}} as a primary competency, but the evidence points to a heavy deadlock.",
  "Obtained {{certification}} which apparently teaches how to locked database table restricting write access.",
  "{{education}} is listed, but they still managed to deploy a heavy query to production.",
  "{{github}} contains more blocked transactions than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to rolled back transaction during migration run.",
  "Obtained {{certification}} which apparently teaches how to locked database table on first transaction.",
  "{{achievement}} was highlighted, but the git logs show they only managed to failed database migration during migration run.",
  "Failed to configure {{project}} because {{candidateName}} decided to executed slow query without database index.",
  "A security audit on {{github}} detected a plain-text database password inside a raw migration.",
  "{{github}} contains more locked locks than original code.",
  "{{github}} contains more heavy locks than original code.",
  "{{education}} is listed, but they still managed to deploy a deadlocked deadlock to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to executed slow query restricting write access.",
  "While debugging {{project}}, we found a database-level logic loop related to {{language}} features.",
  "Obtained {{certification}} which apparently teaches how to executed slow query during migration run.",
  "Failed to configure {{project}} because {{candidateName}} decided to failed database migration on first transaction.",
  "{{github}} contains more heavy connections than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to executed slow query on first transaction.",
  "For {{experience}}, the primary contribution was writing a raw config for a transaction.",
  "{{github}} contains more synchronous locks than original code.",
  "{{github}} contains more unindexed tables than original code.",
  "Obtained {{certification}} which apparently teaches how to blocked network connection causing system timeout.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to executed slow query causing system timeout.",
  "Failed to configure {{project}} because {{candidateName}} decided to failed database migration during migration run.",
  "Obtained {{certification}} which apparently teaches how to locked database table causing system timeout.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to locked database table without database index.",
  "{{github}} contains more synchronous migrations than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to rolled back transaction causing system timeout.",
  "{{achievement}} was highlighted, but the git logs show they only managed to locked database table restricting write access.",
  "{{github}} contains more raw locks than original code.",
  "Obtained {{certification}} which apparently teaches how to executed slow query causing system timeout.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to failed database migration causing system timeout.",
  "{{github}} contains more database-level deadlocks than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to rolled back transaction restricting write access.",
  "{{github}} contains more blocked querys than original code.",
  "Obtained {{certification}} which apparently teaches how to rolled back transaction on first transaction.",
  "For {{experience}}, the primary contribution was writing a heavy config for a migration.",
  "{{achievement}} was highlighted, but the git logs show they only managed to blocked network connection during migration run.",
  "Obtained {{certification}} which apparently teaches how to blocked network connection on first transaction.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to failed database migration on first transaction.",
  "{{achievement}} was highlighted, but the git logs show they only managed to blocked network connection without database index.",
  "{{github}} contains more deadlocked connections than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to failed database migration restricting write access.",
  "A security audit on {{github}} detected a plain-text database password inside a database-level sql.",
  "{{github}} contains more synchronous connections than original code.",
  "For {{experience}}, the primary contribution was writing a locked config for a lock.",
  "Obtained {{certification}} which apparently teaches how to failed database migration without database index.",
  "Listed {{skill}} as a primary competency, but the evidence points to a database-level database.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to executed slow query on first transaction.",
  "For {{experience}}, the primary contribution was writing a unindexed config for a connection.",
  "{{achievement}} was highlighted, but the git logs show they only managed to locked database table without database index.",
  "Obtained {{certification}} which apparently teaches how to executed slow query without database index.",
  "Obtained {{certification}} which apparently teaches how to failed database migration on first transaction.",
  "{{achievement}} was highlighted, but the git logs show they only managed to failed database migration on first transaction.",
  "Failed to configure {{project}} because {{candidateName}} decided to failed database migration without database index.",
  "Obtained {{certification}} which apparently teaches how to rolled back transaction restricting write access.",
  "{{github}} contains more heavy deadlocks than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to rolled back transaction causing system timeout.",
  "Failed to configure {{project}} because {{candidateName}} decided to locked database table restricting write access.",
  "Failed to configure {{project}} because {{candidateName}} decided to rolled back transaction on first transaction.",
  "{{education}} is listed, but they still managed to deploy a unindexed postgres to production.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to blocked network connection restricting write access.",
  "A security audit on {{github}} detected a plain-text database password inside a locked connection.",
  "Obtained {{certification}} which apparently teaches how to failed database migration causing system timeout.",
  "{{achievement}} was highlighted, but the git logs show they only managed to executed slow query without database index.",
  "{{github}} contains more locked sqls than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to executed slow query without database index.",
  "Failed to configure {{project}} because {{candidateName}} decided to executed slow query causing system timeout.",
  "{{github}} contains more unindexed sqls than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to blocked network connection causing system timeout.",
  "A security audit on {{github}} detected a plain-text database password inside a unindexed lock.",
  "{{github}} contains more locked databases than original code.",
  "{{github}} contains more deadlocked sqls than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to rolled back transaction without database index.",
  "Listed {{skill}} as a primary competency, but the evidence points to a locked lock.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to blocked network connection on first transaction.",
  "{{github}} contains more blocked postgress than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to executed slow query restricting write access.",
  "Failed to configure {{project}} because {{candidateName}} decided to blocked network connection on first transaction.",
  "Failed to configure {{project}} because {{candidateName}} decided to executed slow query during migration run.",
  "{{achievement}} was highlighted, but the git logs show they only managed to executed slow query during migration run.",
  "Failed to configure {{project}} because {{candidateName}} decided to locked database table on first transaction.",
  "Failed to configure {{project}} because {{candidateName}} decided to blocked network connection during migration run.",
  "{{github}} contains more blocked databases than original code.",
  "{{github}} contains more unindexed migrations than original code.",
  "{{github}} contains more locked transactions than original code.",
  "{{education}} is listed, but they still managed to deploy a database-level migration to production.",
  "A security audit on {{github}} detected a plain-text database password inside a heavy table."
];

export const punchlines = [
  "The documentation was so empty, I had to use it as a virtual sketchbook.",
  "We would deploy it to production, but our SRE team deserves to sleep at night.",
  "Even Stack Overflow has marked this postgres as off-topic.",
  "The only thing memory-safe about this setup is that nobody has ever tried to run it.",
  "Legend says this synchronous table is still running on localhost.",
  "Legend says this blocked table is still running on localhost.",
  "A junior developer looked at the query and immediately went to touch grass.",
  "It did not optimize our process, but it did make the laptop fan spin like a jet engine.",
  "Legend says this synchronous query is still running on localhost.",
  "The compiler requested emotional support after reading the database-level code.",
  "Legend says this database-level lock is still running on localhost.",
  "The compiler requested emotional support after reading the deadlocked code.",
  "Legend says this locked postgres is still running on localhost.",
  "Legend says this heavy database is still running on localhost.",
  "Legend says this unindexed connection is still running on localhost.",
  "Legend says this locked sql is still running on localhost.",
  "Legend says this raw sql is still running on localhost.",
  "Legend says this raw migration is still running on localhost.",
  "Legend says this synchronous sql is still running on localhost.",
  "Legend says this heavy table is still running on localhost.",
  "Legend says this deadlocked table is still running on localhost.",
  "Legend says this heavy postgres is still running on localhost.",
  "Legend says this raw transaction is still running on localhost.",
  "Legend says this synchronous connection is still running on localhost.",
  "Legend says this raw lock is still running on localhost.",
  "Legend says this blocked migration is still running on localhost.",
  "Legend says this blocked sql is still running on localhost.",
  "Legend says this heavy query is still running on localhost.",
  "Legend says this synchronous transaction is still running on localhost.",
  "Legend says this raw deadlock is still running on localhost.",
  "Legend says this heavy deadlock is still running on localhost.",
  "Legend says this locked table is still running on localhost.",
  "Legend says this raw table is still running on localhost.",
  "Legend says this heavy transaction is still running on localhost.",
  "Legend says this locked migration is still running on localhost.",
  "Legend says this blocked deadlock is still running on localhost.",
  "Legend says this synchronous postgres is still running on localhost.",
  "Legend says this heavy sql is still running on localhost.",
  "Legend says this locked transaction is still running on localhost.",
  "Legend says this blocked database is still running on localhost.",
  "Legend says this raw connection is still running on localhost.",
  "Legend says this deadlocked deadlock is still running on localhost.",
  "Legend says this blocked postgres is still running on localhost.",
  "Legend says this heavy migration is still running on localhost.",
  "Legend says this raw postgres is still running on localhost.",
  "Legend says this blocked transaction is still running on localhost.",
  "Legend says this unindexed query is still running on localhost.",
  "Legend says this locked lock is still running on localhost.",
  "Legend says this unindexed migration is still running on localhost.",
  "Legend says this unindexed lock is still running on localhost.",
  "Legend says this unindexed transaction is still running on localhost.",
  "Legend says this heavy lock is still running on localhost.",
  "Legend says this deadlocked connection is still running on localhost.",
  "Legend says this heavy connection is still running on localhost.",
  "Legend says this locked query is still running on localhost.",
  "Legend says this deadlocked database is still running on localhost.",
  "Legend says this blocked lock is still running on localhost.",
  "Legend says this locked deadlock is still running on localhost.",
  "Legend says this raw database is still running on localhost.",
  "Legend says this synchronous deadlock is still running on localhost.",
  "Legend says this locked connection is still running on localhost.",
  "Legend says this deadlocked transaction is still running on localhost.",
  "Legend says this deadlocked lock is still running on localhost.",
  "Legend says this deadlocked query is still running on localhost.",
  "Legend says this unindexed database is still running on localhost.",
  "This is a classic example of a raw transaction disaster.",
  "This is a classic example of a deadlocked postgres disaster.",
  "This is a classic example of a database-level deadlock disaster.",
  "This is a classic example of a blocked sql disaster.",
  "This is a classic example of a heavy table disaster.",
  "This is a classic example of a deadlocked database disaster.",
  "This is a classic example of a blocked migration disaster.",
  "This is a classic example of a unindexed sql disaster.",
  "This is a classic example of a deadlocked deadlock disaster.",
  "This is a classic example of a heavy deadlock disaster.",
  "This is a classic example of a unindexed postgres disaster.",
  "This is a classic example of a database-level table disaster.",
  "This is a classic example of a unindexed migration disaster.",
  "This is a classic example of a synchronous sql disaster.",
  "This is a classic example of a locked sql disaster.",
  "This is a classic example of a deadlocked table disaster.",
  "This is a classic example of a blocked query disaster.",
  "This is a classic example of a deadlocked sql disaster.",
  "This is a classic example of a heavy sql disaster.",
  "This is a classic example of a raw postgres disaster.",
  "This is a classic example of a synchronous deadlock disaster.",
  "This is a classic example of a heavy database disaster.",
  "This is a classic example of a unindexed lock disaster.",
  "This is a classic example of a locked database disaster.",
  "This is a classic example of a unindexed connection disaster.",
  "This is a classic example of a locked transaction disaster.",
  "This is a classic example of a locked migration disaster.",
  "This is a classic example of a deadlocked connection disaster.",
  "This is a classic example of a locked connection disaster.",
  "This is a classic example of a database-level migration disaster.",
  "This is a classic example of a raw deadlock disaster.",
  "This is a classic example of a locked postgres disaster.",
  "This is a classic example of a locked lock disaster.",
  "This is a classic example of a synchronous query disaster.",
  "This is a classic example of a raw sql disaster.",
  "This is a classic example of a heavy query disaster.",
  "This is a classic example of a blocked database disaster.",
  "This is a classic example of a synchronous postgres disaster.",
  "This is a classic example of a heavy lock disaster.",
  "This is a classic example of a synchronous transaction disaster.",
  "This is a classic example of a synchronous database disaster."
];

export const verdicts = [
  "Ship blocked by blocked check failures.",
  "Rejected on first principles of migration organization.",
  "Rejected on first principles of lock organization.",
  "Ship blocked by database-level check failures.",
  "Return after touching actual production servers.",
  "Rejected on first principles of transaction organization.",
  "Verdict: Table is completely unmergeable.",
  "Needs more commits and fewer explanations.",
  "Request changes on the unindexed lock.",
  "Verdict: Postgres is completely unmergeable.",
  "Closed as unindexed duplicate.",
  "Rejected on first principles of postgres organization.",
  "PR locked database table due to deadlocked implementation.",
  "Request changes on the synchronous sql.",
  "PR failed database migration due to database-level implementation.",
  "Verdict: Sql is completely unmergeable.",
  "PR rolled back transaction due to raw implementation.",
  "Closed as locked duplicate.",
  "Verdict: Database is completely unmergeable.",
  "Request changes on the synchronous migration.",
  "Closed as heavy duplicate.",
  "Rejected on first principles of table organization.",
  "Rejected on first principles of deadlock organization.",
  "Request changes on the raw transaction.",
  "Request changes on the deadlocked transaction.",
  "Closed as raw duplicate.",
  "Request changes on the heavy query.",
  "PR executed slow query due to blocked implementation.",
  "Request changes on the blocked table.",
  "PR rolled back transaction due to unindexed implementation.",
  "Request changes on the heavy deadlock.",
  "Verdict: Migration is completely unmergeable.",
  "Rejected on first principles of query organization.",
  "Request changes on the heavy connection.",
  "Request changes on the database-level deadlock.",
  "Request changes on the locked sql.",
  "Verdict: Deadlock is completely unmergeable.",
  "PR executed slow query due to heavy implementation.",
  "Request changes on the deadlocked connection.",
  "PR executed slow query due to database-level implementation.",
  "Request changes on the database-level table.",
  "Rejected on first principles of sql organization.",
  "PR failed database migration due to synchronous implementation.",
  "Closed as blocked duplicate.",
  "Closed as database-level duplicate.",
  "PR blocked network connection due to heavy implementation.",
  "PR locked database table due to raw implementation.",
  "Request changes on the database-level connection.",
  "Closed as synchronous duplicate.",
  "Request changes on the raw lock.",
  "Request changes on the raw migration.",
  "Closed as deadlocked duplicate.",
  "PR blocked network connection due to raw implementation.",
  "Request changes on the unindexed transaction.",
  "Verdict: Transaction is completely unmergeable.",
  "Verdict: Lock is completely unmergeable.",
  "PR locked database table due to heavy implementation.",
  "PR failed database migration due to deadlocked implementation.",
  "Request changes on the blocked postgres.",
  "PR blocked network connection due to deadlocked implementation.",
  "PR rolled back transaction due to heavy implementation.",
  "PR failed database migration due to raw implementation.",
  "PR blocked network connection due to synchronous implementation.",
  "PR executed slow query due to locked implementation.",
  "PR rolled back transaction due to synchronous implementation.",
  "Verdict: Connection is completely unmergeable.",
  "PR rolled back transaction due to blocked implementation.",
  "Request changes on the unindexed deadlock.",
  "Rejected on first principles of connection organization.",
  "PR failed database migration due to heavy implementation.",
  "Request changes on the synchronous query.",
  "PR failed database migration due to unindexed implementation.",
  "PR locked database table due to synchronous implementation.",
  "PR failed database migration due to blocked implementation.",
  "Request changes on the deadlocked lock.",
  "Request changes on the raw query.",
  "Rejected on first principles of database organization.",
  "PR rolled back transaction due to database-level implementation.",
  "Request changes on the raw table.",
  "Request changes on the locked query.",
  "Request changes on the database-level sql.",
  "PR blocked network connection due to unindexed implementation.",
  "Request changes on the heavy transaction.",
  "Request changes on the raw deadlock.",
  "Request changes on the raw postgres.",
  "Request changes on the raw connection.",
  "PR executed slow query due to deadlocked implementation.",
  "Verdict: Query is completely unmergeable.",
  "Request changes on the locked table.",
  "PR rolled back transaction due to deadlocked implementation.",
  "Request changes on the database-level transaction.",
  "Request changes on the synchronous connection.",
  "PR rolled back transaction due to locked implementation.",
  "Request changes on the deadlocked table."
];

export const easterEggs = [
  "NASA Alert: Space mission aborted due to a minor database parsing error.",
  "Elon Musk Tweet: 'Just deleted the entire transaction pipeline, was completely useless.'",
  "Gordon Ramsay Meltdown: 'This migration is raw! It's absolutely raw!'",
  "Matrix Glitch: You copy-pasted a template and now the server believes it is a real founder.",
  "Gordon Ramsay Meltdown: 'This transaction is raw! It's absolutely raw!'",
  "Steam Achievement Unlocked: Successfully crashed a hello-world app on a $10,000 server.",
  "Gordon Ramsay Meltdown: 'This lock is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted database-level databases.",
  "FBI Investigation: Suspect was found deploying unencrypted synchronous sqls.",
  "FBI Investigation: Suspect was found deploying unencrypted unindexed migrations.",
  "Dark Web Resume Auction: Current bid is $0.00, and the buyer is requesting a refund.",
  "Gordon Ramsay Meltdown: 'This database is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted blocked deadlocks.",
  "FBI Investigation: Suspect was found deploying unencrypted deadlocked connections.",
  "Gordon Ramsay Meltdown: 'This deadlock is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This connection is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This postgres is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted heavy querys.",
  "Gordon Ramsay Meltdown: 'This sql is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted locked databases.",
  "Gordon Ramsay Meltdown: 'This table is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This query is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted raw transactions."
];
