// ES Module exports for dating_profile roast format
export const titles = [
  "Lonely Profile Error",
  "Desperate Bio Error",
  "Standard Date Error",
  "Profile Not Found",
  "Standard Profile Loop",
  "Absolute Generic architecture",
  "The Bio tragedy",
  "Standard Not Found",
  "Clueless Conversation Error",
  "Critical Conversation failure",
  "NullPointerRelationshipException",
  "Interests Not Found",
  "Incident Report: Motivated Conversation",
  "Failed to compile: Date",
  "Incident Report: Motivated Date",
  "Lonely Conversation Loop",
  "The Interests tragedy",
  "Incident Report: Passionate Relationship",
  "Critical Red flag failure",
  "Clueless Standard Loop",
  "Absolute Lonely architecture",
  "Failed to compile: Red flag",
  "NullPointerSwipeException",
  "Desperate Bio Loop",
  "Standard conflict detected",
  "Clueless Standard Error",
  "NullPointerInterestsException",
  "Incident Report: Desperate Conversation",
  "Empty Conversation Loop",
  "Date Not Found",
  "Interests conflict detected",
  "Absolute Clueless architecture",
  "Standard Conversation Loop",
  "Passionate Conversation Loop",
  "Absolute Empty architecture",
  "Generic Swipe Error",
  "Incident Report: Clueless Swipe",
  "The Conversation tragedy",
  "NullPointerRed flagException",
  "Conversation conflict detected",
  "Incident Report: Clueless Conversation",
  "Incident Report: Motivated Standard",
  "Incident Report: Passionate Match",
  "The Profile tragedy",
  "Desperate Conversation Error",
  "Critical Bio failure",
  "Absolute Motivated architecture",
  "Critical Match failure",
  "Passionate Relationship Error",
  "Date conflict detected",
  "Failed to compile: Conversation",
  "The Swipe tragedy",
  "Desperate Interests Loop",
  "Passionate Interests Error",
  "Lonely Red flag Loop",
  "Swipe Not Found",
  "Standard Red flag Error",
  "Incident Report: Lonely Match",
  "Relationship conflict detected",
  "NullPointerMatchException",
  "Absolute Passionate architecture",
  "Motivated Bio Error",
  "Red flag Not Found",
  "Red flag conflict detected",
  "Incident Report: Standard Swipe",
  "Critical Swipe failure",
  "Critical Profile failure",
  "Critical Relationship failure",
  "The Standard tragedy",
  "Failed to compile: Interests",
  "Failed to compile: Match",
  "NullPointerDateException",
  "Motivated Conversation Error",
  "Desperate Date Loop",
  "Absolute Standard architecture",
  "NullPointerConversationException",
  "Incident Report: Generic Conversation",
  "The Date tragedy",
  "Incident Report: Standard Conversation",
  "Incident Report: Empty Date",
  "Bio conflict detected",
  "Empty Profile Error",
  "Incident Report: Empty Swipe",
  "Empty Bio Loop",
  "Passionate Match Error",
  "Failed to compile: Bio",
  "Desperate Date Error",
  "Desperate Interests Error",
  "Failed to compile: Profile",
  "Empty Profile Loop",
  "The Match tragedy",
  "Relationship Not Found",
  "Incident Report: Clueless Date",
  "Desperate Relationship Error",
  "Desperate Standard Loop",
  "NullPointerBioException",
  "Generic Red flag Error",
  "Empty Standard Loop",
  "Incident Report: Standard Date",
  "Lonely Match Error"
];

export const openings = [
  "Initial evaluation shows the developer decided to listed generic interests seeking validation.",
  "Warning: System flagged an attempt to ghosted potential match on the first date.",
  "Recruiters reported a case of desperate bio design.",
  "Alert: The candidate spent three months trying to sent suspicious DMs on the first date.",
  "Alert: The candidate spent three months trying to ignored profile warning seeking validation.",
  "Recruiters reported a case of passionate conversation design.",
  "Alert: The candidate spent three months trying to swiped right by accident without response.",
  "Initial evaluation shows the developer decided to sent suspicious DMs without response.",
  "We checked the history and found a desperate profile log.",
  "A review was filed regarding a clueless standard.",
  "Initial evaluation shows the developer decided to sent suspicious DMs seeking validation.",
  "Initial evaluation shows the developer decided to ghosted potential match in the matches queue.",
  "Warning: System flagged an attempt to sent suspicious DMs in the matches queue.",
  "Scanning candidate profile for standard matchs...",
  "A review was filed regarding a empty standard.",
  "Recruiters reported a case of empty swipe design.",
  "Initial evaluation shows the developer decided to listed generic interests without response.",
  "Alert: The candidate spent three months trying to ignored profile warning without response.",
  "We checked the history and found a desperate swipe log.",
  "A review was filed regarding a empty match.",
  "Scanning candidate profile for standard bios...",
  "Initial evaluation shows the developer decided to ignored profile warning after single conversation.",
  "Warning: System flagged an attempt to ghosted potential match without response.",
  "A review was filed regarding a motivated profile.",
  "Scanning candidate profile for standard dates...",
  "Recruiters reported a case of standard profile design.",
  "The team has initiated audit for the candidate's profile setup.",
  "Warning: System flagged an attempt to swiped right by accident seeking validation.",
  "Warning: System flagged an attempt to sent suspicious DMs after single conversation.",
  "We checked the history and found a standard conversation log.",
  "Scanning candidate profile for empty conversations...",
  "Recruiters reported a case of passionate swipe design.",
  "Initial evaluation shows the developer decided to ghosted potential match without response.",
  "Warning: System flagged an attempt to ghosted potential match in the matches queue.",
  "Alert: The candidate spent three months trying to listed generic interests in the matches queue.",
  "Scanning candidate profile for passionate interestss...",
  "Recruiters reported a case of desperate conversation design.",
  "Recruiters reported a case of lonely bio design.",
  "A review was filed regarding a passionate swipe.",
  "A review was filed regarding a generic standard.",
  "We checked the history and found a passionate relationship log.",
  "A review was filed regarding a passionate match.",
  "Alert: The candidate spent three months trying to ghosted potential match seeking validation.",
  "We checked the history and found a desperate standard log.",
  "Warning: System flagged an attempt to listed generic interests seeking validation.",
  "Alert: The candidate spent three months trying to ghosted potential match on the first date.",
  "We checked the history and found a lonely match log.",
  "Initial evaluation shows the developer decided to ghosted potential match on the first date.",
  "We checked the history and found a passionate match log.",
  "Warning: System flagged an attempt to ignored profile warning after single conversation.",
  "Alert: The candidate spent three months trying to swiped right by accident in the matches queue.",
  "Recruiters reported a case of desperate red flag design.",
  "We checked the history and found a generic swipe log.",
  "Alert: The candidate spent three months trying to sent suspicious DMs in the matches queue.",
  "Scanning candidate profile for lonely relationships...",
  "A review was filed regarding a generic match.",
  "We checked the history and found a clueless standard log.",
  "Scanning candidate profile for motivated swipes...",
  "Warning: System flagged an attempt to ignored profile warning in the matches queue.",
  "Scanning candidate profile for empty swipes...",
  "Warning: System flagged an attempt to swiped right by accident in the matches queue.",
  "Initial evaluation shows the developer decided to listed generic interests on the first date.",
  "Initial evaluation shows the developer decided to swiped right by accident after single conversation.",
  "A review was filed regarding a lonely swipe.",
  "Scanning candidate profile for empty bios...",
  "Warning: System flagged an attempt to listed generic interests in the matches queue.",
  "Scanning candidate profile for lonely profiles...",
  "Scanning candidate profile for clueless dates...",
  "Initial evaluation shows the developer decided to ignored profile warning seeking validation.",
  "Alert: The candidate spent three months trying to swiped right by accident seeking validation.",
  "A review was filed regarding a generic interests.",
  "Warning: System flagged an attempt to ghosted potential match after single conversation.",
  "We checked the history and found a desperate bio log.",
  "We checked the history and found a lonely standard log.",
  "Warning: System flagged an attempt to listed generic interests on the first date.",
  "Alert: The candidate spent three months trying to sent suspicious DMs after single conversation.",
  "We checked the history and found a generic standard log.",
  "Recruiters reported a case of desperate standard design.",
  "Scanning candidate profile for generic dates...",
  "A review was filed regarding a lonely bio.",
  "Alert: The candidate spent three months trying to ignored profile warning after single conversation.",
  "Alert: The candidate spent three months trying to listed generic interests seeking validation.",
  "Recruiters reported a case of empty interests design.",
  "We checked the history and found a empty date log.",
  "Initial evaluation shows the developer decided to swiped right by accident without response.",
  "We checked the history and found a clueless interests log.",
  "Scanning candidate profile for lonely swipes...",
  "A review was filed regarding a standard profile.",
  "We checked the history and found a generic relationship log.",
  "A review was filed regarding a empty swipe.",
  "Initial evaluation shows the developer decided to ignored profile warning without response."
];

export const findings = [
  "A security audit on {{github}} detected a plain-text database password inside a desperate bio.",
  "Obtained {{certification}} which apparently teaches how to ignored profile warning without response.",
  "Failed to configure {{project}} because {{candidateName}} decided to ignored profile warning in the matches queue.",
  "{{achievement}} was highlighted, but the git logs show they only managed to sent suspicious DMs on the first date.",
  "The candidate claims {{framework}} experience, but their repository is just a desperate clone that has been abandoned.",
  "Listed {{skill}} as a primary competency, but the evidence points to a standard profile.",
  "Failed to configure {{project}} because {{candidateName}} decided to ghosted potential match seeking validation.",
  "{{github}} contains more empty bios than original code.",
  "{{github}} contains more standard profiles than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to listed generic interests after single conversation.",
  "While debugging {{project}}, we found a desperate logic loop related to {{language}} features.",
  "For {{experience}}, the primary contribution was writing a lonely config for a swipe.",
  "{{candidateName}} has spent three weeks optimizing a swipe while completely ignoring {{missingSection}}.",
  "Obtained {{certification}} which apparently teaches how to sent suspicious DMs on the first date.",
  "{{github}} contains more passionate dates than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a lonely standard.",
  "Obtained {{certification}} which apparently teaches how to ghosted potential match seeking validation.",
  "For {{experience}}, the primary contribution was writing a clueless config for a date.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ghosted potential match on the first date.",
  "{{github}} contains more generic bios than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to swiped right by accident without response.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to sent suspicious DMs after single conversation.",
  "Obtained {{certification}} which apparently teaches how to sent suspicious DMs seeking validation.",
  "For {{experience}}, the primary contribution was writing a generic config for a bio.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to listed generic interests on the first date.",
  "{{github}} contains more generic profiles than original code.",
  "Listed {{skill}} as a primary competency, but the evidence points to a motivated red flag.",
  "Failed to configure {{project}} because {{candidateName}} decided to sent suspicious DMs seeking validation.",
  "{{github}} contains more clueless swipes than original code.",
  "{{github}} contains more lonely interestss than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ignored profile warning on the first date.",
  "{{github}} contains more standard dates than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a generic conversation.",
  "{{education}} is listed, but they still managed to deploy a motivated interests to production.",
  "{{github}} contains more passionate relationships than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ghosted potential match on the first date.",
  "{{candidateName}} has spent three weeks optimizing a red flag while completely ignoring {{missingSection}}.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to sent suspicious DMs on the first date.",
  "{{github}} contains more clueless bios than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to sent suspicious DMs without response.",
  "Obtained {{certification}} which apparently teaches how to ghosted potential match after single conversation.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ghosted potential match without response.",
  "Failed to configure {{project}} because {{candidateName}} decided to sent suspicious DMs on the first date.",
  "{{education}} is listed, but they still managed to deploy a clueless bio to production.",
  "Listed {{skill}} as a primary competency, but the evidence points to a passionate interests.",
  "Listed {{skill}} as a primary competency, but the evidence points to a empty bio.",
  "Failed to configure {{project}} because {{candidateName}} decided to ghosted potential match after single conversation.",
  "Obtained {{certification}} which apparently teaches how to ignored profile warning after single conversation.",
  "{{github}} contains more desperate matchs than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to sent suspicious DMs seeking validation.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to swiped right by accident seeking validation.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to listed generic interests without response.",
  "Listed {{skill}} as a primary competency, but the evidence points to a generic date.",
  "{{github}} contains more generic red flags than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to sent suspicious DMs without response.",
  "Failed to configure {{project}} because {{candidateName}} decided to listed generic interests seeking validation.",
  "A security audit on {{github}} detected a plain-text database password inside a standard red flag.",
  "{{github}} contains more passionate bios than original code.",
  "For {{experience}}, the primary contribution was writing a desperate config for a match.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ignored profile warning on the first date.",
  "{{education}} is listed, but they still managed to deploy a standard conversation to production.",
  "Obtained {{certification}} which apparently teaches how to sent suspicious DMs in the matches queue.",
  "{{achievement}} was highlighted, but the git logs show they only managed to swiped right by accident without response.",
  "{{github}} contains more empty conversations than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to listed generic interests on the first date.",
  "Listed {{skill}} as a primary competency, but the evidence points to a clueless conversation.",
  "Failed to configure {{project}} because {{candidateName}} decided to listed generic interests in the matches queue.",
  "{{github}} contains more clueless standards than original code.",
  "Obtained {{certification}} which apparently teaches how to listed generic interests in the matches queue.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to listed generic interests seeking validation.",
  "{{github}} contains more motivated dates than original code.",
  "For {{experience}}, the primary contribution was writing a motivated config for a conversation.",
  "{{github}} contains more desperate bios than original code.",
  "{{github}} contains more lonely bios than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a clueless interests.",
  "{{achievement}} was highlighted, but the git logs show they only managed to sent suspicious DMs after single conversation.",
  "{{achievement}} was highlighted, but the git logs show they only managed to listed generic interests seeking validation.",
  "Obtained {{certification}} which apparently teaches how to sent suspicious DMs after single conversation.",
  "Failed to configure {{project}} because {{candidateName}} decided to swiped right by accident in the matches queue.",
  "{{github}} contains more generic swipes than original code.",
  "Obtained {{certification}} which apparently teaches how to ghosted potential match in the matches queue.",
  "A security audit on {{github}} detected a plain-text database password inside a empty profile.",
  "Failed to configure {{project}} because {{candidateName}} decided to ghosted potential match without response.",
  "{{achievement}} was highlighted, but the git logs show they only managed to swiped right by accident in the matches queue.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to swiped right by accident after single conversation.",
  "{{achievement}} was highlighted, but the git logs show they only managed to listed generic interests without response.",
  "Failed to configure {{project}} because {{candidateName}} decided to listed generic interests without response.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ghosted potential match seeking validation.",
  "A security audit on {{github}} detected a plain-text database password inside a passionate swipe.",
  "Failed to configure {{project}} because {{candidateName}} decided to swiped right by accident on the first date.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ghosted potential match in the matches queue.",
  "Obtained {{certification}} which apparently teaches how to ghosted potential match on the first date.",
  "{{achievement}} was highlighted, but the git logs show they only managed to listed generic interests in the matches queue.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ghosted potential match after single conversation.",
  "For {{experience}}, the primary contribution was writing a desperate config for a red flag.",
  "Failed to configure {{project}} because {{candidateName}} decided to sent suspicious DMs after single conversation.",
  "Obtained {{certification}} which apparently teaches how to ignored profile warning in the matches queue.",
  "Failed to configure {{project}} because {{candidateName}} decided to ghosted potential match in the matches queue.",
  "{{education}} is listed, but they still managed to deploy a empty profile to production.",
  "{{education}} is listed, but they still managed to deploy a generic date to production.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to listed generic interests in the matches queue.",
  "Listed {{skill}} as a primary competency, but the evidence points to a motivated relationship.",
  "For {{experience}}, the primary contribution was writing a passionate config for a profile.",
  "{{github}} contains more empty swipes than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to sent suspicious DMs in the matches queue.",
  "Obtained {{certification}} which apparently teaches how to swiped right by accident on the first date.",
  "Failed to configure {{project}} because {{candidateName}} decided to listed generic interests on the first date.",
  "{{github}} contains more standard swipes than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to sent suspicious DMs seeking validation.",
  "{{github}} contains more generic relationships than original code.",
  "{{education}} is listed, but they still managed to deploy a empty red flag to production.",
  "Failed to configure {{project}} because {{candidateName}} decided to listed generic interests after single conversation.",
  "Listed {{skill}} as a primary competency, but the evidence points to a desperate swipe.",
  "Obtained {{certification}} which apparently teaches how to ignored profile warning on the first date.",
  "{{github}} contains more lonely profiles than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to ignored profile warning on the first date.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ghosted potential match in the matches queue.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to sent suspicious DMs in the matches queue.",
  "{{achievement}} was highlighted, but the git logs show they only managed to swiped right by accident on the first date.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ignored profile warning after single conversation.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ignored profile warning without response.",
  "{{github}} contains more generic interestss than original code."
];

export const punchlines = [
  "The compiler requested emotional support after reading the motivated code.",
  "It did not optimize our process, but it did make the laptop fan spin like a jet engine.",
  "The only thing memory-safe about this setup is that nobody has ever tried to run it.",
  "A junior developer looked at the date and immediately went to touch grass.",
  "Legend says this lonely profile is still running on localhost.",
  "The documentation was so empty, I had to use it as a virtual sketchbook.",
  "We would deploy it to production, but our SRE team deserves to sleep at night.",
  "Legend says this clueless relationship is still running on localhost.",
  "Even Stack Overflow has marked this date as off-topic.",
  "Legend says this empty red flag is still running on localhost.",
  "Legend says this empty match is still running on localhost.",
  "Legend says this standard conversation is still running on localhost.",
  "Legend says this empty relationship is still running on localhost.",
  "Legend says this generic interests is still running on localhost.",
  "Legend says this lonely conversation is still running on localhost.",
  "Legend says this empty interests is still running on localhost.",
  "Legend says this clueless interests is still running on localhost.",
  "Even Stack Overflow has marked this red flag as off-topic.",
  "Legend says this generic conversation is still running on localhost.",
  "Legend says this passionate interests is still running on localhost.",
  "Legend says this standard bio is still running on localhost.",
  "Legend says this lonely bio is still running on localhost.",
  "Legend says this generic bio is still running on localhost.",
  "Legend says this lonely date is still running on localhost.",
  "Legend says this desperate match is still running on localhost.",
  "Legend says this clueless bio is still running on localhost.",
  "Legend says this generic standard is still running on localhost.",
  "Legend says this generic profile is still running on localhost.",
  "Legend says this standard interests is still running on localhost.",
  "Legend says this generic date is still running on localhost.",
  "Legend says this standard profile is still running on localhost.",
  "Legend says this desperate swipe is still running on localhost.",
  "Legend says this passionate match is still running on localhost.",
  "A junior developer looked at the red flag and immediately went to touch grass.",
  "Legend says this passionate date is still running on localhost.",
  "Legend says this passionate relationship is still running on localhost.",
  "Legend says this lonely relationship is still running on localhost.",
  "Legend says this motivated interests is still running on localhost.",
  "Legend says this generic swipe is still running on localhost.",
  "Legend says this generic match is still running on localhost.",
  "Legend says this standard relationship is still running on localhost.",
  "Legend says this clueless swipe is still running on localhost.",
  "Legend says this lonely swipe is still running on localhost.",
  "Legend says this passionate conversation is still running on localhost.",
  "Legend says this passionate swipe is still running on localhost.",
  "Legend says this empty standard is still running on localhost.",
  "Legend says this clueless date is still running on localhost.",
  "Legend says this desperate date is still running on localhost.",
  "Legend says this desperate profile is still running on localhost.",
  "Legend says this empty bio is still running on localhost.",
  "Legend says this empty profile is still running on localhost.",
  "Legend says this motivated conversation is still running on localhost.",
  "Legend says this empty swipe is still running on localhost.",
  "Legend says this motivated standard is still running on localhost.",
  "Legend says this motivated date is still running on localhost.",
  "Legend says this desperate bio is still running on localhost.",
  "Legend says this lonely match is still running on localhost.",
  "Legend says this motivated match is still running on localhost.",
  "Legend says this clueless profile is still running on localhost.",
  "This is a classic example of a generic red flag disaster.",
  "This is a classic example of a desperate swipe disaster.",
  "This is a classic example of a clueless relationship disaster.",
  "This is a classic example of a passionate match disaster.",
  "This is a classic example of a clueless conversation disaster.",
  "This is a classic example of a standard standard disaster.",
  "This is a classic example of a desperate interests disaster.",
  "This is a classic example of a motivated date disaster.",
  "This is a classic example of a passionate conversation disaster.",
  "This is a classic example of a empty conversation disaster.",
  "This is a classic example of a lonely red flag disaster.",
  "This is a classic example of a generic bio disaster.",
  "This is a classic example of a generic swipe disaster.",
  "This is a classic example of a motivated red flag disaster.",
  "This is a classic example of a motivated profile disaster.",
  "This is a classic example of a generic relationship disaster.",
  "This is a classic example of a passionate interests disaster.",
  "This is a classic example of a lonely date disaster.",
  "This is a classic example of a motivated swipe disaster.",
  "This is a classic example of a desperate match disaster.",
  "This is a classic example of a empty swipe disaster.",
  "This is a classic example of a desperate conversation disaster.",
  "This is a classic example of a generic profile disaster.",
  "This is a classic example of a generic interests disaster.",
  "This is a classic example of a generic match disaster.",
  "This is a classic example of a generic date disaster.",
  "This is a classic example of a desperate profile disaster.",
  "This is a classic example of a desperate date disaster.",
  "This is a classic example of a clueless profile disaster.",
  "This is a classic example of a lonely match disaster.",
  "This is a classic example of a motivated match disaster.",
  "This is a classic example of a lonely relationship disaster.",
  "This is a classic example of a motivated relationship disaster."
];

export const verdicts = [
  "Return after touching actual production servers.",
  "Needs more commits and fewer explanations.",
  "Rejected on first principles of date organization.",
  "Ship blocked by empty check failures.",
  "Closed as desperate duplicate.",
  "PR ignored profile warning due to empty implementation.",
  "Request changes on the standard interests.",
  "Ship blocked by desperate check failures.",
  "PR ghosted potential match due to empty implementation.",
  "Verdict: Conversation is completely unmergeable.",
  "Request changes on the passionate match.",
  "Request changes on the generic standard.",
  "Closed as standard duplicate.",
  "Ship blocked by clueless check failures.",
  "Request changes on the generic match.",
  "Rejected on first principles of conversation organization.",
  "Closed as clueless duplicate.",
  "Closed as empty duplicate.",
  "PR listed generic interests due to passionate implementation.",
  "PR swiped right by accident due to passionate implementation.",
  "Closed as generic duplicate.",
  "Verdict: Red flag is completely unmergeable.",
  "Request changes on the motivated date.",
  "Request changes on the clueless swipe.",
  "Request changes on the empty red flag.",
  "Request changes on the clueless red flag.",
  "Verdict: Interests is completely unmergeable.",
  "Ship blocked by generic check failures.",
  "Request changes on the motivated profile.",
  "Closed as lonely duplicate.",
  "Ship blocked by passionate check failures.",
  "Ship blocked by standard check failures.",
  "Rejected on first principles of relationship organization.",
  "PR sent suspicious DMs due to passionate implementation.",
  "Closed as motivated duplicate.",
  "Request changes on the lonely bio.",
  "Request changes on the passionate profile.",
  "Verdict: Standard is completely unmergeable.",
  "Ship blocked by lonely check failures.",
  "Request changes on the lonely standard.",
  "Verdict: Bio is completely unmergeable.",
  "Verdict: Swipe is completely unmergeable.",
  "PR swiped right by accident due to generic implementation.",
  "Request changes on the generic bio.",
  "Verdict: Profile is completely unmergeable.",
  "Request changes on the passionate swipe.",
  "PR swiped right by accident due to empty implementation.",
  "PR ignored profile warning due to standard implementation.",
  "Request changes on the standard red flag.",
  "PR listed generic interests due to desperate implementation.",
  "Verdict: Date is completely unmergeable.",
  "Request changes on the empty date.",
  "PR listed generic interests due to motivated implementation.",
  "PR listed generic interests due to standard implementation.",
  "Request changes on the empty standard.",
  "PR ignored profile warning due to generic implementation.",
  "Closed as passionate duplicate.",
  "Rejected on first principles of standard organization.",
  "Rejected on first principles of red flag organization.",
  "PR sent suspicious DMs due to empty implementation.",
  "Request changes on the desperate match.",
  "Rejected on first principles of interests organization.",
  "PR sent suspicious DMs due to desperate implementation.",
  "PR ignored profile warning due to lonely implementation.",
  "Request changes on the motivated conversation.",
  "Request changes on the lonely relationship.",
  "Request changes on the clueless standard.",
  "PR swiped right by accident due to lonely implementation.",
  "Request changes on the clueless bio.",
  "PR ignored profile warning due to motivated implementation.",
  "Request changes on the lonely red flag.",
  "Request changes on the passionate red flag.",
  "PR ghosted potential match due to desperate implementation.",
  "Request changes on the motivated bio.",
  "Rejected on first principles of swipe organization.",
  "PR listed generic interests due to lonely implementation.",
  "Ship blocked by motivated check failures.",
  "Rejected on first principles of profile organization.",
  "Request changes on the lonely date.",
  "PR ignored profile warning due to passionate implementation.",
  "Verdict: Match is completely unmergeable.",
  "PR sent suspicious DMs due to lonely implementation.",
  "PR ignored profile warning due to clueless implementation.",
  "Request changes on the lonely profile.",
  "PR swiped right by accident due to motivated implementation.",
  "PR ghosted potential match due to standard implementation.",
  "Request changes on the motivated relationship.",
  "Request changes on the standard relationship.",
  "PR listed generic interests due to clueless implementation.",
  "Request changes on the desperate interests.",
  "Request changes on the generic profile.",
  "Verdict: Relationship is completely unmergeable.",
  "Request changes on the passionate relationship.",
  "PR sent suspicious DMs due to generic implementation.",
  "Request changes on the generic red flag.",
  "PR sent suspicious DMs due to standard implementation.",
  "Request changes on the clueless date.",
  "PR swiped right by accident due to clueless implementation.",
  "Rejected on first principles of bio organization."
];

export const easterEggs = [
  "Dark Web Resume Auction: Current bid is $0.00, and the buyer is requesting a refund.",
  "NASA Alert: Space mission aborted due to a minor swipe parsing error.",
  "Gordon Ramsay Meltdown: 'This date is raw! It's absolutely raw!'",
  "Matrix Glitch: You copy-pasted a template and now the server believes it is a real founder.",
  "Elon Musk Tweet: 'Just deleted the entire swipe pipeline, was completely useless.'",
  "Gordon Ramsay Meltdown: 'This swipe is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This relationship is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted lonely dates.",
  "FBI Investigation: Suspect was found deploying unencrypted motivated bios.",
  "NASA Alert: Space mission aborted due to a minor red flag parsing error.",
  "Steam Achievement Unlocked: Successfully crashed a hello-world app on a $10,000 server.",
  "Gordon Ramsay Meltdown: 'This match is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted standard swipes.",
  "Elon Musk Tweet: 'Just deleted the entire red flag pipeline, was completely useless.'",
  "FBI Investigation: Suspect was found deploying unencrypted desperate standards.",
  "Gordon Ramsay Meltdown: 'This profile is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This bio is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This conversation is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This interests is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted empty matchs.",
  "Gordon Ramsay Meltdown: 'This red flag is raw! It's absolutely raw!'"
];
