// ES Module exports for docker_log roast format
export const titles = [
  "Incident Report: Raw Image",
  "Failed to compile: Env",
  "Critical Overlay failure",
  "Incident Report: Missing Image",
  "Port conflict detected",
  "Dockerfile Not Found",
  "Absolute Read-only architecture",
  "The Env tragedy",
  "Bloated Volume Error",
  "Overlay Not Found",
  "NullPointerPortException",
  "Failed to compile: Image",
  "Container conflict detected",
  "Untagged Dockerfile Error",
  "Failed to compile: Overlay",
  "Untagged Container Loop",
  "Incident Report: Heavy Entrypoint",
  "Bloated Image Error",
  "NullPointerContainerException",
  "NullPointerVolumeException",
  "Incident Report: Missing Env",
  "Raw Cache Error",
  "Failed to compile: Container",
  "Bloated Entrypoint Error",
  "Bloated Cache Loop",
  "The Container tragedy",
  "Image conflict detected",
  "Raw Image Error",
  "Incident Report: Unprivileged Dockerfile",
  "Incident Report: Read-only Env",
  "NullPointerEnvException",
  "The Daemon tragedy",
  "Critical Dockerfile failure",
  "Read-only Image Loop",
  "Critical Entrypoint failure",
  "Port Not Found",
  "Unprivileged Port Loop",
  "Absolute Missing architecture",
  "Critical Container failure",
  "The Port tragedy",
  "Volume conflict detected",
  "Incident Report: Read-only Cache",
  "NullPointerDaemonException",
  "Entrypoint conflict detected",
  "Read-only Overlay Error",
  "Absolute Untagged architecture",
  "NullPointerEntrypointException",
  "Env conflict detected",
  "NullPointerImageException",
  "Cache Not Found",
  "Incident Report: Bloated Cache",
  "Critical Env failure",
  "Missing Overlay Loop",
  "Read-only Volume Error",
  "Read-only Volume Loop",
  "Crashed Volume Loop",
  "Incident Report: Untagged Port",
  "Incident Report: Crashed Image",
  "NullPointerOverlayException",
  "Incident Report: Heavy Cache",
  "Volume Not Found",
  "Incident Report: Crashed Env",
  "Entrypoint Not Found",
  "Heavy Cache Error",
  "Bloated Dockerfile Loop",
  "Read-only Entrypoint Loop",
  "Incident Report: Untagged Cache",
  "Untagged Daemon Loop",
  "Missing Volume Error",
  "Failed to compile: Dockerfile",
  "Daemon conflict detected",
  "Bloated Port Error",
  "Absolute Heavy architecture",
  "Env Not Found",
  "NullPointerCacheException",
  "Incident Report: Raw Container",
  "Missing Daemon Loop",
  "Overlay conflict detected",
  "Absolute Crashed architecture",
  "Failed to compile: Port",
  "Failed to compile: Cache",
  "The Image tragedy",
  "NullPointerDockerfileException",
  "Critical Image failure",
  "Absolute Raw architecture",
  "Daemon Not Found",
  "Absolute Unprivileged architecture",
  "Incident Report: Bloated Container",
  "Dockerfile conflict detected",
  "Incident Report: Unprivileged Env",
  "The Volume tragedy",
  "Read-only Overlay Loop",
  "Crashed Dockerfile Error",
  "The Cache tragedy",
  "Cache conflict detected",
  "Failed to compile: Entrypoint",
  "Failed to compile: Daemon",
  "Absolute Bloated architecture",
  "Unprivileged Dockerfile Loop",
  "Raw Overlay Loop"
];

export const openings = [
  "The team has initiated audit for the candidate's port setup.",
  "Recruiters reported a case of untagged image design.",
  "Scanning candidate profile for unprivileged containers...",
  "Alert: The candidate spent three months trying to exposed public port exiting with status 137.",
  "Alert: The candidate spent three months trying to started daemon due to segment fault.",
  "Alert: The candidate spent three months trying to pulled raw layer due to segment fault.",
  "Recruiters reported a case of untagged volume design.",
  "Initial evaluation shows the developer decided to mounted read-only path on missing memory.",
  "Scanning candidate profile for read-only dockerfiles...",
  "Warning: System flagged an attempt to exposed public port exiting with status 137.",
  "Warning: System flagged an attempt to exposed public port with host path exposed.",
  "A review was filed regarding a read-only env.",
  "Warning: System flagged an attempt to started daemon without valid shell.",
  "Recruiters reported a case of missing daemon design.",
  "Alert: The candidate spent three months trying to built image with host path exposed.",
  "We checked the history and found a heavy cache log.",
  "Warning: System flagged an attempt to started daemon exiting with status 137.",
  "Warning: System flagged an attempt to started daemon with host path exposed.",
  "Scanning candidate profile for unprivileged volumes...",
  "We checked the history and found a heavy entrypoint log.",
  "A review was filed regarding a unprivileged image.",
  "Initial evaluation shows the developer decided to built image due to segment fault.",
  "A review was filed regarding a untagged image.",
  "A review was filed regarding a crashed volume.",
  "Warning: System flagged an attempt to started daemon due to segment fault.",
  "Warning: System flagged an attempt to mounted read-only path with host path exposed.",
  "A review was filed regarding a read-only volume.",
  "Alert: The candidate spent three months trying to started daemon with host path exposed.",
  "Scanning candidate profile for crashed caches...",
  "Recruiters reported a case of heavy overlay design.",
  "We checked the history and found a crashed overlay log.",
  "A review was filed regarding a untagged port.",
  "A review was filed regarding a heavy volume.",
  "A review was filed regarding a untagged env.",
  "We checked the history and found a read-only entrypoint log.",
  "We checked the history and found a crashed entrypoint log.",
  "Warning: System flagged an attempt to built image with host path exposed.",
  "Initial evaluation shows the developer decided to started daemon without valid shell.",
  "Recruiters reported a case of unprivileged image design.",
  "Scanning candidate profile for missing envs...",
  "Scanning candidate profile for read-only caches...",
  "Initial evaluation shows the developer decided to pulled raw layer on missing memory.",
  "A review was filed regarding a unprivileged port.",
  "Recruiters reported a case of read-only cache design.",
  "A review was filed regarding a unprivileged entrypoint.",
  "Recruiters reported a case of read-only container design.",
  "Scanning candidate profile for heavy containers...",
  "Alert: The candidate spent three months trying to pulled raw layer with host path exposed.",
  "A review was filed regarding a crashed overlay.",
  "A review was filed regarding a unprivileged container.",
  "Recruiters reported a case of missing port design.",
  "Alert: The candidate spent three months trying to built image due to segment fault.",
  "Alert: The candidate spent three months trying to exposed public port without valid shell.",
  "A review was filed regarding a crashed entrypoint.",
  "Scanning candidate profile for missing overlays...",
  "A review was filed regarding a missing cache.",
  "Recruiters reported a case of heavy daemon design.",
  "A review was filed regarding a bloated container.",
  "Scanning candidate profile for heavy entrypoints...",
  "Initial evaluation shows the developer decided to exposed public port with host path exposed.",
  "Warning: System flagged an attempt to built image due to segment fault.",
  "Alert: The candidate spent three months trying to started daemon exiting with status 137.",
  "Initial evaluation shows the developer decided to started daemon on missing memory.",
  "Scanning candidate profile for raw envs...",
  "A review was filed regarding a heavy daemon.",
  "Alert: The candidate spent three months trying to pulled raw layer without valid shell.",
  "Recruiters reported a case of crashed daemon design.",
  "Scanning candidate profile for unprivileged envs...",
  "A review was filed regarding a raw port.",
  "Scanning candidate profile for heavy images...",
  "Alert: The candidate spent three months trying to built image exiting with status 137.",
  "Recruiters reported a case of read-only daemon design.",
  "Scanning candidate profile for missing containers...",
  "Scanning candidate profile for untagged envs...",
  "Initial evaluation shows the developer decided to mounted read-only path due to segment fault.",
  "Warning: System flagged an attempt to mounted read-only path exiting with status 137.",
  "Scanning candidate profile for untagged ports...",
  "Recruiters reported a case of untagged daemon design.",
  "Warning: System flagged an attempt to pulled raw layer without valid shell.",
  "Recruiters reported a case of missing dockerfile design.",
  "Scanning candidate profile for unprivileged daemons...",
  "Alert: The candidate spent three months trying to mounted read-only path with host path exposed.",
  "Initial evaluation shows the developer decided to built image with host path exposed.",
  "A review was filed regarding a bloated dockerfile.",
  "We checked the history and found a unprivileged overlay log.",
  "Scanning candidate profile for unprivileged images...",
  "Alert: The candidate spent three months trying to pulled raw layer on missing memory.",
  "We checked the history and found a bloated volume log.",
  "We checked the history and found a missing image log.",
  "Recruiters reported a case of bloated volume design.",
  "A review was filed regarding a crashed dockerfile."
];

export const findings = [
  "Obtained {{certification}} which apparently teaches how to pulled raw layer on missing memory.",
  "Obtained {{certification}} which apparently teaches how to started daemon without valid shell.",
  "{{education}} is listed, but they still managed to deploy a bloated env to production.",
  "The candidate claims {{framework}} experience, but their repository is just a bloated clone that has been abandoned.",
  "Obtained {{certification}} which apparently teaches how to mounted read-only path without valid shell.",
  "{{education}} is listed, but they still managed to deploy a unprivileged entrypoint to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to mounted read-only path without valid shell.",
  "Obtained {{certification}} which apparently teaches how to exposed public port on missing memory.",
  "{{candidateName}} has spent three weeks optimizing a env while completely ignoring {{missingSection}}.",
  "A security audit on {{github}} detected a plain-text database password inside a read-only env.",
  "Listed {{skill}} as a primary competency, but the evidence points to a heavy container.",
  "For {{experience}}, the primary contribution was writing a raw config for a volume.",
  "{{education}} is listed, but they still managed to deploy a untagged overlay to production.",
  "While debugging {{project}}, we found a read-only logic loop related to {{language}} features.",
  "{{achievement}} was highlighted, but the git logs show they only managed to built image exiting with status 137.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to exposed public port with host path exposed.",
  "While debugging {{project}}, we found a heavy logic loop related to {{language}} features.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to built image with host path exposed.",
  "{{github}} contains more untagged caches than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to started daemon due to segment fault.",
  "Obtained {{certification}} which apparently teaches how to mounted read-only path exiting with status 137.",
  "{{education}} is listed, but they still managed to deploy a raw daemon to production.",
  "Listed {{skill}} as a primary competency, but the evidence points to a raw dockerfile.",
  "A security audit on {{github}} detected a plain-text database password inside a untagged entrypoint.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to mounted read-only path on missing memory.",
  "For {{experience}}, the primary contribution was writing a bloated config for a image.",
  "Failed to configure {{project}} because {{candidateName}} decided to mounted read-only path with host path exposed.",
  "{{github}} contains more bloated caches than original code.",
  "For {{experience}}, the primary contribution was writing a crashed config for a entrypoint.",
  "{{achievement}} was highlighted, but the git logs show they only managed to exposed public port with host path exposed.",
  "A security audit on {{github}} detected a plain-text database password inside a bloated image.",
  "Listed {{skill}} as a primary competency, but the evidence points to a read-only dockerfile.",
  "Listed {{skill}} as a primary competency, but the evidence points to a crashed daemon.",
  "Obtained {{certification}} which apparently teaches how to built image without valid shell.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to pulled raw layer due to segment fault.",
  "{{github}} contains more read-only entrypoints than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to started daemon with host path exposed.",
  "For {{experience}}, the primary contribution was writing a read-only config for a image.",
  "{{github}} contains more unprivileged entrypoints than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to built image exiting with status 137.",
  "Failed to configure {{project}} because {{candidateName}} decided to pulled raw layer due to segment fault.",
  "{{education}} is listed, but they still managed to deploy a missing container to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to started daemon with host path exposed.",
  "{{github}} contains more crashed daemons than original code.",
  "For {{experience}}, the primary contribution was writing a unprivileged config for a container.",
  "Listed {{skill}} as a primary competency, but the evidence points to a bloated env.",
  "Failed to configure {{project}} because {{candidateName}} decided to pulled raw layer with host path exposed.",
  "{{achievement}} was highlighted, but the git logs show they only managed to pulled raw layer exiting with status 137.",
  "Obtained {{certification}} which apparently teaches how to mounted read-only path with host path exposed.",
  "{{github}} contains more unprivileged caches than original code.",
  "For {{experience}}, the primary contribution was writing a heavy config for a daemon.",
  "Obtained {{certification}} which apparently teaches how to mounted read-only path due to segment fault.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to started daemon without valid shell.",
  "Obtained {{certification}} which apparently teaches how to built image due to segment fault.",
  "{{achievement}} was highlighted, but the git logs show they only managed to built image on missing memory.",
  "Obtained {{certification}} which apparently teaches how to pulled raw layer with host path exposed.",
  "A security audit on {{github}} detected a plain-text database password inside a unprivileged volume.",
  "Obtained {{certification}} which apparently teaches how to exposed public port with host path exposed.",
  "Listed {{skill}} as a primary competency, but the evidence points to a unprivileged entrypoint.",
  "Obtained {{certification}} which apparently teaches how to exposed public port exiting with status 137.",
  "Obtained {{certification}} which apparently teaches how to built image exiting with status 137.",
  "{{achievement}} was highlighted, but the git logs show they only managed to exposed public port due to segment fault.",
  "{{achievement}} was highlighted, but the git logs show they only managed to started daemon on missing memory.",
  "{{github}} contains more heavy dockerfiles than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to mounted read-only path with host path exposed.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to started daemon on missing memory.",
  "{{github}} contains more crashed dockerfiles than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a heavy overlay.",
  "{{github}} contains more unprivileged images than original code.",
  "{{github}} contains more bloated envs than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to mounted read-only path without valid shell.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to exposed public port without valid shell.",
  "For {{experience}}, the primary contribution was writing a missing config for a cache.",
  "{{achievement}} was highlighted, but the git logs show they only managed to pulled raw layer due to segment fault.",
  "{{github}} contains more missing envs than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to pulled raw layer with host path exposed.",
  "Failed to configure {{project}} because {{candidateName}} decided to started daemon without valid shell.",
  "{{github}} contains more crashed images than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to pulled raw layer without valid shell.",
  "Failed to configure {{project}} because {{candidateName}} decided to pulled raw layer exiting with status 137.",
  "{{github}} contains more crashed ports than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a crashed dockerfile.",
  "{{github}} contains more bloated overlays than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to exposed public port on missing memory.",
  "{{github}} contains more missing entrypoints than original code.",
  "{{education}} is listed, but they still managed to deploy a read-only daemon to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to started daemon without valid shell.",
  "{{github}} contains more untagged ports than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to built image on missing memory.",
  "{{github}} contains more bloated ports than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to pulled raw layer on missing memory.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to built image without valid shell.",
  "Failed to configure {{project}} because {{candidateName}} decided to mounted read-only path on missing memory.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to mounted read-only path exiting with status 137.",
  "{{github}} contains more heavy overlays than original code.",
  "Obtained {{certification}} which apparently teaches how to pulled raw layer exiting with status 137.",
  "Failed to configure {{project}} because {{candidateName}} decided to started daemon due to segment fault.",
  "{{github}} contains more missing containers than original code.",
  "Obtained {{certification}} which apparently teaches how to pulled raw layer due to segment fault.",
  "{{github}} contains more bloated entrypoints than original code.",
  "{{github}} contains more raw entrypoints than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to exposed public port without valid shell.",
  "Listed {{skill}} as a primary competency, but the evidence points to a missing overlay.",
  "Failed to configure {{project}} because {{candidateName}} decided to mounted read-only path exiting with status 137.",
  "{{achievement}} was highlighted, but the git logs show they only managed to mounted read-only path due to segment fault.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to started daemon due to segment fault.",
  "Failed to configure {{project}} because {{candidateName}} decided to built image without valid shell.",
  "{{github}} contains more untagged containers than original code.",
  "{{github}} contains more bloated dockerfiles than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to exposed public port without valid shell.",
  "{{github}} contains more heavy envs than original code.",
  "{{github}} contains more crashed volumes than original code.",
  "{{github}} contains more bloated containers than original code.",
  "Listed {{skill}} as a primary competency, but the evidence points to a untagged port.",
  "{{achievement}} was highlighted, but the git logs show they only managed to mounted read-only path exiting with status 137.",
  "{{github}} contains more crashed containers than original code.",
  "{{github}} contains more heavy entrypoints than original code.",
  "{{github}} contains more missing daemons than original code.",
  "{{education}} is listed, but they still managed to deploy a crashed cache to production.",
  "Failed to configure {{project}} because {{candidateName}} decided to pulled raw layer on missing memory.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to pulled raw layer exiting with status 137."
];

export const punchlines = [
  "Legend says this unprivileged port is still running on localhost.",
  "The only thing memory-safe about this setup is that nobody has ever tried to run it.",
  "The compiler requested emotional support after reading the crashed code.",
  "The documentation was so empty, I had to use it as a virtual sketchbook.",
  "Legend says this missing volume is still running on localhost.",
  "A junior developer looked at the cache and immediately went to touch grass.",
  "Even Stack Overflow has marked this cache as off-topic.",
  "It did not optimize our process, but it did make the laptop fan spin like a jet engine.",
  "Legend says this bloated daemon is still running on localhost.",
  "We would deploy it to production, but our SRE team deserves to sleep at night.",
  "Legend says this heavy overlay is still running on localhost.",
  "Legend says this raw image is still running on localhost.",
  "Legend says this untagged cache is still running on localhost.",
  "Legend says this heavy volume is still running on localhost.",
  "Legend says this unprivileged entrypoint is still running on localhost.",
  "The compiler requested emotional support after reading the read-only code.",
  "Legend says this heavy container is still running on localhost.",
  "Legend says this crashed daemon is still running on localhost.",
  "Legend says this bloated dockerfile is still running on localhost.",
  "Legend says this bloated port is still running on localhost.",
  "Legend says this heavy entrypoint is still running on localhost.",
  "Legend says this heavy dockerfile is still running on localhost.",
  "Legend says this missing image is still running on localhost.",
  "Legend says this unprivileged volume is still running on localhost.",
  "Legend says this missing dockerfile is still running on localhost.",
  "Legend says this missing overlay is still running on localhost.",
  "Legend says this raw port is still running on localhost.",
  "Legend says this untagged volume is still running on localhost.",
  "Legend says this crashed image is still running on localhost.",
  "Legend says this missing env is still running on localhost.",
  "Legend says this read-only env is still running on localhost.",
  "Legend says this missing port is still running on localhost.",
  "Legend says this raw dockerfile is still running on localhost.",
  "Legend says this untagged image is still running on localhost.",
  "Legend says this untagged port is still running on localhost.",
  "Legend says this untagged env is still running on localhost.",
  "Legend says this crashed env is still running on localhost.",
  "Legend says this bloated image is still running on localhost.",
  "Legend says this heavy daemon is still running on localhost.",
  "Legend says this untagged container is still running on localhost.",
  "Legend says this crashed cache is still running on localhost.",
  "Legend says this unprivileged env is still running on localhost.",
  "Legend says this bloated env is still running on localhost.",
  "Legend says this bloated cache is still running on localhost.",
  "Legend says this heavy image is still running on localhost.",
  "Legend says this missing cache is still running on localhost.",
  "Legend says this raw container is still running on localhost.",
  "Legend says this crashed container is still running on localhost.",
  "Legend says this bloated container is still running on localhost.",
  "Legend says this heavy env is still running on localhost.",
  "Legend says this missing container is still running on localhost.",
  "Legend says this crashed volume is still running on localhost.",
  "Legend says this unprivileged cache is still running on localhost.",
  "Legend says this raw daemon is still running on localhost.",
  "Legend says this heavy cache is still running on localhost.",
  "Legend says this crashed port is still running on localhost.",
  "Legend says this unprivileged container is still running on localhost.",
  "Legend says this unprivileged daemon is still running on localhost.",
  "Legend says this unprivileged overlay is still running on localhost.",
  "Legend says this raw cache is still running on localhost.",
  "Legend says this untagged daemon is still running on localhost.",
  "Legend says this untagged dockerfile is still running on localhost.",
  "Legend says this raw volume is still running on localhost.",
  "Legend says this missing entrypoint is still running on localhost.",
  "This is a classic example of a heavy volume disaster.",
  "This is a classic example of a read-only dockerfile disaster.",
  "This is a classic example of a unprivileged volume disaster.",
  "This is a classic example of a crashed volume disaster.",
  "This is a classic example of a untagged volume disaster.",
  "This is a classic example of a missing overlay disaster.",
  "This is a classic example of a heavy dockerfile disaster.",
  "This is a classic example of a crashed cache disaster.",
  "This is a classic example of a unprivileged entrypoint disaster.",
  "This is a classic example of a untagged entrypoint disaster.",
  "This is a classic example of a missing volume disaster.",
  "This is a classic example of a read-only container disaster.",
  "This is a classic example of a crashed entrypoint disaster.",
  "This is a classic example of a heavy image disaster.",
  "This is a classic example of a bloated dockerfile disaster.",
  "This is a classic example of a crashed container disaster.",
  "This is a classic example of a unprivileged image disaster.",
  "This is a classic example of a unprivileged port disaster.",
  "This is a classic example of a bloated overlay disaster.",
  "This is a classic example of a bloated env disaster.",
  "This is a classic example of a unprivileged cache disaster.",
  "This is a classic example of a missing entrypoint disaster.",
  "This is a classic example of a read-only port disaster.",
  "This is a classic example of a unprivileged container disaster.",
  "This is a classic example of a untagged daemon disaster.",
  "This is a classic example of a raw cache disaster.",
  "This is a classic example of a heavy container disaster.",
  "This is a classic example of a untagged dockerfile disaster.",
  "This is a classic example of a bloated daemon disaster.",
  "This is a classic example of a missing daemon disaster.",
  "This is a classic example of a missing cache disaster.",
  "This is a classic example of a bloated entrypoint disaster.",
  "This is a classic example of a unprivileged overlay disaster.",
  "This is a classic example of a bloated cache disaster.",
  "This is a classic example of a crashed overlay disaster.",
  "This is a classic example of a read-only entrypoint disaster.",
  "This is a classic example of a raw daemon disaster.",
  "This is a classic example of a crashed image disaster.",
  "This is a classic example of a unprivileged env disaster.",
  "This is a classic example of a crashed daemon disaster."
];

export const verdicts = [
  "Needs more commits and fewer explanations.",
  "Rejected on first principles of dockerfile organization.",
  "Closed as bloated duplicate.",
  "Verdict: Cache is completely unmergeable.",
  "Request changes on the unprivileged daemon.",
  "Return after touching actual production servers.",
  "Rejected on first principles of overlay organization.",
  "Ship blocked by untagged check failures.",
  "Ship blocked by bloated check failures.",
  "PR started daemon due to bloated implementation.",
  "Verdict: Entrypoint is completely unmergeable.",
  "Rejected on first principles of volume organization.",
  "Verdict: Env is completely unmergeable.",
  "Verdict: Overlay is completely unmergeable.",
  "Rejected on first principles of image organization.",
  "PR built image due to unprivileged implementation.",
  "Closed as raw duplicate.",
  "Ship blocked by read-only check failures.",
  "Rejected on first principles of cache organization.",
  "Verdict: Dockerfile is completely unmergeable.",
  "Ship blocked by raw check failures.",
  "Ship blocked by unprivileged check failures.",
  "PR mounted read-only path due to bloated implementation.",
  "Verdict: Image is completely unmergeable.",
  "Verdict: Daemon is completely unmergeable.",
  "PR built image due to missing implementation.",
  "PR started daemon due to unprivileged implementation.",
  "Request changes on the untagged entrypoint.",
  "Verdict: Container is completely unmergeable.",
  "Closed as unprivileged duplicate.",
  "Rejected on first principles of env organization.",
  "Request changes on the heavy dockerfile.",
  "Rejected on first principles of container organization.",
  "Request changes on the bloated volume.",
  "Ship blocked by missing check failures.",
  "Closed as read-only duplicate.",
  "Request changes on the missing image.",
  "Closed as untagged duplicate.",
  "PR mounted read-only path due to raw implementation.",
  "Request changes on the read-only cache.",
  "PR exposed public port due to heavy implementation.",
  "PR started daemon due to read-only implementation.",
  "Ship blocked by heavy check failures.",
  "Request changes on the unprivileged env.",
  "Closed as heavy duplicate.",
  "Request changes on the raw daemon.",
  "Rejected on first principles of port organization.",
  "Request changes on the unprivileged container.",
  "Closed as crashed duplicate.",
  "Verdict: Port is completely unmergeable.",
  "PR mounted read-only path due to unprivileged implementation.",
  "Rejected on first principles of daemon organization.",
  "PR pulled raw layer due to unprivileged implementation.",
  "PR built image due to heavy implementation.",
  "Ship blocked by crashed check failures.",
  "Rejected on first principles of entrypoint organization.",
  "Verdict: Volume is completely unmergeable.",
  "PR built image due to crashed implementation.",
  "PR exposed public port due to crashed implementation.",
  "PR exposed public port due to raw implementation.",
  "Request changes on the read-only container.",
  "Request changes on the untagged container.",
  "PR mounted read-only path due to heavy implementation.",
  "Request changes on the bloated image.",
  "PR pulled raw layer due to bloated implementation.",
  "PR pulled raw layer due to missing implementation.",
  "PR built image due to bloated implementation.",
  "Request changes on the unprivileged cache.",
  "Request changes on the heavy entrypoint.",
  "Request changes on the heavy daemon.",
  "Request changes on the read-only dockerfile.",
  "Request changes on the bloated env.",
  "Request changes on the crashed cache.",
  "Request changes on the unprivileged port.",
  "Request changes on the crashed volume.",
  "Request changes on the bloated daemon.",
  "Request changes on the raw env.",
  "Request changes on the raw entrypoint.",
  "Request changes on the heavy image.",
  "Closed as missing duplicate.",
  "PR pulled raw layer due to untagged implementation.",
  "PR started daemon due to crashed implementation.",
  "PR built image due to raw implementation.",
  "PR pulled raw layer due to heavy implementation.",
  "Request changes on the heavy cache.",
  "Request changes on the bloated container.",
  "PR mounted read-only path due to untagged implementation.",
  "Request changes on the raw overlay.",
  "PR started daemon due to missing implementation.",
  "Request changes on the raw dockerfile.",
  "Request changes on the missing overlay.",
  "Request changes on the untagged dockerfile.",
  "PR pulled raw layer due to crashed implementation.",
  "PR exposed public port due to missing implementation.",
  "Request changes on the heavy env.",
  "Request changes on the heavy volume.",
  "Request changes on the heavy container.",
  "Request changes on the raw cache.",
  "PR exposed public port due to untagged implementation.",
  "PR mounted read-only path due to missing implementation."
];

export const easterEggs = [
  "Elon Musk Tweet: 'Just deleted the entire overlay pipeline, was completely useless.'",
  "Matrix Glitch: You copy-pasted a template and now the server believes it is a real founder.",
  "FBI Investigation: Suspect was found deploying unencrypted read-only caches.",
  "Steam Achievement Unlocked: Successfully crashed a hello-world app on a $10,000 server.",
  "FBI Investigation: Suspect was found deploying unencrypted bloated volumes.",
  "FBI Investigation: Suspect was found deploying unencrypted unprivileged entrypoints.",
  "NASA Alert: Space mission aborted due to a minor env parsing error.",
  "FBI Investigation: Suspect was found deploying unencrypted crashed containers.",
  "Gordon Ramsay Meltdown: 'This container is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted untagged dockerfiles.",
  "Dark Web Resume Auction: Current bid is $0.00, and the buyer is requesting a refund.",
  "Gordon Ramsay Meltdown: 'This volume is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This overlay is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This env is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted heavy envs.",
  "Gordon Ramsay Meltdown: 'This cache is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This daemon is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This image is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted missing ports."
];
