// ES Module exports for doctor_diagnosis roast format
export const titles = [
  "The Burnout tragedy",
  "Caffeine Not Found",
  "Incident Report: Tired Heart rate",
  "Sleep conflict detected",
  "Incident Report: Exhausted Sleep",
  "Critical Burnout failure",
  "Condition conflict detected",
  "Absolute Terminal architecture",
  "Acute Heart rate Loop",
  "Critical Heart rate failure",
  "Symptom Not Found",
  "NullPointerHeart rateException",
  "Absolute Acute architecture",
  "The Patient tragedy",
  "Deprived Symptom Error",
  "NullPointerSyndromeException",
  "The Syndrome tragedy",
  "Absolute Hyperactive architecture",
  "Absolute Deprived architecture",
  "Exhausted Heart rate Loop",
  "The Symptom tragedy",
  "Absolute Chronic architecture",
  "Critical Sleep failure",
  "Prescription conflict detected",
  "Incident Report: Terminal Heart rate",
  "Failed to compile: Burnout",
  "High-stress Prescription Loop",
  "Failed to compile: Caffeine",
  "Incident Report: Hyperactive Patient",
  "Chronic Patient Error",
  "Deprived Prescription Error",
  "Deprived Heart rate Error",
  "Failed to compile: Heart rate",
  "Acute Symptom Loop",
  "Incident Report: High-stress Caffeine",
  "Acute Caffeine Loop",
  "NullPointerSymptomException",
  "NullPointerSleepException",
  "Prescription Not Found",
  "Incident Report: Deprived Burnout",
  "High-stress Caffeine Error",
  "The Condition tragedy",
  "Failed to compile: Patient",
  "Terminal Condition Loop",
  "Failed to compile: Symptom",
  "Acute Heart rate Error",
  "High-stress Sleep Error",
  "Critical Patient failure",
  "Absolute High-stress architecture",
  "Sleep Not Found",
  "Exhausted Condition Error",
  "Critical Symptom failure",
  "Tired Burnout Error",
  "Hyperactive Treatment Error",
  "Incident Report: Acute Burnout",
  "Failed to compile: Treatment",
  "Syndrome conflict detected",
  "Chronic Caffeine Error",
  "Incident Report: Terminal Condition",
  "Critical Caffeine failure",
  "Absolute Exhausted architecture",
  "Hyperactive Heart rate Error",
  "Terminal Patient Error",
  "Patient Not Found",
  "Incident Report: High-stress Condition",
  "Absolute Tired architecture",
  "NullPointerPatientException",
  "Patient conflict detected",
  "Acute Treatment Loop",
  "High-stress Syndrome Loop",
  "Burnout conflict detected",
  "Hyperactive Symptom Loop",
  "Incident Report: High-stress Prescription",
  "Critical Syndrome failure",
  "Condition Not Found",
  "Tired Condition Error",
  "Burnout Not Found",
  "NullPointerTreatmentException",
  "Exhausted Prescription Loop",
  "High-stress Condition Loop",
  "Critical Prescription failure",
  "Acute Patient Loop",
  "Failed to compile: Condition",
  "Terminal Heart rate Loop",
  "High-stress Heart rate Loop",
  "Incident Report: Hyperactive Treatment",
  "Syndrome Not Found",
  "Failed to compile: Syndrome",
  "Terminal Syndrome Loop",
  "Hyperactive Prescription Loop",
  "Treatment conflict detected",
  "NullPointerBurnoutException",
  "The Sleep tragedy",
  "Chronic Caffeine Loop",
  "Incident Report: Exhausted Condition",
  "Incident Report: High-stress Patient",
  "Heart rate conflict detected",
  "Incident Report: Acute Symptom",
  "High-stress Patient Loop",
  "Exhausted Burnout Loop"
];

export const openings = [
  "A review was filed regarding a high-stress symptom.",
  "The team has initiated audit for the candidate's caffeine setup.",
  "Alert: The candidate spent three months trying to diagnosed acute syndrome due to caffeine overdose.",
  "The team has initiated audit for the candidate's heart rate setup.",
  "Warning: System flagged an attempt to admitted tired developer after 48-hour coding run.",
  "A review was filed regarding a hyperactive syndrome.",
  "Recruiters reported a case of deprived patient design.",
  "Initial evaluation shows the developer decided to diagnosed acute syndrome requiring grass contact.",
  "Warning: System flagged an attempt to treated compiler anxiety from compiler alert panic.",
  "Recruiters reported a case of exhausted syndrome design.",
  "A review was filed regarding a tired prescription.",
  "We checked the history and found a hyperactive syndrome log.",
  "Scanning candidate profile for acute sleeps...",
  "Scanning candidate profile for exhausted sleeps...",
  "Scanning candidate profile for exhausted conditions...",
  "Alert: The candidate spent three months trying to diagnosed acute syndrome with sleep prescription.",
  "A review was filed regarding a high-stress prescription.",
  "Initial evaluation shows the developer decided to diagnosed acute syndrome from compiler alert panic.",
  "Initial evaluation shows the developer decided to treated compiler anxiety from compiler alert panic.",
  "Alert: The candidate spent three months trying to treated compiler anxiety requiring grass contact.",
  "Recruiters reported a case of acute caffeine design.",
  "Initial evaluation shows the developer decided to admitted tired developer from compiler alert panic.",
  "Warning: System flagged an attempt to monitored system heart rate due to caffeine overdose.",
  "We checked the history and found a chronic sleep log.",
  "Alert: The candidate spent three months trying to prescribed caffeine limit requiring grass contact.",
  "A review was filed regarding a tired treatment.",
  "Initial evaluation shows the developer decided to diagnosed acute syndrome after 48-hour coding run.",
  "Initial evaluation shows the developer decided to prescribed caffeine limit after 48-hour coding run.",
  "Initial evaluation shows the developer decided to prescribed caffeine limit requiring grass contact.",
  "We checked the history and found a terminal syndrome log.",
  "Recruiters reported a case of chronic condition design.",
  "Alert: The candidate spent three months trying to admitted tired developer due to caffeine overdose.",
  "Scanning candidate profile for terminal caffeines...",
  "A review was filed regarding a deprived burnout.",
  "A review was filed regarding a deprived caffeine.",
  "Warning: System flagged an attempt to prescribed caffeine limit due to caffeine overdose.",
  "Warning: System flagged an attempt to admitted tired developer with sleep prescription.",
  "Recruiters reported a case of acute sleep design.",
  "Initial evaluation shows the developer decided to admitted tired developer with sleep prescription.",
  "Scanning candidate profile for deprived syndromes...",
  "We checked the history and found a tired sleep log.",
  "Scanning candidate profile for chronic treatments...",
  "A review was filed regarding a hyperactive burnout.",
  "A review was filed regarding a high-stress caffeine.",
  "We checked the history and found a hyperactive burnout log.",
  "A review was filed regarding a terminal patient.",
  "Recruiters reported a case of deprived treatment design.",
  "Warning: System flagged an attempt to diagnosed acute syndrome after 48-hour coding run.",
  "Alert: The candidate spent three months trying to diagnosed acute syndrome after 48-hour coding run.",
  "Recruiters reported a case of exhausted heart rate design.",
  "Recruiters reported a case of tired condition design.",
  "We checked the history and found a acute heart rate log.",
  "We checked the history and found a hyperactive prescription log.",
  "Warning: System flagged an attempt to prescribed caffeine limit after 48-hour coding run.",
  "A review was filed regarding a hyperactive symptom.",
  "Recruiters reported a case of high-stress burnout design.",
  "We checked the history and found a deprived prescription log.",
  "Alert: The candidate spent three months trying to admitted tired developer from compiler alert panic.",
  "Initial evaluation shows the developer decided to admitted tired developer requiring grass contact.",
  "Recruiters reported a case of terminal caffeine design.",
  "A review was filed regarding a hyperactive heart rate.",
  "Recruiters reported a case of exhausted caffeine design.",
  "Scanning candidate profile for chronic heart rates...",
  "A review was filed regarding a exhausted heart rate.",
  "Initial evaluation shows the developer decided to diagnosed acute syndrome due to caffeine overdose.",
  "Warning: System flagged an attempt to admitted tired developer from compiler alert panic.",
  "Scanning candidate profile for terminal prescriptions...",
  "Scanning candidate profile for acute symptoms...",
  "Alert: The candidate spent three months trying to treated compiler anxiety from compiler alert panic.",
  "Warning: System flagged an attempt to treated compiler anxiety due to caffeine overdose.",
  "Warning: System flagged an attempt to monitored system heart rate with sleep prescription.",
  "Initial evaluation shows the developer decided to monitored system heart rate requiring grass contact.",
  "Warning: System flagged an attempt to admitted tired developer due to caffeine overdose.",
  "Warning: System flagged an attempt to treated compiler anxiety requiring grass contact.",
  "Alert: The candidate spent three months trying to prescribed caffeine limit with sleep prescription.",
  "Alert: The candidate spent three months trying to monitored system heart rate with sleep prescription.",
  "Initial evaluation shows the developer decided to treated compiler anxiety with sleep prescription.",
  "Initial evaluation shows the developer decided to monitored system heart rate after 48-hour coding run.",
  "Recruiters reported a case of exhausted burnout design.",
  "A review was filed regarding a chronic treatment.",
  "Scanning candidate profile for terminal patients...",
  "Alert: The candidate spent three months trying to monitored system heart rate from compiler alert panic.",
  "Warning: System flagged an attempt to treated compiler anxiety with sleep prescription.",
  "A review was filed regarding a hyperactive patient.",
  "Initial evaluation shows the developer decided to prescribed caffeine limit from compiler alert panic.",
  "We checked the history and found a deprived treatment log.",
  "A review was filed regarding a terminal prescription.",
  "Scanning candidate profile for deprived caffeines...",
  "Recruiters reported a case of terminal sleep design.",
  "We checked the history and found a high-stress burnout log.",
  "Alert: The candidate spent three months trying to prescribed caffeine limit due to caffeine overdose.",
  "Warning: System flagged an attempt to treated compiler anxiety after 48-hour coding run."
];

export const findings = [
  "The candidate claims {{framework}} experience, but their repository is just a deprived clone that has been abandoned.",
  "Obtained {{certification}} which apparently teaches how to prescribed caffeine limit due to caffeine overdose.",
  "{{candidateName}} has spent three weeks optimizing a condition while completely ignoring {{missingSection}}.",
  "{{github}} contains more terminal caffeines than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to prescribed caffeine limit due to caffeine overdose.",
  "{{achievement}} was highlighted, but the git logs show they only managed to treated compiler anxiety with sleep prescription.",
  "{{achievement}} was highlighted, but the git logs show they only managed to diagnosed acute syndrome with sleep prescription.",
  "{{achievement}} was highlighted, but the git logs show they only managed to admitted tired developer due to caffeine overdose.",
  "{{education}} is listed, but they still managed to deploy a high-stress prescription to production.",
  "Obtained {{certification}} which apparently teaches how to prescribed caffeine limit from compiler alert panic.",
  "Obtained {{certification}} which apparently teaches how to admitted tired developer requiring grass contact.",
  "Listed {{skill}} as a primary competency, but the evidence points to a terminal caffeine.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to treated compiler anxiety from compiler alert panic.",
  "A security audit on {{github}} detected a plain-text database password inside a exhausted treatment.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to monitored system heart rate with sleep prescription.",
  "{{achievement}} was highlighted, but the git logs show they only managed to treated compiler anxiety after 48-hour coding run.",
  "Listed {{skill}} as a primary competency, but the evidence points to a high-stress treatment.",
  "Obtained {{certification}} which apparently teaches how to prescribed caffeine limit requiring grass contact.",
  "A security audit on {{github}} detected a plain-text database password inside a terminal burnout.",
  "A security audit on {{github}} detected a plain-text database password inside a chronic prescription.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to treated compiler anxiety after 48-hour coding run.",
  "{{achievement}} was highlighted, but the git logs show they only managed to prescribed caffeine limit with sleep prescription.",
  "{{education}} is listed, but they still managed to deploy a acute syndrome to production.",
  "Listed {{skill}} as a primary competency, but the evidence points to a deprived burnout.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to prescribed caffeine limit with sleep prescription.",
  "A security audit on {{github}} detected a plain-text database password inside a high-stress treatment.",
  "Listed {{skill}} as a primary competency, but the evidence points to a tired treatment.",
  "Failed to configure {{project}} because {{candidateName}} decided to treated compiler anxiety after 48-hour coding run.",
  "Obtained {{certification}} which apparently teaches how to monitored system heart rate requiring grass contact.",
  "{{github}} contains more high-stress symptoms than original code.",
  "Obtained {{certification}} which apparently teaches how to diagnosed acute syndrome due to caffeine overdose.",
  "A security audit on {{github}} detected a plain-text database password inside a acute caffeine.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to treated compiler anxiety due to caffeine overdose.",
  "For {{experience}}, the primary contribution was writing a acute config for a syndrome.",
  "{{achievement}} was highlighted, but the git logs show they only managed to monitored system heart rate due to caffeine overdose.",
  "{{achievement}} was highlighted, but the git logs show they only managed to admitted tired developer from compiler alert panic.",
  "Failed to configure {{project}} because {{candidateName}} decided to admitted tired developer requiring grass contact.",
  "Failed to configure {{project}} because {{candidateName}} decided to treated compiler anxiety requiring grass contact.",
  "{{github}} contains more chronic syndromes than original code.",
  "While debugging {{project}}, we found a hyperactive logic loop related to {{language}} features.",
  "{{github}} contains more acute symptoms than original code.",
  "{{education}} is listed, but they still managed to deploy a deprived burnout to production.",
  "For {{experience}}, the primary contribution was writing a chronic config for a condition.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to monitored system heart rate due to caffeine overdose.",
  "Obtained {{certification}} which apparently teaches how to monitored system heart rate after 48-hour coding run.",
  "Obtained {{certification}} which apparently teaches how to admitted tired developer from compiler alert panic.",
  "{{github}} contains more chronic patients than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to monitored system heart rate after 48-hour coding run.",
  "{{github}} contains more tired prescriptions than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to monitored system heart rate from compiler alert panic.",
  "{{education}} is listed, but they still managed to deploy a tired patient to production.",
  "{{github}} contains more hyperactive symptoms than original code.",
  "{{candidateName}} has spent three weeks optimizing a heart rate while completely ignoring {{missingSection}}.",
  "For {{experience}}, the primary contribution was writing a exhausted config for a prescription.",
  "Obtained {{certification}} which apparently teaches how to diagnosed acute syndrome after 48-hour coding run.",
  "Obtained {{certification}} which apparently teaches how to monitored system heart rate due to caffeine overdose.",
  "{{github}} contains more chronic symptoms than original code.",
  "Obtained {{certification}} which apparently teaches how to prescribed caffeine limit after 48-hour coding run.",
  "{{github}} contains more hyperactive patients than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to treated compiler anxiety due to caffeine overdose.",
  "{{github}} contains more exhausted sleeps than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to prescribed caffeine limit after 48-hour coding run.",
  "{{achievement}} was highlighted, but the git logs show they only managed to diagnosed acute syndrome after 48-hour coding run.",
  "Failed to configure {{project}} because {{candidateName}} decided to prescribed caffeine limit from compiler alert panic.",
  "{{education}} is listed, but they still managed to deploy a exhausted prescription to production.",
  "Failed to configure {{project}} because {{candidateName}} decided to prescribed caffeine limit requiring grass contact.",
  "A security audit on {{github}} detected a plain-text database password inside a deprived symptom.",
  "{{github}} contains more acute prescriptions than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to diagnosed acute syndrome from compiler alert panic.",
  "For {{experience}}, the primary contribution was writing a tired config for a heart rate.",
  "{{github}} contains more hyperactive heart rates than original code.",
  "While debugging {{project}}, we found a high-stress logic loop related to {{language}} features.",
  "Listed {{skill}} as a primary competency, but the evidence points to a hyperactive syndrome.",
  "Listed {{skill}} as a primary competency, but the evidence points to a tired heart rate.",
  "{{achievement}} was highlighted, but the git logs show they only managed to admitted tired developer requiring grass contact.",
  "Failed to configure {{project}} because {{candidateName}} decided to admitted tired developer due to caffeine overdose.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to treated compiler anxiety requiring grass contact.",
  "{{achievement}} was highlighted, but the git logs show they only managed to prescribed caffeine limit due to caffeine overdose.",
  "Obtained {{certification}} which apparently teaches how to diagnosed acute syndrome requiring grass contact.",
  "Failed to configure {{project}} because {{candidateName}} decided to treated compiler anxiety from compiler alert panic.",
  "Obtained {{certification}} which apparently teaches how to admitted tired developer with sleep prescription.",
  "Failed to configure {{project}} because {{candidateName}} decided to diagnosed acute syndrome due to caffeine overdose.",
  "For {{experience}}, the primary contribution was writing a tired config for a symptom.",
  "{{github}} contains more terminal conditions than original code.",
  "{{education}} is listed, but they still managed to deploy a exhausted heart rate to production.",
  "Obtained {{certification}} which apparently teaches how to treated compiler anxiety from compiler alert panic.",
  "Failed to configure {{project}} because {{candidateName}} decided to monitored system heart rate requiring grass contact.",
  "{{github}} contains more exhausted caffeines than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to prescribed caffeine limit after 48-hour coding run.",
  "A security audit on {{github}} detected a plain-text database password inside a chronic heart rate.",
  "{{achievement}} was highlighted, but the git logs show they only managed to monitored system heart rate with sleep prescription.",
  "{{achievement}} was highlighted, but the git logs show they only managed to monitored system heart rate from compiler alert panic.",
  "{{education}} is listed, but they still managed to deploy a chronic condition to production.",
  "Obtained {{certification}} which apparently teaches how to diagnosed acute syndrome with sleep prescription.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to admitted tired developer with sleep prescription.",
  "{{achievement}} was highlighted, but the git logs show they only managed to treated compiler anxiety from compiler alert panic.",
  "Listed {{skill}} as a primary competency, but the evidence points to a chronic symptom.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to prescribed caffeine limit from compiler alert panic.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to monitored system heart rate after 48-hour coding run.",
  "Obtained {{certification}} which apparently teaches how to treated compiler anxiety requiring grass contact.",
  "Obtained {{certification}} which apparently teaches how to admitted tired developer after 48-hour coding run.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to treated compiler anxiety with sleep prescription.",
  "For {{experience}}, the primary contribution was writing a deprived config for a treatment.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to prescribed caffeine limit due to caffeine overdose.",
  "For {{experience}}, the primary contribution was writing a high-stress config for a patient.",
  "For {{experience}}, the primary contribution was writing a terminal config for a burnout.",
  "{{achievement}} was highlighted, but the git logs show they only managed to treated compiler anxiety requiring grass contact.",
  "{{achievement}} was highlighted, but the git logs show they only managed to diagnosed acute syndrome due to caffeine overdose.",
  "Failed to configure {{project}} because {{candidateName}} decided to diagnosed acute syndrome requiring grass contact.",
  "A security audit on {{github}} detected a plain-text database password inside a tired syndrome.",
  "{{github}} contains more terminal treatments than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to diagnosed acute syndrome from compiler alert panic.",
  "{{github}} contains more chronic caffeines than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to admitted tired developer requiring grass contact.",
  "{{github}} contains more deprived caffeines than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to admitted tired developer from compiler alert panic.",
  "Obtained {{certification}} which apparently teaches how to admitted tired developer due to caffeine overdose.",
  "{{github}} contains more tired treatments than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to diagnosed acute syndrome requiring grass contact.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to admitted tired developer due to caffeine overdose."
];

export const punchlines = [
  "The compiler requested emotional support after reading the chronic code.",
  "A junior developer looked at the syndrome and immediately went to touch grass.",
  "We would deploy it to production, but our SRE team deserves to sleep at night.",
  "Even Stack Overflow has marked this symptom as off-topic.",
  "Legend says this terminal heart rate is still running on localhost.",
  "The only thing memory-safe about this setup is that nobody has ever tried to run it.",
  "The documentation was so empty, I had to use it as a virtual sketchbook.",
  "Legend says this chronic condition is still running on localhost.",
  "Legend says this high-stress symptom is still running on localhost.",
  "A junior developer looked at the heart rate and immediately went to touch grass.",
  "Legend says this exhausted burnout is still running on localhost.",
  "It did not optimize our process, but it did make the laptop fan spin like a jet engine.",
  "Legend says this tired caffeine is still running on localhost.",
  "The compiler requested emotional support after reading the high-stress code.",
  "Legend says this deprived syndrome is still running on localhost.",
  "Legend says this acute symptom is still running on localhost.",
  "Legend says this tired syndrome is still running on localhost.",
  "Legend says this chronic symptom is still running on localhost.",
  "Legend says this deprived condition is still running on localhost.",
  "Legend says this hyperactive sleep is still running on localhost.",
  "Legend says this tired symptom is still running on localhost.",
  "Even Stack Overflow has marked this heart rate as off-topic.",
  "Legend says this hyperactive syndrome is still running on localhost.",
  "Legend says this exhausted prescription is still running on localhost.",
  "Legend says this tired burnout is still running on localhost.",
  "Legend says this acute caffeine is still running on localhost.",
  "Legend says this tired patient is still running on localhost.",
  "Legend says this terminal condition is still running on localhost.",
  "Legend says this acute syndrome is still running on localhost.",
  "Legend says this high-stress heart rate is still running on localhost.",
  "Legend says this hyperactive condition is still running on localhost.",
  "Legend says this chronic prescription is still running on localhost.",
  "Legend says this hyperactive caffeine is still running on localhost.",
  "Legend says this deprived sleep is still running on localhost.",
  "Legend says this acute burnout is still running on localhost.",
  "Legend says this exhausted treatment is still running on localhost.",
  "Legend says this acute condition is still running on localhost.",
  "Legend says this hyperactive patient is still running on localhost.",
  "Legend says this terminal sleep is still running on localhost.",
  "Legend says this hyperactive treatment is still running on localhost.",
  "Legend says this chronic patient is still running on localhost.",
  "Legend says this deprived burnout is still running on localhost.",
  "Legend says this tired treatment is still running on localhost.",
  "Legend says this chronic syndrome is still running on localhost.",
  "Legend says this terminal symptom is still running on localhost.",
  "Legend says this acute treatment is still running on localhost.",
  "Legend says this terminal prescription is still running on localhost.",
  "Legend says this terminal syndrome is still running on localhost.",
  "Legend says this deprived symptom is still running on localhost.",
  "Legend says this terminal treatment is still running on localhost.",
  "Legend says this hyperactive burnout is still running on localhost.",
  "Legend says this deprived caffeine is still running on localhost.",
  "Legend says this terminal caffeine is still running on localhost.",
  "Legend says this chronic burnout is still running on localhost.",
  "Legend says this acute sleep is still running on localhost.",
  "Legend says this chronic caffeine is still running on localhost.",
  "Legend says this chronic sleep is still running on localhost.",
  "Legend says this exhausted symptom is still running on localhost.",
  "Legend says this hyperactive prescription is still running on localhost.",
  "Legend says this chronic treatment is still running on localhost.",
  "Legend says this exhausted condition is still running on localhost.",
  "Legend says this terminal patient is still running on localhost.",
  "This is a classic example of a chronic prescription disaster.",
  "This is a classic example of a terminal symptom disaster.",
  "This is a classic example of a terminal treatment disaster.",
  "This is a classic example of a acute prescription disaster.",
  "This is a classic example of a exhausted prescription disaster.",
  "This is a classic example of a hyperactive heart rate disaster.",
  "This is a classic example of a terminal burnout disaster.",
  "This is a classic example of a hyperactive prescription disaster.",
  "This is a classic example of a hyperactive syndrome disaster.",
  "This is a classic example of a tired burnout disaster.",
  "This is a classic example of a deprived burnout disaster.",
  "This is a classic example of a tired symptom disaster.",
  "This is a classic example of a exhausted sleep disaster.",
  "This is a classic example of a high-stress symptom disaster.",
  "This is a classic example of a hyperactive patient disaster.",
  "This is a classic example of a chronic symptom disaster.",
  "This is a classic example of a chronic caffeine disaster.",
  "This is a classic example of a deprived sleep disaster.",
  "This is a classic example of a exhausted condition disaster.",
  "This is a classic example of a chronic patient disaster.",
  "This is a classic example of a exhausted symptom disaster.",
  "This is a classic example of a acute burnout disaster.",
  "This is a classic example of a chronic syndrome disaster.",
  "This is a classic example of a high-stress caffeine disaster.",
  "This is a classic example of a hyperactive condition disaster.",
  "This is a classic example of a tired patient disaster.",
  "This is a classic example of a acute syndrome disaster.",
  "This is a classic example of a exhausted treatment disaster.",
  "This is a classic example of a hyperactive symptom disaster.",
  "This is a classic example of a deprived caffeine disaster.",
  "This is a classic example of a chronic sleep disaster.",
  "This is a classic example of a acute condition disaster.",
  "This is a classic example of a deprived heart rate disaster.",
  "This is a classic example of a tired syndrome disaster.",
  "This is a classic example of a high-stress treatment disaster.",
  "This is a classic example of a exhausted syndrome disaster.",
  "This is a classic example of a terminal patient disaster.",
  "This is a classic example of a terminal sleep disaster.",
  "This is a classic example of a deprived treatment disaster."
];

export const verdicts = [
  "PR diagnosed acute syndrome due to chronic implementation.",
  "Return after touching actual production servers.",
  "Request changes on the high-stress heart rate.",
  "Closed as acute duplicate.",
  "Ship blocked by chronic check failures.",
  "Ship blocked by hyperactive check failures.",
  "Verdict: Patient is completely unmergeable.",
  "Ship blocked by tired check failures.",
  "Verdict: Sleep is completely unmergeable.",
  "Ship blocked by exhausted check failures.",
  "Verdict: Condition is completely unmergeable.",
  "Rejected on first principles of condition organization.",
  "Request changes on the terminal burnout.",
  "Ship blocked by high-stress check failures.",
  "PR admitted tired developer due to chronic implementation.",
  "Request changes on the tired syndrome.",
  "Request changes on the deprived condition.",
  "Rejected on first principles of caffeine organization.",
  "Rejected on first principles of burnout organization.",
  "Ship blocked by acute check failures.",
  "Request changes on the tired symptom.",
  "PR diagnosed acute syndrome due to hyperactive implementation.",
  "Needs more commits and fewer explanations.",
  "Rejected on first principles of treatment organization.",
  "Rejected on first principles of symptom organization.",
  "Ship blocked by terminal check failures.",
  "Closed as deprived duplicate.",
  "Closed as hyperactive duplicate.",
  "Verdict: Heart rate is completely unmergeable.",
  "PR monitored system heart rate due to exhausted implementation.",
  "PR diagnosed acute syndrome due to high-stress implementation.",
  "Closed as terminal duplicate.",
  "Rejected on first principles of prescription organization.",
  "Request changes on the deprived treatment.",
  "Verdict: Caffeine is completely unmergeable.",
  "Request changes on the chronic treatment.",
  "Closed as high-stress duplicate.",
  "PR monitored system heart rate due to terminal implementation.",
  "Verdict: Syndrome is completely unmergeable.",
  "Rejected on first principles of heart rate organization.",
  "PR prescribed caffeine limit due to chronic implementation.",
  "Request changes on the acute prescription.",
  "Request changes on the terminal patient.",
  "PR prescribed caffeine limit due to high-stress implementation.",
  "Closed as exhausted duplicate.",
  "Ship blocked by deprived check failures.",
  "PR monitored system heart rate due to high-stress implementation.",
  "Rejected on first principles of sleep organization.",
  "PR diagnosed acute syndrome due to deprived implementation.",
  "PR admitted tired developer due to deprived implementation.",
  "Closed as tired duplicate.",
  "Closed as chronic duplicate.",
  "Request changes on the exhausted treatment.",
  "Verdict: Prescription is completely unmergeable.",
  "Rejected on first principles of patient organization.",
  "Request changes on the deprived burnout.",
  "Request changes on the terminal symptom.",
  "Request changes on the acute sleep.",
  "Rejected on first principles of syndrome organization.",
  "PR treated compiler anxiety due to hyperactive implementation.",
  "Request changes on the acute patient.",
  "Verdict: Treatment is completely unmergeable.",
  "PR monitored system heart rate due to tired implementation.",
  "PR admitted tired developer due to acute implementation.",
  "PR monitored system heart rate due to deprived implementation.",
  "PR treated compiler anxiety due to high-stress implementation.",
  "PR treated compiler anxiety due to acute implementation.",
  "Verdict: Burnout is completely unmergeable.",
  "Request changes on the chronic prescription.",
  "Request changes on the exhausted syndrome.",
  "PR monitored system heart rate due to acute implementation.",
  "PR admitted tired developer due to hyperactive implementation.",
  "Request changes on the terminal heart rate.",
  "Request changes on the acute condition.",
  "Request changes on the exhausted prescription.",
  "PR prescribed caffeine limit due to acute implementation.",
  "PR treated compiler anxiety due to terminal implementation.",
  "Request changes on the exhausted condition.",
  "Request changes on the deprived syndrome.",
  "Request changes on the deprived caffeine.",
  "PR monitored system heart rate due to chronic implementation.",
  "Request changes on the deprived heart rate.",
  "Request changes on the hyperactive prescription.",
  "PR diagnosed acute syndrome due to terminal implementation.",
  "PR prescribed caffeine limit due to deprived implementation.",
  "Request changes on the terminal caffeine.",
  "Request changes on the chronic condition.",
  "PR monitored system heart rate due to hyperactive implementation.",
  "Verdict: Symptom is completely unmergeable.",
  "PR treated compiler anxiety due to deprived implementation.",
  "Request changes on the hyperactive burnout.",
  "Request changes on the chronic sleep.",
  "Request changes on the exhausted burnout.",
  "Request changes on the tired caffeine.",
  "PR diagnosed acute syndrome due to tired implementation.",
  "PR prescribed caffeine limit due to tired implementation.",
  "Request changes on the exhausted sleep.",
  "Request changes on the acute caffeine.",
  "PR admitted tired developer due to exhausted implementation."
];

export const easterEggs = [
  "NASA Alert: Space mission aborted due to a minor treatment parsing error.",
  "Steam Achievement Unlocked: Successfully crashed a hello-world app on a $10,000 server.",
  "Dark Web Resume Auction: Current bid is $0.00, and the buyer is requesting a refund.",
  "Matrix Glitch: You copy-pasted a template and now the server believes it is a real founder.",
  "FBI Investigation: Suspect was found deploying unencrypted deprived prescriptions.",
  "Gordon Ramsay Meltdown: 'This sleep is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This burnout is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted tired burnouts.",
  "Elon Musk Tweet: 'Just deleted the entire caffeine pipeline, was completely useless.'",
  "FBI Investigation: Suspect was found deploying unencrypted terminal sleeps.",
  "FBI Investigation: Suspect was found deploying unencrypted high-stress treatments.",
  "FBI Investigation: Suspect was found deploying unencrypted acute treatments.",
  "Gordon Ramsay Meltdown: 'This caffeine is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted high-stress heart rates.",
  "Gordon Ramsay Meltdown: 'This symptom is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This prescription is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted tired heart rates.",
  "Gordon Ramsay Meltdown: 'This syndrome is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This heart rate is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted hyperactive caffeines.",
  "Gordon Ramsay Meltdown: 'This condition is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted exhausted conditions.",
  "Gordon Ramsay Meltdown: 'This treatment is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This patient is raw! It's absolutely raw!'"
];
