// ES Module exports for gen_z_tiktok roast format
export const titles = [
  "Critical Brain rot failure",
  "The Profile tragedy",
  "Failed to compile: Rizz",
  "Rizz conflict detected",
  "Critical Assignment failure",
  "The Assignment tragedy",
  "Demure Aesthetic Loop",
  "Absolute Basic architecture",
  "Cap Assignment Loop",
  "Mindful Profile Loop",
  "Absolute Cap architecture",
  "The Vibe tragedy",
  "Basic Rizz Loop",
  "Trendy Assignment Error",
  "Basic Vibe Error",
  "NullPointerCaptionException",
  "Incident Report: Brainrot Tiktok",
  "Trendy Energy Error",
  "Brain rot Not Found",
  "Failed to compile: Assignment",
  "Cap conflict detected",
  "Incident Report: Mindful Rizz",
  "Incident Report: Trendy Aesthetic",
  "Mindful Vibe Loop",
  "Failed to compile: Vibe",
  "Incident Report: Cap Vibe",
  "NullPointerVibeException",
  "Critical Aesthetic failure",
  "Failed to compile: Profile",
  "NullPointerAestheticException",
  "Absolute Low-key architecture",
  "Assignment conflict detected",
  "Cap Rizz Error",
  "Incident Report: Demure Assignment",
  "Incident Report: Low-key Assignment",
  "Cap Vibe Loop",
  "Caption Not Found",
  "Vibe Not Found",
  "Incident Report: Mindful Energy",
  "Aesthetic Cap Error",
  "Absolute Mindful architecture",
  "Aesthetic Not Found",
  "Mindful Energy Loop",
  "Profile Not Found",
  "Incident Report: Demure Vibe",
  "Energy conflict detected",
  "The Cap tragedy",
  "Profile conflict detected",
  "Absolute Demure architecture",
  "Low-key Rizz Error",
  "Brain rot conflict detected",
  "Incident Report: Cap Cap",
  "Critical Rizz failure",
  "Aesthetic Brain rot Loop",
  "Incident Report: Cap Rizz",
  "Basic Vibe Loop",
  "Failed to compile: Aesthetic",
  "Trendy Profile Error",
  "Demure Vibe Loop",
  "Mindful Cap Error",
  "Incident Report: Low-key Profile",
  "The Aesthetic tragedy",
  "Basic Cap Error",
  "Rizz Not Found",
  "Energy Not Found",
  "The Brain rot tragedy",
  "Absolute Brainrot architecture",
  "Assignment Not Found",
  "Absolute Trendy architecture",
  "Caption conflict detected",
  "Vibe conflict detected",
  "NullPointerTiktokException",
  "Failed to compile: Tiktok",
  "Low-key Aesthetic Error",
  "The Energy tragedy",
  "Aesthetic Profile Loop",
  "Low-key Caption Loop",
  "Aesthetic Rizz Error",
  "NullPointerEnergyException",
  "Tiktok conflict detected",
  "Demure Brain rot Loop",
  "NullPointerAssignmentException",
  "Cap Profile Loop",
  "NullPointerProfileException",
  "Cap Not Found",
  "Basic Caption Error",
  "Trendy Tiktok Loop",
  "Failed to compile: Brain rot",
  "Incident Report: Trendy Energy",
  "Aesthetic Profile Error",
  "Cap Energy Loop",
  "NullPointerBrain rotException",
  "Brainrot Assignment Error",
  "Critical Caption failure",
  "Cap Caption Loop",
  "Cap Brain rot Error",
  "Incident Report: Brainrot Assignment",
  "Failed to compile: Caption",
  "Incident Report: Demure Brain rot",
  "Brainrot Assignment Loop"
];

export const openings = [
  "A review was filed regarding a low-key profile.",
  "Scanning candidate profile for aesthetic assignments...",
  "Initial evaluation shows the developer decided to scrolled brainrot feed very demure style.",
  "A review was filed regarding a cap profile.",
  "Warning: System flagged an attempt to screenshot simple profile for the algorithm.",
  "Warning: System flagged an attempt to screenshot simple profile on god.",
  "Scanning candidate profile for mindful energys...",
  "A review was filed regarding a brainrot profile.",
  "Alert: The candidate spent three months trying to screenshot simple profile no cap.",
  "A review was filed regarding a demure assignment.",
  "Warning: System flagged an attempt to failed the assignment no cap.",
  "The team has initiated audit for the candidate's vibe setup.",
  "Initial evaluation shows the developer decided to failed the assignment very demure style.",
  "Scanning candidate profile for mindful assignments...",
  "Initial evaluation shows the developer decided to screenshot simple profile very demure style.",
  "We checked the history and found a low-key caption log.",
  "Scanning candidate profile for trendy rizzs...",
  "Scanning candidate profile for aesthetic rizzs...",
  "Recruiters reported a case of low-key vibe design.",
  "We checked the history and found a mindful aesthetic log.",
  "Alert: The candidate spent three months trying to failed the assignment no cap.",
  "Alert: The candidate spent three months trying to failed the assignment very demure style.",
  "Initial evaluation shows the developer decided to screenshot simple profile for the algorithm.",
  "We checked the history and found a trendy profile log.",
  "Scanning candidate profile for mindful aesthetics...",
  "We checked the history and found a mindful profile log.",
  "We checked the history and found a trendy brain rot log.",
  "Scanning candidate profile for demure vibes...",
  "Alert: The candidate spent three months trying to rizzed up recruiter no cap.",
  "Warning: System flagged an attempt to posted cringe video for the algorithm.",
  "Initial evaluation shows the developer decided to posted cringe video no cap.",
  "Warning: System flagged an attempt to failed the assignment with zero rizz.",
  "Scanning candidate profile for brainrot rizzs...",
  "Alert: The candidate spent three months trying to scrolled brainrot feed with zero rizz.",
  "Recruiters reported a case of mindful vibe design.",
  "We checked the history and found a demure caption log.",
  "Warning: System flagged an attempt to rizzed up recruiter for the algorithm.",
  "Warning: System flagged an attempt to scrolled brainrot feed with zero rizz.",
  "Scanning candidate profile for cap tiktoks...",
  "We checked the history and found a brainrot energy log.",
  "We checked the history and found a aesthetic cap log.",
  "Recruiters reported a case of basic aesthetic design.",
  "Warning: System flagged an attempt to posted cringe video very demure style.",
  "Recruiters reported a case of brainrot caption design.",
  "The team has initiated audit for the candidate's brain rot setup.",
  "Recruiters reported a case of cap tiktok design.",
  "Initial evaluation shows the developer decided to failed the assignment with zero rizz.",
  "A review was filed regarding a basic tiktok.",
  "Warning: System flagged an attempt to posted cringe video with zero rizz.",
  "Alert: The candidate spent three months trying to screenshot simple profile with zero rizz.",
  "Warning: System flagged an attempt to scrolled brainrot feed on god.",
  "Warning: System flagged an attempt to posted cringe video no cap.",
  "A review was filed regarding a trendy vibe.",
  "A review was filed regarding a trendy aesthetic.",
  "Scanning candidate profile for aesthetic brain rots...",
  "Warning: System flagged an attempt to failed the assignment on god.",
  "Initial evaluation shows the developer decided to rizzed up recruiter on god.",
  "We checked the history and found a trendy caption log.",
  "Scanning candidate profile for demure tiktoks...",
  "Scanning candidate profile for mindful profiles...",
  "Recruiters reported a case of trendy tiktok design.",
  "Scanning candidate profile for aesthetic profiles...",
  "We checked the history and found a mindful tiktok log.",
  "We checked the history and found a basic rizz log.",
  "Alert: The candidate spent three months trying to failed the assignment for the algorithm.",
  "Alert: The candidate spent three months trying to rizzed up recruiter with zero rizz.",
  "Warning: System flagged an attempt to scrolled brainrot feed no cap.",
  "Recruiters reported a case of trendy cap design.",
  "Alert: The candidate spent three months trying to screenshot simple profile for the algorithm.",
  "Warning: System flagged an attempt to rizzed up recruiter very demure style.",
  "Warning: System flagged an attempt to screenshot simple profile with zero rizz.",
  "Warning: System flagged an attempt to posted cringe video on god.",
  "We checked the history and found a trendy assignment log.",
  "Initial evaluation shows the developer decided to posted cringe video for the algorithm.",
  "Scanning candidate profile for mindful brain rots...",
  "Scanning candidate profile for low-key caps...",
  "Initial evaluation shows the developer decided to failed the assignment on god.",
  "Recruiters reported a case of trendy assignment design.",
  "Scanning candidate profile for trendy assignments...",
  "Recruiters reported a case of basic brain rot design.",
  "We checked the history and found a aesthetic tiktok log.",
  "We checked the history and found a demure vibe log.",
  "Alert: The candidate spent three months trying to screenshot simple profile very demure style.",
  "Scanning candidate profile for demure energys...",
  "Recruiters reported a case of demure aesthetic design.",
  "Alert: The candidate spent three months trying to rizzed up recruiter for the algorithm.",
  "Alert: The candidate spent three months trying to scrolled brainrot feed for the algorithm."
];

export const findings = [
  "{{candidateName}} has spent three weeks optimizing a profile while completely ignoring {{missingSection}}.",
  "The candidate claims {{framework}} experience, but their repository is just a cap clone that has been abandoned.",
  "{{education}} is listed, but they still managed to deploy a brainrot caption to production.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to screenshot simple profile no cap.",
  "Listed {{skill}} as a primary competency, but the evidence points to a brainrot brain rot.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to failed the assignment with zero rizz.",
  "While debugging {{project}}, we found a trendy logic loop related to {{language}} features.",
  "{{education}} is listed, but they still managed to deploy a aesthetic energy to production.",
  "{{education}} is listed, but they still managed to deploy a demure rizz to production.",
  "A security audit on {{github}} detected a plain-text database password inside a brainrot brain rot.",
  "{{achievement}} was highlighted, but the git logs show they only managed to scrolled brainrot feed very demure style.",
  "Failed to configure {{project}} because {{candidateName}} decided to posted cringe video on god.",
  "A security audit on {{github}} detected a plain-text database password inside a cap energy.",
  "Listed {{skill}} as a primary competency, but the evidence points to a cap rizz.",
  "Listed {{skill}} as a primary competency, but the evidence points to a brainrot aesthetic.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to scrolled brainrot feed no cap.",
  "For {{experience}}, the primary contribution was writing a trendy config for a brain rot.",
  "{{github}} contains more cap aesthetics than original code.",
  "{{github}} contains more mindful caps than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a basic assignment.",
  "While debugging {{project}}, we found a low-key logic loop related to {{language}} features.",
  "{{education}} is listed, but they still managed to deploy a cap cap to production.",
  "Obtained {{certification}} which apparently teaches how to posted cringe video no cap.",
  "{{education}} is listed, but they still managed to deploy a basic brain rot to production.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to failed the assignment for the algorithm.",
  "Obtained {{certification}} which apparently teaches how to rizzed up recruiter no cap.",
  "{{achievement}} was highlighted, but the git logs show they only managed to failed the assignment for the algorithm.",
  "For {{experience}}, the primary contribution was writing a cap config for a assignment.",
  "Obtained {{certification}} which apparently teaches how to screenshot simple profile on god.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to failed the assignment very demure style.",
  "Obtained {{certification}} which apparently teaches how to failed the assignment with zero rizz.",
  "Listed {{skill}} as a primary competency, but the evidence points to a demure caption.",
  "{{education}} is listed, but they still managed to deploy a mindful vibe to production.",
  "A security audit on {{github}} detected a plain-text database password inside a demure rizz.",
  "{{github}} contains more low-key captions than original code.",
  "For {{experience}}, the primary contribution was writing a basic config for a vibe.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to posted cringe video very demure style.",
  "A security audit on {{github}} detected a plain-text database password inside a trendy tiktok.",
  "{{achievement}} was highlighted, but the git logs show they only managed to scrolled brainrot feed with zero rizz.",
  "For {{experience}}, the primary contribution was writing a aesthetic config for a tiktok.",
  "For {{experience}}, the primary contribution was writing a demure config for a energy.",
  "Obtained {{certification}} which apparently teaches how to screenshot simple profile with zero rizz.",
  "{{github}} contains more cap energys than original code.",
  "Obtained {{certification}} which apparently teaches how to posted cringe video very demure style.",
  "{{github}} contains more cap assignments than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to screenshot simple profile with zero rizz.",
  "A security audit on {{github}} detected a plain-text database password inside a mindful vibe.",
  "Obtained {{certification}} which apparently teaches how to rizzed up recruiter for the algorithm.",
  "{{github}} contains more brainrot assignments than original code.",
  "{{github}} contains more demure profiles than original code.",
  "{{github}} contains more demure energys than original code.",
  "Obtained {{certification}} which apparently teaches how to screenshot simple profile for the algorithm.",
  "A security audit on {{github}} detected a plain-text database password inside a low-key vibe.",
  "{{achievement}} was highlighted, but the git logs show they only managed to screenshot simple profile on god.",
  "{{candidateName}} has spent three weeks optimizing a brain rot while completely ignoring {{missingSection}}.",
  "Failed to configure {{project}} because {{candidateName}} decided to rizzed up recruiter very demure style.",
  "{{github}} contains more aesthetic aesthetics than original code.",
  "{{github}} contains more aesthetic brain rots than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to screenshot simple profile very demure style.",
  "{{achievement}} was highlighted, but the git logs show they only managed to rizzed up recruiter no cap.",
  "For {{experience}}, the primary contribution was writing a mindful config for a profile.",
  "{{education}} is listed, but they still managed to deploy a low-key rizz to production.",
  "{{github}} contains more mindful captions than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to screenshot simple profile with zero rizz.",
  "Listed {{skill}} as a primary competency, but the evidence points to a trendy assignment.",
  "Failed to configure {{project}} because {{candidateName}} decided to failed the assignment on god.",
  "{{achievement}} was highlighted, but the git logs show they only managed to posted cringe video with zero rizz.",
  "Listed {{skill}} as a primary competency, but the evidence points to a mindful vibe.",
  "{{github}} contains more brainrot rizzs than original code.",
  "Obtained {{certification}} which apparently teaches how to failed the assignment very demure style.",
  "Obtained {{certification}} which apparently teaches how to failed the assignment on god.",
  "{{achievement}} was highlighted, but the git logs show they only managed to posted cringe video for the algorithm.",
  "Listed {{skill}} as a primary competency, but the evidence points to a low-key tiktok.",
  "Failed to configure {{project}} because {{candidateName}} decided to rizzed up recruiter for the algorithm.",
  "{{github}} contains more basic captions than original code.",
  "For {{experience}}, the primary contribution was writing a low-key config for a brain rot.",
  "Failed to configure {{project}} because {{candidateName}} decided to rizzed up recruiter no cap.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to scrolled brainrot feed very demure style.",
  "Failed to configure {{project}} because {{candidateName}} decided to scrolled brainrot feed on god.",
  "{{achievement}} was highlighted, but the git logs show they only managed to screenshot simple profile very demure style.",
  "Obtained {{certification}} which apparently teaches how to failed the assignment for the algorithm.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to rizzed up recruiter very demure style.",
  "Failed to configure {{project}} because {{candidateName}} decided to screenshot simple profile on god.",
  "{{github}} contains more brainrot profiles than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to posted cringe video for the algorithm.",
  "Failed to configure {{project}} because {{candidateName}} decided to failed the assignment for the algorithm.",
  "Failed to configure {{project}} because {{candidateName}} decided to screenshot simple profile for the algorithm.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to posted cringe video with zero rizz.",
  "For {{experience}}, the primary contribution was writing a low-key config for a vibe.",
  "Failed to configure {{project}} because {{candidateName}} decided to rizzed up recruiter with zero rizz.",
  "{{github}} contains more cap rizzs than original code.",
  "{{education}} is listed, but they still managed to deploy a trendy tiktok to production.",
  "For {{experience}}, the primary contribution was writing a brainrot config for a caption.",
  "Failed to configure {{project}} because {{candidateName}} decided to posted cringe video for the algorithm.",
  "Listed {{skill}} as a primary competency, but the evidence points to a low-key brain rot.",
  "A security audit on {{github}} detected a plain-text database password inside a brainrot aesthetic.",
  "{{github}} contains more trendy vibes than original code.",
  "{{github}} contains more brainrot vibes than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to screenshot simple profile very demure style.",
  "{{achievement}} was highlighted, but the git logs show they only managed to failed the assignment very demure style.",
  "{{achievement}} was highlighted, but the git logs show they only managed to failed the assignment with zero rizz.",
  "Failed to configure {{project}} because {{candidateName}} decided to failed the assignment with zero rizz."
];

export const punchlines = [
  "We would deploy it to production, but our SRE team deserves to sleep at night.",
  "The documentation was so empty, I had to use it as a virtual sketchbook.",
  "A junior developer looked at the brain rot and immediately went to touch grass.",
  "It did not optimize our process, but it did make the laptop fan spin like a jet engine.",
  "The compiler requested emotional support after reading the aesthetic code.",
  "Legend says this trendy aesthetic is still running on localhost.",
  "Even Stack Overflow has marked this brain rot as off-topic.",
  "Legend says this demure energy is still running on localhost.",
  "Legend says this low-key energy is still running on localhost.",
  "A junior developer looked at the profile and immediately went to touch grass.",
  "Even Stack Overflow has marked this tiktok as off-topic.",
  "The only thing memory-safe about this setup is that nobody has ever tried to run it.",
  "Legend says this trendy profile is still running on localhost.",
  "Legend says this mindful rizz is still running on localhost.",
  "The compiler requested emotional support after reading the low-key code.",
  "Legend says this demure aesthetic is still running on localhost.",
  "Legend says this mindful energy is still running on localhost.",
  "Legend says this mindful aesthetic is still running on localhost.",
  "Legend says this basic caption is still running on localhost.",
  "Legend says this demure vibe is still running on localhost.",
  "Legend says this cap cap is still running on localhost.",
  "Legend says this brainrot tiktok is still running on localhost.",
  "Legend says this basic tiktok is still running on localhost.",
  "Legend says this basic rizz is still running on localhost.",
  "Legend says this aesthetic profile is still running on localhost.",
  "Legend says this mindful profile is still running on localhost.",
  "Legend says this demure profile is still running on localhost.",
  "Legend says this mindful caption is still running on localhost.",
  "Legend says this basic vibe is still running on localhost.",
  "Legend says this basic profile is still running on localhost.",
  "Legend says this aesthetic assignment is still running on localhost.",
  "Legend says this demure caption is still running on localhost.",
  "Legend says this trendy brain rot is still running on localhost.",
  "Legend says this aesthetic caption is still running on localhost.",
  "Legend says this brainrot caption is still running on localhost.",
  "Legend says this trendy vibe is still running on localhost.",
  "Legend says this demure rizz is still running on localhost.",
  "Legend says this mindful vibe is still running on localhost.",
  "Legend says this trendy tiktok is still running on localhost.",
  "Legend says this trendy rizz is still running on localhost.",
  "Legend says this aesthetic tiktok is still running on localhost.",
  "Legend says this low-key brain rot is still running on localhost.",
  "Legend says this basic aesthetic is still running on localhost.",
  "Legend says this aesthetic vibe is still running on localhost.",
  "Legend says this brainrot assignment is still running on localhost.",
  "Legend says this aesthetic energy is still running on localhost.",
  "Legend says this trendy caption is still running on localhost.",
  "Legend says this basic energy is still running on localhost.",
  "Legend says this trendy energy is still running on localhost.",
  "Legend says this brainrot energy is still running on localhost.",
  "Legend says this mindful assignment is still running on localhost.",
  "Legend says this trendy assignment is still running on localhost.",
  "This is a classic example of a demure assignment disaster.",
  "This is a classic example of a low-key cap disaster.",
  "This is a classic example of a basic profile disaster.",
  "This is a classic example of a low-key brain rot disaster.",
  "This is a classic example of a trendy profile disaster.",
  "This is a classic example of a cap profile disaster.",
  "This is a classic example of a demure brain rot disaster.",
  "This is a classic example of a mindful vibe disaster.",
  "This is a classic example of a trendy energy disaster.",
  "This is a classic example of a basic tiktok disaster.",
  "This is a classic example of a mindful rizz disaster.",
  "This is a classic example of a demure cap disaster.",
  "This is a classic example of a aesthetic tiktok disaster.",
  "This is a classic example of a low-key assignment disaster.",
  "This is a classic example of a brainrot rizz disaster.",
  "This is a classic example of a brainrot cap disaster.",
  "This is a classic example of a mindful cap disaster.",
  "This is a classic example of a trendy cap disaster.",
  "This is a classic example of a cap tiktok disaster.",
  "This is a classic example of a aesthetic profile disaster.",
  "This is a classic example of a demure vibe disaster.",
  "This is a classic example of a basic caption disaster.",
  "This is a classic example of a brainrot profile disaster.",
  "This is a classic example of a mindful brain rot disaster.",
  "This is a classic example of a cap caption disaster.",
  "This is a classic example of a basic aesthetic disaster.",
  "This is a classic example of a mindful energy disaster.",
  "This is a classic example of a basic energy disaster.",
  "This is a classic example of a brainrot energy disaster.",
  "This is a classic example of a demure rizz disaster.",
  "This is a classic example of a mindful aesthetic disaster.",
  "This is a classic example of a aesthetic caption disaster.",
  "This is a classic example of a demure profile disaster.",
  "This is a classic example of a brainrot caption disaster.",
  "This is a classic example of a mindful profile disaster.",
  "This is a classic example of a cap rizz disaster."
];

export const verdicts = [
  "Closed as low-key duplicate.",
  "Ship blocked by basic check failures.",
  "PR posted cringe video due to trendy implementation.",
  "Closed as demure duplicate.",
  "Rejected on first principles of caption organization.",
  "Closed as cap duplicate.",
  "Verdict: Rizz is completely unmergeable.",
  "Request changes on the basic assignment.",
  "Return after touching actual production servers.",
  "Closed as basic duplicate.",
  "Needs more commits and fewer explanations.",
  "PR scrolled brainrot feed due to low-key implementation.",
  "Closed as mindful duplicate.",
  "Rejected on first principles of vibe organization.",
  "Verdict: Tiktok is completely unmergeable.",
  "Closed as aesthetic duplicate.",
  "Request changes on the mindful profile.",
  "PR failed the assignment due to demure implementation.",
  "Verdict: Brain rot is completely unmergeable.",
  "Ship blocked by low-key check failures.",
  "PR scrolled brainrot feed due to trendy implementation.",
  "Request changes on the demure profile.",
  "PR scrolled brainrot feed due to basic implementation.",
  "Rejected on first principles of assignment organization.",
  "Request changes on the low-key assignment.",
  "Rejected on first principles of cap organization.",
  "Rejected on first principles of brain rot organization.",
  "Rejected on first principles of aesthetic organization.",
  "Ship blocked by cap check failures.",
  "PR screenshot simple profile due to cap implementation.",
  "Ship blocked by aesthetic check failures.",
  "Ship blocked by brainrot check failures.",
  "Verdict: Assignment is completely unmergeable.",
  "PR rizzed up recruiter due to brainrot implementation.",
  "PR rizzed up recruiter due to basic implementation.",
  "Request changes on the trendy tiktok.",
  "PR failed the assignment due to mindful implementation.",
  "PR posted cringe video due to demure implementation.",
  "PR rizzed up recruiter due to aesthetic implementation.",
  "Ship blocked by trendy check failures.",
  "Closed as brainrot duplicate.",
  "Rejected on first principles of profile organization.",
  "Request changes on the low-key tiktok.",
  "Rejected on first principles of tiktok organization.",
  "Verdict: Energy is completely unmergeable.",
  "Request changes on the trendy rizz.",
  "Ship blocked by demure check failures.",
  "Verdict: Profile is completely unmergeable.",
  "Ship blocked by mindful check failures.",
  "Request changes on the aesthetic assignment.",
  "Request changes on the brainrot aesthetic.",
  "PR screenshot simple profile due to aesthetic implementation.",
  "Closed as trendy duplicate.",
  "PR scrolled brainrot feed due to cap implementation.",
  "Request changes on the trendy aesthetic.",
  "Request changes on the cap profile.",
  "Request changes on the aesthetic rizz.",
  "Request changes on the cap brain rot.",
  "Rejected on first principles of rizz organization.",
  "Request changes on the mindful energy.",
  "PR screenshot simple profile due to brainrot implementation.",
  "Request changes on the demure brain rot.",
  "Request changes on the aesthetic energy.",
  "Request changes on the demure caption.",
  "Request changes on the demure rizz.",
  "Verdict: Cap is completely unmergeable.",
  "Request changes on the mindful caption.",
  "PR posted cringe video due to basic implementation.",
  "Request changes on the demure energy.",
  "Verdict: Aesthetic is completely unmergeable.",
  "Request changes on the brainrot cap.",
  "Verdict: Caption is completely unmergeable.",
  "Rejected on first principles of energy organization.",
  "Request changes on the basic energy.",
  "Request changes on the low-key aesthetic.",
  "Request changes on the basic rizz.",
  "Request changes on the low-key caption.",
  "PR screenshot simple profile due to low-key implementation.",
  "PR screenshot simple profile due to trendy implementation.",
  "PR screenshot simple profile due to basic implementation.",
  "PR failed the assignment due to trendy implementation.",
  "Verdict: Vibe is completely unmergeable.",
  "PR failed the assignment due to low-key implementation.",
  "Request changes on the trendy assignment.",
  "Request changes on the basic caption.",
  "Request changes on the demure aesthetic.",
  "PR screenshot simple profile due to mindful implementation.",
  "Request changes on the trendy vibe.",
  "PR failed the assignment due to brainrot implementation.",
  "Request changes on the low-key vibe.",
  "Request changes on the brainrot vibe.",
  "Request changes on the aesthetic profile.",
  "PR posted cringe video due to aesthetic implementation.",
  "Request changes on the low-key cap.",
  "PR posted cringe video due to mindful implementation.",
  "PR posted cringe video due to cap implementation.",
  "PR scrolled brainrot feed due to aesthetic implementation.",
  "Request changes on the basic cap.",
  "Request changes on the cap energy."
];

export const easterEggs = [
  "Dark Web Resume Auction: Current bid is $0.00, and the buyer is requesting a refund.",
  "Steam Achievement Unlocked: Successfully crashed a hello-world app on a $10,000 server.",
  "Matrix Glitch: You copy-pasted a template and now the server believes it is a real founder.",
  "Gordon Ramsay Meltdown: 'This energy is raw! It's absolutely raw!'",
  "NASA Alert: Space mission aborted due to a minor cap parsing error.",
  "Gordon Ramsay Meltdown: 'This caption is raw! It's absolutely raw!'",
  "Elon Musk Tweet: 'Just deleted the entire profile pipeline, was completely useless.'",
  "Gordon Ramsay Meltdown: 'This vibe is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This cap is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted low-key assignments.",
  "FBI Investigation: Suspect was found deploying unencrypted demure caps.",
  "FBI Investigation: Suspect was found deploying unencrypted trendy assignments.",
  "FBI Investigation: Suspect was found deploying unencrypted basic vibes.",
  "Gordon Ramsay Meltdown: 'This aesthetic is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This rizz is raw! It's absolutely raw!'",
  "Elon Musk Tweet: 'Just deleted the entire brain rot pipeline, was completely useless.'",
  "Gordon Ramsay Meltdown: 'This profile is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted brainrot energys.",
  "FBI Investigation: Suspect was found deploying unencrypted demure brain rots.",
  "FBI Investigation: Suspect was found deploying unencrypted cap rizzs.",
  "FBI Investigation: Suspect was found deploying unencrypted aesthetic aesthetics.",
  "Gordon Ramsay Meltdown: 'This assignment is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This brain rot is raw! It's absolutely raw!'",
  "NASA Alert: Space mission aborted due to a minor brain rot parsing error."
];
