// ES Module exports for git_commit roast format
export const titles = [
  "Critical Merge failure",
  "Absolute Messy architecture",
  "NullPointerMasterException",
  "Conflicting Commit Loop",
  "Incident Report: Force-pushed Merge",
  "Absolute Early architecture",
  "Early Branch Error",
  "Real Commit Loop",
  "Conflict Not Found",
  "NullPointerRevertException",
  "Critical Master failure",
  "Messy Revert Error",
  "Commit Not Found",
  "The Master tragedy",
  "Master conflict detected",
  "Real Hash Loop",
  "Untested Master Loop",
  "Critical Log failure",
  "Incident Report: Real Revert",
  "Failed to compile: Branch",
  "Force-pushed Hash Loop",
  "Incident Report: Broken Hash",
  "Failed to compile: Revert",
  "Revert Not Found",
  "NullPointerHashException",
  "Failed to compile: Merge",
  "Absolute Broken architecture",
  "Incident Report: Messy Conflict",
  "The Log tragedy",
  "Final Commit Loop",
  "Incident Report: Broken Conflict",
  "Critical Hash failure",
  "Commit conflict detected",
  "Log Not Found",
  "Failed to compile: Master",
  "Final Rebase Loop",
  "Failed to compile: Hash",
  "Early Conflict Loop",
  "Conflict conflict detected",
  "Hash Not Found",
  "Critical Rebase failure",
  "Absolute Force-pushed architecture",
  "Rebase Not Found",
  "Force-pushed Head Error",
  "Failed to compile: Conflict",
  "NullPointerCommitException",
  "Incident Report: Broken Log",
  "Head conflict detected",
  "Conflicting Hash Loop",
  "Critical Head failure",
  "Broken Commit Error",
  "The Head tragedy",
  "Final Commit Error",
  "Early Head Loop",
  "Real Revert Error",
  "The Conflict tragedy",
  "Absolute Untested architecture",
  "Conflicting Revert Error",
  "Absolute Final architecture",
  "Incident Report: Force-pushed Hash",
  "Broken Log Loop",
  "Critical Conflict failure",
  "Failed to compile: Head",
  "Merge Not Found",
  "Absolute Real architecture",
  "Incident Report: Messy Master",
  "NullPointerRebaseException",
  "The Merge tragedy",
  "NullPointerHeadException",
  "NullPointerBranchException",
  "Untested Merge Loop",
  "The Revert tragedy",
  "Messy Log Loop",
  "Incident Report: Early Head",
  "Real Conflict Loop",
  "Critical Branch failure",
  "The Branch tragedy",
  "Incident Report: Messy Branch",
  "Revert conflict detected",
  "Absolute Conflicting architecture",
  "Hash conflict detected",
  "Log conflict detected",
  "The Rebase tragedy",
  "Failed to compile: Commit",
  "Broken Revert Error",
  "Incident Report: Messy Rebase",
  "Critical Commit failure",
  "Incident Report: Messy Hash",
  "Incident Report: Untested Rebase",
  "Untested Master Error",
  "Final Conflict Error",
  "Final Log Error",
  "Incident Report: Early Conflict",
  "Messy Commit Error",
  "Broken Conflict Loop",
  "The Commit tragedy",
  "Real Merge Error",
  "Incident Report: Untested Conflict",
  "NullPointerConflictException",
  "Force-pushed Merge Loop"
];

export const openings = [
  "The team has initiated audit for the candidate's branch setup.",
  "Recruiters reported a case of messy rebase design.",
  "Warning: System flagged an attempt to force-pushed to master without team review.",
  "Recruiters reported a case of conflicting branch design.",
  "Alert: The candidate spent three months trying to reset commit history by total accident.",
  "Warning: System flagged an attempt to rebased local branch breaking the integration.",
  "Initial evaluation shows the developer decided to reset commit history breaking the integration.",
  "Alert: The candidate spent three months trying to reset commit history without team review.",
  "Initial evaluation shows the developer decided to force-pushed to master breaking the integration.",
  "We checked the history and found a broken hash log.",
  "We checked the history and found a force-pushed merge log.",
  "Initial evaluation shows the developer decided to reverted active deployment by total accident.",
  "Warning: System flagged an attempt to reverted active deployment with merge conflicts.",
  "Initial evaluation shows the developer decided to rebased local branch without team review.",
  "Initial evaluation shows the developer decided to force-pushed to master by total accident.",
  "Recruiters reported a case of conflicting commit design.",
  "Alert: The candidate spent three months trying to force-pushed to master by total accident.",
  "A review was filed regarding a real head.",
  "Alert: The candidate spent three months trying to reverted active deployment with merge conflicts.",
  "We checked the history and found a conflicting commit log.",
  "A review was filed regarding a conflicting rebase.",
  "Scanning candidate profile for real masters...",
  "We checked the history and found a final commit log.",
  "Warning: System flagged an attempt to rebased local branch with merge conflicts.",
  "Initial evaluation shows the developer decided to force-pushed to master with merge conflicts.",
  "Initial evaluation shows the developer decided to force-pushed to master to main branch.",
  "Recruiters reported a case of early log design.",
  "Alert: The candidate spent three months trying to rebased local branch without team review.",
  "Initial evaluation shows the developer decided to rebased local branch to main branch.",
  "Scanning candidate profile for broken logs...",
  "Alert: The candidate spent three months trying to reverted active deployment without team review.",
  "Initial evaluation shows the developer decided to reverted active deployment without team review.",
  "Warning: System flagged an attempt to reset commit history breaking the integration.",
  "Scanning candidate profile for messy logs...",
  "Scanning candidate profile for broken heads...",
  "Warning: System flagged an attempt to force-pushed to master to main branch.",
  "Recruiters reported a case of broken hash design.",
  "A review was filed regarding a early master.",
  "Warning: System flagged an attempt to reset commit history with merge conflicts.",
  "Recruiters reported a case of messy conflict design.",
  "Recruiters reported a case of untested master design.",
  "A review was filed regarding a force-pushed head.",
  "Alert: The candidate spent three months trying to force-pushed to master breaking the integration.",
  "We checked the history and found a final branch log.",
  "We checked the history and found a untested merge log.",
  "Recruiters reported a case of untested revert design.",
  "Warning: System flagged an attempt to rebased local branch to main branch.",
  "Initial evaluation shows the developer decided to force-pushed to master without team review.",
  "Scanning candidate profile for early rebases...",
  "Initial evaluation shows the developer decided to rebased local branch with merge conflicts.",
  "Scanning candidate profile for final rebases...",
  "A review was filed regarding a real conflict.",
  "Warning: System flagged an attempt to resolved merge conflict by total accident.",
  "Scanning candidate profile for final logs...",
  "A review was filed regarding a final master.",
  "A review was filed regarding a untested log.",
  "Scanning candidate profile for final merges...",
  "A review was filed regarding a final commit.",
  "Recruiters reported a case of force-pushed commit design.",
  "Recruiters reported a case of conflicting merge design.",
  "A review was filed regarding a messy rebase.",
  "Scanning candidate profile for final conflicts...",
  "Recruiters reported a case of broken branch design.",
  "Scanning candidate profile for untested merges...",
  "A review was filed regarding a conflicting master.",
  "Recruiters reported a case of messy head design.",
  "A review was filed regarding a real master.",
  "A review was filed regarding a conflicting log.",
  "Recruiters reported a case of conflicting revert design.",
  "Warning: System flagged an attempt to force-pushed to master with merge conflicts.",
  "Scanning candidate profile for untested branchs...",
  "Recruiters reported a case of force-pushed log design.",
  "Initial evaluation shows the developer decided to resolved merge conflict breaking the integration.",
  "We checked the history and found a real rebase log.",
  "Warning: System flagged an attempt to resolved merge conflict breaking the integration.",
  "Alert: The candidate spent three months trying to reverted active deployment to main branch.",
  "Recruiters reported a case of untested rebase design.",
  "A review was filed regarding a early conflict.",
  "We checked the history and found a conflicting hash log.",
  "A review was filed regarding a force-pushed rebase.",
  "Recruiters reported a case of early conflict design.",
  "Initial evaluation shows the developer decided to resolved merge conflict with merge conflicts.",
  "A review was filed regarding a untested merge.",
  "Alert: The candidate spent three months trying to rebased local branch by total accident.",
  "Recruiters reported a case of conflicting master design.",
  "A review was filed regarding a broken rebase.",
  "Warning: System flagged an attempt to reverted active deployment breaking the integration.",
  "Warning: System flagged an attempt to reverted active deployment without team review.",
  "We checked the history and found a untested head log.",
  "Warning: System flagged an attempt to reset commit history without team review.",
  "Scanning candidate profile for final hashs..."
];

export const findings = [
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to rebased local branch to main branch.",
  "{{candidateName}} has spent three weeks optimizing a branch while completely ignoring {{missingSection}}.",
  "{{education}} is listed, but they still managed to deploy a conflicting master to production.",
  "{{github}} contains more conflicting branchs than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a messy commit.",
  "The candidate claims {{framework}} experience, but their repository is just a force-pushed clone that has been abandoned.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to reset commit history without team review.",
  "{{github}} contains more force-pushed heads than original code.",
  "While debugging {{project}}, we found a final logic loop related to {{language}} features.",
  "Failed to configure {{project}} because {{candidateName}} decided to force-pushed to master by total accident.",
  "A security audit on {{github}} detected a plain-text database password inside a broken log.",
  "Obtained {{certification}} which apparently teaches how to rebased local branch without team review.",
  "Listed {{skill}} as a primary competency, but the evidence points to a messy head.",
  "Obtained {{certification}} which apparently teaches how to reverted active deployment without team review.",
  "Listed {{skill}} as a primary competency, but the evidence points to a early rebase.",
  "{{github}} contains more final hashs than original code.",
  "Obtained {{certification}} which apparently teaches how to resolved merge conflict with merge conflicts.",
  "{{github}} contains more broken branchs than original code.",
  "Obtained {{certification}} which apparently teaches how to rebased local branch by total accident.",
  "Failed to configure {{project}} because {{candidateName}} decided to force-pushed to master with merge conflicts.",
  "A security audit on {{github}} detected a plain-text database password inside a untested master.",
  "{{github}} contains more final heads than original code.",
  "For {{experience}}, the primary contribution was writing a force-pushed config for a log.",
  "{{achievement}} was highlighted, but the git logs show they only managed to rebased local branch to main branch.",
  "{{education}} is listed, but they still managed to deploy a messy rebase to production.",
  "For {{experience}}, the primary contribution was writing a real config for a master.",
  "{{education}} is listed, but they still managed to deploy a early log to production.",
  "{{github}} contains more messy merges than original code.",
  "Listed {{skill}} as a primary competency, but the evidence points to a final commit.",
  "For {{experience}}, the primary contribution was writing a conflicting config for a log.",
  "Failed to configure {{project}} because {{candidateName}} decided to reverted active deployment to main branch.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to force-pushed to master to main branch.",
  "A security audit on {{github}} detected a plain-text database password inside a force-pushed merge.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to force-pushed to master breaking the integration.",
  "{{github}} contains more broken merges than original code.",
  "{{github}} contains more real logs than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to reset commit history by total accident.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to force-pushed to master with merge conflicts.",
  "Listed {{skill}} as a primary competency, but the evidence points to a force-pushed conflict.",
  "{{github}} contains more final masters than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to rebased local branch without team review.",
  "Obtained {{certification}} which apparently teaches how to force-pushed to master breaking the integration.",
  "Failed to configure {{project}} because {{candidateName}} decided to reset commit history breaking the integration.",
  "{{achievement}} was highlighted, but the git logs show they only managed to rebased local branch with merge conflicts.",
  "Failed to configure {{project}} because {{candidateName}} decided to rebased local branch with merge conflicts.",
  "For {{experience}}, the primary contribution was writing a untested config for a conflict.",
  "Failed to configure {{project}} because {{candidateName}} decided to rebased local branch breaking the integration.",
  "{{achievement}} was highlighted, but the git logs show they only managed to force-pushed to master breaking the integration.",
  "Failed to configure {{project}} because {{candidateName}} decided to reverted active deployment without team review.",
  "Obtained {{certification}} which apparently teaches how to rebased local branch with merge conflicts.",
  "Listed {{skill}} as a primary competency, but the evidence points to a untested master.",
  "{{achievement}} was highlighted, but the git logs show they only managed to resolved merge conflict without team review.",
  "For {{experience}}, the primary contribution was writing a early config for a branch.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to force-pushed to master by total accident.",
  "Obtained {{certification}} which apparently teaches how to reset commit history to main branch.",
  "Failed to configure {{project}} because {{candidateName}} decided to reverted active deployment breaking the integration.",
  "{{education}} is listed, but they still managed to deploy a force-pushed head to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to reset commit history breaking the integration.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to resolved merge conflict to main branch.",
  "Failed to configure {{project}} because {{candidateName}} decided to rebased local branch to main branch.",
  "Obtained {{certification}} which apparently teaches how to rebased local branch breaking the integration.",
  "{{achievement}} was highlighted, but the git logs show they only managed to force-pushed to master without team review.",
  "{{github}} contains more conflicting masters than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to reset commit history breaking the integration.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to reverted active deployment by total accident.",
  "{{education}} is listed, but they still managed to deploy a final head to production.",
  "Listed {{skill}} as a primary competency, but the evidence points to a real branch.",
  "{{github}} contains more final merges than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to reset commit history by total accident.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to force-pushed to master without team review.",
  "Obtained {{certification}} which apparently teaches how to reset commit history without team review.",
  "{{github}} contains more untested conflicts than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to resolved merge conflict to main branch.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to resolved merge conflict breaking the integration.",
  "{{github}} contains more broken logs than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a real hash.",
  "{{achievement}} was highlighted, but the git logs show they only managed to resolved merge conflict with merge conflicts.",
  "A security audit on {{github}} detected a plain-text database password inside a early conflict.",
  "Obtained {{certification}} which apparently teaches how to rebased local branch to main branch.",
  "{{github}} contains more final logs than original code.",
  "For {{experience}}, the primary contribution was writing a broken config for a head.",
  "While debugging {{project}}, we found a force-pushed logic loop related to {{language}} features.",
  "{{achievement}} was highlighted, but the git logs show they only managed to reverted active deployment by total accident.",
  "{{github}} contains more conflicting conflicts than original code.",
  "{{github}} contains more messy commits than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to reverted active deployment with merge conflicts.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to reset commit history with merge conflicts.",
  "{{github}} contains more early logs than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a conflicting rebase.",
  "{{github}} contains more early reverts than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to force-pushed to master by total accident.",
  "{{achievement}} was highlighted, but the git logs show they only managed to reset commit history without team review.",
  "{{github}} contains more untested commits than original code.",
  "{{education}} is listed, but they still managed to deploy a real branch to production.",
  "{{github}} contains more untested logs than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to reverted active deployment with merge conflicts.",
  "{{achievement}} was highlighted, but the git logs show they only managed to reset commit history by total accident.",
  "A security audit on {{github}} detected a plain-text database password inside a final branch.",
  "{{github}} contains more real heads than original code.",
  "Obtained {{certification}} which apparently teaches how to force-pushed to master without team review.",
  "Obtained {{certification}} which apparently teaches how to resolved merge conflict to main branch.",
  "{{github}} contains more broken rebases than original code.",
  "{{github}} contains more final commits than original code.",
  "Obtained {{certification}} which apparently teaches how to resolved merge conflict breaking the integration.",
  "Failed to configure {{project}} because {{candidateName}} decided to force-pushed to master without team review.",
  "Obtained {{certification}} which apparently teaches how to reset commit history breaking the integration.",
  "{{github}} contains more messy conflicts than original code.",
  "Obtained {{certification}} which apparently teaches how to reverted active deployment breaking the integration."
];

export const punchlines = [
  "Even Stack Overflow has marked this revert as off-topic.",
  "Legend says this untested branch is still running on localhost.",
  "We would deploy it to production, but our SRE team deserves to sleep at night.",
  "It did not optimize our process, but it did make the laptop fan spin like a jet engine.",
  "A junior developer looked at the branch and immediately went to touch grass.",
  "The compiler requested emotional support after reading the messy code.",
  "Legend says this broken commit is still running on localhost.",
  "The only thing memory-safe about this setup is that nobody has ever tried to run it.",
  "The documentation was so empty, I had to use it as a virtual sketchbook.",
  "Legend says this real conflict is still running on localhost.",
  "Legend says this force-pushed log is still running on localhost.",
  "Legend says this final rebase is still running on localhost.",
  "The compiler requested emotional support after reading the force-pushed code.",
  "Legend says this real head is still running on localhost.",
  "Legend says this conflicting hash is still running on localhost.",
  "Legend says this conflicting rebase is still running on localhost.",
  "Legend says this messy revert is still running on localhost.",
  "Legend says this early conflict is still running on localhost.",
  "Legend says this broken branch is still running on localhost.",
  "Legend says this conflicting merge is still running on localhost.",
  "Legend says this final branch is still running on localhost.",
  "Legend says this messy log is still running on localhost.",
  "Legend says this broken master is still running on localhost.",
  "Legend says this real commit is still running on localhost.",
  "Legend says this broken hash is still running on localhost.",
  "Legend says this untested conflict is still running on localhost.",
  "Legend says this untested revert is still running on localhost.",
  "Legend says this real hash is still running on localhost.",
  "Legend says this conflicting revert is still running on localhost.",
  "Legend says this early rebase is still running on localhost.",
  "Legend says this messy conflict is still running on localhost.",
  "Legend says this untested merge is still running on localhost.",
  "Legend says this untested commit is still running on localhost.",
  "Legend says this real revert is still running on localhost.",
  "Legend says this messy merge is still running on localhost.",
  "Legend says this conflicting head is still running on localhost.",
  "Legend says this early log is still running on localhost.",
  "Legend says this final merge is still running on localhost.",
  "Legend says this messy commit is still running on localhost.",
  "Legend says this untested master is still running on localhost.",
  "Legend says this final head is still running on localhost.",
  "Legend says this untested head is still running on localhost.",
  "Legend says this messy hash is still running on localhost.",
  "Legend says this broken log is still running on localhost.",
  "Legend says this messy head is still running on localhost.",
  "Legend says this broken revert is still running on localhost.",
  "Legend says this untested rebase is still running on localhost.",
  "Legend says this final master is still running on localhost.",
  "Legend says this early merge is still running on localhost.",
  "Legend says this final commit is still running on localhost.",
  "Legend says this early branch is still running on localhost.",
  "Legend says this conflicting conflict is still running on localhost.",
  "Legend says this real log is still running on localhost.",
  "Legend says this untested hash is still running on localhost.",
  "Legend says this broken head is still running on localhost.",
  "Legend says this broken merge is still running on localhost.",
  "Legend says this final conflict is still running on localhost.",
  "Legend says this final hash is still running on localhost.",
  "Legend says this broken conflict is still running on localhost.",
  "Legend says this final revert is still running on localhost.",
  "Legend says this conflicting master is still running on localhost.",
  "Legend says this conflicting branch is still running on localhost.",
  "Legend says this early head is still running on localhost.",
  "Legend says this real rebase is still running on localhost.",
  "Legend says this real branch is still running on localhost.",
  "Legend says this real merge is still running on localhost.",
  "Legend says this real master is still running on localhost.",
  "Legend says this broken rebase is still running on localhost.",
  "Legend says this messy rebase is still running on localhost.",
  "This is a classic example of a early merge disaster.",
  "This is a classic example of a force-pushed conflict disaster.",
  "This is a classic example of a messy log disaster.",
  "This is a classic example of a broken master disaster.",
  "This is a classic example of a real revert disaster.",
  "This is a classic example of a final commit disaster.",
  "This is a classic example of a untested rebase disaster.",
  "This is a classic example of a broken revert disaster.",
  "This is a classic example of a conflicting head disaster.",
  "This is a classic example of a force-pushed merge disaster.",
  "This is a classic example of a broken hash disaster.",
  "This is a classic example of a real log disaster.",
  "This is a classic example of a real commit disaster.",
  "This is a classic example of a final rebase disaster.",
  "This is a classic example of a force-pushed hash disaster.",
  "This is a classic example of a force-pushed branch disaster.",
  "This is a classic example of a final merge disaster.",
  "This is a classic example of a untested revert disaster.",
  "This is a classic example of a real master disaster.",
  "This is a classic example of a early hash disaster.",
  "This is a classic example of a untested commit disaster.",
  "This is a classic example of a conflicting revert disaster.",
  "This is a classic example of a messy hash disaster.",
  "This is a classic example of a messy conflict disaster.",
  "This is a classic example of a early rebase disaster.",
  "This is a classic example of a final hash disaster.",
  "This is a classic example of a final log disaster.",
  "This is a classic example of a real conflict disaster.",
  "This is a classic example of a conflicting branch disaster.",
  "This is a classic example of a messy head disaster.",
  "This is a classic example of a messy commit disaster.",
  "This is a classic example of a force-pushed log disaster.",
  "This is a classic example of a untested branch disaster.",
  "This is a classic example of a conflicting master disaster.",
  "This is a classic example of a real merge disaster.",
  "This is a classic example of a messy revert disaster.",
  "This is a classic example of a final master disaster.",
  "This is a classic example of a untested merge disaster."
];

export const verdicts = [
  "Request changes on the messy merge.",
  "PR resolved merge conflict due to messy implementation.",
  "Request changes on the untested hash.",
  "Return after touching actual production servers.",
  "PR reverted active deployment due to messy implementation.",
  "Closed as untested duplicate.",
  "PR reset commit history due to untested implementation.",
  "PR resolved merge conflict due to real implementation.",
  "PR reverted active deployment due to final implementation.",
  "Closed as messy duplicate.",
  "Rejected on first principles of hash organization.",
  "Needs more commits and fewer explanations.",
  "Verdict: Master is completely unmergeable.",
  "Closed as force-pushed duplicate.",
  "Rejected on first principles of branch organization.",
  "Request changes on the force-pushed commit.",
  "Request changes on the untested conflict.",
  "Ship blocked by untested check failures.",
  "Ship blocked by early check failures.",
  "PR resolved merge conflict due to broken implementation.",
  "Request changes on the messy head.",
  "Ship blocked by broken check failures.",
  "Request changes on the real merge.",
  "Ship blocked by force-pushed check failures.",
  "Rejected on first principles of master organization.",
  "PR rebased local branch due to force-pushed implementation.",
  "Verdict: Head is completely unmergeable.",
  "PR force-pushed to master due to broken implementation.",
  "Verdict: Log is completely unmergeable.",
  "PR resolved merge conflict due to force-pushed implementation.",
  "Request changes on the untested master.",
  "Rejected on first principles of rebase organization.",
  "Closed as early duplicate.",
  "Verdict: Branch is completely unmergeable.",
  "Rejected on first principles of revert organization.",
  "Rejected on first principles of merge organization.",
  "Verdict: Merge is completely unmergeable.",
  "PR reset commit history due to messy implementation.",
  "Request changes on the final rebase.",
  "Ship blocked by messy check failures.",
  "Closed as final duplicate.",
  "Request changes on the real rebase.",
  "Closed as real duplicate.",
  "PR reverted active deployment due to broken implementation.",
  "Request changes on the force-pushed master.",
  "Ship blocked by final check failures.",
  "Request changes on the early head.",
  "Rejected on first principles of commit organization.",
  "Verdict: Commit is completely unmergeable.",
  "Request changes on the messy commit.",
  "Request changes on the conflicting commit.",
  "Verdict: Revert is completely unmergeable.",
  "Request changes on the final merge.",
  "PR rebased local branch due to broken implementation.",
  "Request changes on the final revert.",
  "PR force-pushed to master due to messy implementation.",
  "PR reset commit history due to force-pushed implementation.",
  "Request changes on the conflicting head.",
  "Verdict: Hash is completely unmergeable.",
  "Verdict: Rebase is completely unmergeable.",
  "Ship blocked by real check failures.",
  "Rejected on first principles of conflict organization.",
  "Ship blocked by conflicting check failures.",
  "Request changes on the final head.",
  "Request changes on the force-pushed conflict.",
  "Request changes on the early hash.",
  "PR rebased local branch due to messy implementation.",
  "Request changes on the real revert.",
  "Request changes on the broken revert.",
  "Request changes on the early master.",
  "Request changes on the broken conflict.",
  "Closed as broken duplicate.",
  "PR reverted active deployment due to conflicting implementation.",
  "Rejected on first principles of log organization.",
  "Request changes on the broken log.",
  "Rejected on first principles of head organization.",
  "Request changes on the force-pushed log.",
  "Request changes on the early branch.",
  "PR resolved merge conflict due to early implementation.",
  "Request changes on the messy rebase.",
  "PR reverted active deployment due to early implementation.",
  "PR reset commit history due to early implementation.",
  "Verdict: Conflict is completely unmergeable.",
  "Request changes on the early rebase.",
  "Request changes on the force-pushed rebase.",
  "Request changes on the early revert.",
  "Request changes on the final master.",
  "Closed as conflicting duplicate.",
  "Request changes on the final log.",
  "Request changes on the messy branch.",
  "Request changes on the early merge.",
  "PR reset commit history due to conflicting implementation.",
  "Request changes on the force-pushed branch.",
  "PR reverted active deployment due to real implementation.",
  "PR rebased local branch due to untested implementation.",
  "Request changes on the conflicting merge.",
  "Request changes on the broken master.",
  "PR rebased local branch due to early implementation.",
  "PR reset commit history due to broken implementation."
];

export const easterEggs = [
  "FBI Investigation: Suspect was found deploying unencrypted force-pushed reverts.",
  "Gordon Ramsay Meltdown: 'This rebase is raw! It's absolutely raw!'",
  "NASA Alert: Space mission aborted due to a minor head parsing error.",
  "FBI Investigation: Suspect was found deploying unencrypted early reverts.",
  "Dark Web Resume Auction: Current bid is $0.00, and the buyer is requesting a refund.",
  "Gordon Ramsay Meltdown: 'This hash is raw! It's absolutely raw!'",
  "Elon Musk Tweet: 'Just deleted the entire head pipeline, was completely useless.'",
  "FBI Investigation: Suspect was found deploying unencrypted messy masters.",
  "Matrix Glitch: You copy-pasted a template and now the server believes it is a real founder.",
  "Steam Achievement Unlocked: Successfully crashed a hello-world app on a $10,000 server.",
  "FBI Investigation: Suspect was found deploying unencrypted broken heads.",
  "FBI Investigation: Suspect was found deploying unencrypted conflicting logs.",
  "Gordon Ramsay Meltdown: 'This log is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This revert is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This master is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This commit is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This branch is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This conflict is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted untested rebases.",
  "Gordon Ramsay Meltdown: 'This merge is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This head is raw! It's absolutely raw!'"
];
