// ES Module exports for github_issue roast format
export const titles = [
  "PR Not Found",
  "The Branch tragedy",
  "The Repo tragedy",
  "Failed to compile: README",
  "Incident Report: Cloned Issue",
  "Deprecated PR Error",
  "Failed to compile: PR",
  "Absolute Spammy architecture",
  "Fork-heavy Repo Error",
  "Action Not Found",
  "Critical Commit failure",
  "Absolute Cloned architecture",
  "Malformed Workflow Loop",
  "Failed to compile: Linter",
  "The Issue tragedy",
  "The Commit tragedy",
  "Untested Commit Loop",
  "Malformed README Loop",
  "Incident Report: Fork-heavy Commit",
  "Failed to compile: Action",
  "Linter conflict detected",
  "NullPointerForkException",
  "Issue conflict detected",
  "Commit conflict detected",
  "README conflict detected",
  "Critical Workflow failure",
  "Failed to compile: Issue",
  "Incident Report: Stale Issue",
  "Incident Report: Broken Action",
  "NullPointerRepoException",
  "Repo Not Found",
  "NullPointerREADMEException",
  "Absolute Broken architecture",
  "Cloned Action Loop",
  "NullPointerCommitException",
  "Workflow conflict detected",
  "Fork conflict detected",
  "Absolute Malformed architecture",
  "Spammy Fork Loop",
  "Cloned Commit Loop",
  "Absolute Deprecated architecture",
  "Stale Fork Loop",
  "Fork Not Found",
  "Stale Fork Error",
  "Cloned Branch Error",
  "Branch Not Found",
  "Absolute Untested architecture",
  "The Workflow tragedy",
  "Stale Repo Loop",
  "The PR tragedy",
  "Stale Action Error",
  "PR conflict detected",
  "Linter Not Found",
  "Incident Report: Broken Repo",
  "Critical Issue failure",
  "Incident Report: Deprecated Issue",
  "Critical Repo failure",
  "Fork-heavy Fork Error",
  "Failed to compile: Workflow",
  "Absolute Fork-heavy architecture",
  "Broken README Error",
  "Fork-heavy Linter Loop",
  "Issue Not Found",
  "NullPointerBranchException",
  "Incident Report: Cloned Branch",
  "NullPointerActionException",
  "Critical Linter failure",
  "Deprecated Workflow Error",
  "Incident Report: Stale Linter",
  "NullPointerWorkflowException",
  "Critical Fork failure",
  "Deprecated Repo Loop",
  "NullPointerIssueException",
  "Deprecated README Loop",
  "Failed to compile: Branch",
  "Incident Report: Broken Fork",
  "Failed to compile: Repo",
  "Incident Report: Spammy Commit",
  "Incident Report: Spammy Branch",
  "Incident Report: Spammy Linter",
  "Spammy Branch Error",
  "NullPointerPRException",
  "Spammy Commit Loop",
  "Spammy Issue Loop",
  "Spammy Repo Loop",
  "Incident Report: Fork-heavy Action",
  "Untested Linter Error",
  "Incident Report: Untested Issue",
  "Fork-heavy Commit Loop",
  "NullPointerLinterException",
  "Incident Report: Broken README",
  "Deprecated Linter Error",
  "Spammy README Loop",
  "The README tragedy",
  "Malformed Action Error",
  "Incident Report: Untested Fork",
  "The Fork tragedy",
  "Spammy Repo Error",
  "Broken Repo Error",
  "Critical README failure"
];

export const openings = [
  "A review was filed regarding a malformed branch.",
  "The team has initiated audit for the candidate's workflow setup.",
  "Scanning candidate profile for cloned workflows...",
  "Alert: The candidate spent three months trying to forgot tests with merge conflicts.",
  "Initial evaluation shows the developer decided to force-pushed to main at 3 AM.",
  "Initial evaluation shows the developer decided to deleted configuration triggering warnings.",
  "Recruiters reported a case of malformed repo design.",
  "A review was filed regarding a malformed linter.",
  "Alert: The candidate spent three months trying to cloned a template causing crash.",
  "Alert: The candidate spent three months trying to force-pushed to main triggering warnings.",
  "We checked the history and found a malformed repo log.",
  "Scanning candidate profile for untested workflows...",
  "We checked the history and found a fork-heavy repo log.",
  "Scanning candidate profile for cloned forks...",
  "Scanning candidate profile for stale forks...",
  "Alert: The candidate spent three months trying to ignored linter alerts triggering warnings.",
  "Recruiters reported a case of malformed linter design.",
  "Recruiters reported a case of cloned commit design.",
  "We checked the history and found a deprecated PR log.",
  "A review was filed regarding a malformed commit.",
  "A review was filed regarding a fork-heavy linter.",
  "Scanning candidate profile for stale READMEs...",
  "A review was filed regarding a untested issue.",
  "Recruiters reported a case of deprecated branch design.",
  "A review was filed regarding a untested linter.",
  "Scanning candidate profile for untested forks...",
  "Warning: System flagged an attempt to forgot tests causing crash.",
  "Alert: The candidate spent three months trying to force-pushed to main with merge conflicts.",
  "Warning: System flagged an attempt to forgot tests with merge conflicts.",
  "Scanning candidate profile for broken commits...",
  "We checked the history and found a malformed README log.",
  "Warning: System flagged an attempt to deleted configuration triggering warnings.",
  "A review was filed regarding a spammy linter.",
  "Warning: System flagged an attempt to force-pushed to main without approval.",
  "Scanning candidate profile for cloned actions...",
  "Warning: System flagged an attempt to cloned a template triggering warnings.",
  "Scanning candidate profile for spammy forks...",
  "Warning: System flagged an attempt to forgot tests without approval.",
  "Scanning candidate profile for stale PRs...",
  "Initial evaluation shows the developer decided to cloned a template triggering warnings.",
  "Alert: The candidate spent three months trying to deleted configuration with merge conflicts.",
  "A review was filed regarding a deprecated workflow.",
  "Scanning candidate profile for deprecated issues...",
  "Initial evaluation shows the developer decided to forgot tests without approval.",
  "Scanning candidate profile for malformed repos...",
  "Warning: System flagged an attempt to cloned a template at 3 AM.",
  "Recruiters reported a case of malformed fork design.",
  "Recruiters reported a case of stale issue design.",
  "Recruiters reported a case of malformed README design.",
  "Recruiters reported a case of stale action design.",
  "Alert: The candidate spent three months trying to deleted configuration triggering warnings.",
  "We checked the history and found a untested fork log.",
  "A review was filed regarding a deprecated README.",
  "Warning: System flagged an attempt to deleted configuration without approval.",
  "Initial evaluation shows the developer decided to cloned a template causing crash.",
  "Initial evaluation shows the developer decided to ignored linter alerts at 3 AM.",
  "Warning: System flagged an attempt to cloned a template causing crash.",
  "A review was filed regarding a malformed README.",
  "Initial evaluation shows the developer decided to ignored linter alerts with merge conflicts.",
  "Warning: System flagged an attempt to cloned a template without approval.",
  "A review was filed regarding a fork-heavy README.",
  "Alert: The candidate spent three months trying to force-pushed to main without approval.",
  "Scanning candidate profile for deprecated branchs...",
  "A review was filed regarding a stale linter.",
  "Recruiters reported a case of spammy repo design.",
  "Warning: System flagged an attempt to ignored linter alerts causing crash.",
  "Scanning candidate profile for fork-heavy READMEs...",
  "Alert: The candidate spent three months trying to forgot tests without approval.",
  "A review was filed regarding a broken commit.",
  "We checked the history and found a untested issue log.",
  "We checked the history and found a stale issue log.",
  "A review was filed regarding a untested README.",
  "Scanning candidate profile for malformed workflows...",
  "Recruiters reported a case of fork-heavy commit design.",
  "Initial evaluation shows the developer decided to force-pushed to main with merge conflicts.",
  "We checked the history and found a malformed branch log.",
  "A review was filed regarding a spammy README.",
  "Scanning candidate profile for spammy branchs...",
  "We checked the history and found a spammy linter log.",
  "Warning: System flagged an attempt to deleted configuration with merge conflicts.",
  "Recruiters reported a case of malformed action design.",
  "Recruiters reported a case of cloned linter design.",
  "Recruiters reported a case of deprecated fork design."
];

export const findings = [
  "{{education}} is listed, but they still managed to deploy a spammy fork to production.",
  "Listed {{skill}} as a primary competency, but the evidence points to a fork-heavy issue.",
  "Obtained {{certification}} which apparently teaches how to forgot tests without approval.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to cloned a template without approval.",
  "Obtained {{certification}} which apparently teaches how to deleted configuration at 3 AM.",
  "{{github}} contains more malformed issues than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to ignored linter alerts without approval.",
  "Obtained {{certification}} which apparently teaches how to force-pushed to main at 3 AM.",
  "{{candidateName}} has spent three weeks optimizing a commit while completely ignoring {{missingSection}}.",
  "While debugging {{project}}, we found a spammy logic loop related to {{language}} features.",
  "The candidate claims {{framework}} experience, but their repository is just a fork-heavy clone that has been abandoned.",
  "Failed to configure {{project}} because {{candidateName}} decided to cloned a template causing crash.",
  "For {{experience}}, the primary contribution was writing a untested config for a PR.",
  "Failed to configure {{project}} because {{candidateName}} decided to force-pushed to main without approval.",
  "A security audit on {{github}} detected a plain-text database password inside a untested issue.",
  "{{github}} contains more untested actions than original code.",
  "Listed {{skill}} as a primary competency, but the evidence points to a deprecated fork.",
  "{{github}} contains more deprecated linters than original code.",
  "{{github}} contains more fork-heavy actions than original code.",
  "Listed {{skill}} as a primary competency, but the evidence points to a stale commit.",
  "{{education}} is listed, but they still managed to deploy a untested repo to production.",
  "Obtained {{certification}} which apparently teaches how to force-pushed to main with merge conflicts.",
  "Listed {{skill}} as a primary competency, but the evidence points to a broken README.",
  "Failed to configure {{project}} because {{candidateName}} decided to cloned a template triggering warnings.",
  "{{achievement}} was highlighted, but the git logs show they only managed to deleted configuration at 3 AM.",
  "For {{experience}}, the primary contribution was writing a spammy config for a fork.",
  "For {{experience}}, the primary contribution was writing a malformed config for a action.",
  "Failed to configure {{project}} because {{candidateName}} decided to cloned a template without approval.",
  "Obtained {{certification}} which apparently teaches how to cloned a template without approval.",
  "Obtained {{certification}} which apparently teaches how to ignored linter alerts triggering warnings.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to cloned a template causing crash.",
  "Failed to configure {{project}} because {{candidateName}} decided to force-pushed to main causing crash.",
  "Failed to configure {{project}} because {{candidateName}} decided to deleted configuration triggering warnings.",
  "Listed {{skill}} as a primary competency, but the evidence points to a untested PR.",
  "A security audit on {{github}} detected a plain-text database password inside a cloned linter.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ignored linter alerts without approval.",
  "{{achievement}} was highlighted, but the git logs show they only managed to forgot tests with merge conflicts.",
  "{{education}} is listed, but they still managed to deploy a malformed action to production.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to force-pushed to main with merge conflicts.",
  "{{achievement}} was highlighted, but the git logs show they only managed to cloned a template without approval.",
  "Obtained {{certification}} which apparently teaches how to ignored linter alerts without approval.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to cloned a template triggering warnings.",
  "{{achievement}} was highlighted, but the git logs show they only managed to force-pushed to main at 3 AM.",
  "For {{experience}}, the primary contribution was writing a stale config for a workflow.",
  "Failed to configure {{project}} because {{candidateName}} decided to force-pushed to main triggering warnings.",
  "{{github}} contains more stale PRs than original code.",
  "Listed {{skill}} as a primary competency, but the evidence points to a cloned repo.",
  "Obtained {{certification}} which apparently teaches how to cloned a template with merge conflicts.",
  "{{github}} contains more spammy PRs than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a malformed repo.",
  "{{github}} contains more broken linters than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to forgot tests triggering warnings.",
  "{{achievement}} was highlighted, but the git logs show they only managed to cloned a template triggering warnings.",
  "{{github}} contains more broken PRs than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ignored linter alerts triggering warnings.",
  "For {{experience}}, the primary contribution was writing a deprecated config for a README.",
  "{{achievement}} was highlighted, but the git logs show they only managed to forgot tests causing crash.",
  "A security audit on {{github}} detected a plain-text database password inside a stale fork.",
  "{{github}} contains more stale forks than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to ignored linter alerts causing crash.",
  "For {{experience}}, the primary contribution was writing a cloned config for a branch.",
  "Obtained {{certification}} which apparently teaches how to cloned a template causing crash.",
  "Listed {{skill}} as a primary competency, but the evidence points to a spammy branch.",
  "Failed to configure {{project}} because {{candidateName}} decided to deleted configuration without approval.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to deleted configuration at 3 AM.",
  "{{github}} contains more cloned forks than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to force-pushed to main without approval.",
  "While debugging {{project}}, we found a fork-heavy logic loop related to {{language}} features.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to force-pushed to main triggering warnings.",
  "Failed to configure {{project}} because {{candidateName}} decided to forgot tests causing crash.",
  "{{github}} contains more broken commits than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to cloned a template causing crash.",
  "Failed to configure {{project}} because {{candidateName}} decided to deleted configuration causing crash.",
  "{{education}} is listed, but they still managed to deploy a deprecated issue to production.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ignored linter alerts triggering warnings.",
  "{{github}} contains more stale actions than original code.",
  "Obtained {{certification}} which apparently teaches how to forgot tests with merge conflicts.",
  "Failed to configure {{project}} because {{candidateName}} decided to forgot tests without approval.",
  "Obtained {{certification}} which apparently teaches how to forgot tests triggering warnings.",
  "{{education}} is listed, but they still managed to deploy a fork-heavy branch to production.",
  "Failed to configure {{project}} because {{candidateName}} decided to force-pushed to main with merge conflicts.",
  "{{github}} contains more stale READMEs than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to cloned a template with merge conflicts.",
  "Listed {{skill}} as a primary competency, but the evidence points to a malformed action.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to forgot tests triggering warnings.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ignored linter alerts causing crash.",
  "A security audit on {{github}} detected a plain-text database password inside a spammy commit.",
  "Failed to configure {{project}} because {{candidateName}} decided to ignored linter alerts with merge conflicts.",
  "{{github}} contains more deprecated forks than original code.",
  "Obtained {{certification}} which apparently teaches how to ignored linter alerts causing crash.",
  "{{education}} is listed, but they still managed to deploy a broken linter to production.",
  "{{github}} contains more malformed repos than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a deprecated workflow.",
  "{{github}} contains more cloned branchs than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to cloned a template with merge conflicts.",
  "{{education}} is listed, but they still managed to deploy a cloned commit to production.",
  "{{github}} contains more malformed actions than original code."
];

export const punchlines = [
  "The compiler requested emotional support after reading the untested code.",
  "Even Stack Overflow has marked this workflow as off-topic.",
  "Legend says this fork-heavy commit is still running on localhost.",
  "The only thing memory-safe about this setup is that nobody has ever tried to run it.",
  "A junior developer looked at the linter and immediately went to touch grass.",
  "Legend says this deprecated branch is still running on localhost.",
  "The documentation was so empty, I had to use it as a virtual sketchbook.",
  "It did not optimize our process, but it did make the laptop fan spin like a jet engine.",
  "Legend says this cloned workflow is still running on localhost.",
  "We would deploy it to production, but our SRE team deserves to sleep at night.",
  "Legend says this cloned issue is still running on localhost.",
  "The compiler requested emotional support after reading the fork-heavy code.",
  "Legend says this spammy repo is still running on localhost.",
  "Legend says this untested branch is still running on localhost.",
  "Legend says this broken fork is still running on localhost.",
  "Legend says this spammy branch is still running on localhost.",
  "Legend says this broken action is still running on localhost.",
  "Legend says this stale workflow is still running on localhost.",
  "Legend says this untested workflow is still running on localhost.",
  "Legend says this broken workflow is still running on localhost.",
  "Legend says this cloned fork is still running on localhost.",
  "Legend says this malformed fork is still running on localhost.",
  "Legend says this malformed issue is still running on localhost.",
  "Legend says this deprecated commit is still running on localhost.",
  "Legend says this untested linter is still running on localhost.",
  "Legend says this spammy workflow is still running on localhost.",
  "Legend says this broken issue is still running on localhost.",
  "Legend says this cloned README is still running on localhost.",
  "Legend says this untested issue is still running on localhost.",
  "Legend says this deprecated README is still running on localhost.",
  "Legend says this spammy linter is still running on localhost.",
  "Legend says this broken README is still running on localhost.",
  "Legend says this untested repo is still running on localhost.",
  "Legend says this malformed branch is still running on localhost.",
  "Legend says this stale branch is still running on localhost.",
  "Legend says this stale repo is still running on localhost.",
  "Legend says this malformed repo is still running on localhost.",
  "Legend says this untested README is still running on localhost.",
  "Legend says this cloned action is still running on localhost.",
  "Legend says this cloned repo is still running on localhost.",
  "Legend says this cloned commit is still running on localhost.",
  "Legend says this malformed commit is still running on localhost.",
  "Legend says this untested fork is still running on localhost.",
  "Legend says this broken linter is still running on localhost.",
  "Legend says this spammy commit is still running on localhost.",
  "Legend says this broken commit is still running on localhost.",
  "Legend says this untested action is still running on localhost.",
  "Legend says this deprecated issue is still running on localhost.",
  "Legend says this deprecated linter is still running on localhost.",
  "Legend says this stale commit is still running on localhost.",
  "Legend says this spammy issue is still running on localhost.",
  "Legend says this cloned branch is still running on localhost.",
  "Legend says this malformed linter is still running on localhost.",
  "Legend says this spammy README is still running on localhost.",
  "Legend says this spammy action is still running on localhost.",
  "This is a classic example of a malformed action disaster.",
  "This is a classic example of a cloned repo disaster.",
  "This is a classic example of a broken fork disaster.",
  "This is a classic example of a stale workflow disaster.",
  "This is a classic example of a fork-heavy action disaster.",
  "This is a classic example of a spammy commit disaster.",
  "This is a classic example of a untested repo disaster.",
  "This is a classic example of a deprecated branch disaster.",
  "This is a classic example of a cloned commit disaster.",
  "This is a classic example of a stale action disaster.",
  "This is a classic example of a broken issue disaster.",
  "This is a classic example of a stale branch disaster.",
  "This is a classic example of a malformed fork disaster.",
  "This is a classic example of a cloned fork disaster.",
  "This is a classic example of a malformed repo disaster.",
  "This is a classic example of a fork-heavy README disaster.",
  "This is a classic example of a spammy fork disaster.",
  "This is a classic example of a broken linter disaster.",
  "This is a classic example of a deprecated fork disaster.",
  "This is a classic example of a spammy workflow disaster.",
  "This is a classic example of a deprecated repo disaster.",
  "This is a classic example of a spammy branch disaster.",
  "This is a classic example of a deprecated commit disaster.",
  "This is a classic example of a deprecated issue disaster.",
  "This is a classic example of a cloned README disaster.",
  "This is a classic example of a spammy linter disaster.",
  "This is a classic example of a stale commit disaster.",
  "This is a classic example of a untested README disaster.",
  "This is a classic example of a malformed branch disaster.",
  "This is a classic example of a stale issue disaster.",
  "This is a classic example of a spammy action disaster.",
  "This is a classic example of a deprecated action disaster.",
  "This is a classic example of a broken action disaster.",
  "This is a classic example of a untested linter disaster.",
  "This is a classic example of a fork-heavy issue disaster."
];

export const verdicts = [
  "Verdict: Issue is completely unmergeable.",
  "Closed as deprecated duplicate.",
  "Rejected on first principles of PR organization.",
  "Return after touching actual production servers.",
  "PR ignored linter alerts due to malformed implementation.",
  "PR force-pushed to main due to untested implementation.",
  "Verdict: Linter is completely unmergeable.",
  "Closed as fork-heavy duplicate.",
  "Request changes on the cloned PR.",
  "Verdict: PR is completely unmergeable.",
  "Request changes on the untested branch.",
  "Closed as stale duplicate.",
  "Needs more commits and fewer explanations.",
  "PR ignored linter alerts due to fork-heavy implementation.",
  "Closed as malformed duplicate.",
  "Closed as broken duplicate.",
  "Request changes on the malformed fork.",
  "PR force-pushed to main due to deprecated implementation.",
  "Closed as spammy duplicate.",
  "PR forgot tests due to malformed implementation.",
  "Request changes on the stale commit.",
  "PR cloned a template due to fork-heavy implementation.",
  "Ship blocked by broken check failures.",
  "Request changes on the broken issue.",
  "Request changes on the spammy linter.",
  "Verdict: Branch is completely unmergeable.",
  "PR forgot tests due to broken implementation.",
  "Ship blocked by deprecated check failures.",
  "PR force-pushed to main due to stale implementation.",
  "PR deleted configuration due to deprecated implementation.",
  "PR cloned a template due to untested implementation.",
  "Request changes on the malformed workflow.",
  "Ship blocked by fork-heavy check failures.",
  "Request changes on the malformed commit.",
  "Ship blocked by spammy check failures.",
  "Verdict: Workflow is completely unmergeable.",
  "PR cloned a template due to spammy implementation.",
  "Closed as untested duplicate.",
  "PR ignored linter alerts due to untested implementation.",
  "Ship blocked by untested check failures.",
  "Request changes on the malformed linter.",
  "Verdict: Fork is completely unmergeable.",
  "Request changes on the broken README.",
  "Ship blocked by cloned check failures.",
  "Ship blocked by stale check failures.",
  "Verdict: Repo is completely unmergeable.",
  "Ship blocked by malformed check failures.",
  "Verdict: README is completely unmergeable.",
  "Request changes on the stale issue.",
  "Request changes on the spammy fork.",
  "Request changes on the broken commit.",
  "Closed as cloned duplicate.",
  "PR ignored linter alerts due to broken implementation.",
  "Request changes on the spammy README.",
  "PR forgot tests due to fork-heavy implementation.",
  "PR force-pushed to main due to spammy implementation.",
  "Request changes on the stale branch.",
  "Request changes on the deprecated fork.",
  "Request changes on the spammy branch.",
  "Request changes on the untested linter.",
  "Verdict: Commit is completely unmergeable.",
  "PR ignored linter alerts due to cloned implementation.",
  "PR forgot tests due to untested implementation.",
  "PR force-pushed to main due to cloned implementation.",
  "Request changes on the deprecated commit.",
  "Request changes on the untested README.",
  "Request changes on the malformed README.",
  "PR force-pushed to main due to malformed implementation.",
  "Verdict: Action is completely unmergeable.",
  "Request changes on the fork-heavy README.",
  "Request changes on the stale linter.",
  "PR force-pushed to main due to fork-heavy implementation.",
  "Request changes on the deprecated repo.",
  "Request changes on the fork-heavy workflow.",
  "PR forgot tests due to cloned implementation.",
  "Request changes on the spammy action.",
  "PR ignored linter alerts due to spammy implementation.",
  "Request changes on the deprecated issue.",
  "Request changes on the spammy workflow.",
  "Request changes on the fork-heavy action.",
  "PR cloned a template due to malformed implementation.",
  "PR ignored linter alerts due to deprecated implementation.",
  "Request changes on the fork-heavy linter.",
  "Request changes on the fork-heavy branch.",
  "Request changes on the untested issue."
];

export const easterEggs = [
  "Matrix Glitch: You copy-pasted a template and now the server believes it is a real founder.",
  "NASA Alert: Space mission aborted due to a minor linter parsing error.",
  "Steam Achievement Unlocked: Successfully crashed a hello-world app on a $10,000 server.",
  "Gordon Ramsay Meltdown: 'This action is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted stale linters.",
  "Gordon Ramsay Meltdown: 'This issue is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This linter is raw! It's absolutely raw!'",
  "Elon Musk Tweet: 'Just deleted the entire issue pipeline, was completely useless.'",
  "Dark Web Resume Auction: Current bid is $0.00, and the buyer is requesting a refund.",
  "FBI Investigation: Suspect was found deploying unencrypted broken actions.",
  "FBI Investigation: Suspect was found deploying unencrypted untested READMEs.",
  "FBI Investigation: Suspect was found deploying unencrypted cloned workflows.",
  "FBI Investigation: Suspect was found deploying unencrypted fork-heavy actions.",
  "FBI Investigation: Suspect was found deploying unencrypted malformed issues.",
  "Gordon Ramsay Meltdown: 'This repo is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This branch is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This workflow is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This README is raw! It's absolutely raw!'"
];
