// ES Module exports for google_search roast format
export const titles = [
  "Absolute Sketchy architecture",
  "NullPointerTutorialException",
  "Critical Forum failure",
  "Failed to compile: Video",
  "Empty Tutorial Loop",
  "Failed to compile: Tutorial",
  "Failed to compile: Answers",
  "The Query tragedy",
  "NullPointerVideoException",
  "Absolute Simple architecture",
  "Answers Not Found",
  "Forum conflict detected",
  "NullPointerLinksException",
  "Common Query Error",
  "Search conflict detected",
  "Critical Links failure",
  "Absolute Common architecture",
  "Incident Report: Obvious Tutorial",
  "Critical Video failure",
  "NullPointerSearchException",
  "Tutorial Not Found",
  "Autocomplete Not Found",
  "Sketchy Answers Loop",
  "NullPointerQuestionException",
  "Video conflict detected",
  "Links Not Found",
  "Incident Report: Low-quality Query",
  "The Search tragedy",
  "The Tutorial tragedy",
  "Incident Report: Sketchy Links",
  "Obvious Links Loop",
  "Critical Query failure",
  "Incident Report: Obvious Links",
  "Critical Question failure",
  "Simple Tutorial Loop",
  "Failed to compile: Forum",
  "Sketchy Video Loop",
  "Failed to compile: Links",
  "Incident Report: Basic Autocomplete",
  "Autocomplete conflict detected",
  "Answers conflict detected",
  "Empty Search Loop",
  "The Links tragedy",
  "Absolute Low-quality architecture",
  "Incident Report: Common Search",
  "Query conflict detected",
  "NullPointerAutocompleteException",
  "Obvious Autocomplete Loop",
  "Critical Search failure",
  "Video Not Found",
  "Question Not Found",
  "The Video tragedy",
  "Absolute Obvious architecture",
  "Common Forum Loop",
  "Basic-level Question Loop",
  "Incident Report: Basic Query",
  "NullPointerQueryException",
  "Absolute Basic-level architecture",
  "Simple Answers Error",
  "Critical Result failure",
  "Failed to compile: Autocomplete",
  "Tutorial conflict detected",
  "Failed to compile: Search",
  "Basic-level Forum Loop",
  "The Forum tragedy",
  "Result conflict detected",
  "Low-quality Tutorial Loop",
  "Incident Report: Empty Answers",
  "Sketchy Autocomplete Error",
  "Absolute Basic architecture",
  "Sketchy Autocomplete Loop",
  "Empty Query Error",
  "Basic-level Answers Error",
  "Failed to compile: Query",
  "Failed to compile: Result",
  "Low-quality Result Loop",
  "Obvious Tutorial Loop",
  "Simple Video Loop",
  "Search Not Found",
  "Query Not Found",
  "Sketchy Answers Error",
  "Question conflict detected",
  "Incident Report: Low-quality Tutorial",
  "Obvious Question Error",
  "Incident Report: Sketchy Answers",
  "The Autocomplete tragedy",
  "Critical Autocomplete failure",
  "Basic Question Loop",
  "Failed to compile: Question",
  "The Result tragedy",
  "Incident Report: Basic Links",
  "NullPointerResultException",
  "Low-quality Video Loop",
  "Basic-level Forum Error",
  "Low-quality Links Error",
  "Simple Question Error",
  "Links conflict detected",
  "Common Result Error",
  "Low-quality Autocomplete Error",
  "Result Not Found"
];

export const openings = [
  "Initial evaluation shows the developer decided to scrolled search page to avoid reading docs.",
  "Warning: System flagged an attempt to searched generic query to avoid reading docs.",
  "A review was filed regarding a obvious question.",
  "Initial evaluation shows the developer decided to asked basic question for the third time.",
  "Warning: System flagged an attempt to clicked sketchy link on page 2 of Google.",
  "Recruiters reported a case of sketchy query design.",
  "Recruiters reported a case of simple query design.",
  "We checked the history and found a simple links log.",
  "We checked the history and found a low-quality autocomplete log.",
  "The team has initiated audit for the candidate's tutorial setup.",
  "Scanning candidate profile for basic-level results...",
  "Warning: System flagged an attempt to browsed video tutorial without finding answers.",
  "Alert: The candidate spent three months trying to scrolled search page on page 2 of Google.",
  "We checked the history and found a empty search log.",
  "Initial evaluation shows the developer decided to scrolled search page on sketchy helper forum.",
  "Scanning candidate profile for basic tutorials...",
  "Alert: The candidate spent three months trying to searched generic query to avoid reading docs.",
  "Warning: System flagged an attempt to browsed video tutorial for the third time.",
  "Scanning candidate profile for obvious querys...",
  "Recruiters reported a case of low-quality forum design.",
  "Warning: System flagged an attempt to asked basic question to avoid reading docs.",
  "Scanning candidate profile for basic autocompletes...",
  "Initial evaluation shows the developer decided to asked basic question on page 2 of Google.",
  "Initial evaluation shows the developer decided to browsed video tutorial on page 2 of Google.",
  "Warning: System flagged an attempt to clicked sketchy link without finding answers.",
  "Warning: System flagged an attempt to asked basic question without finding answers.",
  "Scanning candidate profile for sketchy tutorials...",
  "Recruiters reported a case of basic-level query design.",
  "We checked the history and found a basic video log.",
  "A review was filed regarding a sketchy query.",
  "Recruiters reported a case of basic-level result design.",
  "Recruiters reported a case of low-quality video design.",
  "A review was filed regarding a common links.",
  "A review was filed regarding a empty question.",
  "Scanning candidate profile for low-quality forums...",
  "Scanning candidate profile for sketchy autocompletes...",
  "A review was filed regarding a low-quality autocomplete.",
  "Warning: System flagged an attempt to browsed video tutorial on sketchy helper forum.",
  "Warning: System flagged an attempt to searched generic query on page 2 of Google.",
  "A review was filed regarding a low-quality result.",
  "Alert: The candidate spent three months trying to scrolled search page without finding answers.",
  "Initial evaluation shows the developer decided to asked basic question to avoid reading docs.",
  "A review was filed regarding a low-quality query.",
  "Scanning candidate profile for common videos...",
  "Alert: The candidate spent three months trying to searched generic query without finding answers.",
  "We checked the history and found a basic-level search log.",
  "Recruiters reported a case of obvious search design.",
  "A review was filed regarding a common forum.",
  "We checked the history and found a basic query log.",
  "We checked the history and found a basic answers log.",
  "A review was filed regarding a simple forum.",
  "A review was filed regarding a low-quality tutorial.",
  "We checked the history and found a obvious forum log.",
  "Alert: The candidate spent three months trying to clicked sketchy link on sketchy helper forum.",
  "Alert: The candidate spent three months trying to asked basic question to avoid reading docs.",
  "Recruiters reported a case of sketchy result design.",
  "A review was filed regarding a obvious links.",
  "Scanning candidate profile for common querys...",
  "A review was filed regarding a low-quality video.",
  "Scanning candidate profile for empty answerss...",
  "We checked the history and found a common tutorial log.",
  "A review was filed regarding a sketchy links.",
  "Scanning candidate profile for basic-level querys...",
  "A review was filed regarding a common result.",
  "Recruiters reported a case of sketchy answers design.",
  "A review was filed regarding a simple tutorial.",
  "A review was filed regarding a low-quality question.",
  "Warning: System flagged an attempt to scrolled search page for the third time.",
  "We checked the history and found a obvious video log.",
  "We checked the history and found a empty video log.",
  "Initial evaluation shows the developer decided to searched generic query on page 2 of Google.",
  "Alert: The candidate spent three months trying to asked basic question without finding answers.",
  "Initial evaluation shows the developer decided to clicked sketchy link to avoid reading docs.",
  "Scanning candidate profile for simple questions...",
  "We checked the history and found a sketchy tutorial log.",
  "Alert: The candidate spent three months trying to asked basic question for the third time.",
  "Warning: System flagged an attempt to scrolled search page on page 2 of Google.",
  "We checked the history and found a empty tutorial log.",
  "Scanning candidate profile for basic-level linkss...",
  "Recruiters reported a case of obvious result design.",
  "We checked the history and found a obvious links log.",
  "Scanning candidate profile for empty linkss...",
  "Warning: System flagged an attempt to searched generic query without finding answers.",
  "We checked the history and found a simple tutorial log.",
  "We checked the history and found a common forum log.",
  "Warning: System flagged an attempt to asked basic question on sketchy helper forum.",
  "Alert: The candidate spent three months trying to clicked sketchy link without finding answers.",
  "Scanning candidate profile for low-quality linkss...",
  "Alert: The candidate spent three months trying to searched generic query for the third time.",
  "Alert: The candidate spent three months trying to scrolled search page for the third time."
];

export const findings = [
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to browsed video tutorial without finding answers.",
  "{{candidateName}} has spent three weeks optimizing a links while completely ignoring {{missingSection}}.",
  "{{achievement}} was highlighted, but the git logs show they only managed to clicked sketchy link without finding answers.",
  "Failed to configure {{project}} because {{candidateName}} decided to browsed video tutorial on page 2 of Google.",
  "Listed {{skill}} as a primary competency, but the evidence points to a obvious forum.",
  "A security audit on {{github}} detected a plain-text database password inside a obvious autocomplete.",
  "{{achievement}} was highlighted, but the git logs show they only managed to scrolled search page on sketchy helper forum.",
  "{{achievement}} was highlighted, but the git logs show they only managed to clicked sketchy link for the third time.",
  "The candidate claims {{framework}} experience, but their repository is just a basic-level clone that has been abandoned.",
  "{{education}} is listed, but they still managed to deploy a basic forum to production.",
  "For {{experience}}, the primary contribution was writing a obvious config for a query.",
  "Failed to configure {{project}} because {{candidateName}} decided to searched generic query on sketchy helper forum.",
  "{{achievement}} was highlighted, but the git logs show they only managed to clicked sketchy link on sketchy helper forum.",
  "While debugging {{project}}, we found a simple logic loop related to {{language}} features.",
  "{{education}} is listed, but they still managed to deploy a low-quality autocomplete to production.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to scrolled search page on page 2 of Google.",
  "A security audit on {{github}} detected a plain-text database password inside a empty query.",
  "Obtained {{certification}} which apparently teaches how to clicked sketchy link to avoid reading docs.",
  "{{github}} contains more sketchy tutorials than original code.",
  "Obtained {{certification}} which apparently teaches how to searched generic query without finding answers.",
  "{{achievement}} was highlighted, but the git logs show they only managed to browsed video tutorial for the third time.",
  "Failed to configure {{project}} because {{candidateName}} decided to scrolled search page on page 2 of Google.",
  "Obtained {{certification}} which apparently teaches how to scrolled search page on sketchy helper forum.",
  "{{education}} is listed, but they still managed to deploy a simple result to production.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to browsed video tutorial on page 2 of Google.",
  "{{github}} contains more basic searchs than original code.",
  "For {{experience}}, the primary contribution was writing a low-quality config for a query.",
  "For {{experience}}, the primary contribution was writing a simple config for a search.",
  "Obtained {{certification}} which apparently teaches how to scrolled search page to avoid reading docs.",
  "Obtained {{certification}} which apparently teaches how to asked basic question on page 2 of Google.",
  "{{education}} is listed, but they still managed to deploy a obvious answers to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to asked basic question on sketchy helper forum.",
  "Listed {{skill}} as a primary competency, but the evidence points to a simple result.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to searched generic query to avoid reading docs.",
  "Obtained {{certification}} which apparently teaches how to searched generic query for the third time.",
  "For {{experience}}, the primary contribution was writing a basic-level config for a video.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to asked basic question to avoid reading docs.",
  "{{github}} contains more low-quality searchs than original code.",
  "Obtained {{certification}} which apparently teaches how to clicked sketchy link on page 2 of Google.",
  "Obtained {{certification}} which apparently teaches how to searched generic query on page 2 of Google.",
  "The candidate claims {{framework}} experience, but their repository is just a low-quality clone that has been abandoned.",
  "{{achievement}} was highlighted, but the git logs show they only managed to searched generic query to avoid reading docs.",
  "Listed {{skill}} as a primary competency, but the evidence points to a common question.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to browsed video tutorial to avoid reading docs.",
  "Failed to configure {{project}} because {{candidateName}} decided to scrolled search page for the third time.",
  "Failed to configure {{project}} because {{candidateName}} decided to asked basic question for the third time.",
  "Listed {{skill}} as a primary competency, but the evidence points to a sketchy query.",
  "{{achievement}} was highlighted, but the git logs show they only managed to browsed video tutorial on page 2 of Google.",
  "Obtained {{certification}} which apparently teaches how to searched generic query on sketchy helper forum.",
  "Listed {{skill}} as a primary competency, but the evidence points to a basic-level video.",
  "For {{experience}}, the primary contribution was writing a common config for a links.",
  "Obtained {{certification}} which apparently teaches how to asked basic question on sketchy helper forum.",
  "Obtained {{certification}} which apparently teaches how to browsed video tutorial without finding answers.",
  "For {{experience}}, the primary contribution was writing a basic config for a question.",
  "Obtained {{certification}} which apparently teaches how to clicked sketchy link on sketchy helper forum.",
  "{{achievement}} was highlighted, but the git logs show they only managed to browsed video tutorial to avoid reading docs.",
  "{{github}} contains more simple answerss than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to browsed video tutorial for the third time.",
  "{{github}} contains more sketchy autocompletes than original code.",
  "{{github}} contains more empty answerss than original code.",
  "{{education}} is listed, but they still managed to deploy a common query to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to asked basic question for the third time.",
  "{{github}} contains more sketchy answerss than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a basic-level search.",
  "Failed to configure {{project}} because {{candidateName}} decided to asked basic question on sketchy helper forum.",
  "{{education}} is listed, but they still managed to deploy a sketchy video to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to asked basic question to avoid reading docs.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to asked basic question without finding answers.",
  "{{github}} contains more basic querys than original code.",
  "Obtained {{certification}} which apparently teaches how to clicked sketchy link for the third time.",
  "Failed to configure {{project}} because {{candidateName}} decided to searched generic query to avoid reading docs.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to clicked sketchy link without finding answers.",
  "{{education}} is listed, but they still managed to deploy a basic-level search to production.",
  "Failed to configure {{project}} because {{candidateName}} decided to browsed video tutorial to avoid reading docs.",
  "Failed to configure {{project}} because {{candidateName}} decided to clicked sketchy link without finding answers.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to scrolled search page without finding answers.",
  "While debugging {{project}}, we found a low-quality logic loop related to {{language}} features.",
  "A security audit on {{github}} detected a plain-text database password inside a low-quality result.",
  "Obtained {{certification}} which apparently teaches how to browsed video tutorial for the third time.",
  "Failed to configure {{project}} because {{candidateName}} decided to scrolled search page without finding answers.",
  "Obtained {{certification}} which apparently teaches how to browsed video tutorial on sketchy helper forum.",
  "Failed to configure {{project}} because {{candidateName}} decided to clicked sketchy link on sketchy helper forum.",
  "Failed to configure {{project}} because {{candidateName}} decided to clicked sketchy link to avoid reading docs.",
  "Failed to configure {{project}} because {{candidateName}} decided to scrolled search page to avoid reading docs.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to asked basic question for the third time.",
  "{{achievement}} was highlighted, but the git logs show they only managed to scrolled search page without finding answers.",
  "Failed to configure {{project}} because {{candidateName}} decided to scrolled search page on sketchy helper forum.",
  "{{achievement}} was highlighted, but the git logs show they only managed to searched generic query for the third time.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to scrolled search page on sketchy helper forum.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to clicked sketchy link for the third time.",
  "{{achievement}} was highlighted, but the git logs show they only managed to browsed video tutorial without finding answers.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to asked basic question on page 2 of Google.",
  "A security audit on {{github}} detected a plain-text database password inside a basic forum.",
  "{{achievement}} was highlighted, but the git logs show they only managed to scrolled search page for the third time.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to clicked sketchy link on page 2 of Google.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to scrolled search page to avoid reading docs.",
  "Failed to configure {{project}} because {{candidateName}} decided to searched generic query on page 2 of Google.",
  "Failed to configure {{project}} because {{candidateName}} decided to searched generic query without finding answers.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to asked basic question on sketchy helper forum.",
  "{{github}} contains more common searchs than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to searched generic query on sketchy helper forum.",
  "Failed to configure {{project}} because {{candidateName}} decided to asked basic question without finding answers.",
  "Obtained {{certification}} which apparently teaches how to asked basic question for the third time.",
  "{{github}} contains more basic-level answerss than original code.",
  "{{github}} contains more sketchy forums than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to browsed video tutorial on sketchy helper forum.",
  "{{github}} contains more common linkss than original code.",
  "Obtained {{certification}} which apparently teaches how to asked basic question without finding answers.",
  "{{achievement}} was highlighted, but the git logs show they only managed to asked basic question on page 2 of Google.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to clicked sketchy link on sketchy helper forum.",
  "Listed {{skill}} as a primary competency, but the evidence points to a basic answers.",
  "For {{experience}}, the primary contribution was writing a empty config for a tutorial.",
  "{{github}} contains more obvious querys than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a simple question.",
  "Failed to configure {{project}} because {{candidateName}} decided to clicked sketchy link on page 2 of Google.",
  "Listed {{skill}} as a primary competency, but the evidence points to a empty links.",
  "Failed to configure {{project}} because {{candidateName}} decided to searched generic query for the third time."
];

export const punchlines = [
  "The compiler requested emotional support after reading the low-quality code.",
  "It did not optimize our process, but it did make the laptop fan spin like a jet engine.",
  "Even Stack Overflow has marked this question as off-topic.",
  "The only thing memory-safe about this setup is that nobody has ever tried to run it.",
  "Legend says this obvious links is still running on localhost.",
  "Legend says this basic-level tutorial is still running on localhost.",
  "A junior developer looked at the result and immediately went to touch grass.",
  "We would deploy it to production, but our SRE team deserves to sleep at night.",
  "The compiler requested emotional support after reading the obvious code.",
  "Legend says this empty links is still running on localhost.",
  "The documentation was so empty, I had to use it as a virtual sketchbook.",
  "Legend says this sketchy tutorial is still running on localhost.",
  "Legend says this low-quality search is still running on localhost.",
  "Legend says this sketchy video is still running on localhost.",
  "Legend says this empty search is still running on localhost.",
  "The compiler requested emotional support after reading the basic-level code.",
  "Legend says this empty video is still running on localhost.",
  "Legend says this basic answers is still running on localhost.",
  "Legend says this obvious search is still running on localhost.",
  "Legend says this sketchy answers is still running on localhost.",
  "Legend says this simple query is still running on localhost.",
  "Legend says this basic question is still running on localhost.",
  "Legend says this sketchy links is still running on localhost.",
  "Legend says this simple autocomplete is still running on localhost.",
  "Legend says this common result is still running on localhost.",
  "Legend says this common forum is still running on localhost.",
  "Legend says this simple tutorial is still running on localhost.",
  "Legend says this basic forum is still running on localhost.",
  "Legend says this obvious result is still running on localhost.",
  "Legend says this simple result is still running on localhost.",
  "Legend says this sketchy question is still running on localhost.",
  "Legend says this empty query is still running on localhost.",
  "Legend says this sketchy search is still running on localhost.",
  "Legend says this simple search is still running on localhost.",
  "Legend says this common video is still running on localhost.",
  "Legend says this common tutorial is still running on localhost.",
  "Legend says this obvious tutorial is still running on localhost.",
  "Legend says this simple links is still running on localhost.",
  "Legend says this empty answers is still running on localhost.",
  "Legend says this common search is still running on localhost.",
  "Legend says this sketchy forum is still running on localhost.",
  "Legend says this empty forum is still running on localhost.",
  "Legend says this obvious query is still running on localhost.",
  "Legend says this basic search is still running on localhost.",
  "Legend says this simple forum is still running on localhost.",
  "Legend says this empty question is still running on localhost.",
  "Legend says this simple answers is still running on localhost.",
  "Legend says this common autocomplete is still running on localhost.",
  "Legend says this common query is still running on localhost.",
  "Legend says this obvious forum is still running on localhost.",
  "Legend says this sketchy result is still running on localhost.",
  "Legend says this obvious question is still running on localhost.",
  "Legend says this simple question is still running on localhost.",
  "Legend says this common answers is still running on localhost.",
  "Legend says this sketchy query is still running on localhost.",
  "Legend says this obvious answers is still running on localhost.",
  "Legend says this simple video is still running on localhost.",
  "Legend says this sketchy autocomplete is still running on localhost.",
  "Legend says this empty autocomplete is still running on localhost.",
  "Legend says this basic links is still running on localhost.",
  "This is a classic example of a basic forum disaster.",
  "This is a classic example of a basic question disaster.",
  "This is a classic example of a low-quality forum disaster.",
  "This is a classic example of a basic-level tutorial disaster.",
  "This is a classic example of a basic video disaster.",
  "This is a classic example of a simple autocomplete disaster.",
  "This is a classic example of a simple search disaster.",
  "This is a classic example of a obvious question disaster.",
  "This is a classic example of a basic-level search disaster.",
  "This is a classic example of a obvious query disaster.",
  "This is a classic example of a simple tutorial disaster.",
  "This is a classic example of a common query disaster.",
  "This is a classic example of a common question disaster.",
  "This is a classic example of a common answers disaster.",
  "This is a classic example of a obvious tutorial disaster.",
  "This is a classic example of a obvious result disaster.",
  "This is a classic example of a low-quality tutorial disaster.",
  "This is a classic example of a simple video disaster.",
  "This is a classic example of a empty tutorial disaster.",
  "This is a classic example of a sketchy forum disaster.",
  "This is a classic example of a simple forum disaster.",
  "This is a classic example of a common search disaster.",
  "This is a classic example of a obvious video disaster.",
  "This is a classic example of a common video disaster.",
  "This is a classic example of a simple result disaster.",
  "This is a classic example of a basic-level query disaster.",
  "This is a classic example of a sketchy video disaster.",
  "This is a classic example of a basic links disaster.",
  "This is a classic example of a low-quality query disaster.",
  "This is a classic example of a empty question disaster.",
  "This is a classic example of a common tutorial disaster.",
  "This is a classic example of a empty video disaster.",
  "This is a classic example of a sketchy tutorial disaster.",
  "This is a classic example of a sketchy search disaster.",
  "This is a classic example of a sketchy autocomplete disaster.",
  "This is a classic example of a sketchy query disaster.",
  "This is a classic example of a sketchy links disaster.",
  "This is a classic example of a empty forum disaster.",
  "This is a classic example of a empty search disaster.",
  "This is a classic example of a simple links disaster."
];

export const verdicts = [
  "Rejected on first principles of result organization.",
  "Closed as basic-level duplicate.",
  "Closed as common duplicate.",
  "Request changes on the obvious video.",
  "Request changes on the obvious links.",
  "Request changes on the basic question.",
  "Verdict: Query is completely unmergeable.",
  "Ship blocked by common check failures.",
  "Rejected on first principles of autocomplete organization.",
  "Rejected on first principles of forum organization.",
  "PR clicked sketchy link due to low-quality implementation.",
  "Return after touching actual production servers.",
  "Request changes on the common autocomplete.",
  "PR browsed video tutorial due to simple implementation.",
  "Needs more commits and fewer explanations.",
  "Closed as empty duplicate.",
  "Request changes on the basic answers.",
  "Ship blocked by simple check failures.",
  "Verdict: Question is completely unmergeable.",
  "Closed as sketchy duplicate.",
  "Rejected on first principles of video organization.",
  "PR scrolled search page due to low-quality implementation.",
  "Request changes on the low-quality tutorial.",
  "Rejected on first principles of tutorial organization.",
  "Request changes on the sketchy tutorial.",
  "Verdict: Search is completely unmergeable.",
  "PR scrolled search page due to obvious implementation.",
  "Verdict: Links is completely unmergeable.",
  "Verdict: Autocomplete is completely unmergeable.",
  "Rejected on first principles of answers organization.",
  "Closed as obvious duplicate.",
  "Request changes on the sketchy answers.",
  "Ship blocked by empty check failures.",
  "Request changes on the sketchy video.",
  "Ship blocked by basic check failures.",
  "Closed as basic duplicate.",
  "Request changes on the basic query.",
  "Closed as simple duplicate.",
  "Ship blocked by low-quality check failures.",
  "Verdict: Tutorial is completely unmergeable.",
  "PR scrolled search page due to empty implementation.",
  "Verdict: Forum is completely unmergeable.",
  "Request changes on the empty search.",
  "Verdict: Answers is completely unmergeable.",
  "Ship blocked by obvious check failures.",
  "Verdict: Result is completely unmergeable.",
  "Verdict: Video is completely unmergeable.",
  "PR clicked sketchy link due to basic implementation.",
  "PR searched generic query due to empty implementation.",
  "PR browsed video tutorial due to empty implementation.",
  "Request changes on the obvious autocomplete.",
  "Closed as low-quality duplicate.",
  "PR searched generic query due to simple implementation.",
  "Request changes on the simple answers.",
  "Request changes on the basic-level links.",
  "PR asked basic question due to basic-level implementation.",
  "PR searched generic query due to basic implementation.",
  "PR searched generic query due to obvious implementation.",
  "Request changes on the low-quality video.",
  "Request changes on the empty result.",
  "Rejected on first principles of links organization.",
  "PR asked basic question due to simple implementation.",
  "Request changes on the common tutorial.",
  "Request changes on the common result.",
  "PR searched generic query due to sketchy implementation.",
  "PR asked basic question due to sketchy implementation.",
  "Ship blocked by sketchy check failures.",
  "Request changes on the simple links.",
  "Rejected on first principles of search organization.",
  "Request changes on the obvious question.",
  "PR clicked sketchy link due to simple implementation.",
  "Request changes on the sketchy search.",
  "Request changes on the low-quality answers.",
  "Request changes on the basic-level forum.",
  "Request changes on the obvious tutorial.",
  "Request changes on the common query.",
  "Rejected on first principles of query organization.",
  "Request changes on the common video.",
  "Request changes on the simple autocomplete.",
  "PR browsed video tutorial due to low-quality implementation.",
  "PR browsed video tutorial due to basic implementation.",
  "PR browsed video tutorial due to sketchy implementation.",
  "Request changes on the sketchy query.",
  "PR asked basic question due to low-quality implementation.",
  "PR browsed video tutorial due to obvious implementation.",
  "PR scrolled search page due to basic-level implementation.",
  "Rejected on first principles of question organization.",
  "Request changes on the low-quality links.",
  "Request changes on the low-quality forum.",
  "PR clicked sketchy link due to obvious implementation.",
  "PR clicked sketchy link due to empty implementation.",
  "Request changes on the obvious result.",
  "Request changes on the obvious search."
];

export const easterEggs = [
  "Matrix Glitch: You copy-pasted a template and now the server believes it is a real founder.",
  "NASA Alert: Space mission aborted due to a minor answers parsing error.",
  "FBI Investigation: Suspect was found deploying unencrypted basic-level autocompletes.",
  "Dark Web Resume Auction: Current bid is $0.00, and the buyer is requesting a refund.",
  "Steam Achievement Unlocked: Successfully crashed a hello-world app on a $10,000 server.",
  "Gordon Ramsay Meltdown: 'This autocomplete is raw! It's absolutely raw!'",
  "Elon Musk Tweet: 'Just deleted the entire query pipeline, was completely useless.'",
  "Gordon Ramsay Meltdown: 'This video is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This query is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted basic querys.",
  "FBI Investigation: Suspect was found deploying unencrypted empty searchs.",
  "Gordon Ramsay Meltdown: 'This tutorial is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted obvious tutorials.",
  "FBI Investigation: Suspect was found deploying unencrypted low-quality linkss.",
  "Gordon Ramsay Meltdown: 'This answers is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This result is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This search is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted sketchy linkss.",
  "FBI Investigation: Suspect was found deploying unencrypted simple results.",
  "Gordon Ramsay Meltdown: 'This links is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This forum is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This question is raw! It's absolutely raw!'"
];
