// ES Module exports for gordon_ramsay roast format
export const titles = [
  "Failed to compile: Freezer",
  "Freezer conflict detected",
  "NullPointerMenuException",
  "Absolute Messy architecture",
  "Critical Nightmare failure",
  "Incident Report: Frozen Trash",
  "Dry Kitchen Error",
  "Incident Report: Messy Freezer",
  "Tasteless Trash Loop",
  "Incident Report: Dry Trash",
  "Incident Report: Rotten Menu",
  "Failed to compile: Chef-special",
  "Failed to compile: Menu",
  "NullPointerSpaghettiException",
  "Incident Report: Lazy Raw",
  "Absolute Frozen architecture",
  "Failed to compile: Raw",
  "The Nightmare tragedy",
  "Absolute Terrible architecture",
  "Lazy Freezer Error",
  "Terrible Chef Loop",
  "Dry Freezer Loop",
  "Tasteless Freezer Error",
  "Incident Report: Dry Disaster",
  "The Freezer tragedy",
  "Dry Menu Error",
  "Failed to compile: Nightmare",
  "Rotten Spaghetti Error",
  "Kitchen Not Found",
  "Incident Report: Terrible Kitchen",
  "Critical Raw failure",
  "Incident Report: Messy Chef-special",
  "Critical Freezer failure",
  "Spaghetti conflict detected",
  "Raw conflict detected",
  "Trash Not Found",
  "Incident Report: Tasteless Trash",
  "Absolute Dry architecture",
  "The Raw tragedy",
  "Absolute Rotten architecture",
  "Incident Report: Terrible Disaster",
  "Nightmare conflict detected",
  "Tasteless Menu Loop",
  "Critical Chef-special failure",
  "Lazy Nightmare Loop",
  "Absolute Raw architecture",
  "Frozen Raw Error",
  "Incident Report: Tasteless Nightmare",
  "Messy Raw Loop",
  "NullPointerKitchenException",
  "Tasteless Menu Error",
  "Raw Freezer Error",
  "Disaster Not Found",
  "NullPointerTrashException",
  "Chef Not Found",
  "NullPointerChefException",
  "Frozen Chef Loop",
  "Incident Report: Frozen Freezer",
  "Trash conflict detected",
  "Critical Kitchen failure",
  "NullPointerNightmareException",
  "Messy Trash Loop",
  "Absolute Tasteless architecture",
  "Nightmare Not Found",
  "Incident Report: Messy Trash",
  "Failed to compile: Chef",
  "Messy Kitchen Loop",
  "NullPointerFreezerException",
  "Failed to compile: Trash",
  "Freezer Not Found",
  "Rotten Chef Error",
  "Incident Report: Frozen Raw",
  "Messy Menu Error",
  "Incident Report: Tasteless Disaster",
  "Critical Spaghetti failure",
  "Menu Not Found",
  "Critical Chef failure",
  "Incident Report: Terrible Chef",
  "Critical Disaster failure",
  "Chef-special Not Found",
  "The Chef-special tragedy",
  "Disaster conflict detected",
  "The Spaghetti tragedy",
  "Lazy Disaster Error",
  "Spaghetti Not Found",
  "Critical Trash failure",
  "The Menu tragedy",
  "Messy Menu Loop",
  "Tasteless Kitchen Loop",
  "Messy Freezer Loop",
  "Frozen Chef-special Loop",
  "Messy Chef-special Loop",
  "Kitchen conflict detected",
  "Tasteless Disaster Error",
  "Incident Report: Raw Disaster",
  "Failed to compile: Kitchen",
  "Raw Chef Error",
  "Incident Report: Raw Chef",
  "Dry Freezer Error",
  "Failed to compile: Disaster"
];

export const openings = [
  "Alert: The candidate spent three months trying to served raw spaghetti with raw ingredients.",
  "Warning: System flagged an attempt to hated frozen dish causing absolute horror.",
  "Initial evaluation shows the developer decided to inspected messy kitchen with raw ingredients.",
  "We checked the history and found a frozen chef log.",
  "A review was filed regarding a raw menu.",
  "We checked the history and found a lazy chef log.",
  "The team has initiated audit for the candidate's disaster setup.",
  "Warning: System flagged an attempt to hated frozen dish without single comment.",
  "Alert: The candidate spent three months trying to served raw spaghetti without single comment.",
  "Alert: The candidate spent three months trying to threw directly in trash directly in the bin.",
  "Scanning candidate profile for lazy nightmares...",
  "Warning: System flagged an attempt to hated frozen dish at the SRE team.",
  "Initial evaluation shows the developer decided to inspected messy kitchen at the SRE team.",
  "Scanning candidate profile for lazy chefs...",
  "We checked the history and found a rotten raw log.",
  "Recruiters reported a case of rotten freezer design.",
  "Initial evaluation shows the developer decided to screamed at chef directly in the bin.",
  "Alert: The candidate spent three months trying to screamed at chef at the SRE team.",
  "We checked the history and found a tasteless chef-special log.",
  "A review was filed regarding a messy menu.",
  "The team has initiated audit for the candidate's chef-special setup.",
  "Alert: The candidate spent three months trying to screamed at chef directly in the bin.",
  "We checked the history and found a dry disaster log.",
  "A review was filed regarding a dry disaster.",
  "Scanning candidate profile for messy trashs...",
  "We checked the history and found a frozen trash log.",
  "Alert: The candidate spent three months trying to threw directly in trash causing absolute horror.",
  "Recruiters reported a case of frozen chef-special design.",
  "Scanning candidate profile for rotten disasters...",
  "Warning: System flagged an attempt to served raw spaghetti causing absolute horror.",
  "Recruiters reported a case of terrible menu design.",
  "Warning: System flagged an attempt to served raw spaghetti directly in the bin.",
  "Initial evaluation shows the developer decided to screamed at chef without single comment.",
  "Initial evaluation shows the developer decided to hated frozen dish with raw ingredients.",
  "Initial evaluation shows the developer decided to threw directly in trash with raw ingredients.",
  "Warning: System flagged an attempt to threw directly in trash at the SRE team.",
  "Warning: System flagged an attempt to inspected messy kitchen at the SRE team.",
  "We checked the history and found a lazy nightmare log.",
  "Warning: System flagged an attempt to threw directly in trash causing absolute horror.",
  "We checked the history and found a dry trash log.",
  "Alert: The candidate spent three months trying to served raw spaghetti at the SRE team.",
  "We checked the history and found a terrible chef log.",
  "Warning: System flagged an attempt to threw directly in trash with raw ingredients.",
  "Alert: The candidate spent three months trying to served raw spaghetti causing absolute horror.",
  "Recruiters reported a case of dry raw design.",
  "Alert: The candidate spent three months trying to inspected messy kitchen without single comment.",
  "Recruiters reported a case of dry trash design.",
  "Recruiters reported a case of lazy disaster design.",
  "Initial evaluation shows the developer decided to inspected messy kitchen directly in the bin.",
  "Recruiters reported a case of frozen menu design.",
  "A review was filed regarding a lazy disaster.",
  "Scanning candidate profile for raw menus...",
  "We checked the history and found a rotten chef log.",
  "We checked the history and found a tasteless menu log.",
  "Warning: System flagged an attempt to screamed at chef without single comment.",
  "Warning: System flagged an attempt to served raw spaghetti with raw ingredients.",
  "We checked the history and found a terrible nightmare log.",
  "Warning: System flagged an attempt to inspected messy kitchen directly in the bin.",
  "A review was filed regarding a lazy trash.",
  "Initial evaluation shows the developer decided to hated frozen dish at the SRE team.",
  "We checked the history and found a rotten kitchen log.",
  "Recruiters reported a case of terrible trash design.",
  "Warning: System flagged an attempt to screamed at chef at the SRE team.",
  "Initial evaluation shows the developer decided to threw directly in trash at the SRE team.",
  "Recruiters reported a case of terrible freezer design.",
  "A review was filed regarding a raw chef-special.",
  "Initial evaluation shows the developer decided to screamed at chef at the SRE team.",
  "Warning: System flagged an attempt to threw directly in trash without single comment.",
  "Scanning candidate profile for terrible chefs...",
  "We checked the history and found a rotten menu log.",
  "Scanning candidate profile for frozen trashs...",
  "Recruiters reported a case of rotten kitchen design.",
  "Recruiters reported a case of tasteless spaghetti design.",
  "Scanning candidate profile for dry menus...",
  "Scanning candidate profile for tasteless nightmares...",
  "Alert: The candidate spent three months trying to threw directly in trash at the SRE team.",
  "Initial evaluation shows the developer decided to screamed at chef causing absolute horror.",
  "Recruiters reported a case of raw freezer design.",
  "A review was filed regarding a dry nightmare.",
  "Scanning candidate profile for tasteless chefs...",
  "Recruiters reported a case of dry chef-special design.",
  "Recruiters reported a case of messy disaster design.",
  "Scanning candidate profile for rotten spaghettis...",
  "Scanning candidate profile for lazy disasters...",
  "Scanning candidate profile for dry nightmares...",
  "We checked the history and found a tasteless raw log.",
  "Alert: The candidate spent three months trying to hated frozen dish with raw ingredients.",
  "Scanning candidate profile for dry disasters...",
  "A review was filed regarding a dry kitchen.",
  "Alert: The candidate spent three months trying to hated frozen dish at the SRE team.",
  "Initial evaluation shows the developer decided to threw directly in trash without single comment.",
  "We checked the history and found a dry chef log.",
  "Initial evaluation shows the developer decided to inspected messy kitchen without single comment."
];

export const findings = [
  "While debugging {{project}}, we found a lazy logic loop related to {{language}} features.",
  "The candidate claims {{framework}} experience, but their repository is just a raw clone that has been abandoned.",
  "Obtained {{certification}} which apparently teaches how to served raw spaghetti causing absolute horror.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to served raw spaghetti with raw ingredients.",
  "{{github}} contains more rotten nightmares than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to hated frozen dish at the SRE team.",
  "{{candidateName}} has spent three weeks optimizing a disaster while completely ignoring {{missingSection}}.",
  "For {{experience}}, the primary contribution was writing a lazy config for a raw.",
  "A security audit on {{github}} detected a plain-text database password inside a messy menu.",
  "Obtained {{certification}} which apparently teaches how to screamed at chef without single comment.",
  "{{achievement}} was highlighted, but the git logs show they only managed to threw directly in trash without single comment.",
  "Listed {{skill}} as a primary competency, but the evidence points to a messy raw.",
  "{{github}} contains more terrible chefs than original code.",
  "{{github}} contains more rotten disasters than original code.",
  "{{github}} contains more dry chefs than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to screamed at chef directly in the bin.",
  "Listed {{skill}} as a primary competency, but the evidence points to a tasteless freezer.",
  "For {{experience}}, the primary contribution was writing a tasteless config for a chef.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to hated frozen dish without single comment.",
  "A security audit on {{github}} detected a plain-text database password inside a raw disaster.",
  "For {{experience}}, the primary contribution was writing a messy config for a chef-special.",
  "A security audit on {{github}} detected a plain-text database password inside a rotten chef.",
  "Listed {{skill}} as a primary competency, but the evidence points to a frozen menu.",
  "{{education}} is listed, but they still managed to deploy a tasteless freezer to production.",
  "{{education}} is listed, but they still managed to deploy a terrible disaster to production.",
  "Obtained {{certification}} which apparently teaches how to served raw spaghetti without single comment.",
  "Failed to configure {{project}} because {{candidateName}} decided to served raw spaghetti at the SRE team.",
  "Obtained {{certification}} which apparently teaches how to served raw spaghetti at the SRE team.",
  "For {{experience}}, the primary contribution was writing a messy config for a spaghetti.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to hated frozen dish directly in the bin.",
  "{{github}} contains more frozen nightmares than original code.",
  "{{education}} is listed, but they still managed to deploy a messy menu to production.",
  "A security audit on {{github}} detected a plain-text database password inside a terrible freezer.",
  "Obtained {{certification}} which apparently teaches how to hated frozen dish causing absolute horror.",
  "Listed {{skill}} as a primary competency, but the evidence points to a messy chef-special.",
  "{{achievement}} was highlighted, but the git logs show they only managed to inspected messy kitchen without single comment.",
  "{{github}} contains more tasteless trashs than original code.",
  "Listed {{skill}} as a primary competency, but the evidence points to a lazy trash.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to inspected messy kitchen with raw ingredients.",
  "{{education}} is listed, but they still managed to deploy a dry kitchen to production.",
  "{{github}} contains more raw raws than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to inspected messy kitchen with raw ingredients.",
  "{{github}} contains more messy kitchens than original code.",
  "{{education}} is listed, but they still managed to deploy a raw chef-special to production.",
  "Failed to configure {{project}} because {{candidateName}} decided to hated frozen dish directly in the bin.",
  "{{candidateName}} has spent three weeks optimizing a chef-special while completely ignoring {{missingSection}}.",
  "{{github}} contains more rotten kitchens than original code.",
  "{{github}} contains more frozen chef-specials than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to served raw spaghetti directly in the bin.",
  "Failed to configure {{project}} because {{candidateName}} decided to inspected messy kitchen without single comment.",
  "{{github}} contains more lazy chefs than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a lazy trash.",
  "Obtained {{certification}} which apparently teaches how to inspected messy kitchen at the SRE team.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to hated frozen dish at the SRE team.",
  "{{achievement}} was highlighted, but the git logs show they only managed to screamed at chef at the SRE team.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to inspected messy kitchen without single comment.",
  "{{achievement}} was highlighted, but the git logs show they only managed to screamed at chef directly in the bin.",
  "Obtained {{certification}} which apparently teaches how to threw directly in trash directly in the bin.",
  "{{achievement}} was highlighted, but the git logs show they only managed to served raw spaghetti without single comment.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to threw directly in trash directly in the bin.",
  "For {{experience}}, the primary contribution was writing a frozen config for a trash.",
  "Listed {{skill}} as a primary competency, but the evidence points to a dry chef.",
  "{{achievement}} was highlighted, but the git logs show they only managed to inspected messy kitchen causing absolute horror.",
  "{{github}} contains more rotten spaghettis than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to screamed at chef causing absolute horror.",
  "{{achievement}} was highlighted, but the git logs show they only managed to inspected messy kitchen at the SRE team.",
  "Obtained {{certification}} which apparently teaches how to inspected messy kitchen without single comment.",
  "Obtained {{certification}} which apparently teaches how to inspected messy kitchen with raw ingredients.",
  "{{education}} is listed, but they still managed to deploy a lazy raw to production.",
  "{{github}} contains more raw chefs than original code.",
  "{{github}} contains more dry menus than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to threw directly in trash causing absolute horror.",
  "Obtained {{certification}} which apparently teaches how to screamed at chef causing absolute horror.",
  "Obtained {{certification}} which apparently teaches how to hated frozen dish with raw ingredients.",
  "{{github}} contains more messy nightmares than original code.",
  "{{github}} contains more lazy raws than original code.",
  "Listed {{skill}} as a primary competency, but the evidence points to a terrible spaghetti.",
  "{{achievement}} was highlighted, but the git logs show they only managed to served raw spaghetti directly in the bin.",
  "{{achievement}} was highlighted, but the git logs show they only managed to threw directly in trash with raw ingredients.",
  "{{github}} contains more terrible trashs than original code.",
  "Obtained {{certification}} which apparently teaches how to served raw spaghetti with raw ingredients.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to threw directly in trash causing absolute horror.",
  "Obtained {{certification}} which apparently teaches how to threw directly in trash without single comment.",
  "{{github}} contains more lazy kitchens than original code.",
  "{{github}} contains more dry kitchens than original code.",
  "{{github}} contains more lazy nightmares than original code.",
  "Obtained {{certification}} which apparently teaches how to threw directly in trash causing absolute horror.",
  "{{github}} contains more terrible freezers than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to inspected messy kitchen at the SRE team.",
  "Obtained {{certification}} which apparently teaches how to hated frozen dish at the SRE team.",
  "Obtained {{certification}} which apparently teaches how to hated frozen dish without single comment.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to served raw spaghetti at the SRE team.",
  "Obtained {{certification}} which apparently teaches how to screamed at chef at the SRE team.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to inspected messy kitchen directly in the bin.",
  "For {{experience}}, the primary contribution was writing a terrible config for a disaster.",
  "{{achievement}} was highlighted, but the git logs show they only managed to screamed at chef with raw ingredients.",
  "Failed to configure {{project}} because {{candidateName}} decided to threw directly in trash directly in the bin.",
  "Obtained {{certification}} which apparently teaches how to inspected messy kitchen directly in the bin.",
  "Failed to configure {{project}} because {{candidateName}} decided to served raw spaghetti causing absolute horror.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to screamed at chef with raw ingredients.",
  "Failed to configure {{project}} because {{candidateName}} decided to hated frozen dish without single comment.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to served raw spaghetti causing absolute horror.",
  "{{achievement}} was highlighted, but the git logs show they only managed to hated frozen dish with raw ingredients.",
  "Failed to configure {{project}} because {{candidateName}} decided to threw directly in trash without single comment.",
  "Failed to configure {{project}} because {{candidateName}} decided to hated frozen dish at the SRE team.",
  "Failed to configure {{project}} because {{candidateName}} decided to threw directly in trash causing absolute horror.",
  "A security audit on {{github}} detected a plain-text database password inside a raw chef-special.",
  "Obtained {{certification}} which apparently teaches how to threw directly in trash at the SRE team.",
  "Failed to configure {{project}} because {{candidateName}} decided to threw directly in trash at the SRE team.",
  "Failed to configure {{project}} because {{candidateName}} decided to hated frozen dish causing absolute horror.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to screamed at chef at the SRE team.",
  "{{github}} contains more tasteless freezers than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to hated frozen dish with raw ingredients."
];

export const punchlines = [
  "The only thing memory-safe about this setup is that nobody has ever tried to run it.",
  "Even Stack Overflow has marked this nightmare as off-topic.",
  "A junior developer looked at the trash and immediately went to touch grass.",
  "The compiler requested emotional support after reading the terrible code.",
  "The documentation was so empty, I had to use it as a virtual sketchbook.",
  "Even Stack Overflow has marked this chef-special as off-topic.",
  "It did not optimize our process, but it did make the laptop fan spin like a jet engine.",
  "Legend says this rotten chef is still running on localhost.",
  "Legend says this dry trash is still running on localhost.",
  "We would deploy it to production, but our SRE team deserves to sleep at night.",
  "Legend says this rotten freezer is still running on localhost.",
  "Legend says this rotten nightmare is still running on localhost.",
  "Legend says this terrible nightmare is still running on localhost.",
  "Legend says this raw trash is still running on localhost.",
  "Legend says this tasteless disaster is still running on localhost.",
  "Legend says this terrible trash is still running on localhost.",
  "Legend says this raw menu is still running on localhost.",
  "Legend says this rotten raw is still running on localhost.",
  "Legend says this terrible kitchen is still running on localhost.",
  "Legend says this messy freezer is still running on localhost.",
  "Legend says this terrible chef-special is still running on localhost.",
  "Legend says this frozen disaster is still running on localhost.",
  "Legend says this messy nightmare is still running on localhost.",
  "Legend says this frozen chef is still running on localhost.",
  "Legend says this terrible spaghetti is still running on localhost.",
  "Legend says this tasteless nightmare is still running on localhost.",
  "Legend says this tasteless spaghetti is still running on localhost.",
  "Legend says this rotten menu is still running on localhost.",
  "A junior developer looked at the chef-special and immediately went to touch grass.",
  "Legend says this frozen spaghetti is still running on localhost.",
  "Legend says this lazy menu is still running on localhost.",
  "Legend says this frozen kitchen is still running on localhost.",
  "Legend says this dry menu is still running on localhost.",
  "Legend says this lazy chef is still running on localhost.",
  "Legend says this tasteless kitchen is still running on localhost.",
  "Legend says this messy menu is still running on localhost.",
  "Legend says this frozen freezer is still running on localhost.",
  "Legend says this lazy kitchen is still running on localhost.",
  "Legend says this lazy nightmare is still running on localhost.",
  "Legend says this terrible disaster is still running on localhost.",
  "Legend says this raw freezer is still running on localhost.",
  "Legend says this tasteless freezer is still running on localhost.",
  "Legend says this lazy trash is still running on localhost.",
  "Legend says this raw spaghetti is still running on localhost.",
  "Legend says this dry freezer is still running on localhost.",
  "Legend says this lazy disaster is still running on localhost.",
  "Legend says this raw nightmare is still running on localhost.",
  "Legend says this rotten trash is still running on localhost.",
  "Legend says this messy disaster is still running on localhost.",
  "Legend says this tasteless menu is still running on localhost.",
  "Legend says this rotten kitchen is still running on localhost.",
  "Legend says this terrible freezer is still running on localhost.",
  "Legend says this frozen trash is still running on localhost.",
  "Legend says this tasteless trash is still running on localhost.",
  "Legend says this messy trash is still running on localhost.",
  "Legend says this frozen nightmare is still running on localhost.",
  "Legend says this lazy spaghetti is still running on localhost.",
  "Legend says this dry nightmare is still running on localhost.",
  "Legend says this frozen menu is still running on localhost.",
  "Legend says this lazy raw is still running on localhost.",
  "Legend says this dry raw is still running on localhost.",
  "Legend says this dry chef is still running on localhost.",
  "Legend says this tasteless chef is still running on localhost.",
  "Legend says this messy chef is still running on localhost.",
  "Legend says this messy raw is still running on localhost.",
  "This is a classic example of a lazy freezer disaster.",
  "This is a classic example of a tasteless chef disaster.",
  "This is a classic example of a terrible chef-special disaster.",
  "This is a classic example of a messy kitchen disaster.",
  "This is a classic example of a raw trash disaster.",
  "This is a classic example of a rotten disaster disaster.",
  "This is a classic example of a frozen nightmare disaster.",
  "This is a classic example of a frozen chef disaster.",
  "This is a classic example of a dry chef disaster.",
  "This is a classic example of a messy freezer disaster.",
  "This is a classic example of a messy spaghetti disaster.",
  "This is a classic example of a terrible freezer disaster.",
  "This is a classic example of a dry nightmare disaster.",
  "This is a classic example of a terrible raw disaster.",
  "This is a classic example of a terrible kitchen disaster.",
  "This is a classic example of a tasteless menu disaster.",
  "This is a classic example of a messy trash disaster.",
  "This is a classic example of a lazy trash disaster.",
  "This is a classic example of a dry freezer disaster.",
  "This is a classic example of a tasteless freezer disaster.",
  "This is a classic example of a terrible menu disaster.",
  "This is a classic example of a messy nightmare disaster.",
  "This is a classic example of a lazy raw disaster.",
  "This is a classic example of a lazy menu disaster.",
  "This is a classic example of a tasteless raw disaster.",
  "This is a classic example of a frozen trash disaster.",
  "This is a classic example of a terrible trash disaster.",
  "This is a classic example of a frozen freezer disaster.",
  "This is a classic example of a terrible spaghetti disaster.",
  "This is a classic example of a raw chef disaster."
];

export const verdicts = [
  "Request changes on the tasteless spaghetti.",
  "Request changes on the frozen trash.",
  "Verdict: Disaster is completely unmergeable.",
  "Ship blocked by raw check failures.",
  "Closed as frozen duplicate.",
  "PR screamed at chef due to frozen implementation.",
  "Request changes on the terrible trash.",
  "Ship blocked by messy check failures.",
  "Needs more commits and fewer explanations.",
  "PR inspected messy kitchen due to dry implementation.",
  "Request changes on the raw raw.",
  "Closed as rotten duplicate.",
  "Closed as raw duplicate.",
  "PR inspected messy kitchen due to lazy implementation.",
  "Verdict: Chef-special is completely unmergeable.",
  "Return after touching actual production servers.",
  "Verdict: Trash is completely unmergeable.",
  "Rejected on first principles of menu organization.",
  "Rejected on first principles of raw organization.",
  "Closed as lazy duplicate.",
  "Verdict: Spaghetti is completely unmergeable.",
  "PR hated frozen dish due to raw implementation.",
  "Request changes on the rotten menu.",
  "Ship blocked by frozen check failures.",
  "Closed as tasteless duplicate.",
  "Ship blocked by dry check failures.",
  "Rejected on first principles of chef organization.",
  "Rejected on first principles of kitchen organization.",
  "Verdict: Kitchen is completely unmergeable.",
  "Verdict: Raw is completely unmergeable.",
  "Rejected on first principles of freezer organization.",
  "Request changes on the tasteless chef-special.",
  "Request changes on the tasteless trash.",
  "Rejected on first principles of trash organization.",
  "PR hated frozen dish due to lazy implementation.",
  "Verdict: Freezer is completely unmergeable.",
  "Request changes on the messy freezer.",
  "Ship blocked by terrible check failures.",
  "Request changes on the dry kitchen.",
  "PR threw directly in trash due to rotten implementation.",
  "PR hated frozen dish due to rotten implementation.",
  "PR served raw spaghetti due to terrible implementation.",
  "Verdict: Nightmare is completely unmergeable.",
  "Closed as terrible duplicate.",
  "PR inspected messy kitchen due to terrible implementation.",
  "Ship blocked by rotten check failures.",
  "Request changes on the frozen chef.",
  "Request changes on the terrible chef-special.",
  "Rejected on first principles of spaghetti organization.",
  "Rejected on first principles of nightmare organization.",
  "Ship blocked by lazy check failures.",
  "Verdict: Menu is completely unmergeable.",
  "Closed as dry duplicate.",
  "Request changes on the messy disaster.",
  "Ship blocked by tasteless check failures.",
  "Request changes on the lazy chef.",
  "Request changes on the rotten chef.",
  "PR hated frozen dish due to messy implementation.",
  "PR inspected messy kitchen due to raw implementation.",
  "Request changes on the lazy disaster.",
  "Request changes on the messy chef.",
  "PR served raw spaghetti due to lazy implementation.",
  "Request changes on the tasteless freezer.",
  "PR served raw spaghetti due to rotten implementation.",
  "PR inspected messy kitchen due to rotten implementation.",
  "Request changes on the dry menu.",
  "PR screamed at chef due to terrible implementation.",
  "Closed as messy duplicate.",
  "PR threw directly in trash due to dry implementation.",
  "PR threw directly in trash due to terrible implementation.",
  "Request changes on the rotten nightmare.",
  "PR screamed at chef due to lazy implementation.",
  "PR screamed at chef due to tasteless implementation.",
  "PR screamed at chef due to raw implementation.",
  "Request changes on the lazy freezer.",
  "Rejected on first principles of disaster organization.",
  "PR inspected messy kitchen due to tasteless implementation.",
  "PR hated frozen dish due to terrible implementation.",
  "PR threw directly in trash due to tasteless implementation.",
  "Request changes on the terrible menu.",
  "Request changes on the dry trash.",
  "Request changes on the lazy spaghetti.",
  "Request changes on the frozen spaghetti.",
  "Request changes on the terrible kitchen.",
  "Request changes on the raw chef-special."
];

export const easterEggs = [
  "Elon Musk Tweet: 'Just deleted the entire disaster pipeline, was completely useless.'",
  "Dark Web Resume Auction: Current bid is $0.00, and the buyer is requesting a refund.",
  "Matrix Glitch: You copy-pasted a template and now the server believes it is a real founder.",
  "NASA Alert: Space mission aborted due to a minor disaster parsing error.",
  "Gordon Ramsay Meltdown: 'This chef is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted dry raws.",
  "Steam Achievement Unlocked: Successfully crashed a hello-world app on a $10,000 server.",
  "Gordon Ramsay Meltdown: 'This spaghetti is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted lazy spaghettis.",
  "Elon Musk Tweet: 'Just deleted the entire chef-special pipeline, was completely useless.'",
  "FBI Investigation: Suspect was found deploying unencrypted rotten chefs.",
  "FBI Investigation: Suspect was found deploying unencrypted terrible nightmares.",
  "Gordon Ramsay Meltdown: 'This nightmare is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted messy chef-specials.",
  "Gordon Ramsay Meltdown: 'This trash is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This menu is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted messy freezers.",
  "NASA Alert: Space mission aborted due to a minor chef-special parsing error.",
  "Gordon Ramsay Meltdown: 'This freezer is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This disaster is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted frozen menus.",
  "FBI Investigation: Suspect was found deploying unencrypted tasteless kitchens."
];
