// ES Module exports for horror_story roast format
export const titles = [
  "Critical Legacy failure",
  "Curse Not Found",
  "Critical Graveyard failure",
  "Critical Darkness failure",
  "Critical SVN failure",
  "Forgotten Curse Loop",
  "The Shadow tragedy",
  "The SVN tragedy",
  "Shadow Not Found",
  "Failed to compile: Shadow",
  "SVN Not Found",
  "Dead Shadow Loop",
  "Dark Legacy Loop",
  "Failed to compile: Skeleton",
  "Legacy Not Found",
  "The Skeleton tragedy",
  "Legacy conflict detected",
  "Forgotten Ghost Error",
  "NullPointerGraveyardException",
  "Critical Skeleton failure",
  "Absolute Dark architecture",
  "Absolute Cursed architecture",
  "Absolute Haunted architecture",
  "Skeleton Not Found",
  "Scary Darkness Loop",
  "Critical Shadow failure",
  "Cursed Curse Loop",
  "Incident Report: Dark Ghost",
  "Incident Report: Haunted Graveyard",
  "Dark Legacy Error",
  "Incident Report: Scary Graveyard",
  "Legacy SVN Loop",
  "The Monster tragedy",
  "Skeleton conflict detected",
  "Ancient Monster Loop",
  "Forgotten Darkness Error",
  "Failed to compile: Darkness",
  "Legacy COBOL Loop",
  "Ghost Not Found",
  "Legacy Legacy Loop",
  "Ancient SVN Error",
  "Failed to compile: COBOL",
  "Haunted Graveyard Loop",
  "Dark COBOL Loop",
  "Scary Skeleton Loop",
  "Failed to compile: Monster",
  "Incident Report: Dead SVN",
  "The Darkness tragedy",
  "Dead SVN Error",
  "Darkness Not Found",
  "NullPointerLegacyException",
  "Dark Skeleton Loop",
  "Cursed Darkness Loop",
  "Graveyard Not Found",
  "Graveyard conflict detected",
  "COBOL Not Found",
  "Legacy Monster Loop",
  "Incident Report: Dark Darkness",
  "Failed to compile: Legacy",
  "Monster Not Found",
  "Failed to compile: Ghost",
  "NullPointerSVNException",
  "The Graveyard tragedy",
  "Incident Report: Dark Skeleton",
  "Haunted Monster Loop",
  "Dark Shadow Loop",
  "Ghost conflict detected",
  "NullPointerMonsterException",
  "The COBOL tragedy",
  "Ancient Darkness Loop",
  "Cursed Monster Error",
  "The Legacy tragedy",
  "Incident Report: Dark SVN",
  "Curse conflict detected",
  "Ancient COBOL Loop",
  "Dark Curse Loop",
  "Incident Report: Cursed Curse",
  "Incident Report: Forgotten Graveyard",
  "Incident Report: Legacy Shadow",
  "NullPointerSkeletonException",
  "Scary Curse Loop",
  "Incident Report: Legacy Curse",
  "Shadow conflict detected",
  "Absolute Dead architecture",
  "Monster conflict detected",
  "SVN conflict detected",
  "Critical COBOL failure",
  "Cursed COBOL Error",
  "Haunted Curse Error",
  "Forgotten SVN Loop",
  "Dead Ghost Error",
  "Dark SVN Loop",
  "Incident Report: Forgotten SVN",
  "Darkness conflict detected",
  "Incident Report: Haunted Darkness",
  "Critical Ghost failure",
  "Critical Curse failure",
  "Incident Report: Dark Monster",
  "Forgotten Darkness Loop",
  "NullPointerCurseException"
];

export const openings = [
  "We checked the history and found a ancient legacy log.",
  "Alert: The candidate spent three months trying to compiled legacy COBOL without single comment.",
  "Warning: System flagged an attempt to compiled legacy COBOL in the dark.",
  "A review was filed regarding a forgotten SVN.",
  "A review was filed regarding a dark darkness.",
  "Recruiters reported a case of dark darkness design.",
  "Scanning candidate profile for cursed darknesss...",
  "Initial evaluation shows the developer decided to wrote raw pointers causing server to crash.",
  "Warning: System flagged an attempt to survived server crash releasing ancient bug.",
  "Initial evaluation shows the developer decided to compiled legacy COBOL in the dark.",
  "The team has initiated audit for the candidate's COBOL setup.",
  "Scanning candidate profile for cursed ghosts...",
  "Scanning candidate profile for forgotten ghosts...",
  "Alert: The candidate spent three months trying to wrote raw pointers releasing ancient bug.",
  "We checked the history and found a legacy darkness log.",
  "Initial evaluation shows the developer decided to wrote raw pointers releasing ancient bug.",
  "Recruiters reported a case of legacy darkness design.",
  "Warning: System flagged an attempt to compiled legacy COBOL without single comment.",
  "Warning: System flagged an attempt to screamed in panic in the dark.",
  "We checked the history and found a haunted COBOL log.",
  "Alert: The candidate spent three months trying to wrote raw pointers in the dark.",
  "We checked the history and found a scary monster log.",
  "Recruiters reported a case of cursed COBOL design.",
  "Scanning candidate profile for cursed shadows...",
  "We checked the history and found a legacy monster log.",
  "Warning: System flagged an attempt to opened index file in the dark.",
  "Recruiters reported a case of dark SVN design.",
  "Initial evaluation shows the developer decided to opened index file and nobody answered.",
  "Scanning candidate profile for legacy darknesss...",
  "Warning: System flagged an attempt to compiled legacy COBOL and nobody answered.",
  "Warning: System flagged an attempt to survived server crash and nobody answered.",
  "We checked the history and found a cursed SVN log.",
  "Scanning candidate profile for dead skeletons...",
  "Alert: The candidate spent three months trying to survived server crash in the dark.",
  "A review was filed regarding a ancient skeleton.",
  "We checked the history and found a forgotten monster log.",
  "Initial evaluation shows the developer decided to wrote raw pointers without single comment.",
  "Warning: System flagged an attempt to screamed in panic causing server to crash.",
  "Alert: The candidate spent three months trying to screamed in panic without single comment.",
  "Initial evaluation shows the developer decided to survived server crash releasing ancient bug.",
  "Recruiters reported a case of scary ghost design.",
  "Recruiters reported a case of dead graveyard design.",
  "Scanning candidate profile for cursed SVNs...",
  "We checked the history and found a haunted monster log.",
  "We checked the history and found a dark legacy log.",
  "Scanning candidate profile for ancient COBOLs...",
  "Warning: System flagged an attempt to screamed in panic and nobody answered.",
  "Alert: The candidate spent three months trying to opened index file and nobody answered.",
  "A review was filed regarding a scary SVN.",
  "Warning: System flagged an attempt to screamed in panic without single comment.",
  "Initial evaluation shows the developer decided to survived server crash and nobody answered.",
  "We checked the history and found a legacy shadow log.",
  "A review was filed regarding a scary darkness.",
  "Scanning candidate profile for forgotten monsters...",
  "We checked the history and found a ancient darkness log.",
  "A review was filed regarding a dead COBOL.",
  "Warning: System flagged an attempt to screamed in panic releasing ancient bug.",
  "Scanning candidate profile for forgotten COBOLs...",
  "Scanning candidate profile for forgotten curses...",
  "A review was filed regarding a haunted SVN.",
  "We checked the history and found a haunted skeleton log.",
  "We checked the history and found a scary curse log.",
  "Initial evaluation shows the developer decided to screamed in panic and nobody answered.",
  "A review was filed regarding a cursed curse.",
  "We checked the history and found a cursed COBOL log.",
  "A review was filed regarding a cursed SVN.",
  "A review was filed regarding a legacy shadow.",
  "Warning: System flagged an attempt to opened index file releasing ancient bug.",
  "We checked the history and found a cursed skeleton log.",
  "Initial evaluation shows the developer decided to compiled legacy COBOL without single comment.",
  "Recruiters reported a case of dead SVN design.",
  "Alert: The candidate spent three months trying to opened index file causing server to crash.",
  "Scanning candidate profile for cursed graveyards...",
  "Recruiters reported a case of forgotten ghost design.",
  "Recruiters reported a case of dead legacy design.",
  "We checked the history and found a ancient curse log.",
  "We checked the history and found a scary COBOL log.",
  "Scanning candidate profile for haunted darknesss...",
  "Initial evaluation shows the developer decided to wrote raw pointers and nobody answered.",
  "Recruiters reported a case of dead COBOL design.",
  "Alert: The candidate spent three months trying to screamed in panic releasing ancient bug.",
  "Initial evaluation shows the developer decided to survived server crash causing server to crash.",
  "Scanning candidate profile for dead legacys...",
  "Warning: System flagged an attempt to opened index file without single comment.",
  "A review was filed regarding a legacy COBOL.",
  "Alert: The candidate spent three months trying to compiled legacy COBOL in the dark.",
  "We checked the history and found a cursed shadow log.",
  "Initial evaluation shows the developer decided to compiled legacy COBOL releasing ancient bug.",
  "Alert: The candidate spent three months trying to wrote raw pointers without single comment.",
  "Alert: The candidate spent three months trying to opened index file releasing ancient bug.",
  "Recruiters reported a case of dark skeleton design."
];

export const findings = [
  "A security audit on {{github}} detected a plain-text database password inside a cursed ghost.",
  "Listed {{skill}} as a primary competency, but the evidence points to a cursed ghost.",
  "{{achievement}} was highlighted, but the git logs show they only managed to screamed in panic releasing ancient bug.",
  "Failed to configure {{project}} because {{candidateName}} decided to compiled legacy COBOL and nobody answered.",
  "{{candidateName}} has spent three weeks optimizing a darkness while completely ignoring {{missingSection}}.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to compiled legacy COBOL and nobody answered.",
  "{{github}} contains more legacy curses than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a ancient SVN.",
  "While debugging {{project}}, we found a forgotten logic loop related to {{language}} features.",
  "{{education}} is listed, but they still managed to deploy a dead legacy to production.",
  "For {{experience}}, the primary contribution was writing a dark config for a monster.",
  "For {{experience}}, the primary contribution was writing a ancient config for a darkness.",
  "Listed {{skill}} as a primary competency, but the evidence points to a legacy monster.",
  "{{education}} is listed, but they still managed to deploy a ancient skeleton to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to compiled legacy COBOL in the dark.",
  "{{achievement}} was highlighted, but the git logs show they only managed to opened index file releasing ancient bug.",
  "Obtained {{certification}} which apparently teaches how to screamed in panic releasing ancient bug.",
  "The candidate claims {{framework}} experience, but their repository is just a dark clone that has been abandoned.",
  "{{github}} contains more dead COBOLs than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to wrote raw pointers and nobody answered.",
  "{{github}} contains more dark shadows than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a haunted legacy.",
  "A security audit on {{github}} detected a plain-text database password inside a dark darkness.",
  "{{education}} is listed, but they still managed to deploy a cursed COBOL to production.",
  "{{github}} contains more ancient graveyards than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to opened index file releasing ancient bug.",
  "{{education}} is listed, but they still managed to deploy a scary shadow to production.",
  "Obtained {{certification}} which apparently teaches how to opened index file without single comment.",
  "Failed to configure {{project}} because {{candidateName}} decided to wrote raw pointers in the dark.",
  "Failed to configure {{project}} because {{candidateName}} decided to survived server crash causing server to crash.",
  "For {{experience}}, the primary contribution was writing a haunted config for a legacy.",
  "Obtained {{certification}} which apparently teaches how to survived server crash and nobody answered.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to compiled legacy COBOL causing server to crash.",
  "{{achievement}} was highlighted, but the git logs show they only managed to survived server crash causing server to crash.",
  "Failed to configure {{project}} because {{candidateName}} decided to opened index file and nobody answered.",
  "{{github}} contains more dark curses than original code.",
  "Listed {{skill}} as a primary competency, but the evidence points to a haunted shadow.",
  "Failed to configure {{project}} because {{candidateName}} decided to survived server crash releasing ancient bug.",
  "{{education}} is listed, but they still managed to deploy a forgotten curse to production.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to screamed in panic without single comment.",
  "Failed to configure {{project}} because {{candidateName}} decided to wrote raw pointers and nobody answered.",
  "{{achievement}} was highlighted, but the git logs show they only managed to wrote raw pointers without single comment.",
  "For {{experience}}, the primary contribution was writing a forgotten config for a ghost.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to survived server crash causing server to crash.",
  "{{github}} contains more forgotten skeletons than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a scary monster.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to opened index file causing server to crash.",
  "Failed to configure {{project}} because {{candidateName}} decided to screamed in panic in the dark.",
  "{{github}} contains more forgotten ghosts than original code.",
  "Obtained {{certification}} which apparently teaches how to compiled legacy COBOL releasing ancient bug.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to opened index file and nobody answered.",
  "Failed to configure {{project}} because {{candidateName}} decided to screamed in panic without single comment.",
  "{{achievement}} was highlighted, but the git logs show they only managed to screamed in panic in the dark.",
  "Failed to configure {{project}} because {{candidateName}} decided to opened index file without single comment.",
  "Obtained {{certification}} which apparently teaches how to survived server crash releasing ancient bug.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to compiled legacy COBOL in the dark.",
  "Obtained {{certification}} which apparently teaches how to compiled legacy COBOL without single comment.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to opened index file without single comment.",
  "{{github}} contains more cursed SVNs than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a dead skeleton.",
  "Listed {{skill}} as a primary competency, but the evidence points to a dark darkness.",
  "Obtained {{certification}} which apparently teaches how to screamed in panic in the dark.",
  "Obtained {{certification}} which apparently teaches how to survived server crash in the dark.",
  "Failed to configure {{project}} because {{candidateName}} decided to screamed in panic releasing ancient bug.",
  "{{achievement}} was highlighted, but the git logs show they only managed to survived server crash without single comment.",
  "{{github}} contains more dead shadows than original code.",
  "Obtained {{certification}} which apparently teaches how to wrote raw pointers causing server to crash.",
  "{{github}} contains more haunted COBOLs than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to wrote raw pointers without single comment.",
  "{{github}} contains more ancient shadows than original code.",
  "Obtained {{certification}} which apparently teaches how to wrote raw pointers and nobody answered.",
  "Obtained {{certification}} which apparently teaches how to wrote raw pointers without single comment.",
  "Failed to configure {{project}} because {{candidateName}} decided to wrote raw pointers releasing ancient bug.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to survived server crash without single comment.",
  "Failed to configure {{project}} because {{candidateName}} decided to opened index file releasing ancient bug.",
  "{{github}} contains more forgotten COBOLs than original code.",
  "Listed {{skill}} as a primary competency, but the evidence points to a forgotten SVN.",
  "Failed to configure {{project}} because {{candidateName}} decided to compiled legacy COBOL releasing ancient bug.",
  "{{github}} contains more cursed ghosts than original code.",
  "{{github}} contains more ancient legacys than original code.",
  "Obtained {{certification}} which apparently teaches how to survived server crash causing server to crash.",
  "Obtained {{certification}} which apparently teaches how to screamed in panic and nobody answered.",
  "{{github}} contains more forgotten legacys than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to compiled legacy COBOL and nobody answered.",
  "{{github}} contains more dead SVNs than original code.",
  "{{github}} contains more scary SVNs than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to opened index file in the dark.",
  "{{github}} contains more haunted skeletons than original code.",
  "Obtained {{certification}} which apparently teaches how to opened index file causing server to crash.",
  "Obtained {{certification}} which apparently teaches how to wrote raw pointers in the dark.",
  "{{github}} contains more dead darknesss than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to survived server crash and nobody answered.",
  "Obtained {{certification}} which apparently teaches how to opened index file releasing ancient bug.",
  "Failed to configure {{project}} because {{candidateName}} decided to survived server crash without single comment.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to wrote raw pointers in the dark.",
  "For {{experience}}, the primary contribution was writing a dead config for a SVN.",
  "{{achievement}} was highlighted, but the git logs show they only managed to opened index file without single comment.",
  "{{github}} contains more ancient monsters than original code.",
  "Obtained {{certification}} which apparently teaches how to compiled legacy COBOL causing server to crash.",
  "Obtained {{certification}} which apparently teaches how to compiled legacy COBOL and nobody answered.",
  "{{achievement}} was highlighted, but the git logs show they only managed to wrote raw pointers and nobody answered."
];

export const punchlines = [
  "The only thing memory-safe about this setup is that nobody has ever tried to run it.",
  "A junior developer looked at the skeleton and immediately went to touch grass.",
  "Legend says this ancient darkness is still running on localhost.",
  "We would deploy it to production, but our SRE team deserves to sleep at night.",
  "It did not optimize our process, but it did make the laptop fan spin like a jet engine.",
  "The documentation was so empty, I had to use it as a virtual sketchbook.",
  "Even Stack Overflow has marked this skeleton as off-topic.",
  "The compiler requested emotional support after reading the scary code.",
  "Legend says this ancient curse is still running on localhost.",
  "Legend says this dead COBOL is still running on localhost.",
  "Legend says this haunted graveyard is still running on localhost.",
  "Legend says this haunted legacy is still running on localhost.",
  "Legend says this forgotten graveyard is still running on localhost.",
  "Legend says this cursed graveyard is still running on localhost.",
  "Legend says this dead shadow is still running on localhost.",
  "Legend says this forgotten shadow is still running on localhost.",
  "Legend says this haunted monster is still running on localhost.",
  "Legend says this haunted darkness is still running on localhost.",
  "Legend says this scary COBOL is still running on localhost.",
  "Legend says this cursed SVN is still running on localhost.",
  "Legend says this forgotten curse is still running on localhost.",
  "Legend says this ancient SVN is still running on localhost.",
  "Legend says this dark legacy is still running on localhost.",
  "Legend says this ancient COBOL is still running on localhost.",
  "Legend says this dark curse is still running on localhost.",
  "Legend says this dark shadow is still running on localhost.",
  "Legend says this ancient legacy is still running on localhost.",
  "Legend says this legacy shadow is still running on localhost.",
  "Legend says this cursed darkness is still running on localhost.",
  "Legend says this forgotten legacy is still running on localhost.",
  "Legend says this dark COBOL is still running on localhost.",
  "Legend says this legacy darkness is still running on localhost.",
  "Legend says this dark graveyard is still running on localhost.",
  "Legend says this forgotten skeleton is still running on localhost.",
  "Legend says this dead darkness is still running on localhost.",
  "Legend says this legacy graveyard is still running on localhost.",
  "Legend says this haunted curse is still running on localhost.",
  "Legend says this dead graveyard is still running on localhost.",
  "Legend says this legacy SVN is still running on localhost.",
  "Legend says this scary curse is still running on localhost.",
  "Legend says this cursed curse is still running on localhost.",
  "Legend says this cursed monster is still running on localhost.",
  "Legend says this dead ghost is still running on localhost.",
  "Legend says this dead SVN is still running on localhost.",
  "Legend says this cursed COBOL is still running on localhost.",
  "Legend says this ancient monster is still running on localhost.",
  "Legend says this legacy monster is still running on localhost.",
  "Legend says this haunted skeleton is still running on localhost.",
  "Legend says this dark monster is still running on localhost.",
  "Legend says this scary shadow is still running on localhost.",
  "Legend says this legacy skeleton is still running on localhost.",
  "Legend says this dark SVN is still running on localhost.",
  "Legend says this forgotten darkness is still running on localhost.",
  "Legend says this haunted ghost is still running on localhost.",
  "Legend says this scary legacy is still running on localhost.",
  "Legend says this haunted shadow is still running on localhost.",
  "Legend says this ancient shadow is still running on localhost.",
  "Legend says this scary skeleton is still running on localhost.",
  "Legend says this scary graveyard is still running on localhost.",
  "Legend says this scary monster is still running on localhost.",
  "Legend says this dark skeleton is still running on localhost.",
  "Legend says this cursed skeleton is still running on localhost.",
  "Legend says this legacy ghost is still running on localhost.",
  "Legend says this haunted SVN is still running on localhost.",
  "Legend says this scary SVN is still running on localhost.",
  "Legend says this cursed legacy is still running on localhost.",
  "Legend says this ancient skeleton is still running on localhost.",
  "This is a classic example of a cursed curse disaster.",
  "This is a classic example of a legacy SVN disaster.",
  "This is a classic example of a ancient shadow disaster.",
  "This is a classic example of a dark COBOL disaster.",
  "This is a classic example of a dark darkness disaster.",
  "This is a classic example of a legacy curse disaster.",
  "This is a classic example of a forgotten SVN disaster.",
  "This is a classic example of a scary monster disaster.",
  "This is a classic example of a legacy COBOL disaster.",
  "This is a classic example of a forgotten legacy disaster.",
  "This is a classic example of a dead graveyard disaster.",
  "This is a classic example of a scary curse disaster.",
  "This is a classic example of a dead shadow disaster.",
  "This is a classic example of a cursed monster disaster.",
  "This is a classic example of a dark skeleton disaster.",
  "This is a classic example of a legacy ghost disaster.",
  "This is a classic example of a scary skeleton disaster.",
  "This is a classic example of a ancient monster disaster.",
  "This is a classic example of a forgotten COBOL disaster.",
  "This is a classic example of a dead skeleton disaster.",
  "This is a classic example of a scary legacy disaster.",
  "This is a classic example of a legacy skeleton disaster.",
  "This is a classic example of a dark SVN disaster.",
  "This is a classic example of a cursed SVN disaster.",
  "This is a classic example of a ancient SVN disaster.",
  "This is a classic example of a legacy shadow disaster.",
  "This is a classic example of a dead curse disaster.",
  "This is a classic example of a cursed graveyard disaster.",
  "This is a classic example of a forgotten monster disaster.",
  "This is a classic example of a scary graveyard disaster.",
  "This is a classic example of a forgotten shadow disaster.",
  "This is a classic example of a dead legacy disaster.",
  "This is a classic example of a legacy darkness disaster.",
  "This is a classic example of a scary shadow disaster.",
  "This is a classic example of a haunted shadow disaster.",
  "This is a classic example of a ancient COBOL disaster.",
  "This is a classic example of a forgotten curse disaster.",
  "This is a classic example of a ancient legacy disaster.",
  "This is a classic example of a cursed skeleton disaster.",
  "This is a classic example of a legacy graveyard disaster.",
  "This is a classic example of a dead monster disaster.",
  "This is a classic example of a haunted graveyard disaster.",
  "This is a classic example of a haunted COBOL disaster.",
  "This is a classic example of a scary COBOL disaster."
];

export const verdicts = [
  "Closed as legacy duplicate.",
  "PR compiled legacy COBOL due to dead implementation.",
  "Rejected on first principles of darkness organization.",
  "PR opened index file due to dark implementation.",
  "Needs more commits and fewer explanations.",
  "PR survived server crash due to dead implementation.",
  "Verdict: Darkness is completely unmergeable.",
  "Closed as scary duplicate.",
  "Verdict: Legacy is completely unmergeable.",
  "Ship blocked by forgotten check failures.",
  "PR opened index file due to haunted implementation.",
  "PR screamed in panic due to cursed implementation.",
  "Verdict: Shadow is completely unmergeable.",
  "Request changes on the cursed graveyard.",
  "Return after touching actual production servers.",
  "Request changes on the haunted darkness.",
  "Verdict: Skeleton is completely unmergeable.",
  "Ship blocked by haunted check failures.",
  "Closed as haunted duplicate.",
  "Rejected on first principles of shadow organization.",
  "Verdict: Curse is completely unmergeable.",
  "Ship blocked by scary check failures.",
  "Request changes on the scary COBOL.",
  "PR compiled legacy COBOL due to dark implementation.",
  "PR compiled legacy COBOL due to ancient implementation.",
  "Verdict: Graveyard is completely unmergeable.",
  "Closed as forgotten duplicate.",
  "PR wrote raw pointers due to forgotten implementation.",
  "Ship blocked by legacy check failures.",
  "Closed as ancient duplicate.",
  "Closed as dead duplicate.",
  "Closed as dark duplicate.",
  "Request changes on the cursed legacy.",
  "PR screamed in panic due to scary implementation.",
  "PR wrote raw pointers due to ancient implementation.",
  "PR wrote raw pointers due to dead implementation.",
  "Rejected on first principles of SVN organization.",
  "Verdict: SVN is completely unmergeable.",
  "PR wrote raw pointers due to cursed implementation.",
  "Rejected on first principles of ghost organization.",
  "Request changes on the ancient monster.",
  "PR screamed in panic due to forgotten implementation.",
  "Verdict: COBOL is completely unmergeable.",
  "Request changes on the dead legacy.",
  "Request changes on the dead monster.",
  "Request changes on the cursed SVN.",
  "Request changes on the forgotten legacy.",
  "Rejected on first principles of COBOL organization.",
  "Request changes on the scary darkness.",
  "Request changes on the haunted ghost.",
  "Rejected on first principles of graveyard organization.",
  "Request changes on the haunted legacy.",
  "Rejected on first principles of skeleton organization.",
  "PR compiled legacy COBOL due to haunted implementation.",
  "Rejected on first principles of monster organization.",
  "Request changes on the dead shadow.",
  "PR screamed in panic due to ancient implementation.",
  "Rejected on first principles of legacy organization.",
  "Request changes on the legacy COBOL.",
  "PR survived server crash due to forgotten implementation.",
  "PR screamed in panic due to dark implementation.",
  "Closed as cursed duplicate.",
  "PR compiled legacy COBOL due to cursed implementation.",
  "Ship blocked by dark check failures.",
  "PR survived server crash due to cursed implementation.",
  "Ship blocked by dead check failures.",
  "Ship blocked by ancient check failures.",
  "Request changes on the forgotten darkness.",
  "Request changes on the haunted SVN.",
  "Request changes on the haunted graveyard.",
  "Verdict: Monster is completely unmergeable.",
  "Verdict: Ghost is completely unmergeable.",
  "Request changes on the scary skeleton.",
  "PR opened index file due to ancient implementation.",
  "Request changes on the dark skeleton.",
  "Request changes on the dark graveyard.",
  "Request changes on the dead darkness.",
  "PR survived server crash due to scary implementation.",
  "Request changes on the legacy monster.",
  "PR survived server crash due to haunted implementation.",
  "Ship blocked by cursed check failures.",
  "PR opened index file due to cursed implementation.",
  "Request changes on the ancient legacy.",
  "PR wrote raw pointers due to dark implementation.",
  "PR compiled legacy COBOL due to scary implementation.",
  "Rejected on first principles of curse organization.",
  "Request changes on the legacy skeleton.",
  "PR survived server crash due to legacy implementation.",
  "Request changes on the scary curse.",
  "Request changes on the ancient COBOL.",
  "PR compiled legacy COBOL due to forgotten implementation.",
  "Request changes on the cursed darkness.",
  "Request changes on the legacy curse.",
  "Request changes on the haunted monster.",
  "Request changes on the dark curse.",
  "Request changes on the ancient skeleton.",
  "Request changes on the legacy SVN.",
  "Request changes on the dark monster."
];

export const easterEggs = [
  "NASA Alert: Space mission aborted due to a minor COBOL parsing error.",
  "Dark Web Resume Auction: Current bid is $0.00, and the buyer is requesting a refund.",
  "Steam Achievement Unlocked: Successfully crashed a hello-world app on a $10,000 server.",
  "Elon Musk Tweet: 'Just deleted the entire ghost pipeline, was completely useless.'",
  "FBI Investigation: Suspect was found deploying unencrypted scary skeletons.",
  "Matrix Glitch: You copy-pasted a template and now the server believes it is a real founder.",
  "FBI Investigation: Suspect was found deploying unencrypted legacy ghosts.",
  "Gordon Ramsay Meltdown: 'This skeleton is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted dead SVNs.",
  "FBI Investigation: Suspect was found deploying unencrypted cursed COBOLs.",
  "FBI Investigation: Suspect was found deploying unencrypted forgotten legacys.",
  "Gordon Ramsay Meltdown: 'This ghost is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This graveyard is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This legacy is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This curse is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted ancient monsters.",
  "Gordon Ramsay Meltdown: 'This monster is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This COBOL is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This SVN is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This shadow is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This darkness is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted haunted curses."
];
