// ES Module exports for npm_install_log roast format
export const titles = [
  "Missing Package Error",
  "The Node_modules tragedy",
  "The Shrinkwrap tragedy",
  "The Vulnerability tragedy",
  "Insecure Peer-dep Error",
  "Incident Report: Missing Error",
  "Dependency Not Found",
  "Insecure Error Loop",
  "Node_modules conflict detected",
  "Failed to compile: Shrinkwrap",
  "The Audit tragedy",
  "Absolute Deprecated architecture",
  "Warning Not Found",
  "Peer Error Loop",
  "NullPointerPeer-depException",
  "Incident Report: Insecure Lockfile",
  "Incident Report: Peer Error",
  "Insecure Audit Error",
  "Bloated Shrinkwrap Loop",
  "Shrinkwrap Not Found",
  "Incident Report: Incompatible Audit",
  "Incident Report: Missing Dependency",
  "Deprecated Warning Error",
  "Nested Package Error",
  "Nested Vulnerability Error",
  "Deprecated Dependency Error",
  "Error conflict detected",
  "Missing Peer-dep Loop",
  "Failed to compile: Dependency",
  "Bloated Lockfile Loop",
  "Node_modules Not Found",
  "Failed to compile: Error",
  "Absolute Nested architecture",
  "Vulnerability conflict detected",
  "Absolute Bloated architecture",
  "Critical Error failure",
  "Peer Package Error",
  "Nested Lockfile Loop",
  "Failed to compile: Node_modules",
  "NullPointerDependencyException",
  "Critical Node_modules failure",
  "Critical Warning failure",
  "NullPointerAuditException",
  "Absolute Peer architecture",
  "Peer Shrinkwrap Loop",
  "Failed to compile: Package",
  "Shrinkwrap conflict detected",
  "Lockfile Not Found",
  "Nested Shrinkwrap Error",
  "Incompatible Audit Loop",
  "Nested Vulnerability Loop",
  "Audit Not Found",
  "Incident Report: Insecure Shrinkwrap",
  "The Dependency tragedy",
  "Incident Report: Missing Shrinkwrap",
  "Dependency conflict detected",
  "NullPointerErrorException",
  "Deprecated Vulnerability Loop",
  "Incompatible Package Error",
  "Missing Warning Error",
  "Critical Shrinkwrap failure",
  "Broken Package Error",
  "Incident Report: Missing Peer-dep",
  "Absolute Insecure architecture",
  "Incident Report: Broken Warning",
  "Failed to compile: Peer-dep",
  "Package Not Found",
  "NullPointerNode_modulesException",
  "Critical Audit failure",
  "NullPointerShrinkwrapException",
  "Incident Report: Deprecated Warning",
  "Bloated Error Error",
  "Failed to compile: Lockfile",
  "Deprecated Node_modules Loop",
  "The Warning tragedy",
  "Bloated Shrinkwrap Error",
  "Absolute Missing architecture",
  "Incident Report: Bloated Warning",
  "Package conflict detected",
  "The Lockfile tragedy",
  "Incompatible Audit Error",
  "NullPointerWarningException",
  "Error Not Found",
  "Insecure Dependency Error",
  "The Package tragedy",
  "Absolute Broken architecture",
  "Bloated Warning Loop",
  "Critical Vulnerability failure",
  "Peer Peer-dep Loop",
  "NullPointerPackageException",
  "Incident Report: Nested Vulnerability",
  "Incident Report: Nested Peer-dep",
  "Nested Error Loop",
  "Broken Shrinkwrap Error",
  "Incompatible Dependency Error",
  "Failed to compile: Warning",
  "Insecure Vulnerability Error",
  "Failed to compile: Audit",
  "Failed to compile: Vulnerability",
  "Audit conflict detected"
];

export const openings = [
  "Initial evaluation shows the developer decided to resolved peer-deps with 400 vulnerabilities.",
  "The team has initiated audit for the candidate's lockfile setup.",
  "Alert: The candidate spent three months trying to resolved peer-deps causing disk full.",
  "Warning: System flagged an attempt to downloaded node_modules with high risk.",
  "Warning: System flagged an attempt to ignored vulnerabilities triggering alerts.",
  "Scanning candidate profile for deprecated shrinkwraps...",
  "We checked the history and found a broken audit log.",
  "A review was filed regarding a nested vulnerability.",
  "A review was filed regarding a broken vulnerability.",
  "Recruiters reported a case of incompatible error design.",
  "We checked the history and found a bloated node_modules log.",
  "Initial evaluation shows the developer decided to ran npm audit breaking lockfile.",
  "Alert: The candidate spent three months trying to downloaded node_modules triggering alerts.",
  "We checked the history and found a deprecated error log.",
  "A review was filed regarding a nested peer-dep.",
  "We checked the history and found a incompatible dependency log.",
  "We checked the history and found a deprecated peer-dep log.",
  "Alert: The candidate spent three months trying to bypassed warning checks breaking lockfile.",
  "A review was filed regarding a incompatible shrinkwrap.",
  "Warning: System flagged an attempt to bypassed warning checks triggering alerts.",
  "Scanning candidate profile for nested peer-deps...",
  "Alert: The candidate spent three months trying to ran npm audit triggering alerts.",
  "We checked the history and found a deprecated warning log.",
  "Scanning candidate profile for nested lockfiles...",
  "Recruiters reported a case of missing lockfile design.",
  "Alert: The candidate spent three months trying to downloaded node_modules causing disk full.",
  "We checked the history and found a broken vulnerability log.",
  "Alert: The candidate spent three months trying to ignored vulnerabilities with high risk.",
  "Scanning candidate profile for bloated lockfiles...",
  "Alert: The candidate spent three months trying to ran npm audit breaking lockfile.",
  "A review was filed regarding a deprecated peer-dep.",
  "Warning: System flagged an attempt to downloaded node_modules causing disk full.",
  "Recruiters reported a case of nested peer-dep design.",
  "Scanning candidate profile for incompatible peer-deps...",
  "Scanning candidate profile for nested audits...",
  "We checked the history and found a incompatible lockfile log.",
  "Alert: The candidate spent three months trying to ignored vulnerabilities causing disk full.",
  "Scanning candidate profile for deprecated warnings...",
  "We checked the history and found a bloated vulnerability log.",
  "Initial evaluation shows the developer decided to ran npm audit with high risk.",
  "Initial evaluation shows the developer decided to bypassed warning checks with 400 vulnerabilities.",
  "Scanning candidate profile for insecure audits...",
  "Alert: The candidate spent three months trying to ran npm audit causing disk full.",
  "Recruiters reported a case of missing error design.",
  "Scanning candidate profile for deprecated packages...",
  "Initial evaluation shows the developer decided to ignored vulnerabilities with high risk.",
  "Recruiters reported a case of broken dependency design.",
  "A review was filed regarding a insecure audit.",
  "Scanning candidate profile for insecure dependencys...",
  "Alert: The candidate spent three months trying to ignored vulnerabilities with 400 vulnerabilities.",
  "Scanning candidate profile for deprecated peer-deps...",
  "Initial evaluation shows the developer decided to bypassed warning checks with high risk.",
  "The team has initiated audit for the candidate's node_modules setup.",
  "Recruiters reported a case of nested audit design.",
  "Recruiters reported a case of insecure dependency design.",
  "A review was filed regarding a incompatible warning.",
  "Warning: System flagged an attempt to bypassed warning checks with high risk.",
  "Scanning candidate profile for incompatible vulnerabilitys...",
  "Warning: System flagged an attempt to ignored vulnerabilities with high risk.",
  "Warning: System flagged an attempt to ignored vulnerabilities breaking lockfile.",
  "Initial evaluation shows the developer decided to bypassed warning checks triggering alerts.",
  "Initial evaluation shows the developer decided to ignored vulnerabilities causing disk full.",
  "Warning: System flagged an attempt to downloaded node_modules triggering alerts.",
  "Scanning candidate profile for insecure packages...",
  "We checked the history and found a broken package log.",
  "Scanning candidate profile for broken vulnerabilitys...",
  "Recruiters reported a case of deprecated lockfile design.",
  "Scanning candidate profile for insecure warnings...",
  "Warning: System flagged an attempt to resolved peer-deps causing disk full.",
  "Initial evaluation shows the developer decided to resolved peer-deps causing disk full.",
  "A review was filed regarding a missing vulnerability.",
  "Scanning candidate profile for nested node_moduless...",
  "We checked the history and found a incompatible audit log.",
  "Alert: The candidate spent three months trying to bypassed warning checks with high risk.",
  "Warning: System flagged an attempt to downloaded node_modules breaking lockfile.",
  "A review was filed regarding a peer audit.",
  "A review was filed regarding a incompatible package.",
  "Scanning candidate profile for incompatible audits...",
  "A review was filed regarding a deprecated warning.",
  "Recruiters reported a case of peer lockfile design.",
  "Alert: The candidate spent three months trying to downloaded node_modules with 400 vulnerabilities.",
  "Warning: System flagged an attempt to resolved peer-deps breaking lockfile.",
  "Recruiters reported a case of deprecated package design.",
  "A review was filed regarding a nested package.",
  "Recruiters reported a case of insecure node_modules design.",
  "A review was filed regarding a bloated node_modules.",
  "A review was filed regarding a incompatible error.",
  "Alert: The candidate spent three months trying to bypassed warning checks triggering alerts.",
  "Recruiters reported a case of missing node_modules design.",
  "Warning: System flagged an attempt to resolved peer-deps with 400 vulnerabilities.",
  "A review was filed regarding a peer lockfile.",
  "Warning: System flagged an attempt to ran npm audit with high risk.",
  "A review was filed regarding a broken shrinkwrap.",
  "The team has initiated audit for the candidate's peer-dep setup."
];

export const findings = [
  "{{candidateName}} has spent three weeks optimizing a peer-dep while completely ignoring {{missingSection}}.",
  "The candidate claims {{framework}} experience, but their repository is just a broken clone that has been abandoned.",
  "For {{experience}}, the primary contribution was writing a insecure config for a shrinkwrap.",
  "Obtained {{certification}} which apparently teaches how to ran npm audit with high risk.",
  "Failed to configure {{project}} because {{candidateName}} decided to bypassed warning checks breaking lockfile.",
  "Obtained {{certification}} which apparently teaches how to ignored vulnerabilities breaking lockfile.",
  "For {{experience}}, the primary contribution was writing a missing config for a node_modules.",
  "For {{experience}}, the primary contribution was writing a nested config for a peer-dep.",
  "{{education}} is listed, but they still managed to deploy a nested shrinkwrap to production.",
  "{{education}} is listed, but they still managed to deploy a incompatible audit to production.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to resolved peer-deps causing disk full.",
  "Listed {{skill}} as a primary competency, but the evidence points to a bloated dependency.",
  "Listed {{skill}} as a primary competency, but the evidence points to a broken peer-dep.",
  "A security audit on {{github}} detected a plain-text database password inside a missing node_modules.",
  "{{education}} is listed, but they still managed to deploy a bloated lockfile to production.",
  "Obtained {{certification}} which apparently teaches how to ran npm audit causing disk full.",
  "Obtained {{certification}} which apparently teaches how to ran npm audit triggering alerts.",
  "{{achievement}} was highlighted, but the git logs show they only managed to resolved peer-deps with 400 vulnerabilities.",
  "{{candidateName}} has spent three weeks optimizing a warning while completely ignoring {{missingSection}}.",
  "While debugging {{project}}, we found a deprecated logic loop related to {{language}} features.",
  "{{achievement}} was highlighted, but the git logs show they only managed to resolved peer-deps triggering alerts.",
  "{{github}} contains more peer peer-deps than original code.",
  "Listed {{skill}} as a primary competency, but the evidence points to a incompatible lockfile.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to downloaded node_modules with 400 vulnerabilities.",
  "Listed {{skill}} as a primary competency, but the evidence points to a insecure node_modules.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ran npm audit breaking lockfile.",
  "{{education}} is listed, but they still managed to deploy a incompatible peer-dep to production.",
  "Obtained {{certification}} which apparently teaches how to downloaded node_modules with high risk.",
  "{{achievement}} was highlighted, but the git logs show they only managed to resolved peer-deps breaking lockfile.",
  "Failed to configure {{project}} because {{candidateName}} decided to resolved peer-deps causing disk full.",
  "{{github}} contains more insecure shrinkwraps than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to downloaded node_modules with high risk.",
  "A security audit on {{github}} detected a plain-text database password inside a bloated warning.",
  "{{github}} contains more deprecated audits than original code.",
  "{{github}} contains more broken vulnerabilitys than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to bypassed warning checks with high risk.",
  "Failed to configure {{project}} because {{candidateName}} decided to ran npm audit with 400 vulnerabilities.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to downloaded node_modules causing disk full.",
  "Obtained {{certification}} which apparently teaches how to resolved peer-deps with 400 vulnerabilities.",
  "Listed {{skill}} as a primary competency, but the evidence points to a broken audit.",
  "{{candidateName}} has spent three weeks optimizing a node_modules while completely ignoring {{missingSection}}.",
  "Failed to configure {{project}} because {{candidateName}} decided to ran npm audit causing disk full.",
  "A security audit on {{github}} detected a plain-text database password inside a nested dependency.",
  "{{github}} contains more insecure dependencys than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to bypassed warning checks breaking lockfile.",
  "{{education}} is listed, but they still managed to deploy a missing warning to production.",
  "A security audit on {{github}} detected a plain-text database password inside a deprecated audit.",
  "{{github}} contains more missing errors than original code.",
  "{{github}} contains more nested lockfiles than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to ignored vulnerabilities with 400 vulnerabilities.",
  "{{github}} contains more broken dependencys than original code.",
  "{{github}} contains more broken packages than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ran npm audit with high risk.",
  "Obtained {{certification}} which apparently teaches how to ignored vulnerabilities with 400 vulnerabilities.",
  "{{github}} contains more nested warnings than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to resolved peer-deps causing disk full.",
  "Listed {{skill}} as a primary competency, but the evidence points to a insecure shrinkwrap.",
  "{{achievement}} was highlighted, but the git logs show they only managed to bypassed warning checks causing disk full.",
  "For {{experience}}, the primary contribution was writing a incompatible config for a error.",
  "For {{experience}}, the primary contribution was writing a broken config for a warning.",
  "Obtained {{certification}} which apparently teaches how to downloaded node_modules breaking lockfile.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ran npm audit causing disk full.",
  "{{education}} is listed, but they still managed to deploy a peer node_modules to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ran npm audit causing disk full.",
  "{{github}} contains more peer audits than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ran npm audit breaking lockfile.",
  "A security audit on {{github}} detected a plain-text database password inside a missing error.",
  "{{github}} contains more bloated node_moduless than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ignored vulnerabilities triggering alerts.",
  "Failed to configure {{project}} because {{candidateName}} decided to ran npm audit breaking lockfile.",
  "Obtained {{certification}} which apparently teaches how to downloaded node_modules triggering alerts.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to downloaded node_modules breaking lockfile.",
  "Obtained {{certification}} which apparently teaches how to bypassed warning checks triggering alerts.",
  "A security audit on {{github}} detected a plain-text database password inside a broken package.",
  "{{education}} is listed, but they still managed to deploy a deprecated vulnerability to production.",
  "{{github}} contains more nested audits than original code.",
  "{{github}} contains more bloated warnings than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a incompatible vulnerability.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ignored vulnerabilities with high risk.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ignored vulnerabilities breaking lockfile.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ran npm audit with high risk.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to bypassed warning checks triggering alerts.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ran npm audit with 400 vulnerabilities.",
  "Obtained {{certification}} which apparently teaches how to bypassed warning checks with 400 vulnerabilities.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to bypassed warning checks causing disk full.",
  "{{achievement}} was highlighted, but the git logs show they only managed to bypassed warning checks triggering alerts.",
  "Obtained {{certification}} which apparently teaches how to bypassed warning checks breaking lockfile.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to resolved peer-deps breaking lockfile.",
  "Failed to configure {{project}} because {{candidateName}} decided to ran npm audit triggering alerts.",
  "{{achievement}} was highlighted, but the git logs show they only managed to downloaded node_modules causing disk full.",
  "{{github}} contains more peer errors than original code.",
  "Obtained {{certification}} which apparently teaches how to ignored vulnerabilities with high risk.",
  "A security audit on {{github}} detected a plain-text database password inside a broken peer-dep.",
  "Listed {{skill}} as a primary competency, but the evidence points to a peer package.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to resolved peer-deps triggering alerts.",
  "{{achievement}} was highlighted, but the git logs show they only managed to downloaded node_modules breaking lockfile.",
  "Obtained {{certification}} which apparently teaches how to downloaded node_modules with 400 vulnerabilities.",
  "{{github}} contains more nested shrinkwraps than original code.",
  "Obtained {{certification}} which apparently teaches how to ran npm audit breaking lockfile.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ignored vulnerabilities causing disk full.",
  "{{github}} contains more peer lockfiles than original code.",
  "For {{experience}}, the primary contribution was writing a missing config for a vulnerability.",
  "{{achievement}} was highlighted, but the git logs show they only managed to downloaded node_modules with 400 vulnerabilities.",
  "{{education}} is listed, but they still managed to deploy a insecure error to production.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ignored vulnerabilities with high risk.",
  "Obtained {{certification}} which apparently teaches how to resolved peer-deps causing disk full.",
  "{{education}} is listed, but they still managed to deploy a peer dependency to production.",
  "{{github}} contains more broken errors than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to bypassed warning checks with 400 vulnerabilities.",
  "{{github}} contains more bloated audits than original code.",
  "{{github}} contains more peer warnings than original code.",
  "Obtained {{certification}} which apparently teaches how to downloaded node_modules causing disk full.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ran npm audit with 400 vulnerabilities.",
  "For {{experience}}, the primary contribution was writing a bloated config for a audit.",
  "Listed {{skill}} as a primary competency, but the evidence points to a missing error.",
  "{{github}} contains more broken audits than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a insecure shrinkwrap.",
  "{{github}} contains more insecure audits than original code.",
  "For {{experience}}, the primary contribution was writing a peer config for a lockfile."
];

export const punchlines = [
  "A junior developer looked at the warning and immediately went to touch grass.",
  "Legend says this deprecated dependency is still running on localhost.",
  "The documentation was so empty, I had to use it as a virtual sketchbook.",
  "Legend says this nested peer-dep is still running on localhost.",
  "We would deploy it to production, but our SRE team deserves to sleep at night.",
  "It did not optimize our process, but it did make the laptop fan spin like a jet engine.",
  "A junior developer looked at the node_modules and immediately went to touch grass.",
  "Even Stack Overflow has marked this error as off-topic.",
  "The only thing memory-safe about this setup is that nobody has ever tried to run it.",
  "The compiler requested emotional support after reading the insecure code.",
  "Legend says this incompatible node_modules is still running on localhost.",
  "Legend says this insecure lockfile is still running on localhost.",
  "Legend says this nested shrinkwrap is still running on localhost.",
  "Legend says this deprecated shrinkwrap is still running on localhost.",
  "Even Stack Overflow has marked this node_modules as off-topic.",
  "Legend says this broken shrinkwrap is still running on localhost.",
  "Even Stack Overflow has marked this peer-dep as off-topic.",
  "Legend says this incompatible warning is still running on localhost.",
  "A junior developer looked at the peer-dep and immediately went to touch grass.",
  "Legend says this incompatible shrinkwrap is still running on localhost.",
  "Legend says this incompatible dependency is still running on localhost.",
  "Legend says this broken dependency is still running on localhost.",
  "Legend says this missing error is still running on localhost.",
  "Legend says this incompatible error is still running on localhost.",
  "Legend says this broken error is still running on localhost.",
  "Legend says this bloated shrinkwrap is still running on localhost.",
  "Legend says this deprecated vulnerability is still running on localhost.",
  "Legend says this nested package is still running on localhost.",
  "Legend says this broken lockfile is still running on localhost.",
  "Legend says this peer lockfile is still running on localhost.",
  "Legend says this bloated lockfile is still running on localhost.",
  "Legend says this missing package is still running on localhost.",
  "Legend says this insecure shrinkwrap is still running on localhost.",
  "Legend says this missing warning is still running on localhost.",
  "Legend says this insecure dependency is still running on localhost.",
  "Legend says this insecure warning is still running on localhost.",
  "Legend says this peer package is still running on localhost.",
  "Legend says this broken package is still running on localhost.",
  "Legend says this nested lockfile is still running on localhost.",
  "Legend says this incompatible package is still running on localhost.",
  "Legend says this peer vulnerability is still running on localhost.",
  "Legend says this insecure error is still running on localhost.",
  "Legend says this nested dependency is still running on localhost.",
  "Legend says this missing dependency is still running on localhost.",
  "Legend says this deprecated lockfile is still running on localhost.",
  "Legend says this insecure vulnerability is still running on localhost.",
  "Legend says this nested error is still running on localhost.",
  "Legend says this bloated package is still running on localhost.",
  "Legend says this nested warning is still running on localhost.",
  "Legend says this bloated vulnerability is still running on localhost.",
  "Legend says this missing vulnerability is still running on localhost.",
  "Legend says this deprecated audit is still running on localhost.",
  "Legend says this broken vulnerability is still running on localhost.",
  "Legend says this bloated dependency is still running on localhost.",
  "Legend says this peer warning is still running on localhost.",
  "Legend says this incompatible lockfile is still running on localhost.",
  "Legend says this broken warning is still running on localhost.",
  "Legend says this peer error is still running on localhost.",
  "Legend says this peer audit is still running on localhost.",
  "This is a classic example of a deprecated dependency disaster.",
  "This is a classic example of a missing lockfile disaster.",
  "This is a classic example of a missing node_modules disaster.",
  "This is a classic example of a missing package disaster.",
  "This is a classic example of a bloated node_modules disaster.",
  "This is a classic example of a incompatible peer-dep disaster.",
  "This is a classic example of a missing shrinkwrap disaster.",
  "This is a classic example of a deprecated audit disaster.",
  "This is a classic example of a nested peer-dep disaster.",
  "This is a classic example of a incompatible package disaster.",
  "This is a classic example of a peer error disaster.",
  "This is a classic example of a incompatible vulnerability disaster.",
  "This is a classic example of a nested lockfile disaster.",
  "This is a classic example of a peer dependency disaster.",
  "This is a classic example of a broken error disaster.",
  "This is a classic example of a missing dependency disaster.",
  "This is a classic example of a missing error disaster.",
  "This is a classic example of a deprecated lockfile disaster.",
  "This is a classic example of a nested audit disaster.",
  "This is a classic example of a peer vulnerability disaster.",
  "This is a classic example of a broken shrinkwrap disaster.",
  "This is a classic example of a peer audit disaster.",
  "This is a classic example of a broken lockfile disaster.",
  "This is a classic example of a nested error disaster.",
  "This is a classic example of a missing vulnerability disaster.",
  "This is a classic example of a deprecated vulnerability disaster.",
  "This is a classic example of a insecure error disaster.",
  "This is a classic example of a deprecated shrinkwrap disaster.",
  "This is a classic example of a broken dependency disaster.",
  "This is a classic example of a deprecated error disaster.",
  "This is a classic example of a peer lockfile disaster.",
  "This is a classic example of a peer warning disaster.",
  "This is a classic example of a nested node_modules disaster.",
  "This is a classic example of a peer package disaster.",
  "This is a classic example of a missing audit disaster.",
  "This is a classic example of a incompatible error disaster.",
  "This is a classic example of a insecure package disaster.",
  "This is a classic example of a nested vulnerability disaster.",
  "This is a classic example of a bloated vulnerability disaster."
];

export const verdicts = [
  "Needs more commits and fewer explanations.",
  "Verdict: Audit is completely unmergeable.",
  "Verdict: Node_modules is completely unmergeable.",
  "Verdict: Vulnerability is completely unmergeable.",
  "Ship blocked by incompatible check failures.",
  "Ship blocked by deprecated check failures.",
  "Closed as missing duplicate.",
  "PR resolved peer-deps due to broken implementation.",
  "Verdict: Lockfile is completely unmergeable.",
  "Rejected on first principles of audit organization.",
  "Ship blocked by broken check failures.",
  "Request changes on the incompatible lockfile.",
  "Verdict: Dependency is completely unmergeable.",
  "Request changes on the bloated error.",
  "PR bypassed warning checks due to broken implementation.",
  "Verdict: Peer-dep is completely unmergeable.",
  "Return after touching actual production servers.",
  "Verdict: Package is completely unmergeable.",
  "Closed as broken duplicate.",
  "Ship blocked by bloated check failures.",
  "PR resolved peer-deps due to nested implementation.",
  "PR ignored vulnerabilities due to incompatible implementation.",
  "PR downloaded node_modules due to incompatible implementation.",
  "PR downloaded node_modules due to insecure implementation.",
  "PR downloaded node_modules due to peer implementation.",
  "Rejected on first principles of node_modules organization.",
  "Verdict: Warning is completely unmergeable.",
  "Ship blocked by insecure check failures.",
  "Request changes on the missing node_modules.",
  "PR bypassed warning checks due to missing implementation.",
  "Closed as insecure duplicate.",
  "PR resolved peer-deps due to bloated implementation.",
  "Rejected on first principles of error organization.",
  "Request changes on the broken dependency.",
  "PR resolved peer-deps due to incompatible implementation.",
  "Rejected on first principles of dependency organization.",
  "PR bypassed warning checks due to bloated implementation.",
  "Closed as deprecated duplicate.",
  "Rejected on first principles of package organization.",
  "Request changes on the broken vulnerability.",
  "PR ran npm audit due to nested implementation.",
  "Ship blocked by peer check failures.",
  "Verdict: Shrinkwrap is completely unmergeable.",
  "Request changes on the missing audit.",
  "Request changes on the broken shrinkwrap.",
  "Request changes on the peer package.",
  "Rejected on first principles of shrinkwrap organization.",
  "Rejected on first principles of peer-dep organization.",
  "Request changes on the broken error.",
  "Ship blocked by missing check failures.",
  "Request changes on the incompatible shrinkwrap.",
  "Request changes on the bloated warning.",
  "Request changes on the insecure audit.",
  "PR ran npm audit due to peer implementation.",
  "PR ignored vulnerabilities due to nested implementation.",
  "Closed as peer duplicate.",
  "Request changes on the peer shrinkwrap.",
  "Verdict: Error is completely unmergeable.",
  "PR ran npm audit due to deprecated implementation.",
  "Ship blocked by nested check failures.",
  "PR resolved peer-deps due to insecure implementation.",
  "PR ignored vulnerabilities due to missing implementation.",
  "Rejected on first principles of vulnerability organization.",
  "Closed as incompatible duplicate.",
  "Request changes on the incompatible peer-dep.",
  "Request changes on the deprecated warning.",
  "PR downloaded node_modules due to broken implementation.",
  "PR resolved peer-deps due to missing implementation.",
  "Request changes on the insecure node_modules.",
  "PR bypassed warning checks due to peer implementation.",
  "Rejected on first principles of warning organization.",
  "PR ignored vulnerabilities due to peer implementation.",
  "Request changes on the peer vulnerability.",
  "Closed as nested duplicate.",
  "Request changes on the deprecated package.",
  "Request changes on the incompatible warning.",
  "Request changes on the nested dependency.",
  "PR bypassed warning checks due to insecure implementation.",
  "PR downloaded node_modules due to nested implementation.",
  "Request changes on the deprecated dependency.",
  "PR ignored vulnerabilities due to insecure implementation.",
  "Request changes on the nested warning.",
  "PR ran npm audit due to insecure implementation.",
  "PR bypassed warning checks due to incompatible implementation.",
  "Request changes on the bloated dependency.",
  "Closed as bloated duplicate.",
  "Request changes on the broken package.",
  "Request changes on the insecure dependency.",
  "PR ran npm audit due to missing implementation.",
  "Request changes on the insecure error.",
  "Request changes on the missing vulnerability.",
  "Request changes on the nested package.",
  "Request changes on the incompatible vulnerability.",
  "Request changes on the nested error.",
  "PR ignored vulnerabilities due to deprecated implementation.",
  "Request changes on the broken peer-dep.",
  "Request changes on the bloated audit.",
  "Request changes on the deprecated node_modules.",
  "Request changes on the deprecated audit."
];

export const easterEggs = [
  "Steam Achievement Unlocked: Successfully crashed a hello-world app on a $10,000 server.",
  "Dark Web Resume Auction: Current bid is $0.00, and the buyer is requesting a refund.",
  "FBI Investigation: Suspect was found deploying unencrypted nested warnings.",
  "Elon Musk Tweet: 'Just deleted the entire node_modules pipeline, was completely useless.'",
  "Elon Musk Tweet: 'Just deleted the entire dependency pipeline, was completely useless.'",
  "NASA Alert: Space mission aborted due to a minor shrinkwrap parsing error.",
  "Matrix Glitch: You copy-pasted a template and now the server believes it is a real founder.",
  "FBI Investigation: Suspect was found deploying unencrypted broken lockfiles.",
  "Gordon Ramsay Meltdown: 'This error is raw! It's absolutely raw!'",
  "NASA Alert: Space mission aborted due to a minor node_modules parsing error.",
  "Gordon Ramsay Meltdown: 'This dependency is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted insecure dependencys.",
  "FBI Investigation: Suspect was found deploying unencrypted deprecated shrinkwraps.",
  "Gordon Ramsay Meltdown: 'This audit is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted bloated vulnerabilitys.",
  "Gordon Ramsay Meltdown: 'This lockfile is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This vulnerability is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This warning is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted missing node_moduless.",
  "FBI Investigation: Suspect was found deploying unencrypted insecure peer-deps.",
  "Gordon Ramsay Meltdown: 'This package is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This node_modules is raw! It's absolutely raw!'",
  "NASA Alert: Space mission aborted due to a minor peer-dep parsing error.",
  "Gordon Ramsay Meltdown: 'This shrinkwrap is raw! It's absolutely raw!'",
  "Elon Musk Tweet: 'Just deleted the entire peer-dep pipeline, was completely useless.'",
  "Gordon Ramsay Meltdown: 'This peer-dep is raw! It's absolutely raw!'"
];
