// ES Module exports for police_report roast format
export const titles = [
  "Critical Officer failure",
  "Failed to compile: Arrest",
  "Arrest conflict detected",
  "Logs Not Found",
  "Database Not Found",
  "Scene Not Found",
  "Incident Report: Unauthorized Arrest",
  "NullPointerSuspectException",
  "Destructive Backup Error",
  "Crash Not Found",
  "Incident Report: Unauthorized Backup",
  "Missing Officer Error",
  "Missing Arrest Error",
  "NullPointerBackupException",
  "Logs conflict detected",
  "Clumsy Suspect Loop",
  "Incident Report: Hostile Incident",
  "Unstable Arrest Loop",
  "Incident Not Found",
  "NullPointerSceneException",
  "NullPointerArrestException",
  "Critical Database failure",
  "Absolute Hostile architecture",
  "Hostile Breach Error",
  "NullPointerDatabaseException",
  "Hostile Officer Loop",
  "Arrest Not Found",
  "Incident Report: Unstable Backup",
  "Unstable Officer Error",
  "Critical Incident failure",
  "The Backup tragedy",
  "Absolute Destructive architecture",
  "Incident Report: Hostile Breach",
  "NullPointerLogsException",
  "Breach Not Found",
  "NullPointerOfficerException",
  "Critical Scene failure",
  "NullPointerIncidentException",
  "NullPointerBreachException",
  "The Scene tragedy",
  "Absolute Raw architecture",
  "Hostile Breach Loop",
  "Hostile Database Error",
  "The Incident tragedy",
  "Hostile Logs Error",
  "Clumsy Database Loop",
  "Unstable Breach Error",
  "Clumsy Officer Loop",
  "Incident Report: Missing Database",
  "Breach conflict detected",
  "The Breach tragedy",
  "Suspicious Backup Error",
  "Incident Report: Destructive Logs",
  "Incident conflict detected",
  "Failed to compile: Breach",
  "Database conflict detected",
  "Absolute Unauthorized architecture",
  "The Officer tragedy",
  "Incident Report: Destructive Breach",
  "Failed to compile: Database",
  "Failed to compile: Incident",
  "Suspicious Incident Error",
  "Officer Not Found",
  "Raw Crash Error",
  "Absolute Clumsy architecture",
  "NullPointerCrashException",
  "Clumsy Database Error",
  "Incident Report: Unstable Scene",
  "Incident Report: Clumsy Suspect",
  "Suspect Not Found",
  "Critical Suspect failure",
  "Suspicious Backup Loop",
  "Unstable Logs Error",
  "Raw Officer Loop",
  "Incident Report: Suspicious Backup",
  "Incident Report: Suspicious Database",
  "Critical Logs failure",
  "Raw Breach Error",
  "Suspect conflict detected",
  "Incident Report: Missing Crash",
  "Absolute Unstable architecture",
  "Critical Arrest failure",
  "Failed to compile: Logs",
  "Suspicious Breach Error",
  "Incident Report: Raw Officer",
  "Officer conflict detected",
  "Incident Report: Raw Crash",
  "Raw Suspect Error",
  "Suspicious Suspect Loop",
  "Incident Report: Hostile Crash",
  "Incident Report: Clumsy Backup",
  "Failed to compile: Backup",
  "Raw Scene Loop",
  "Backup conflict detected",
  "Failed to compile: Scene",
  "Failed to compile: Officer",
  "Incident Report: Raw Backup",
  "Unstable Incident Error",
  "Failed to compile: Suspect",
  "The Crash tragedy"
];

export const openings = [
  "We checked the history and found a unstable scene log.",
  "Scanning candidate profile for suspicious backups...",
  "Scanning candidate profile for suspicious arrests...",
  "Initial evaluation shows the developer decided to arrested suspect developer leaving zero logs behind.",
  "Initial evaluation shows the developer decided to investigated database crash at the scene of crash.",
  "Warning: System flagged an attempt to traced unauthorized breach using hardcoded shell commands.",
  "Scanning candidate profile for hostile suspects...",
  "Recruiters reported a case of hostile logs design.",
  "Recruiters reported a case of raw incident design.",
  "A review was filed regarding a unauthorized database.",
  "Initial evaluation shows the developer decided to deleted backup history without valid key credentials.",
  "Initial evaluation shows the developer decided to deleted backup history using hardcoded shell commands.",
  "Warning: System flagged an attempt to wiped local database leaving zero logs behind.",
  "Recruiters reported a case of raw crash design.",
  "Scanning candidate profile for suspicious logss...",
  "A review was filed regarding a raw logs.",
  "Warning: System flagged an attempt to investigated database crash leaving zero logs behind.",
  "Recruiters reported a case of destructive officer design.",
  "Alert: The candidate spent three months trying to wiped local database forcing recovery protocols.",
  "Alert: The candidate spent three months trying to arrested suspect developer at the scene of crash.",
  "We checked the history and found a raw incident log.",
  "Initial evaluation shows the developer decided to deleted backup history forcing recovery protocols.",
  "A review was filed regarding a suspicious backup.",
  "Initial evaluation shows the developer decided to wiped local database without valid key credentials.",
  "The team has initiated audit for the candidate's suspect setup.",
  "Warning: System flagged an attempt to investigated database crash using hardcoded shell commands.",
  "We checked the history and found a unstable breach log.",
  "We checked the history and found a destructive database log.",
  "Initial evaluation shows the developer decided to arrested suspect developer without valid key credentials.",
  "Recruiters reported a case of clumsy suspect design.",
  "We checked the history and found a unstable incident log.",
  "A review was filed regarding a raw crash.",
  "Initial evaluation shows the developer decided to wiped local database at the scene of crash.",
  "Warning: System flagged an attempt to wiped local database using hardcoded shell commands.",
  "Scanning candidate profile for unauthorized breachs...",
  "Scanning candidate profile for destructive arrests...",
  "Scanning candidate profile for clumsy incidents...",
  "Recruiters reported a case of missing breach design.",
  "We checked the history and found a missing breach log.",
  "A review was filed regarding a unstable crash.",
  "We checked the history and found a raw officer log.",
  "We checked the history and found a clumsy scene log.",
  "We checked the history and found a unauthorized crash log.",
  "Alert: The candidate spent three months trying to investigated database crash at the scene of crash.",
  "A review was filed regarding a destructive database.",
  "Warning: System flagged an attempt to deleted backup history forcing recovery protocols.",
  "A review was filed regarding a hostile officer.",
  "A review was filed regarding a destructive suspect.",
  "Scanning candidate profile for clumsy officers...",
  "Scanning candidate profile for missing databases...",
  "Alert: The candidate spent three months trying to deleted backup history without valid key credentials.",
  "Recruiters reported a case of suspicious incident design.",
  "Alert: The candidate spent three months trying to investigated database crash without valid key credentials.",
  "Recruiters reported a case of destructive crash design.",
  "Warning: System flagged an attempt to wiped local database at the scene of crash.",
  "A review was filed regarding a hostile crash.",
  "We checked the history and found a clumsy arrest log.",
  "Alert: The candidate spent three months trying to investigated database crash forcing recovery protocols.",
  "We checked the history and found a suspicious backup log.",
  "Alert: The candidate spent three months trying to wiped local database without valid key credentials.",
  "Alert: The candidate spent three months trying to arrested suspect developer leaving zero logs behind.",
  "Warning: System flagged an attempt to traced unauthorized breach forcing recovery protocols.",
  "Scanning candidate profile for unauthorized arrests...",
  "Warning: System flagged an attempt to arrested suspect developer without valid key credentials.",
  "Warning: System flagged an attempt to arrested suspect developer forcing recovery protocols.",
  "We checked the history and found a hostile arrest log.",
  "Recruiters reported a case of missing logs design.",
  "Alert: The candidate spent three months trying to traced unauthorized breach without valid key credentials.",
  "Initial evaluation shows the developer decided to deleted backup history at the scene of crash.",
  "A review was filed regarding a clumsy scene.",
  "Alert: The candidate spent three months trying to traced unauthorized breach at the scene of crash.",
  "Initial evaluation shows the developer decided to wiped local database forcing recovery protocols.",
  "A review was filed regarding a suspicious incident.",
  "Scanning candidate profile for hostile breachs...",
  "Alert: The candidate spent three months trying to deleted backup history at the scene of crash.",
  "Initial evaluation shows the developer decided to arrested suspect developer using hardcoded shell commands.",
  "Initial evaluation shows the developer decided to investigated database crash forcing recovery protocols.",
  "Warning: System flagged an attempt to deleted backup history at the scene of crash.",
  "Warning: System flagged an attempt to arrested suspect developer at the scene of crash.",
  "Initial evaluation shows the developer decided to arrested suspect developer at the scene of crash.",
  "Recruiters reported a case of unauthorized suspect design.",
  "We checked the history and found a unauthorized scene log.",
  "We checked the history and found a missing crash log.",
  "Alert: The candidate spent three months trying to deleted backup history using hardcoded shell commands.",
  "Initial evaluation shows the developer decided to deleted backup history leaving zero logs behind.",
  "We checked the history and found a raw backup log.",
  "A review was filed regarding a hostile breach.",
  "A review was filed regarding a clumsy incident.",
  "Initial evaluation shows the developer decided to arrested suspect developer forcing recovery protocols.",
  "Scanning candidate profile for suspicious databases...",
  "We checked the history and found a destructive scene log.",
  "Recruiters reported a case of suspicious logs design."
];

export const findings = [
  "Obtained {{certification}} which apparently teaches how to investigated database crash leaving zero logs behind.",
  "Obtained {{certification}} which apparently teaches how to arrested suspect developer without valid key credentials.",
  "While debugging {{project}}, we found a unstable logic loop related to {{language}} features.",
  "{{github}} contains more destructive incidents than original code.",
  "The candidate claims {{framework}} experience, but their repository is just a unauthorized clone that has been abandoned.",
  "Obtained {{certification}} which apparently teaches how to wiped local database using hardcoded shell commands.",
  "{{github}} contains more unauthorized databases than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to traced unauthorized breach using hardcoded shell commands.",
  "{{github}} contains more unstable crashs than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a clumsy crash.",
  "{{github}} contains more unstable logss than original code.",
  "{{education}} is listed, but they still managed to deploy a missing logs to production.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to arrested suspect developer using hardcoded shell commands.",
  "A security audit on {{github}} detected a plain-text database password inside a suspicious suspect.",
  "Obtained {{certification}} which apparently teaches how to wiped local database leaving zero logs behind.",
  "{{education}} is listed, but they still managed to deploy a unstable officer to production.",
  "Listed {{skill}} as a primary competency, but the evidence points to a clumsy crash.",
  "Obtained {{certification}} which apparently teaches how to wiped local database without valid key credentials.",
  "Listed {{skill}} as a primary competency, but the evidence points to a hostile suspect.",
  "{{candidateName}} has spent three weeks optimizing a crash while completely ignoring {{missingSection}}.",
  "{{achievement}} was highlighted, but the git logs show they only managed to arrested suspect developer leaving zero logs behind.",
  "{{github}} contains more unauthorized logss than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to wiped local database using hardcoded shell commands.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to investigated database crash leaving zero logs behind.",
  "Obtained {{certification}} which apparently teaches how to wiped local database at the scene of crash.",
  "Obtained {{certification}} which apparently teaches how to traced unauthorized breach at the scene of crash.",
  "{{education}} is listed, but they still managed to deploy a destructive suspect to production.",
  "For {{experience}}, the primary contribution was writing a destructive config for a suspect.",
  "A security audit on {{github}} detected a plain-text database password inside a destructive logs.",
  "{{achievement}} was highlighted, but the git logs show they only managed to investigated database crash forcing recovery protocols.",
  "Failed to configure {{project}} because {{candidateName}} decided to wiped local database forcing recovery protocols.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to investigated database crash at the scene of crash.",
  "For {{experience}}, the primary contribution was writing a unauthorized config for a officer.",
  "A security audit on {{github}} detected a plain-text database password inside a missing breach.",
  "Failed to configure {{project}} because {{candidateName}} decided to traced unauthorized breach at the scene of crash.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to investigated database crash forcing recovery protocols.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to traced unauthorized breach at the scene of crash.",
  "{{education}} is listed, but they still managed to deploy a unauthorized arrest to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to arrested suspect developer without valid key credentials.",
  "Obtained {{certification}} which apparently teaches how to deleted backup history leaving zero logs behind.",
  "Failed to configure {{project}} because {{candidateName}} decided to arrested suspect developer without valid key credentials.",
  "{{achievement}} was highlighted, but the git logs show they only managed to deleted backup history using hardcoded shell commands.",
  "{{education}} is listed, but they still managed to deploy a clumsy crash to production.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to deleted backup history without valid key credentials.",
  "{{github}} contains more clumsy databases than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to deleted backup history using hardcoded shell commands.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to wiped local database forcing recovery protocols.",
  "A security audit on {{github}} detected a plain-text database password inside a hostile incident.",
  "{{achievement}} was highlighted, but the git logs show they only managed to traced unauthorized breach without valid key credentials.",
  "Listed {{skill}} as a primary competency, but the evidence points to a raw logs.",
  "Failed to configure {{project}} because {{candidateName}} decided to traced unauthorized breach forcing recovery protocols.",
  "Obtained {{certification}} which apparently teaches how to deleted backup history at the scene of crash.",
  "{{github}} contains more suspicious scenes than original code.",
  "Listed {{skill}} as a primary competency, but the evidence points to a unauthorized scene.",
  "{{github}} contains more missing officers than original code.",
  "{{github}} contains more suspicious backups than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to traced unauthorized breach using hardcoded shell commands.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to wiped local database without valid key credentials.",
  "Failed to configure {{project}} because {{candidateName}} decided to arrested suspect developer forcing recovery protocols.",
  "Obtained {{certification}} which apparently teaches how to arrested suspect developer at the scene of crash.",
  "Obtained {{certification}} which apparently teaches how to traced unauthorized breach using hardcoded shell commands.",
  "Failed to configure {{project}} because {{candidateName}} decided to investigated database crash leaving zero logs behind.",
  "{{achievement}} was highlighted, but the git logs show they only managed to investigated database crash at the scene of crash.",
  "{{github}} contains more hostile databases than original code.",
  "Obtained {{certification}} which apparently teaches how to arrested suspect developer leaving zero logs behind.",
  "{{github}} contains more suspicious incidents than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to deleted backup history forcing recovery protocols.",
  "{{achievement}} was highlighted, but the git logs show they only managed to wiped local database forcing recovery protocols.",
  "For {{experience}}, the primary contribution was writing a missing config for a backup.",
  "{{achievement}} was highlighted, but the git logs show they only managed to investigated database crash leaving zero logs behind.",
  "{{achievement}} was highlighted, but the git logs show they only managed to traced unauthorized breach at the scene of crash.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to deleted backup history at the scene of crash.",
  "For {{experience}}, the primary contribution was writing a unstable config for a database.",
  "Obtained {{certification}} which apparently teaches how to investigated database crash at the scene of crash.",
  "{{github}} contains more hostile breachs than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to arrested suspect developer leaving zero logs behind.",
  "Failed to configure {{project}} because {{candidateName}} decided to deleted backup history using hardcoded shell commands.",
  "{{achievement}} was highlighted, but the git logs show they only managed to traced unauthorized breach forcing recovery protocols.",
  "{{github}} contains more clumsy incidents than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to deleted backup history forcing recovery protocols.",
  "{{github}} contains more raw crashs than original code.",
  "Obtained {{certification}} which apparently teaches how to wiped local database forcing recovery protocols.",
  "{{achievement}} was highlighted, but the git logs show they only managed to investigated database crash without valid key credentials.",
  "{{github}} contains more missing arrests than original code.",
  "{{education}} is listed, but they still managed to deploy a suspicious database to production.",
  "{{github}} contains more missing backups than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to investigated database crash without valid key credentials.",
  "{{achievement}} was highlighted, but the git logs show they only managed to wiped local database using hardcoded shell commands.",
  "{{github}} contains more destructive suspects than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a unauthorized scene.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to traced unauthorized breach using hardcoded shell commands.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to arrested suspect developer without valid key credentials.",
  "{{github}} contains more missing suspects than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to wiped local database using hardcoded shell commands.",
  "Failed to configure {{project}} because {{candidateName}} decided to wiped local database leaving zero logs behind.",
  "{{achievement}} was highlighted, but the git logs show they only managed to arrested suspect developer at the scene of crash.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to traced unauthorized breach without valid key credentials.",
  "Listed {{skill}} as a primary competency, but the evidence points to a missing breach.",
  "Failed to configure {{project}} because {{candidateName}} decided to deleted backup history at the scene of crash.",
  "{{github}} contains more suspicious logss than original code.",
  "Obtained {{certification}} which apparently teaches how to traced unauthorized breach without valid key credentials.",
  "{{github}} contains more unauthorized breachs than original code.",
  "{{github}} contains more unstable backups than original code.",
  "{{github}} contains more missing incidents than original code.",
  "{{github}} contains more clumsy arrests than original code.",
  "Obtained {{certification}} which apparently teaches how to deleted backup history forcing recovery protocols.",
  "Failed to configure {{project}} because {{candidateName}} decided to arrested suspect developer leaving zero logs behind.",
  "{{github}} contains more unstable breachs than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to traced unauthorized breach without valid key credentials.",
  "Failed to configure {{project}} because {{candidateName}} decided to traced unauthorized breach leaving zero logs behind.",
  "{{github}} contains more suspicious officers than original code.",
  "{{github}} contains more missing breachs than original code.",
  "{{github}} contains more suspicious breachs than original code.",
  "Obtained {{certification}} which apparently teaches how to deleted backup history using hardcoded shell commands.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to traced unauthorized breach forcing recovery protocols.",
  "A security audit on {{github}} detected a plain-text database password inside a unstable officer.",
  "{{achievement}} was highlighted, but the git logs show they only managed to deleted backup history leaving zero logs behind.",
  "{{github}} contains more destructive backups than original code.",
  "Obtained {{certification}} which apparently teaches how to arrested suspect developer using hardcoded shell commands."
];

export const punchlines = [
  "It did not optimize our process, but it did make the laptop fan spin like a jet engine.",
  "Legend says this unauthorized suspect is still running on localhost.",
  "Legend says this unauthorized logs is still running on localhost.",
  "Even Stack Overflow has marked this suspect as off-topic.",
  "Legend says this hostile incident is still running on localhost.",
  "We would deploy it to production, but our SRE team deserves to sleep at night.",
  "A junior developer looked at the breach and immediately went to touch grass.",
  "The only thing memory-safe about this setup is that nobody has ever tried to run it.",
  "Legend says this suspicious scene is still running on localhost.",
  "The documentation was so empty, I had to use it as a virtual sketchbook.",
  "The compiler requested emotional support after reading the hostile code.",
  "Legend says this destructive officer is still running on localhost.",
  "Legend says this hostile crash is still running on localhost.",
  "Legend says this unauthorized incident is still running on localhost.",
  "Legend says this clumsy backup is still running on localhost.",
  "Legend says this suspicious officer is still running on localhost.",
  "Legend says this clumsy incident is still running on localhost.",
  "Legend says this missing officer is still running on localhost.",
  "Legend says this unstable database is still running on localhost.",
  "Legend says this unstable crash is still running on localhost.",
  "Legend says this destructive breach is still running on localhost.",
  "Legend says this raw crash is still running on localhost.",
  "Legend says this clumsy database is still running on localhost.",
  "Legend says this hostile scene is still running on localhost.",
  "Legend says this raw incident is still running on localhost.",
  "Legend says this missing backup is still running on localhost.",
  "Legend says this unstable suspect is still running on localhost.",
  "Legend says this unauthorized scene is still running on localhost.",
  "Legend says this unstable incident is still running on localhost.",
  "Legend says this hostile backup is still running on localhost.",
  "Legend says this destructive scene is still running on localhost.",
  "Legend says this raw suspect is still running on localhost.",
  "Legend says this destructive incident is still running on localhost.",
  "Legend says this clumsy arrest is still running on localhost.",
  "Legend says this unauthorized crash is still running on localhost.",
  "Legend says this destructive database is still running on localhost.",
  "Legend says this unstable scene is still running on localhost.",
  "Legend says this destructive suspect is still running on localhost.",
  "Legend says this clumsy officer is still running on localhost.",
  "Legend says this suspicious database is still running on localhost.",
  "Legend says this raw scene is still running on localhost.",
  "Legend says this destructive backup is still running on localhost.",
  "Legend says this suspicious crash is still running on localhost.",
  "Legend says this missing logs is still running on localhost.",
  "Legend says this unstable backup is still running on localhost.",
  "Legend says this clumsy scene is still running on localhost.",
  "Legend says this suspicious suspect is still running on localhost.",
  "Legend says this suspicious arrest is still running on localhost.",
  "Legend says this hostile arrest is still running on localhost.",
  "Legend says this missing database is still running on localhost.",
  "Legend says this unauthorized backup is still running on localhost.",
  "Legend says this unstable logs is still running on localhost.",
  "Legend says this raw logs is still running on localhost.",
  "Legend says this clumsy breach is still running on localhost.",
  "Legend says this missing incident is still running on localhost.",
  "Legend says this hostile suspect is still running on localhost.",
  "Legend says this raw backup is still running on localhost.",
  "Legend says this suspicious incident is still running on localhost.",
  "Legend says this unstable breach is still running on localhost.",
  "Legend says this destructive crash is still running on localhost.",
  "Legend says this suspicious breach is still running on localhost.",
  "Legend says this destructive arrest is still running on localhost.",
  "Legend says this hostile database is still running on localhost.",
  "Legend says this unauthorized arrest is still running on localhost.",
  "Legend says this destructive logs is still running on localhost.",
  "Legend says this raw arrest is still running on localhost.",
  "Legend says this unauthorized breach is still running on localhost.",
  "Legend says this hostile breach is still running on localhost.",
  "Legend says this unauthorized officer is still running on localhost.",
  "Legend says this raw officer is still running on localhost.",
  "Legend says this hostile officer is still running on localhost.",
  "Legend says this hostile logs is still running on localhost.",
  "Legend says this unstable arrest is still running on localhost.",
  "This is a classic example of a missing logs disaster.",
  "This is a classic example of a destructive logs disaster.",
  "This is a classic example of a hostile backup disaster.",
  "This is a classic example of a raw officer disaster.",
  "This is a classic example of a suspicious backup disaster.",
  "This is a classic example of a suspicious scene disaster.",
  "This is a classic example of a hostile officer disaster.",
  "This is a classic example of a clumsy database disaster.",
  "This is a classic example of a unauthorized logs disaster.",
  "This is a classic example of a unstable backup disaster.",
  "This is a classic example of a raw suspect disaster.",
  "This is a classic example of a hostile logs disaster.",
  "This is a classic example of a suspicious breach disaster.",
  "This is a classic example of a hostile arrest disaster.",
  "This is a classic example of a hostile breach disaster.",
  "This is a classic example of a unstable crash disaster.",
  "This is a classic example of a destructive crash disaster.",
  "This is a classic example of a destructive suspect disaster.",
  "This is a classic example of a unauthorized breach disaster.",
  "This is a classic example of a unstable officer disaster.",
  "This is a classic example of a suspicious database disaster.",
  "This is a classic example of a destructive incident disaster.",
  "This is a classic example of a unauthorized incident disaster.",
  "This is a classic example of a clumsy breach disaster.",
  "This is a classic example of a raw backup disaster.",
  "This is a classic example of a unstable arrest disaster.",
  "This is a classic example of a clumsy crash disaster.",
  "This is a classic example of a raw scene disaster.",
  "This is a classic example of a missing incident disaster.",
  "This is a classic example of a unstable breach disaster.",
  "This is a classic example of a suspicious suspect disaster.",
  "This is a classic example of a unauthorized scene disaster.",
  "This is a classic example of a unauthorized suspect disaster.",
  "This is a classic example of a destructive officer disaster.",
  "This is a classic example of a unstable scene disaster.",
  "This is a classic example of a missing arrest disaster.",
  "This is a classic example of a raw database disaster.",
  "This is a classic example of a raw incident disaster.",
  "This is a classic example of a missing backup disaster."
];

export const verdicts = [
  "Ship blocked by destructive check failures.",
  "Ship blocked by clumsy check failures.",
  "Rejected on first principles of arrest organization.",
  "PR investigated database crash due to clumsy implementation.",
  "Rejected on first principles of scene organization.",
  "PR traced unauthorized breach due to raw implementation.",
  "PR investigated database crash due to unstable implementation.",
  "Needs more commits and fewer explanations.",
  "Ship blocked by unstable check failures.",
  "Verdict: Breach is completely unmergeable.",
  "Rejected on first principles of logs organization.",
  "Return after touching actual production servers.",
  "Closed as clumsy duplicate.",
  "Ship blocked by suspicious check failures.",
  "PR deleted backup history due to destructive implementation.",
  "Rejected on first principles of crash organization.",
  "Request changes on the hostile scene.",
  "Closed as raw duplicate.",
  "Closed as missing duplicate.",
  "Closed as hostile duplicate.",
  "Ship blocked by unauthorized check failures.",
  "Rejected on first principles of database organization.",
  "PR arrested suspect developer due to raw implementation.",
  "Request changes on the clumsy arrest.",
  "Request changes on the missing breach.",
  "Ship blocked by missing check failures.",
  "Rejected on first principles of breach organization.",
  "Request changes on the missing suspect.",
  "Closed as suspicious duplicate.",
  "Ship blocked by hostile check failures.",
  "Verdict: Arrest is completely unmergeable.",
  "Verdict: Incident is completely unmergeable.",
  "PR arrested suspect developer due to unstable implementation.",
  "Rejected on first principles of suspect organization.",
  "Request changes on the suspicious logs.",
  "Closed as unstable duplicate.",
  "PR traced unauthorized breach due to unstable implementation.",
  "Closed as unauthorized duplicate.",
  "PR investigated database crash due to missing implementation.",
  "PR traced unauthorized breach due to destructive implementation.",
  "Request changes on the unstable suspect.",
  "Verdict: Logs is completely unmergeable.",
  "Request changes on the suspicious officer.",
  "Rejected on first principles of officer organization.",
  "Request changes on the hostile backup.",
  "Request changes on the suspicious database.",
  "Request changes on the unauthorized incident.",
  "PR wiped local database due to missing implementation.",
  "PR investigated database crash due to destructive implementation.",
  "PR traced unauthorized breach due to suspicious implementation.",
  "PR arrested suspect developer due to suspicious implementation.",
  "Rejected on first principles of backup organization.",
  "Verdict: Database is completely unmergeable.",
  "Request changes on the hostile database.",
  "Rejected on first principles of incident organization.",
  "PR wiped local database due to unauthorized implementation.",
  "Request changes on the hostile suspect.",
  "PR deleted backup history due to clumsy implementation.",
  "Verdict: Scene is completely unmergeable.",
  "Request changes on the destructive crash.",
  "Request changes on the unauthorized database.",
  "PR deleted backup history due to unstable implementation.",
  "Verdict: Suspect is completely unmergeable.",
  "PR traced unauthorized breach due to clumsy implementation.",
  "Request changes on the unauthorized suspect.",
  "Request changes on the missing incident.",
  "PR traced unauthorized breach due to missing implementation.",
  "Verdict: Backup is completely unmergeable.",
  "Request changes on the destructive breach.",
  "Request changes on the hostile breach.",
  "PR wiped local database due to hostile implementation.",
  "PR wiped local database due to suspicious implementation.",
  "PR wiped local database due to destructive implementation.",
  "PR arrested suspect developer due to missing implementation.",
  "Request changes on the suspicious arrest.",
  "Request changes on the hostile arrest.",
  "Verdict: Crash is completely unmergeable.",
  "Ship blocked by raw check failures.",
  "PR deleted backup history due to unauthorized implementation.",
  "Request changes on the clumsy crash.",
  "PR traced unauthorized breach due to hostile implementation.",
  "Verdict: Officer is completely unmergeable.",
  "Request changes on the hostile incident.",
  "Request changes on the destructive scene.",
  "Request changes on the raw scene.",
  "PR deleted backup history due to missing implementation.",
  "Request changes on the raw breach.",
  "Closed as destructive duplicate.",
  "Request changes on the clumsy breach.",
  "Request changes on the suspicious scene.",
  "Request changes on the unauthorized logs.",
  "PR arrested suspect developer due to hostile implementation.",
  "Request changes on the unauthorized backup.",
  "Request changes on the missing scene.",
  "PR deleted backup history due to raw implementation.",
  "Request changes on the missing database.",
  "Request changes on the destructive database.",
  "Request changes on the hostile officer.",
  "Request changes on the missing logs.",
  "PR deleted backup history due to suspicious implementation."
];

export const easterEggs = [
  "Elon Musk Tweet: 'Just deleted the entire arrest pipeline, was completely useless.'",
  "FBI Investigation: Suspect was found deploying unencrypted clumsy incidents.",
  "Matrix Glitch: You copy-pasted a template and now the server believes it is a real founder.",
  "Dark Web Resume Auction: Current bid is $0.00, and the buyer is requesting a refund.",
  "NASA Alert: Space mission aborted due to a minor arrest parsing error.",
  "Gordon Ramsay Meltdown: 'This logs is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This database is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted unstable arrests.",
  "Steam Achievement Unlocked: Successfully crashed a hello-world app on a $10,000 server.",
  "Gordon Ramsay Meltdown: 'This scene is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted hostile suspects.",
  "FBI Investigation: Suspect was found deploying unencrypted suspicious databases.",
  "FBI Investigation: Suspect was found deploying unencrypted destructive logss.",
  "Gordon Ramsay Meltdown: 'This backup is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This officer is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted raw breachs.",
  "Gordon Ramsay Meltdown: 'This breach is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This crash is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This arrest is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This incident is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted missing crashs.",
  "FBI Investigation: Suspect was found deploying unencrypted unauthorized backups."
];
