// ES Module exports for security_audit roast format
export const titles = [
  "NullPointerExploitException",
  "Cve conflict detected",
  "Leaked Injection Error",
  "Default Overflow Error",
  "Critical Injection failure",
  "Weak Scanner Error",
  "Critical Cve failure",
  "Absolute Exposed architecture",
  "Cve Not Found",
  "Credentials Not Found",
  "Failed to compile: Injection",
  "Scanner conflict detected",
  "The Credentials tragedy",
  "Leaked Cve Error",
  "Absolute Leaked architecture",
  "Failed to compile: Exploit",
  "Weak Cve Loop",
  "Plain-text Token Error",
  "Raw Breach Loop",
  "NullPointerCveException",
  "Absolute Unencrypted architecture",
  "Failed to compile: Credentials",
  "Breach conflict detected",
  "The Firewall tragedy",
  "Critical Exploit failure",
  "Unencrypted Firewall Error",
  "Exposed Overflow Error",
  "Critical Breach failure",
  "Plain-text Credentials Error",
  "The Overflow tragedy",
  "Incident Report: Weak Credentials",
  "Payload Not Found",
  "Incident Report: Raw Payload",
  "Critical Overflow failure",
  "Incident Report: Plain-text Firewall",
  "Failed to compile: Breach",
  "Exposed Payload Error",
  "Incident Report: Raw Injection",
  "Firewall Not Found",
  "Absolute Weak architecture",
  "Overflow Not Found",
  "Critical Scanner failure",
  "Firewall conflict detected",
  "Unencrypted Firewall Loop",
  "Incident Report: Exposed Exploit",
  "Unencrypted Exploit Loop",
  "Plain-text Cve Error",
  "NullPointerInjectionException",
  "Leaked Scanner Loop",
  "Absolute Raw architecture",
  "Incident Report: Leaked Credentials",
  "Breach Not Found",
  "Critical Credentials failure",
  "NullPointerPayloadException",
  "Credentials conflict detected",
  "The Injection tragedy",
  "Unencrypted Cve Loop",
  "Hardcoded Token Error",
  "Leaked Firewall Error",
  "Token Not Found",
  "Scanner Not Found",
  "Incident Report: Leaked Payload",
  "Failed to compile: Payload",
  "Default Cve Error",
  "The Payload tragedy",
  "Default Credentials Loop",
  "Exposed Cve Loop",
  "Unencrypted Token Error",
  "The Exploit tragedy",
  "Incident Report: Exposed Credentials",
  "Plain-text Payload Loop",
  "Failed to compile: Overflow",
  "Token conflict detected",
  "NullPointerTokenException",
  "Critical Firewall failure",
  "Raw Firewall Error",
  "The Cve tragedy",
  "Default Firewall Error",
  "Failed to compile: Token",
  "Critical Token failure",
  "Incident Report: Hardcoded Exploit",
  "Injection Not Found",
  "NullPointerScannerException",
  "Incident Report: Default Cve",
  "NullPointerBreachException",
  "Absolute Hardcoded architecture",
  "Incident Report: Hardcoded Scanner",
  "Leaked Credentials Error",
  "NullPointerFirewallException",
  "Hardcoded Firewall Error",
  "Incident Report: Exposed Injection",
  "Incident Report: Plain-text Credentials",
  "Incident Report: Plain-text Exploit",
  "Raw Credentials Loop",
  "Unencrypted Breach Loop",
  "NullPointerCredentialsException",
  "Weak Payload Error",
  "Incident Report: Plain-text Payload",
  "Plain-text Injection Error",
  "Incident Report: Plain-text Token"
];

export const openings = [
  "Scanning candidate profile for raw injections...",
  "We checked the history and found a leaked breach log.",
  "We checked the history and found a unencrypted exploit log.",
  "Scanning candidate profile for hardcoded overflows...",
  "Alert: The candidate spent three months trying to detected credentials via SQL injection.",
  "Warning: System flagged an attempt to injected payload to public git logs.",
  "The team has initiated audit for the candidate's credentials setup.",
  "Scanning candidate profile for default breachs...",
  "Warning: System flagged an attempt to exploited overflow compromising root access.",
  "Recruiters reported a case of plain-text exploit design.",
  "Warning: System flagged an attempt to detected credentials compromising root access.",
  "Initial evaluation shows the developer decided to injected payload to public git logs.",
  "Scanning candidate profile for default payloads...",
  "Initial evaluation shows the developer decided to bypassed firewall to public git logs.",
  "Recruiters reported a case of plain-text breach design.",
  "Recruiters reported a case of hardcoded scanner design.",
  "A review was filed regarding a weak injection.",
  "Recruiters reported a case of plain-text scanner design.",
  "A review was filed regarding a exposed overflow.",
  "A review was filed regarding a hardcoded injection.",
  "Recruiters reported a case of exposed credentials design.",
  "We checked the history and found a plain-text credentials log.",
  "A review was filed regarding a unencrypted token.",
  "A review was filed regarding a unencrypted exploit.",
  "Warning: System flagged an attempt to bypassed firewall in local directory.",
  "Recruiters reported a case of default injection design.",
  "A review was filed regarding a exposed injection.",
  "Warning: System flagged an attempt to scanned endpoint without authorization.",
  "A review was filed regarding a unencrypted firewall.",
  "Recruiters reported a case of leaked token design.",
  "Alert: The candidate spent three months trying to exploited overflow in local directory.",
  "We checked the history and found a hardcoded injection log.",
  "We checked the history and found a exposed credentials log.",
  "Scanning candidate profile for weak scanners...",
  "Scanning candidate profile for default overflows...",
  "Alert: The candidate spent three months trying to scanned endpoint compromising root access.",
  "Initial evaluation shows the developer decided to scanned endpoint to public git logs.",
  "Alert: The candidate spent three months trying to injected payload compromising root access.",
  "Warning: System flagged an attempt to detected credentials to public git logs.",
  "Alert: The candidate spent three months trying to detected credentials in local directory.",
  "A review was filed regarding a leaked breach.",
  "A review was filed regarding a plain-text breach.",
  "Recruiters reported a case of raw overflow design.",
  "Alert: The candidate spent three months trying to exploited overflow without authorization.",
  "Alert: The candidate spent three months trying to bypassed firewall to public git logs.",
  "Warning: System flagged an attempt to detected credentials via SQL injection.",
  "Scanning candidate profile for unencrypted overflows...",
  "Recruiters reported a case of weak cve design.",
  "We checked the history and found a raw injection log.",
  "Recruiters reported a case of exposed scanner design.",
  "Scanning candidate profile for plain-text exploits...",
  "Warning: System flagged an attempt to bypassed firewall without authorization.",
  "Recruiters reported a case of exposed firewall design.",
  "Initial evaluation shows the developer decided to scanned endpoint without authorization.",
  "Initial evaluation shows the developer decided to bypassed firewall via SQL injection.",
  "Scanning candidate profile for leaked cves...",
  "Recruiters reported a case of leaked scanner design.",
  "Alert: The candidate spent three months trying to injected payload in local directory.",
  "A review was filed regarding a weak scanner.",
  "Alert: The candidate spent three months trying to exploited overflow to public git logs.",
  "Recruiters reported a case of hardcoded breach design.",
  "A review was filed regarding a raw firewall.",
  "Initial evaluation shows the developer decided to detected credentials in local directory.",
  "Alert: The candidate spent three months trying to injected payload to public git logs.",
  "We checked the history and found a weak injection log.",
  "Alert: The candidate spent three months trying to scanned endpoint without authorization.",
  "A review was filed regarding a plain-text token.",
  "Warning: System flagged an attempt to scanned endpoint compromising root access.",
  "A review was filed regarding a default exploit.",
  "A review was filed regarding a exposed token.",
  "Initial evaluation shows the developer decided to bypassed firewall in local directory.",
  "Initial evaluation shows the developer decided to detected credentials to public git logs.",
  "Scanning candidate profile for default exploits...",
  "Initial evaluation shows the developer decided to exploited overflow without authorization.",
  "Scanning candidate profile for weak breachs...",
  "We checked the history and found a unencrypted token log.",
  "Recruiters reported a case of default exploit design.",
  "Warning: System flagged an attempt to scanned endpoint to public git logs.",
  "Alert: The candidate spent three months trying to bypassed firewall without authorization.",
  "Initial evaluation shows the developer decided to exploited overflow to public git logs.",
  "A review was filed regarding a hardcoded token.",
  "A review was filed regarding a exposed cve.",
  "Initial evaluation shows the developer decided to bypassed firewall without authorization.",
  "Recruiters reported a case of plain-text injection design.",
  "A review was filed regarding a weak credentials.",
  "Alert: The candidate spent three months trying to detected credentials without authorization.",
  "We checked the history and found a default overflow log.",
  "Alert: The candidate spent three months trying to bypassed firewall via SQL injection.",
  "Warning: System flagged an attempt to scanned endpoint via SQL injection.",
  "A review was filed regarding a weak firewall."
];

export const findings = [
  "For {{experience}}, the primary contribution was writing a unencrypted config for a injection.",
  "{{github}} contains more unencrypted scanners than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to exploited overflow via SQL injection.",
  "For {{experience}}, the primary contribution was writing a hardcoded config for a credentials.",
  "{{achievement}} was highlighted, but the git logs show they only managed to injected payload via SQL injection.",
  "While debugging {{project}}, we found a raw logic loop related to {{language}} features.",
  "{{achievement}} was highlighted, but the git logs show they only managed to scanned endpoint in local directory.",
  "A security audit on {{github}} detected a plain-text database password inside a plain-text injection.",
  "{{candidateName}} has spent three weeks optimizing a payload while completely ignoring {{missingSection}}.",
  "Obtained {{certification}} which apparently teaches how to injected payload to public git logs.",
  "The candidate claims {{framework}} experience, but their repository is just a exposed clone that has been abandoned.",
  "Failed to configure {{project}} because {{candidateName}} decided to exploited overflow to public git logs.",
  "{{achievement}} was highlighted, but the git logs show they only managed to scanned endpoint compromising root access.",
  "Failed to configure {{project}} because {{candidateName}} decided to scanned endpoint compromising root access.",
  "Failed to configure {{project}} because {{candidateName}} decided to scanned endpoint to public git logs.",
  "Obtained {{certification}} which apparently teaches how to exploited overflow via SQL injection.",
  "Obtained {{certification}} which apparently teaches how to bypassed firewall compromising root access.",
  "For {{experience}}, the primary contribution was writing a plain-text config for a overflow.",
  "Listed {{skill}} as a primary competency, but the evidence points to a hardcoded exploit.",
  "{{achievement}} was highlighted, but the git logs show they only managed to bypassed firewall via SQL injection.",
  "Obtained {{certification}} which apparently teaches how to injected payload without authorization.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to bypassed firewall in local directory.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to exploited overflow without authorization.",
  "Failed to configure {{project}} because {{candidateName}} decided to detected credentials compromising root access.",
  "Listed {{skill}} as a primary competency, but the evidence points to a weak payload.",
  "{{education}} is listed, but they still managed to deploy a plain-text injection to production.",
  "{{education}} is listed, but they still managed to deploy a default credentials to production.",
  "Failed to configure {{project}} because {{candidateName}} decided to injected payload compromising root access.",
  "{{education}} is listed, but they still managed to deploy a leaked overflow to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to exploited overflow in local directory.",
  "{{achievement}} was highlighted, but the git logs show they only managed to detected credentials via SQL injection.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to detected credentials to public git logs.",
  "Obtained {{certification}} which apparently teaches how to scanned endpoint without authorization.",
  "Obtained {{certification}} which apparently teaches how to detected credentials without authorization.",
  "Listed {{skill}} as a primary competency, but the evidence points to a leaked cve.",
  "{{education}} is listed, but they still managed to deploy a unencrypted token to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to exploited overflow without authorization.",
  "For {{experience}}, the primary contribution was writing a weak config for a overflow.",
  "Obtained {{certification}} which apparently teaches how to detected credentials to public git logs.",
  "Obtained {{certification}} which apparently teaches how to exploited overflow in local directory.",
  "Obtained {{certification}} which apparently teaches how to scanned endpoint in local directory.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to injected payload to public git logs.",
  "A security audit on {{github}} detected a plain-text database password inside a weak firewall.",
  "Failed to configure {{project}} because {{candidateName}} decided to detected credentials without authorization.",
  "Listed {{skill}} as a primary competency, but the evidence points to a exposed firewall.",
  "{{achievement}} was highlighted, but the git logs show they only managed to bypassed firewall in local directory.",
  "Obtained {{certification}} which apparently teaches how to bypassed firewall to public git logs.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to scanned endpoint compromising root access.",
  "Failed to configure {{project}} because {{candidateName}} decided to exploited overflow without authorization.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to injected payload compromising root access.",
  "For {{experience}}, the primary contribution was writing a exposed config for a cve.",
  "{{github}} contains more hardcoded tokens than original code.",
  "Obtained {{certification}} which apparently teaches how to injected payload in local directory.",
  "{{education}} is listed, but they still managed to deploy a exposed cve to production.",
  "A security audit on {{github}} detected a plain-text database password inside a exposed scanner.",
  "{{achievement}} was highlighted, but the git logs show they only managed to injected payload without authorization.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to exploited overflow to public git logs.",
  "A security audit on {{github}} detected a plain-text database password inside a raw breach.",
  "{{github}} contains more unencrypted overflows than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to detected credentials to public git logs.",
  "{{achievement}} was highlighted, but the git logs show they only managed to exploited overflow compromising root access.",
  "A security audit on {{github}} detected a plain-text database password inside a leaked credentials.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to scanned endpoint to public git logs.",
  "Listed {{skill}} as a primary competency, but the evidence points to a unencrypted token.",
  "For {{experience}}, the primary contribution was writing a raw config for a scanner.",
  "For {{experience}}, the primary contribution was writing a default config for a firewall.",
  "A security audit on {{github}} detected a plain-text database password inside a hardcoded cve.",
  "Obtained {{certification}} which apparently teaches how to scanned endpoint via SQL injection.",
  "{{education}} is listed, but they still managed to deploy a raw firewall to production.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to scanned endpoint via SQL injection.",
  "Failed to configure {{project}} because {{candidateName}} decided to scanned endpoint in local directory.",
  "Failed to configure {{project}} because {{candidateName}} decided to bypassed firewall without authorization.",
  "{{education}} is listed, but they still managed to deploy a hardcoded injection to production.",
  "Obtained {{certification}} which apparently teaches how to bypassed firewall in local directory.",
  "Failed to configure {{project}} because {{candidateName}} decided to scanned endpoint via SQL injection.",
  "{{achievement}} was highlighted, but the git logs show they only managed to scanned endpoint without authorization.",
  "Obtained {{certification}} which apparently teaches how to injected payload compromising root access.",
  "Failed to configure {{project}} because {{candidateName}} decided to exploited overflow compromising root access.",
  "{{github}} contains more raw exploits than original code.",
  "{{github}} contains more unencrypted injections than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to injected payload compromising root access.",
  "{{github}} contains more unencrypted cves than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to injected payload without authorization.",
  "{{github}} contains more raw overflows than original code.",
  "Obtained {{certification}} which apparently teaches how to injected payload via SQL injection.",
  "{{achievement}} was highlighted, but the git logs show they only managed to detected credentials compromising root access.",
  "{{github}} contains more plain-text credentialss than original code.",
  "For {{experience}}, the primary contribution was writing a leaked config for a breach.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to bypassed firewall to public git logs.",
  "{{github}} contains more exposed payloads than original code.",
  "{{github}} contains more leaked credentialss than original code.",
  "While debugging {{project}}, we found a plain-text logic loop related to {{language}} features.",
  "{{github}} contains more unencrypted payloads than original code.",
  "{{github}} contains more exposed scanners than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to injected payload in local directory.",
  "{{github}} contains more exposed injections than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to injected payload via SQL injection.",
  "Listed {{skill}} as a primary competency, but the evidence points to a plain-text breach.",
  "Failed to configure {{project}} because {{candidateName}} decided to exploited overflow in local directory.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to bypassed firewall compromising root access.",
  "Failed to configure {{project}} because {{candidateName}} decided to scanned endpoint without authorization.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to exploited overflow in local directory.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to detected credentials in local directory.",
  "Failed to configure {{project}} because {{candidateName}} decided to exploited overflow via SQL injection.",
  "Listed {{skill}} as a primary competency, but the evidence points to a default scanner.",
  "Obtained {{certification}} which apparently teaches how to exploited overflow without authorization.",
  "Obtained {{certification}} which apparently teaches how to detected credentials via SQL injection.",
  "{{github}} contains more weak payloads than original code.",
  "Obtained {{certification}} which apparently teaches how to detected credentials in local directory.",
  "Failed to configure {{project}} because {{candidateName}} decided to injected payload without authorization.",
  "Obtained {{certification}} which apparently teaches how to exploited overflow to public git logs.",
  "Obtained {{certification}} which apparently teaches how to scanned endpoint to public git logs.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to injected payload in local directory.",
  "Failed to configure {{project}} because {{candidateName}} decided to bypassed firewall via SQL injection.",
  "Obtained {{certification}} which apparently teaches how to exploited overflow compromising root access.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to bypassed firewall without authorization.",
  "{{github}} contains more leaked cves than original code.",
  "{{github}} contains more default firewalls than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to scanned endpoint in local directory.",
  "Failed to configure {{project}} because {{candidateName}} decided to detected credentials via SQL injection.",
  "{{github}} contains more default injections than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to injected payload via SQL injection.",
  "Failed to configure {{project}} because {{candidateName}} decided to injected payload to public git logs.",
  "{{education}} is listed, but they still managed to deploy a weak breach to production.",
  "{{github}} contains more leaked payloads than original code."
];

export const punchlines = [
  "Even Stack Overflow has marked this overflow as off-topic.",
  "It did not optimize our process, but it did make the laptop fan spin like a jet engine.",
  "The compiler requested emotional support after reading the raw code.",
  "Legend says this exposed injection is still running on localhost.",
  "The only thing memory-safe about this setup is that nobody has ever tried to run it.",
  "The documentation was so empty, I had to use it as a virtual sketchbook.",
  "We would deploy it to production, but our SRE team deserves to sleep at night.",
  "Legend says this exposed payload is still running on localhost.",
  "Legend says this plain-text firewall is still running on localhost.",
  "Legend says this weak overflow is still running on localhost.",
  "A junior developer looked at the payload and immediately went to touch grass.",
  "Legend says this raw payload is still running on localhost.",
  "Legend says this raw cve is still running on localhost.",
  "Legend says this leaked overflow is still running on localhost.",
  "Legend says this hardcoded scanner is still running on localhost.",
  "Legend says this default credentials is still running on localhost.",
  "Legend says this raw scanner is still running on localhost.",
  "The compiler requested emotional support after reading the plain-text code.",
  "Legend says this unencrypted firewall is still running on localhost.",
  "Legend says this weak payload is still running on localhost.",
  "Legend says this default exploit is still running on localhost.",
  "Legend says this exposed credentials is still running on localhost.",
  "Legend says this raw injection is still running on localhost.",
  "Legend says this exposed breach is still running on localhost.",
  "Legend says this leaked firewall is still running on localhost.",
  "Legend says this hardcoded overflow is still running on localhost.",
  "Legend says this leaked cve is still running on localhost.",
  "Legend says this default scanner is still running on localhost.",
  "Legend says this default token is still running on localhost.",
  "Legend says this unencrypted token is still running on localhost.",
  "Legend says this unencrypted injection is still running on localhost.",
  "Legend says this hardcoded exploit is still running on localhost.",
  "Legend says this unencrypted payload is still running on localhost.",
  "Legend says this unencrypted scanner is still running on localhost.",
  "Legend says this weak scanner is still running on localhost.",
  "Legend says this raw firewall is still running on localhost.",
  "Legend says this default payload is still running on localhost.",
  "Legend says this exposed token is still running on localhost.",
  "Legend says this raw overflow is still running on localhost.",
  "Legend says this default overflow is still running on localhost.",
  "Legend says this hardcoded token is still running on localhost.",
  "Legend says this weak token is still running on localhost.",
  "Legend says this weak cve is still running on localhost.",
  "Legend says this hardcoded breach is still running on localhost.",
  "Legend says this leaked breach is still running on localhost.",
  "Legend says this leaked scanner is still running on localhost.",
  "Legend says this default breach is still running on localhost.",
  "Legend says this unencrypted breach is still running on localhost.",
  "Legend says this leaked token is still running on localhost.",
  "Legend says this weak breach is still running on localhost.",
  "Legend says this exposed cve is still running on localhost.",
  "Legend says this raw token is still running on localhost.",
  "Legend says this exposed exploit is still running on localhost.",
  "Legend says this default firewall is still running on localhost.",
  "Legend says this leaked exploit is still running on localhost.",
  "Legend says this default cve is still running on localhost.",
  "Legend says this unencrypted cve is still running on localhost.",
  "Legend says this weak exploit is still running on localhost.",
  "Legend says this exposed firewall is still running on localhost.",
  "Legend says this exposed overflow is still running on localhost.",
  "Legend says this leaked payload is still running on localhost.",
  "Legend says this raw exploit is still running on localhost.",
  "Legend says this leaked credentials is still running on localhost.",
  "Legend says this leaked injection is still running on localhost.",
  "Legend says this hardcoded firewall is still running on localhost.",
  "Legend says this weak firewall is still running on localhost.",
  "Legend says this raw breach is still running on localhost.",
  "Legend says this weak credentials is still running on localhost.",
  "This is a classic example of a raw token disaster.",
  "This is a classic example of a default exploit disaster.",
  "This is a classic example of a plain-text overflow disaster.",
  "This is a classic example of a default cve disaster.",
  "This is a classic example of a plain-text breach disaster.",
  "This is a classic example of a default breach disaster.",
  "This is a classic example of a hardcoded firewall disaster.",
  "This is a classic example of a leaked injection disaster.",
  "This is a classic example of a hardcoded injection disaster.",
  "This is a classic example of a plain-text payload disaster.",
  "This is a classic example of a hardcoded overflow disaster.",
  "This is a classic example of a plain-text token disaster.",
  "This is a classic example of a exposed payload disaster.",
  "This is a classic example of a weak firewall disaster.",
  "This is a classic example of a leaked overflow disaster.",
  "This is a classic example of a leaked cve disaster.",
  "This is a classic example of a unencrypted cve disaster.",
  "This is a classic example of a hardcoded cve disaster.",
  "This is a classic example of a plain-text cve disaster.",
  "This is a classic example of a raw breach disaster.",
  "This is a classic example of a weak scanner disaster.",
  "This is a classic example of a weak payload disaster.",
  "This is a classic example of a exposed credentials disaster.",
  "This is a classic example of a unencrypted breach disaster.",
  "This is a classic example of a default scanner disaster.",
  "This is a classic example of a raw overflow disaster.",
  "This is a classic example of a unencrypted payload disaster.",
  "This is a classic example of a weak cve disaster.",
  "This is a classic example of a weak credentials disaster.",
  "This is a classic example of a exposed token disaster.",
  "This is a classic example of a leaked payload disaster.",
  "This is a classic example of a default credentials disaster.",
  "This is a classic example of a hardcoded credentials disaster.",
  "This is a classic example of a exposed overflow disaster.",
  "This is a classic example of a raw credentials disaster.",
  "This is a classic example of a exposed exploit disaster.",
  "This is a classic example of a raw firewall disaster.",
  "This is a classic example of a hardcoded breach disaster."
];

export const verdicts = [
  "Ship blocked by weak check failures.",
  "Verdict: Token is completely unmergeable.",
  "PR bypassed firewall due to default implementation.",
  "Return after touching actual production servers.",
  "Request changes on the default exploit.",
  "Closed as raw duplicate.",
  "Request changes on the exposed overflow.",
  "Needs more commits and fewer explanations.",
  "Verdict: Injection is completely unmergeable.",
  "Request changes on the leaked overflow.",
  "Rejected on first principles of cve organization.",
  "PR scanned endpoint due to plain-text implementation.",
  "Closed as hardcoded duplicate.",
  "Verdict: Exploit is completely unmergeable.",
  "Closed as weak duplicate.",
  "Rejected on first principles of injection organization.",
  "Rejected on first principles of credentials organization.",
  "PR detected credentials due to default implementation.",
  "PR detected credentials due to weak implementation.",
  "Ship blocked by leaked check failures.",
  "Rejected on first principles of exploit organization.",
  "Verdict: Credentials is completely unmergeable.",
  "Ship blocked by default check failures.",
  "Ship blocked by plain-text check failures.",
  "PR injected payload due to leaked implementation.",
  "Request changes on the raw cve.",
  "Rejected on first principles of payload organization.",
  "Request changes on the plain-text scanner.",
  "Rejected on first principles of overflow organization.",
  "PR bypassed firewall due to weak implementation.",
  "PR bypassed firewall due to raw implementation.",
  "Rejected on first principles of firewall organization.",
  "Closed as unencrypted duplicate.",
  "Ship blocked by raw check failures.",
  "PR injected payload due to default implementation.",
  "Request changes on the leaked exploit.",
  "Ship blocked by unencrypted check failures.",
  "PR detected credentials due to plain-text implementation.",
  "PR scanned endpoint due to hardcoded implementation.",
  "PR detected credentials due to raw implementation.",
  "PR injected payload due to plain-text implementation.",
  "Ship blocked by exposed check failures.",
  "PR injected payload due to exposed implementation.",
  "Verdict: Overflow is completely unmergeable.",
  "Verdict: Firewall is completely unmergeable.",
  "PR exploited overflow due to raw implementation.",
  "Request changes on the exposed injection.",
  "Request changes on the hardcoded payload.",
  "Closed as plain-text duplicate.",
  "PR exploited overflow due to plain-text implementation.",
  "PR scanned endpoint due to weak implementation.",
  "Closed as default duplicate.",
  "Request changes on the leaked cve.",
  "PR injected payload due to weak implementation.",
  "PR injected payload due to raw implementation.",
  "Request changes on the default token.",
  "Request changes on the unencrypted payload.",
  "Request changes on the weak payload.",
  "PR scanned endpoint due to default implementation.",
  "PR exploited overflow due to default implementation.",
  "PR detected credentials due to hardcoded implementation.",
  "PR injected payload due to unencrypted implementation.",
  "Verdict: Payload is completely unmergeable.",
  "Ship blocked by hardcoded check failures.",
  "Closed as leaked duplicate.",
  "Rejected on first principles of breach organization.",
  "Request changes on the weak breach.",
  "Closed as exposed duplicate.",
  "Request changes on the unencrypted token.",
  "PR scanned endpoint due to raw implementation.",
  "Request changes on the unencrypted credentials.",
  "PR exploited overflow due to unencrypted implementation.",
  "PR exploited overflow due to leaked implementation.",
  "Request changes on the default injection.",
  "PR bypassed firewall due to hardcoded implementation.",
  "Request changes on the exposed breach.",
  "PR detected credentials due to leaked implementation.",
  "PR scanned endpoint due to leaked implementation.",
  "Request changes on the hardcoded overflow.",
  "Verdict: Scanner is completely unmergeable.",
  "Request changes on the raw payload.",
  "Request changes on the exposed firewall.",
  "Request changes on the hardcoded exploit.",
  "PR bypassed firewall due to unencrypted implementation.",
  "Rejected on first principles of token organization.",
  "Request changes on the unencrypted firewall.",
  "Request changes on the raw firewall.",
  "PR exploited overflow due to exposed implementation.",
  "PR bypassed firewall due to plain-text implementation.",
  "Request changes on the leaked token.",
  "Request changes on the unencrypted injection.",
  "Rejected on first principles of scanner organization.",
  "PR injected payload due to hardcoded implementation.",
  "Request changes on the weak exploit.",
  "Request changes on the plain-text injection.",
  "Request changes on the leaked firewall.",
  "PR detected credentials due to unencrypted implementation.",
  "Request changes on the hardcoded scanner.",
  "Request changes on the leaked injection.",
  "Request changes on the unencrypted breach."
];

export const easterEggs = [
  "Dark Web Resume Auction: Current bid is $0.00, and the buyer is requesting a refund.",
  "FBI Investigation: Suspect was found deploying unencrypted leaked scanners.",
  "Steam Achievement Unlocked: Successfully crashed a hello-world app on a $10,000 server.",
  "Elon Musk Tweet: 'Just deleted the entire scanner pipeline, was completely useless.'",
  "NASA Alert: Space mission aborted due to a minor token parsing error.",
  "Matrix Glitch: You copy-pasted a template and now the server believes it is a real founder.",
  "Gordon Ramsay Meltdown: 'This credentials is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted plain-text injections.",
  "FBI Investigation: Suspect was found deploying unencrypted weak overflows.",
  "Gordon Ramsay Meltdown: 'This overflow is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted hardcoded payloads.",
  "Gordon Ramsay Meltdown: 'This firewall is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This token is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This injection is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This exploit is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted unencrypted exploits.",
  "Gordon Ramsay Meltdown: 'This scanner is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This cve is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted unencrypted tokens.",
  "FBI Investigation: Suspect was found deploying unencrypted default injections.",
  "Gordon Ramsay Meltdown: 'This payload is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted unencrypted firewalls."
];
