// ES Module exports for shakespearean roast format
export const titles = [
  "Incident Report: Sad Verse",
  "Absolute Tragic architecture",
  "Sorrow conflict detected",
  "Tragedy Not Found",
  "Absolute Flowery architecture",
  "Flowery Sorrow Loop",
  "The Verse tragedy",
  "Failed to compile: Death",
  "Apprentice conflict detected",
  "Incident Report: Weary Apprentice",
  "Critical Scene failure",
  "Incident Report: Flowery King",
  "Cursed King Error",
  "Incident Report: Flowery Fool",
  "Incident Report: Foolish Fool",
  "Critical King failure",
  "NullPointerTragedyException",
  "Ancient Fool Loop",
  "Ancient Tragedy Error",
  "Tragic Sorrow Loop",
  "Sad Act Loop",
  "Critical Sorrow failure",
  "Verse conflict detected",
  "The Labor tragedy",
  "Act Not Found",
  "Death Not Found",
  "Incident Report: Foolish Sorrow",
  "NullPointerActException",
  "NullPointerSceneException",
  "Incident Report: Weary Verse",
  "The Fool tragedy",
  "Critical Apprentice failure",
  "Dramatic Scene Error",
  "NullPointerLaborException",
  "Failed to compile: Scene",
  "Absolute Sad architecture",
  "Flowery Scene Loop",
  "Incident Report: Dramatic Act",
  "Failed to compile: Verse",
  "Incident Report: Weary Act",
  "NullPointerFoolException",
  "Failed to compile: Sorrow",
  "Incident Report: Dramatic Apprentice",
  "Failed to compile: Fool",
  "The Scene tragedy",
  "Scene Not Found",
  "Failed to compile: Act",
  "Tragic Labor Loop",
  "Death conflict detected",
  "Weary Tragedy Loop",
  "The Act tragedy",
  "Incident Report: Ancient King",
  "King Not Found",
  "Labor conflict detected",
  "Incident Report: Sad Labor",
  "Tragic Verse Error",
  "Failed to compile: King",
  "Incident Report: Weary Labor",
  "Critical Fool failure",
  "Dramatic Fool Loop",
  "Incident Report: Weary Death",
  "Act conflict detected",
  "NullPointerDeathException",
  "Dramatic Fool Error",
  "Foolish Tragedy Loop",
  "The Tragedy tragedy",
  "Scene conflict detected",
  "Incident Report: Cursed King",
  "Absolute Ancient architecture",
  "Failed to compile: Labor",
  "Sad Labor Error",
  "Critical Labor failure",
  "Incident Report: Cursed Scene",
  "Absolute Foolish architecture",
  "Fool conflict detected",
  "Incident Report: Flowery Death",
  "Incident Report: Tragic Scene",
  "Cursed Apprentice Error",
  "Ancient Scene Error",
  "The King tragedy",
  "Incident Report: Tragic King",
  "Foolish Apprentice Error",
  "Tragedy conflict detected",
  "Incident Report: Sad Fool",
  "Flowery Act Error",
  "The Death tragedy",
  "NullPointerSorrowException",
  "Absolute Dramatic architecture",
  "Incident Report: Ancient Death",
  "Incident Report: Ancient Verse",
  "Flowery Verse Error",
  "Sad Sorrow Loop",
  "Absolute Weary architecture",
  "Incident Report: Dramatic Death",
  "Apprentice Not Found",
  "Failed to compile: Tragedy",
  "Dramatic Act Error",
  "Ancient Death Loop",
  "The Sorrow tragedy",
  "Weary Act Loop"
];

export const openings = [
  "Initial evaluation shows the developer decided to ignored wise advisor unto the server.",
  "Recruiters reported a case of ancient labor design.",
  "Alert: The candidate spent three months trying to wrote flowery verse in the third act.",
  "Scanning candidate profile for flowery scenes...",
  "We checked the history and found a ancient death log.",
  "Scanning candidate profile for cursed acts...",
  "Alert: The candidate spent three months trying to wrote flowery verse beneath the cold sky.",
  "Warning: System flagged an attempt to wept over code unto the server.",
  "Alert: The candidate spent three months trying to wept over code to mock the gods.",
  "Recruiters reported a case of flowery fool design.",
  "We checked the history and found a weary sorrow log.",
  "Warning: System flagged an attempt to failed tragic runtime with great sorrow.",
  "Scanning candidate profile for foolish scenes...",
  "Alert: The candidate spent three months trying to entered stage crying unto the server.",
  "Warning: System flagged an attempt to wept over code beneath the cold sky.",
  "Recruiters reported a case of dramatic king design.",
  "Initial evaluation shows the developer decided to failed tragic runtime with great sorrow.",
  "Warning: System flagged an attempt to entered stage crying with great sorrow.",
  "Recruiters reported a case of flowery king design.",
  "Recruiters reported a case of dramatic verse design.",
  "Warning: System flagged an attempt to failed tragic runtime unto the server.",
  "Recruiters reported a case of cursed act design.",
  "We checked the history and found a cursed tragedy log.",
  "A review was filed regarding a dramatic scene.",
  "Warning: System flagged an attempt to wept over code to mock the gods.",
  "Alert: The candidate spent three months trying to wrote flowery verse unto the server.",
  "A review was filed regarding a dramatic tragedy.",
  "Alert: The candidate spent three months trying to entered stage crying with great sorrow.",
  "A review was filed regarding a foolish apprentice.",
  "Initial evaluation shows the developer decided to wept over code in the third act.",
  "A review was filed regarding a ancient verse.",
  "Alert: The candidate spent three months trying to entered stage crying in the third act.",
  "Recruiters reported a case of sad tragedy design.",
  "Recruiters reported a case of ancient verse design.",
  "The team has initiated audit for the candidate's death setup.",
  "Warning: System flagged an attempt to entered stage crying to mock the gods.",
  "Recruiters reported a case of sad sorrow design.",
  "Alert: The candidate spent three months trying to failed tragic runtime in the third act.",
  "We checked the history and found a foolish labor log.",
  "Warning: System flagged an attempt to failed tragic runtime in the third act.",
  "Alert: The candidate spent three months trying to wept over code in the third act.",
  "A review was filed regarding a weary labor.",
  "Warning: System flagged an attempt to ignored wise advisor beneath the cold sky.",
  "Alert: The candidate spent three months trying to failed tragic runtime to mock the gods.",
  "We checked the history and found a foolish act log.",
  "Warning: System flagged an attempt to failed tragic runtime beneath the cold sky.",
  "Warning: System flagged an attempt to failed tragic runtime to mock the gods.",
  "Scanning candidate profile for sad fools...",
  "Alert: The candidate spent three months trying to ignored wise advisor beneath the cold sky.",
  "Scanning candidate profile for cursed deaths...",
  "A review was filed regarding a sad tragedy.",
  "A review was filed regarding a ancient tragedy.",
  "Scanning candidate profile for ancient verses...",
  "Initial evaluation shows the developer decided to wept over code to mock the gods.",
  "Warning: System flagged an attempt to wrote flowery verse with great sorrow.",
  "A review was filed regarding a sad king.",
  "Alert: The candidate spent three months trying to ignored wise advisor unto the server.",
  "We checked the history and found a tragic scene log.",
  "Recruiters reported a case of flowery labor design.",
  "Scanning candidate profile for flowery acts...",
  "We checked the history and found a foolish king log.",
  "Initial evaluation shows the developer decided to failed tragic runtime in the third act.",
  "Warning: System flagged an attempt to ignored wise advisor in the third act.",
  "We checked the history and found a dramatic verse log.",
  "A review was filed regarding a weary verse.",
  "Recruiters reported a case of foolish verse design.",
  "Warning: System flagged an attempt to wrote flowery verse to mock the gods.",
  "Recruiters reported a case of ancient king design.",
  "We checked the history and found a flowery verse log.",
  "We checked the history and found a cursed king log.",
  "Alert: The candidate spent three months trying to wept over code beneath the cold sky.",
  "Warning: System flagged an attempt to wrote flowery verse beneath the cold sky.",
  "Initial evaluation shows the developer decided to entered stage crying to mock the gods.",
  "Scanning candidate profile for dramatic apprentices...",
  "Recruiters reported a case of weary act design.",
  "Initial evaluation shows the developer decided to failed tragic runtime to mock the gods.",
  "Recruiters reported a case of weary tragedy design.",
  "Recruiters reported a case of foolish labor design.",
  "We checked the history and found a sad fool log.",
  "Warning: System flagged an attempt to ignored wise advisor unto the server.",
  "We checked the history and found a weary scene log.",
  "Scanning candidate profile for dramatic sorrows...",
  "Alert: The candidate spent three months trying to wrote flowery verse with great sorrow.",
  "Scanning candidate profile for cursed labors...",
  "Initial evaluation shows the developer decided to ignored wise advisor in the third act.",
  "Initial evaluation shows the developer decided to wept over code with great sorrow.",
  "Scanning candidate profile for weary deaths...",
  "Alert: The candidate spent three months trying to entered stage crying to mock the gods.",
  "Alert: The candidate spent three months trying to failed tragic runtime with great sorrow.",
  "Recruiters reported a case of foolish apprentice design.",
  "Recruiters reported a case of flowery death design.",
  "A review was filed regarding a tragic labor.",
  "Scanning candidate profile for foolish deaths..."
];

export const findings = [
  "Failed to configure {{project}} because {{candidateName}} decided to wept over code unto the server.",
  "While debugging {{project}}, we found a weary logic loop related to {{language}} features.",
  "Obtained {{certification}} which apparently teaches how to failed tragic runtime beneath the cold sky.",
  "Failed to configure {{project}} because {{candidateName}} decided to ignored wise advisor to mock the gods.",
  "{{candidateName}} has spent three weeks optimizing a act while completely ignoring {{missingSection}}.",
  "A security audit on {{github}} detected a plain-text database password inside a cursed labor.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ignored wise advisor in the third act.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to wrote flowery verse to mock the gods.",
  "A security audit on {{github}} detected a plain-text database password inside a foolish death.",
  "Failed to configure {{project}} because {{candidateName}} decided to entered stage crying unto the server.",
  "A security audit on {{github}} detected a plain-text database password inside a sad apprentice.",
  "{{education}} is listed, but they still managed to deploy a flowery verse to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to failed tragic runtime unto the server.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to failed tragic runtime to mock the gods.",
  "Listed {{skill}} as a primary competency, but the evidence points to a foolish tragedy.",
  "The candidate claims {{framework}} experience, but their repository is just a flowery clone that has been abandoned.",
  "{{education}} is listed, but they still managed to deploy a ancient act to production.",
  "For {{experience}}, the primary contribution was writing a weary config for a labor.",
  "Failed to configure {{project}} because {{candidateName}} decided to entered stage crying to mock the gods.",
  "{{education}} is listed, but they still managed to deploy a sad tragedy to production.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ignored wise advisor beneath the cold sky.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ignored wise advisor beneath the cold sky.",
  "{{github}} contains more flowery kings than original code.",
  "{{github}} contains more dramatic kings than original code.",
  "For {{experience}}, the primary contribution was writing a sad config for a tragedy.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to wrote flowery verse with great sorrow.",
  "For {{experience}}, the primary contribution was writing a dramatic config for a apprentice.",
  "Failed to configure {{project}} because {{candidateName}} decided to entered stage crying with great sorrow.",
  "Listed {{skill}} as a primary competency, but the evidence points to a flowery king.",
  "Failed to configure {{project}} because {{candidateName}} decided to ignored wise advisor beneath the cold sky.",
  "Obtained {{certification}} which apparently teaches how to entered stage crying beneath the cold sky.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to wept over code to mock the gods.",
  "For {{experience}}, the primary contribution was writing a flowery config for a death.",
  "Failed to configure {{project}} because {{candidateName}} decided to entered stage crying beneath the cold sky.",
  "A security audit on {{github}} detected a plain-text database password inside a flowery scene.",
  "Listed {{skill}} as a primary competency, but the evidence points to a sad act.",
  "Failed to configure {{project}} because {{candidateName}} decided to wept over code in the third act.",
  "Listed {{skill}} as a primary competency, but the evidence points to a ancient death.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ignored wise advisor in the third act.",
  "Failed to configure {{project}} because {{candidateName}} decided to wept over code with great sorrow.",
  "A security audit on {{github}} detected a plain-text database password inside a dramatic verse.",
  "{{github}} contains more dramatic labors than original code.",
  "{{github}} contains more tragic scenes than original code.",
  "{{github}} contains more weary verses than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ignored wise advisor with great sorrow.",
  "Obtained {{certification}} which apparently teaches how to wept over code beneath the cold sky.",
  "{{achievement}} was highlighted, but the git logs show they only managed to failed tragic runtime with great sorrow.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to wrote flowery verse in the third act.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to entered stage crying beneath the cold sky.",
  "Obtained {{certification}} which apparently teaches how to wept over code in the third act.",
  "Obtained {{certification}} which apparently teaches how to wrote flowery verse with great sorrow.",
  "{{github}} contains more ancient apprentices than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a ancient sorrow.",
  "{{github}} contains more ancient acts than original code.",
  "Listed {{skill}} as a primary competency, but the evidence points to a weary scene.",
  "Listed {{skill}} as a primary competency, but the evidence points to a tragic labor.",
  "{{achievement}} was highlighted, but the git logs show they only managed to entered stage crying beneath the cold sky.",
  "{{achievement}} was highlighted, but the git logs show they only managed to entered stage crying in the third act.",
  "{{github}} contains more cursed fools than original code.",
  "{{github}} contains more cursed scenes than original code.",
  "{{github}} contains more dramatic apprentices than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ignored wise advisor with great sorrow.",
  "For {{experience}}, the primary contribution was writing a cursed config for a king.",
  "{{education}} is listed, but they still managed to deploy a tragic sorrow to production.",
  "Obtained {{certification}} which apparently teaches how to wept over code unto the server.",
  "{{github}} contains more sad fools than original code.",
  "{{github}} contains more tragic fools than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to wrote flowery verse to mock the gods.",
  "{{achievement}} was highlighted, but the git logs show they only managed to wept over code in the third act.",
  "Obtained {{certification}} which apparently teaches how to failed tragic runtime in the third act.",
  "Obtained {{certification}} which apparently teaches how to ignored wise advisor unto the server.",
  "Failed to configure {{project}} because {{candidateName}} decided to wept over code to mock the gods.",
  "For {{experience}}, the primary contribution was writing a foolish config for a verse.",
  "Obtained {{certification}} which apparently teaches how to ignored wise advisor to mock the gods.",
  "{{achievement}} was highlighted, but the git logs show they only managed to wrote flowery verse unto the server.",
  "Failed to configure {{project}} because {{candidateName}} decided to wept over code beneath the cold sky.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to wept over code in the third act.",
  "{{education}} is listed, but they still managed to deploy a weary scene to production.",
  "{{github}} contains more weary kings than original code.",
  "Obtained {{certification}} which apparently teaches how to wept over code to mock the gods.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to wrote flowery verse unto the server.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to entered stage crying in the third act.",
  "For {{experience}}, the primary contribution was writing a tragic config for a sorrow.",
  "Obtained {{certification}} which apparently teaches how to entered stage crying in the third act.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to entered stage crying with great sorrow.",
  "Failed to configure {{project}} because {{candidateName}} decided to failed tragic runtime in the third act.",
  "{{github}} contains more cursed deaths than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a tragic tragedy.",
  "{{github}} contains more flowery deaths than original code.",
  "Obtained {{certification}} which apparently teaches how to entered stage crying to mock the gods.",
  "{{github}} contains more ancient scenes than original code.",
  "{{github}} contains more foolish verses than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to wept over code with great sorrow.",
  "{{github}} contains more sad apprentices than original code.",
  "{{github}} contains more dramatic tragedys than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to entered stage crying to mock the gods.",
  "Obtained {{certification}} which apparently teaches how to ignored wise advisor with great sorrow.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to failed tragic runtime beneath the cold sky.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ignored wise advisor unto the server.",
  "Obtained {{certification}} which apparently teaches how to wrote flowery verse unto the server.",
  "{{github}} contains more sad deaths than original code.",
  "Obtained {{certification}} which apparently teaches how to failed tragic runtime unto the server.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to wept over code unto the server.",
  "{{github}} contains more cursed tragedys than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to failed tragic runtime to mock the gods.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to failed tragic runtime unto the server.",
  "{{achievement}} was highlighted, but the git logs show they only managed to wept over code with great sorrow.",
  "{{github}} contains more dramatic verses than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to entered stage crying unto the server."
];

export const punchlines = [
  "The compiler requested emotional support after reading the dramatic code.",
  "It did not optimize our process, but it did make the laptop fan spin like a jet engine.",
  "Even Stack Overflow has marked this death as off-topic.",
  "The only thing memory-safe about this setup is that nobody has ever tried to run it.",
  "We would deploy it to production, but our SRE team deserves to sleep at night.",
  "The documentation was so empty, I had to use it as a virtual sketchbook.",
  "A junior developer looked at the verse and immediately went to touch grass.",
  "Legend says this flowery labor is still running on localhost.",
  "Legend says this sad death is still running on localhost.",
  "Legend says this sad scene is still running on localhost.",
  "Legend says this ancient labor is still running on localhost.",
  "Legend says this dramatic king is still running on localhost.",
  "Legend says this cursed fool is still running on localhost.",
  "Legend says this sad verse is still running on localhost.",
  "Legend says this cursed tragedy is still running on localhost.",
  "Legend says this tragic tragedy is still running on localhost.",
  "Legend says this weary act is still running on localhost.",
  "Legend says this cursed act is still running on localhost.",
  "Legend says this flowery king is still running on localhost.",
  "Legend says this sad sorrow is still running on localhost.",
  "Legend says this tragic act is still running on localhost.",
  "Legend says this foolish verse is still running on localhost.",
  "Legend says this ancient act is still running on localhost.",
  "Legend says this tragic scene is still running on localhost.",
  "Legend says this weary king is still running on localhost.",
  "Legend says this dramatic apprentice is still running on localhost.",
  "Legend says this ancient apprentice is still running on localhost.",
  "Legend says this dramatic tragedy is still running on localhost.",
  "Legend says this flowery fool is still running on localhost.",
  "Legend says this flowery death is still running on localhost.",
  "Legend says this dramatic act is still running on localhost.",
  "Legend says this sad king is still running on localhost.",
  "Legend says this tragic labor is still running on localhost.",
  "Legend says this tragic sorrow is still running on localhost.",
  "Legend says this foolish king is still running on localhost.",
  "Legend says this sad labor is still running on localhost.",
  "Legend says this ancient king is still running on localhost.",
  "Legend says this sad apprentice is still running on localhost.",
  "Legend says this ancient verse is still running on localhost.",
  "Legend says this weary apprentice is still running on localhost.",
  "Legend says this tragic verse is still running on localhost.",
  "Legend says this ancient sorrow is still running on localhost.",
  "Legend says this flowery tragedy is still running on localhost.",
  "Legend says this dramatic labor is still running on localhost.",
  "Legend says this sad fool is still running on localhost.",
  "Legend says this cursed apprentice is still running on localhost.",
  "Legend says this cursed scene is still running on localhost.",
  "Legend says this flowery verse is still running on localhost.",
  "Legend says this sad tragedy is still running on localhost.",
  "Legend says this flowery act is still running on localhost.",
  "Legend says this foolish fool is still running on localhost.",
  "Legend says this weary fool is still running on localhost.",
  "Legend says this tragic king is still running on localhost.",
  "Legend says this weary labor is still running on localhost.",
  "Legend says this ancient fool is still running on localhost.",
  "Legend says this foolish labor is still running on localhost.",
  "Legend says this dramatic death is still running on localhost.",
  "Legend says this dramatic fool is still running on localhost.",
  "Legend says this dramatic scene is still running on localhost.",
  "Legend says this weary sorrow is still running on localhost.",
  "Legend says this weary verse is still running on localhost.",
  "Legend says this flowery apprentice is still running on localhost.",
  "Legend says this cursed death is still running on localhost.",
  "Legend says this foolish scene is still running on localhost.",
  "Legend says this weary death is still running on localhost.",
  "Legend says this cursed labor is still running on localhost.",
  "Legend says this cursed king is still running on localhost.",
  "Legend says this foolish tragedy is still running on localhost.",
  "Legend says this weary tragedy is still running on localhost.",
  "Legend says this dramatic sorrow is still running on localhost.",
  "This is a classic example of a weary labor disaster.",
  "This is a classic example of a tragic fool disaster.",
  "This is a classic example of a sad tragedy disaster.",
  "This is a classic example of a tragic sorrow disaster.",
  "This is a classic example of a foolish labor disaster.",
  "This is a classic example of a weary apprentice disaster.",
  "This is a classic example of a ancient death disaster.",
  "This is a classic example of a tragic apprentice disaster.",
  "This is a classic example of a foolish act disaster.",
  "This is a classic example of a tragic death disaster.",
  "This is a classic example of a flowery verse disaster.",
  "This is a classic example of a ancient labor disaster.",
  "This is a classic example of a flowery labor disaster.",
  "This is a classic example of a cursed tragedy disaster.",
  "This is a classic example of a dramatic verse disaster.",
  "This is a classic example of a tragic act disaster.",
  "This is a classic example of a flowery death disaster.",
  "This is a classic example of a cursed verse disaster.",
  "This is a classic example of a dramatic act disaster.",
  "This is a classic example of a ancient scene disaster.",
  "This is a classic example of a weary sorrow disaster.",
  "This is a classic example of a sad verse disaster.",
  "This is a classic example of a tragic king disaster.",
  "This is a classic example of a foolish apprentice disaster.",
  "This is a classic example of a weary verse disaster.",
  "This is a classic example of a foolish sorrow disaster.",
  "This is a classic example of a foolish death disaster.",
  "This is a classic example of a dramatic sorrow disaster.",
  "This is a classic example of a ancient apprentice disaster.",
  "This is a classic example of a ancient fool disaster.",
  "This is a classic example of a cursed scene disaster.",
  "This is a classic example of a cursed act disaster.",
  "This is a classic example of a dramatic apprentice disaster.",
  "This is a classic example of a weary act disaster.",
  "This is a classic example of a foolish fool disaster.",
  "This is a classic example of a tragic verse disaster.",
  "This is a classic example of a flowery king disaster.",
  "This is a classic example of a dramatic tragedy disaster."
];

export const verdicts = [
  "PR failed tragic runtime due to tragic implementation.",
  "Closed as dramatic duplicate.",
  "Closed as sad duplicate.",
  "Ship blocked by flowery check failures.",
  "Needs more commits and fewer explanations.",
  "PR ignored wise advisor due to dramatic implementation.",
  "Return after touching actual production servers.",
  "Closed as weary duplicate.",
  "Rejected on first principles of fool organization.",
  "Request changes on the dramatic tragedy.",
  "Verdict: Act is completely unmergeable.",
  "Request changes on the weary apprentice.",
  "Rejected on first principles of apprentice organization.",
  "Rejected on first principles of act organization.",
  "Verdict: King is completely unmergeable.",
  "Verdict: Death is completely unmergeable.",
  "PR wrote flowery verse due to cursed implementation.",
  "Rejected on first principles of verse organization.",
  "Rejected on first principles of death organization.",
  "PR wrote flowery verse due to dramatic implementation.",
  "Verdict: Sorrow is completely unmergeable.",
  "PR entered stage crying due to sad implementation.",
  "PR wept over code due to dramatic implementation.",
  "Closed as foolish duplicate.",
  "Request changes on the sad tragedy.",
  "Ship blocked by foolish check failures.",
  "Request changes on the sad verse.",
  "Request changes on the dramatic verse.",
  "Request changes on the dramatic fool.",
  "Ship blocked by sad check failures.",
  "Verdict: Fool is completely unmergeable.",
  "Verdict: Verse is completely unmergeable.",
  "Request changes on the ancient labor.",
  "Ship blocked by ancient check failures.",
  "Request changes on the tragic scene.",
  "PR ignored wise advisor due to foolish implementation.",
  "Closed as ancient duplicate.",
  "Verdict: Tragedy is completely unmergeable.",
  "Rejected on first principles of tragedy organization.",
  "Closed as cursed duplicate.",
  "Ship blocked by weary check failures.",
  "Ship blocked by dramatic check failures.",
  "Verdict: Scene is completely unmergeable.",
  "PR wrote flowery verse due to foolish implementation.",
  "Request changes on the cursed tragedy.",
  "Request changes on the sad scene.",
  "Ship blocked by tragic check failures.",
  "Request changes on the ancient verse.",
  "Closed as tragic duplicate.",
  "PR entered stage crying due to tragic implementation.",
  "PR ignored wise advisor due to ancient implementation.",
  "Request changes on the weary king.",
  "Request changes on the cursed verse.",
  "Request changes on the weary verse.",
  "Rejected on first principles of labor organization.",
  "Verdict: Apprentice is completely unmergeable.",
  "Rejected on first principles of king organization.",
  "Request changes on the weary labor.",
  "Ship blocked by cursed check failures.",
  "Request changes on the sad apprentice.",
  "PR wept over code due to sad implementation.",
  "Rejected on first principles of sorrow organization.",
  "Request changes on the foolish king.",
  "Request changes on the foolish labor.",
  "Verdict: Labor is completely unmergeable.",
  "Request changes on the cursed king.",
  "Request changes on the weary sorrow.",
  "Request changes on the dramatic act.",
  "Request changes on the ancient scene.",
  "Request changes on the foolish tragedy.",
  "Request changes on the sad sorrow.",
  "Request changes on the cursed act.",
  "Closed as flowery duplicate.",
  "Request changes on the dramatic apprentice.",
  "Request changes on the flowery labor.",
  "PR wept over code due to ancient implementation.",
  "PR ignored wise advisor due to sad implementation.",
  "Request changes on the sad fool.",
  "Rejected on first principles of scene organization.",
  "Request changes on the ancient king.",
  "PR wept over code due to cursed implementation.",
  "Request changes on the dramatic sorrow.",
  "Request changes on the foolish death.",
  "Request changes on the flowery king.",
  "Request changes on the foolish verse.",
  "PR ignored wise advisor due to tragic implementation.",
  "PR wrote flowery verse due to tragic implementation.",
  "Request changes on the foolish sorrow.",
  "Request changes on the dramatic labor.",
  "Request changes on the tragic act.",
  "PR wept over code due to flowery implementation.",
  "Request changes on the flowery fool.",
  "PR entered stage crying due to foolish implementation.",
  "Request changes on the tragic verse.",
  "Request changes on the tragic king."
];

export const easterEggs = [
  "Dark Web Resume Auction: Current bid is $0.00, and the buyer is requesting a refund.",
  "Elon Musk Tweet: 'Just deleted the entire act pipeline, was completely useless.'",
  "Matrix Glitch: You copy-pasted a template and now the server believes it is a real founder.",
  "Gordon Ramsay Meltdown: 'This verse is raw! It's absolutely raw!'",
  "Steam Achievement Unlocked: Successfully crashed a hello-world app on a $10,000 server.",
  "Gordon Ramsay Meltdown: 'This tragedy is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted weary scenes.",
  "FBI Investigation: Suspect was found deploying unencrypted sad kings.",
  "Gordon Ramsay Meltdown: 'This death is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This scene is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted foolish labors.",
  "Gordon Ramsay Meltdown: 'This sorrow is raw! It's absolutely raw!'",
  "NASA Alert: Space mission aborted due to a minor king parsing error.",
  "Gordon Ramsay Meltdown: 'This apprentice is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted cursed acts.",
  "FBI Investigation: Suspect was found deploying unencrypted dramatic tragedys.",
  "Gordon Ramsay Meltdown: 'This act is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This king is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This labor is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted flowery apprentices.",
  "Gordon Ramsay Meltdown: 'This fool is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted tragic verses."
];
