// ES Module exports for sports_commentary roast format
export const titles = [
  "Trophy Not Found",
  "The Play tragedy",
  "The Coach tragedy",
  "Run Not Found",
  "Legendary Run Loop",
  "Incident Report: Competitive Player",
  "The Player tragedy",
  "NullPointerPlayerException",
  "Absolute Failed architecture",
  "Incident Report: Legendary Champion",
  "Absolute Unprepared architecture",
  "NullPointerCoachException",
  "Critical Run failure",
  "The Stadium tragedy",
  "NullPointerGameException",
  "Failed to compile: Score",
  "Incident Report: Unprepared Game",
  "Critical Team failure",
  "Stadium Not Found",
  "Failed to compile: Coach",
  "Critical Score failure",
  "Failed Play Error",
  "Team conflict detected",
  "Absolute Competitive architecture",
  "Incident Report: Fast Trophy",
  "The Game tragedy",
  "NullPointerTrophyException",
  "Champion conflict detected",
  "Critical Play failure",
  "Run conflict detected",
  "Incident Report: Failed Stadium",
  "Competitive Team Error",
  "Absolute Terrible architecture",
  "Champion Not Found",
  "Incident Report: Failed Run",
  "Critical Coach failure",
  "Score conflict detected",
  "Absolute Legendary architecture",
  "Trophy conflict detected",
  "Failed Player Loop",
  "Failed to compile: Run",
  "Stadium conflict detected",
  "Game conflict detected",
  "The Trophy tragedy",
  "Competitive Coach Error",
  "NullPointerChampionException",
  "Critical Champion failure",
  "Absolute Fast architecture",
  "Failed to compile: Team",
  "Incident Report: Slow Game",
  "Unprepared Coach Error",
  "Failed to compile: Trophy",
  "Competitive Trophy Loop",
  "The Run tragedy",
  "Slow Play Error",
  "Fast Player Error",
  "Competitive Champion Error",
  "Team Not Found",
  "Legendary Champion Loop",
  "Slow Score Loop",
  "Incident Report: Legendary Game",
  "Play conflict detected",
  "Unprepared Game Error",
  "Failed to compile: Game",
  "Play Not Found",
  "Incident Report: Slow Score",
  "Fast Game Loop",
  "Legendary Trophy Error",
  "Incident Report: Failed Game",
  "Incident Report: Slow Play",
  "Critical Stadium failure",
  "NullPointerRunException",
  "NullPointerTeamException",
  "Fast Coach Loop",
  "Winning Stadium Loop",
  "Coach conflict detected",
  "Slow Run Loop",
  "Player Not Found",
  "Failed to compile: Play",
  "Terrible Stadium Error",
  "Terrible Champion Loop",
  "Winning Player Loop",
  "Critical Trophy failure",
  "Slow Team Loop",
  "Legendary Player Error",
  "Fast Player Loop",
  "Incident Report: Winning Run",
  "Slow Player Error",
  "Terrible Champion Error",
  "Coach Not Found",
  "Incident Report: Failed Trophy",
  "Score Not Found",
  "Game Not Found",
  "NullPointerPlayException",
  "Player conflict detected",
  "Unprepared Score Loop",
  "The Team tragedy",
  "Fast Play Error",
  "Failed Game Error",
  "NullPointerScoreException"
];

export const openings = [
  "Warning: System flagged an attempt to failed the sprint in the final seconds.",
  "Warning: System flagged an attempt to failed the sprint losing team confidence.",
  "Alert: The candidate spent three months trying to lost the tournament in the final seconds.",
  "Recruiters reported a case of unprepared champion design.",
  "Warning: System flagged an attempt to dropped the ball in the final seconds.",
  "We checked the history and found a fast player log.",
  "We checked the history and found a terrible player log.",
  "Initial evaluation shows the developer decided to failed the sprint on national television.",
  "Recruiters reported a case of fast player design.",
  "The team has initiated audit for the candidate's stadium setup.",
  "Alert: The candidate spent three months trying to failed the sprint on national television.",
  "We checked the history and found a winning coach log.",
  "Warning: System flagged an attempt to failed the sprint with zero points.",
  "Initial evaluation shows the developer decided to failed the sprint for the touchdown.",
  "Warning: System flagged an attempt to lost the tournament with zero points.",
  "We checked the history and found a unprepared champion log.",
  "Initial evaluation shows the developer decided to lost the tournament losing team confidence.",
  "We checked the history and found a slow trophy log.",
  "Alert: The candidate spent three months trying to missed the target in the final seconds.",
  "We checked the history and found a failed game log.",
  "Initial evaluation shows the developer decided to lost the tournament in the final seconds.",
  "Initial evaluation shows the developer decided to missed the target for the touchdown.",
  "Recruiters reported a case of slow score design.",
  "Recruiters reported a case of legendary team design.",
  "Alert: The candidate spent three months trying to dropped the ball on national television.",
  "Warning: System flagged an attempt to ran slow play in the final seconds.",
  "Alert: The candidate spent three months trying to ran slow play with zero points.",
  "Recruiters reported a case of legendary score design.",
  "Alert: The candidate spent three months trying to failed the sprint with zero points.",
  "Recruiters reported a case of competitive run design.",
  "Warning: System flagged an attempt to ran slow play for the touchdown.",
  "Recruiters reported a case of terrible game design.",
  "Recruiters reported a case of competitive coach design.",
  "We checked the history and found a failed coach log.",
  "A review was filed regarding a fast player.",
  "Warning: System flagged an attempt to lost the tournament losing team confidence.",
  "A review was filed regarding a terrible champion.",
  "We checked the history and found a failed team log.",
  "Recruiters reported a case of winning stadium design.",
  "Initial evaluation shows the developer decided to failed the sprint in the final seconds.",
  "Warning: System flagged an attempt to missed the target for the touchdown.",
  "Initial evaluation shows the developer decided to ran slow play in the final seconds.",
  "Alert: The candidate spent three months trying to missed the target on national television.",
  "Alert: The candidate spent three months trying to ran slow play for the touchdown.",
  "Scanning candidate profile for unprepared coachs...",
  "A review was filed regarding a competitive game.",
  "Scanning candidate profile for fast scores...",
  "Warning: System flagged an attempt to lost the tournament in the final seconds.",
  "Recruiters reported a case of legendary champion design.",
  "Recruiters reported a case of competitive player design.",
  "Initial evaluation shows the developer decided to dropped the ball with zero points.",
  "Alert: The candidate spent three months trying to ran slow play losing team confidence.",
  "We checked the history and found a slow play log.",
  "A review was filed regarding a legendary run.",
  "Recruiters reported a case of unprepared coach design.",
  "A review was filed regarding a competitive coach.",
  "A review was filed regarding a winning run.",
  "Alert: The candidate spent three months trying to lost the tournament losing team confidence.",
  "Scanning candidate profile for fast trophys...",
  "A review was filed regarding a winning team.",
  "Recruiters reported a case of winning coach design.",
  "Scanning candidate profile for legendary champions...",
  "Initial evaluation shows the developer decided to ran slow play losing team confidence.",
  "Warning: System flagged an attempt to lost the tournament for the touchdown.",
  "We checked the history and found a competitive game log.",
  "We checked the history and found a winning champion log.",
  "Alert: The candidate spent three months trying to failed the sprint losing team confidence.",
  "We checked the history and found a slow stadium log.",
  "Recruiters reported a case of competitive score design.",
  "Recruiters reported a case of terrible team design.",
  "A review was filed regarding a slow play.",
  "Initial evaluation shows the developer decided to lost the tournament with zero points.",
  "We checked the history and found a terrible stadium log.",
  "We checked the history and found a competitive trophy log.",
  "Initial evaluation shows the developer decided to failed the sprint losing team confidence.",
  "Alert: The candidate spent three months trying to dropped the ball losing team confidence.",
  "Warning: System flagged an attempt to missed the target in the final seconds.",
  "A review was filed regarding a failed game.",
  "Scanning candidate profile for unprepared trophys...",
  "Recruiters reported a case of competitive team design.",
  "We checked the history and found a legendary score log.",
  "Recruiters reported a case of fast game design.",
  "We checked the history and found a unprepared run log.",
  "We checked the history and found a failed score log.",
  "A review was filed regarding a failed play.",
  "Recruiters reported a case of terrible score design.",
  "Scanning candidate profile for unprepared games...",
  "Recruiters reported a case of fast trophy design.",
  "We checked the history and found a slow team log.",
  "Alert: The candidate spent three months trying to lost the tournament with zero points.",
  "Scanning candidate profile for winning coachs...",
  "Alert: The candidate spent three months trying to failed the sprint in the final seconds.",
  "A review was filed regarding a fast stadium."
];

export const findings = [
  "{{education}} is listed, but they still managed to deploy a terrible run to production.",
  "A security audit on {{github}} detected a plain-text database password inside a fast player.",
  "{{github}} contains more fast runs than original code.",
  "Listed {{skill}} as a primary competency, but the evidence points to a fast score.",
  "Listed {{skill}} as a primary competency, but the evidence points to a competitive game.",
  "For {{experience}}, the primary contribution was writing a fast config for a champion.",
  "{{candidateName}} has spent three weeks optimizing a coach while completely ignoring {{missingSection}}.",
  "Failed to configure {{project}} because {{candidateName}} decided to missed the target in the final seconds.",
  "{{achievement}} was highlighted, but the git logs show they only managed to lost the tournament in the final seconds.",
  "The candidate claims {{framework}} experience, but their repository is just a slow clone that has been abandoned.",
  "{{education}} is listed, but they still managed to deploy a unprepared trophy to production.",
  "{{github}} contains more fast champions than original code.",
  "Obtained {{certification}} which apparently teaches how to dropped the ball on national television.",
  "Listed {{skill}} as a primary competency, but the evidence points to a legendary coach.",
  "For {{experience}}, the primary contribution was writing a slow config for a play.",
  "Listed {{skill}} as a primary competency, but the evidence points to a unprepared run.",
  "A security audit on {{github}} detected a plain-text database password inside a competitive play.",
  "Failed to configure {{project}} because {{candidateName}} decided to lost the tournament losing team confidence.",
  "Failed to configure {{project}} because {{candidateName}} decided to ran slow play on national television.",
  "{{education}} is listed, but they still managed to deploy a legendary stadium to production.",
  "While debugging {{project}}, we found a competitive logic loop related to {{language}} features.",
  "Listed {{skill}} as a primary competency, but the evidence points to a terrible play.",
  "{{achievement}} was highlighted, but the git logs show they only managed to dropped the ball on national television.",
  "Obtained {{certification}} which apparently teaches how to lost the tournament losing team confidence.",
  "{{education}} is listed, but they still managed to deploy a failed play to production.",
  "{{github}} contains more terrible games than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to failed the sprint on national television.",
  "Failed to configure {{project}} because {{candidateName}} decided to missed the target with zero points.",
  "Failed to configure {{project}} because {{candidateName}} decided to dropped the ball with zero points.",
  "For {{experience}}, the primary contribution was writing a terrible config for a coach.",
  "{{education}} is listed, but they still managed to deploy a competitive game to production.",
  "Obtained {{certification}} which apparently teaches how to missed the target in the final seconds.",
  "{{achievement}} was highlighted, but the git logs show they only managed to dropped the ball for the touchdown.",
  "{{education}} is listed, but they still managed to deploy a winning team to production.",
  "Failed to configure {{project}} because {{candidateName}} decided to failed the sprint with zero points.",
  "{{achievement}} was highlighted, but the git logs show they only managed to dropped the ball in the final seconds.",
  "Failed to configure {{project}} because {{candidateName}} decided to missed the target on national television.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to missed the target on national television.",
  "A security audit on {{github}} detected a plain-text database password inside a unprepared coach.",
  "{{github}} contains more unprepared games than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to missed the target for the touchdown.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ran slow play on national television.",
  "A security audit on {{github}} detected a plain-text database password inside a terrible team.",
  "A security audit on {{github}} detected a plain-text database password inside a legendary stadium.",
  "{{github}} contains more unprepared teams than original code.",
  "{{github}} contains more failed champions than original code.",
  "Obtained {{certification}} which apparently teaches how to ran slow play with zero points.",
  "Obtained {{certification}} which apparently teaches how to missed the target with zero points.",
  "{{github}} contains more legendary plays than original code.",
  "Obtained {{certification}} which apparently teaches how to missed the target on national television.",
  "Failed to configure {{project}} because {{candidateName}} decided to ran slow play in the final seconds.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ran slow play in the final seconds.",
  "Failed to configure {{project}} because {{candidateName}} decided to failed the sprint on national television.",
  "{{achievement}} was highlighted, but the git logs show they only managed to lost the tournament losing team confidence.",
  "Obtained {{certification}} which apparently teaches how to failed the sprint on national television.",
  "{{achievement}} was highlighted, but the git logs show they only managed to missed the target losing team confidence.",
  "Listed {{skill}} as a primary competency, but the evidence points to a slow stadium.",
  "For {{experience}}, the primary contribution was writing a unprepared config for a game.",
  "Obtained {{certification}} which apparently teaches how to failed the sprint with zero points.",
  "Failed to configure {{project}} because {{candidateName}} decided to dropped the ball in the final seconds.",
  "{{education}} is listed, but they still managed to deploy a fast coach to production.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to lost the tournament on national television.",
  "{{github}} contains more unprepared scores than original code.",
  "{{github}} contains more failed scores than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ran slow play for the touchdown.",
  "Obtained {{certification}} which apparently teaches how to missed the target losing team confidence.",
  "Obtained {{certification}} which apparently teaches how to ran slow play on national television.",
  "Obtained {{certification}} which apparently teaches how to dropped the ball with zero points.",
  "{{github}} contains more legendary games than original code.",
  "{{github}} contains more fast plays than original code.",
  "{{github}} contains more fast trophys than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to ran slow play on national television.",
  "For {{experience}}, the primary contribution was writing a winning config for a team.",
  "For {{experience}}, the primary contribution was writing a failed config for a run.",
  "{{github}} contains more winning trophys than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to failed the sprint with zero points.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to dropped the ball with zero points.",
  "Listed {{skill}} as a primary competency, but the evidence points to a failed team.",
  "Obtained {{certification}} which apparently teaches how to dropped the ball losing team confidence.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to failed the sprint in the final seconds.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to failed the sprint for the touchdown.",
  "{{github}} contains more slow champions than original code.",
  "Obtained {{certification}} which apparently teaches how to lost the tournament on national television.",
  "A security audit on {{github}} detected a plain-text database password inside a failed game.",
  "Failed to configure {{project}} because {{candidateName}} decided to dropped the ball on national television.",
  "{{github}} contains more slow players than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to lost the tournament for the touchdown.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to missed the target in the final seconds.",
  "{{github}} contains more competitive trophys than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to ran slow play for the touchdown.",
  "{{github}} contains more winning games than original code.",
  "For {{experience}}, the primary contribution was writing a legendary config for a trophy.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to dropped the ball for the touchdown.",
  "A security audit on {{github}} detected a plain-text database password inside a winning run.",
  "Failed to configure {{project}} because {{candidateName}} decided to failed the sprint in the final seconds.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to missed the target for the touchdown.",
  "Obtained {{certification}} which apparently teaches how to ran slow play for the touchdown.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to dropped the ball losing team confidence.",
  "{{github}} contains more winning stadiums than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to lost the tournament for the touchdown.",
  "Failed to configure {{project}} because {{candidateName}} decided to missed the target for the touchdown.",
  "Obtained {{certification}} which apparently teaches how to dropped the ball in the final seconds.",
  "Obtained {{certification}} which apparently teaches how to lost the tournament with zero points.",
  "{{github}} contains more terrible scores than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ran slow play for the touchdown.",
  "{{github}} contains more terrible trophys than original code.",
  "{{github}} contains more winning coachs than original code.",
  "Obtained {{certification}} which apparently teaches how to dropped the ball for the touchdown.",
  "Obtained {{certification}} which apparently teaches how to ran slow play in the final seconds.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to ran slow play losing team confidence.",
  "{{achievement}} was highlighted, but the git logs show they only managed to failed the sprint on national television.",
  "{{github}} contains more unprepared champions than original code.",
  "Obtained {{certification}} which apparently teaches how to missed the target for the touchdown.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to dropped the ball in the final seconds."
];

export const punchlines = [
  "The documentation was so empty, I had to use it as a virtual sketchbook.",
  "A junior developer looked at the player and immediately went to touch grass.",
  "The compiler requested emotional support after reading the legendary code.",
  "We would deploy it to production, but our SRE team deserves to sleep at night.",
  "The only thing memory-safe about this setup is that nobody has ever tried to run it.",
  "Legend says this failed game is still running on localhost.",
  "Even Stack Overflow has marked this play as off-topic.",
  "It did not optimize our process, but it did make the laptop fan spin like a jet engine.",
  "Legend says this competitive stadium is still running on localhost.",
  "Legend says this unprepared champion is still running on localhost.",
  "Legend says this failed score is still running on localhost.",
  "Legend says this legendary coach is still running on localhost.",
  "Legend says this unprepared run is still running on localhost.",
  "Legend says this competitive game is still running on localhost.",
  "Legend says this terrible score is still running on localhost.",
  "Legend says this fast trophy is still running on localhost.",
  "Legend says this unprepared score is still running on localhost.",
  "Legend says this failed stadium is still running on localhost.",
  "Legend says this winning stadium is still running on localhost.",
  "Legend says this slow stadium is still running on localhost.",
  "Legend says this slow score is still running on localhost.",
  "Legend says this failed play is still running on localhost.",
  "Legend says this legendary game is still running on localhost.",
  "Legend says this failed champion is still running on localhost.",
  "Legend says this fast player is still running on localhost.",
  "Legend says this failed coach is still running on localhost.",
  "Legend says this fast team is still running on localhost.",
  "Legend says this legendary run is still running on localhost.",
  "Legend says this unprepared trophy is still running on localhost.",
  "Legend says this winning champion is still running on localhost.",
  "Legend says this fast champion is still running on localhost.",
  "Legend says this failed team is still running on localhost.",
  "Legend says this winning score is still running on localhost.",
  "Legend says this fast play is still running on localhost.",
  "Legend says this legendary trophy is still running on localhost.",
  "Legend says this terrible champion is still running on localhost.",
  "Legend says this unprepared stadium is still running on localhost.",
  "Legend says this failed player is still running on localhost.",
  "Legend says this competitive play is still running on localhost.",
  "Legend says this unprepared team is still running on localhost.",
  "Legend says this terrible coach is still running on localhost.",
  "Legend says this competitive trophy is still running on localhost.",
  "Legend says this terrible stadium is still running on localhost.",
  "Legend says this terrible player is still running on localhost.",
  "Legend says this terrible play is still running on localhost.",
  "Legend says this fast game is still running on localhost.",
  "Legend says this winning game is still running on localhost.",
  "Legend says this winning coach is still running on localhost.",
  "Legend says this unprepared game is still running on localhost.",
  "Legend says this terrible trophy is still running on localhost.",
  "Legend says this legendary player is still running on localhost.",
  "Legend says this fast coach is still running on localhost.",
  "Legend says this winning trophy is still running on localhost.",
  "Legend says this fast run is still running on localhost.",
  "Legend says this winning player is still running on localhost.",
  "Legend says this terrible team is still running on localhost.",
  "Legend says this unprepared player is still running on localhost.",
  "Legend says this slow coach is still running on localhost.",
  "Legend says this terrible game is still running on localhost.",
  "Legend says this legendary team is still running on localhost.",
  "Legend says this legendary stadium is still running on localhost.",
  "Legend says this slow champion is still running on localhost.",
  "Legend says this slow run is still running on localhost.",
  "Legend says this slow player is still running on localhost.",
  "Legend says this failed run is still running on localhost.",
  "This is a classic example of a competitive run disaster.",
  "This is a classic example of a winning team disaster.",
  "This is a classic example of a winning trophy disaster.",
  "This is a classic example of a slow coach disaster.",
  "This is a classic example of a slow team disaster.",
  "This is a classic example of a slow trophy disaster.",
  "This is a classic example of a unprepared run disaster.",
  "This is a classic example of a unprepared champion disaster.",
  "This is a classic example of a legendary team disaster.",
  "This is a classic example of a failed game disaster.",
  "This is a classic example of a failed coach disaster.",
  "This is a classic example of a slow play disaster.",
  "This is a classic example of a terrible champion disaster.",
  "This is a classic example of a unprepared trophy disaster.",
  "This is a classic example of a winning champion disaster.",
  "This is a classic example of a slow player disaster.",
  "This is a classic example of a fast player disaster.",
  "This is a classic example of a legendary score disaster.",
  "This is a classic example of a fast champion disaster.",
  "This is a classic example of a terrible run disaster.",
  "This is a classic example of a winning run disaster.",
  "This is a classic example of a legendary game disaster.",
  "This is a classic example of a terrible coach disaster.",
  "This is a classic example of a competitive coach disaster.",
  "This is a classic example of a competitive trophy disaster.",
  "This is a classic example of a terrible game disaster.",
  "This is a classic example of a winning player disaster.",
  "This is a classic example of a competitive champion disaster.",
  "This is a classic example of a legendary stadium disaster.",
  "This is a classic example of a failed champion disaster.",
  "This is a classic example of a terrible play disaster.",
  "This is a classic example of a competitive game disaster.",
  "This is a classic example of a slow game disaster.",
  "This is a classic example of a fast stadium disaster.",
  "This is a classic example of a winning stadium disaster.",
  "This is a classic example of a unprepared player disaster.",
  "This is a classic example of a unprepared coach disaster.",
  "This is a classic example of a terrible player disaster."
];

export const verdicts = [
  "Verdict: Player is completely unmergeable.",
  "Needs more commits and fewer explanations.",
  "Rejected on first principles of run organization.",
  "Return after touching actual production servers.",
  "Ship blocked by competitive check failures.",
  "Rejected on first principles of coach organization.",
  "Closed as fast duplicate.",
  "Request changes on the slow score.",
  "PR dropped the ball due to fast implementation.",
  "Request changes on the fast game.",
  "PR missed the target due to terrible implementation.",
  "Request changes on the fast team.",
  "Ship blocked by slow check failures.",
  "Verdict: Game is completely unmergeable.",
  "Closed as legendary duplicate.",
  "PR ran slow play due to slow implementation.",
  "PR missed the target due to legendary implementation.",
  "Verdict: Coach is completely unmergeable.",
  "Rejected on first principles of play organization.",
  "PR lost the tournament due to failed implementation.",
  "Ship blocked by legendary check failures.",
  "PR missed the target due to failed implementation.",
  "Closed as unprepared duplicate.",
  "Closed as competitive duplicate.",
  "Verdict: Play is completely unmergeable.",
  "Request changes on the terrible team.",
  "Verdict: Champion is completely unmergeable.",
  "Request changes on the unprepared trophy.",
  "Closed as slow duplicate.",
  "Request changes on the unprepared player.",
  "PR dropped the ball due to unprepared implementation.",
  "Ship blocked by fast check failures.",
  "Rejected on first principles of stadium organization.",
  "Rejected on first principles of score organization.",
  "Request changes on the competitive champion.",
  "Request changes on the competitive score.",
  "Request changes on the slow trophy.",
  "PR failed the sprint due to legendary implementation.",
  "Ship blocked by failed check failures.",
  "Request changes on the legendary score.",
  "Rejected on first principles of team organization.",
  "Verdict: Trophy is completely unmergeable.",
  "Request changes on the failed coach.",
  "Request changes on the winning score.",
  "Request changes on the winning trophy.",
  "Request changes on the slow team.",
  "Closed as winning duplicate.",
  "PR failed the sprint due to winning implementation.",
  "PR lost the tournament due to winning implementation.",
  "Ship blocked by winning check failures.",
  "PR dropped the ball due to competitive implementation.",
  "Request changes on the unprepared coach.",
  "Rejected on first principles of player organization.",
  "Request changes on the failed score.",
  "Request changes on the terrible play.",
  "Ship blocked by terrible check failures.",
  "Verdict: Stadium is completely unmergeable.",
  "Request changes on the terrible champion.",
  "Rejected on first principles of trophy organization.",
  "Request changes on the competitive play.",
  "Request changes on the slow player.",
  "Closed as failed duplicate.",
  "PR missed the target due to slow implementation.",
  "PR lost the tournament due to slow implementation.",
  "Verdict: Team is completely unmergeable.",
  "Rejected on first principles of game organization.",
  "Request changes on the competitive player.",
  "Request changes on the unprepared score.",
  "Ship blocked by unprepared check failures.",
  "PR failed the sprint due to unprepared implementation.",
  "Verdict: Run is completely unmergeable.",
  "Closed as terrible duplicate.",
  "Rejected on first principles of champion organization.",
  "Request changes on the terrible run.",
  "PR dropped the ball due to winning implementation.",
  "PR missed the target due to winning implementation.",
  "Request changes on the winning champion.",
  "PR lost the tournament due to fast implementation.",
  "Request changes on the unprepared champion.",
  "Request changes on the legendary stadium.",
  "Request changes on the unprepared play.",
  "Request changes on the terrible stadium.",
  "Request changes on the unprepared stadium.",
  "PR dropped the ball due to slow implementation.",
  "Request changes on the fast player.",
  "Request changes on the unprepared game.",
  "Request changes on the terrible game.",
  "Request changes on the competitive trophy.",
  "Request changes on the competitive game.",
  "Request changes on the fast trophy.",
  "PR lost the tournament due to unprepared implementation.",
  "Request changes on the unprepared team.",
  "Request changes on the failed team.",
  "PR missed the target due to unprepared implementation.",
  "Request changes on the fast score."
];

export const easterEggs = [
  "Matrix Glitch: You copy-pasted a template and now the server believes it is a real founder.",
  "Dark Web Resume Auction: Current bid is $0.00, and the buyer is requesting a refund.",
  "Steam Achievement Unlocked: Successfully crashed a hello-world app on a $10,000 server.",
  "FBI Investigation: Suspect was found deploying unencrypted fast plays.",
  "Gordon Ramsay Meltdown: 'This champion is raw! It's absolutely raw!'",
  "Elon Musk Tweet: 'Just deleted the entire trophy pipeline, was completely useless.'",
  "NASA Alert: Space mission aborted due to a minor champion parsing error.",
  "FBI Investigation: Suspect was found deploying unencrypted winning teams.",
  "Gordon Ramsay Meltdown: 'This play is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This stadium is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This run is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted competitive champions.",
  "Gordon Ramsay Meltdown: 'This coach is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This score is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This game is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This team is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted failed runs.",
  "Gordon Ramsay Meltdown: 'This trophy is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted unprepared trophys.",
  "FBI Investigation: Suspect was found deploying unencrypted terrible games."
];
