// ES Module exports for stack_overflow roast format
export const titles = [
  "The Moderator tragedy",
  "Basic Code Loop",
  "NullPointerGuidelinesException",
  "Critical Thread failure",
  "Downvoted Thread Error",
  "Failed to compile: Moderator",
  "Incident Report: Basic Downvote",
  "Thread Not Found",
  "NullPointerScoreException",
  "The Code tragedy",
  "Simple Guidelines Loop",
  "Absolute Basic architecture",
  "Incident Report: Off-topic Code",
  "Off-topic Score Loop",
  "Absolute Useless architecture",
  "Closed Answer Error",
  "Downvote Not Found",
  "The Duplicate tragedy",
  "Moderator Not Found",
  "NullPointerModeratorException",
  "Failed to compile: Code",
  "Closure Not Found",
  "Incident Report: Basic Guidelines",
  "Closure conflict detected",
  "The Downvote tragedy",
  "NullPointerClosureException",
  "Failed to compile: Downvote",
  "Off-topic Closure Loop",
  "Incident Report: Off-topic Closure",
  "Score Not Found",
  "Critical Closure failure",
  "Raw Score Loop",
  "Code conflict detected",
  "NullPointerQuestionException",
  "Downvoted Answer Loop",
  "Critical Question failure",
  "Incident Report: Raw Duplicate",
  "Absolute Duplicate architecture",
  "Incident Report: Basic Thread",
  "The Answer tragedy",
  "Simple Question Error",
  "NullPointerThreadException",
  "Absolute Raw architecture",
  "Critical Downvote failure",
  "Raw Closure Error",
  "Code Not Found",
  "Failed to compile: Score",
  "Useless Guidelines Loop",
  "Incident Report: Raw Score",
  "Simple Thread Loop",
  "Absolute Closed architecture",
  "Failed to compile: Thread",
  "NullPointerAnswerException",
  "Failed to compile: Duplicate",
  "Closed Thread Error",
  "Incident Report: Duplicate Code",
  "Absolute Simple architecture",
  "Duplicate Not Found",
  "Incident Report: Closed Downvote",
  "Incident Report: Closed Closure",
  "Duplicate Moderator Loop",
  "Critical Moderator failure",
  "NullPointerDuplicateException",
  "Useless Score Error",
  "NullPointerDownvoteException",
  "Simple Downvote Loop",
  "Raw Duplicate Loop",
  "Critical Duplicate failure",
  "Failed to compile: Question",
  "Basic Thread Loop",
  "Question Not Found",
  "The Closure tragedy",
  "Incident Report: Duplicate Answer",
  "Incident Report: Useless Answer",
  "Simple Code Error",
  "Failed to compile: Answer",
  "Thread conflict detected",
  "Moderator conflict detected",
  "Duplicate conflict detected",
  "Answer conflict detected",
  "Question conflict detected",
  "Off-topic Answer Loop",
  "Absolute Off-topic architecture",
  "Incident Report: Useless Score",
  "Duplicate Score Loop",
  "Score conflict detected",
  "Simple Answer Loop",
  "Incident Report: Closed Moderator",
  "Downvoted Guidelines Error",
  "Answer Not Found",
  "Raw Closure Loop",
  "Simple Closure Error",
  "Simple Code Loop",
  "Off-topic Code Loop",
  "NullPointerCodeException",
  "The Score tragedy",
  "Downvoted Moderator Loop",
  "Closed Moderator Loop",
  "Critical Guidelines failure",
  "The Question tragedy"
];

export const openings = [
  "Scanning candidate profile for raw duplicates...",
  "Scanning candidate profile for useless duplicates...",
  "We checked the history and found a useless closure log.",
  "Scanning candidate profile for closed moderators...",
  "Alert: The candidate spent three months trying to downvoted duplicate question violating coding guidelines.",
  "A review was filed regarding a off-topic code.",
  "The team has initiated audit for the candidate's thread setup.",
  "Recruiters reported a case of simple duplicate design.",
  "Scanning candidate profile for basic codes...",
  "Alert: The candidate spent three months trying to asked basic question with negative score.",
  "Alert: The candidate spent three months trying to downvoted duplicate question by senior moderator.",
  "Warning: System flagged an attempt to asked basic question as off-topic spam.",
  "Warning: System flagged an attempt to downvoted duplicate question as off-topic spam.",
  "We checked the history and found a duplicate question log.",
  "We checked the history and found a downvoted moderator log.",
  "A review was filed regarding a basic guidelines.",
  "Recruiters reported a case of closed question design.",
  "Alert: The candidate spent three months trying to asked basic question by senior moderator.",
  "A review was filed regarding a raw thread.",
  "A review was filed regarding a downvoted question.",
  "A review was filed regarding a closed answer.",
  "Scanning candidate profile for raw moderators...",
  "Initial evaluation shows the developer decided to downvoted duplicate question with negative score.",
  "Warning: System flagged an attempt to closed thread off-topic with negative score.",
  "We checked the history and found a downvoted question log.",
  "Alert: The candidate spent three months trying to flagged useless answer without reading details.",
  "Initial evaluation shows the developer decided to asked basic question with negative score.",
  "Scanning candidate profile for closed downvotes...",
  "A review was filed regarding a raw code.",
  "Initial evaluation shows the developer decided to asked basic question without reading details.",
  "A review was filed regarding a closed question.",
  "Scanning candidate profile for basic questions...",
  "Initial evaluation shows the developer decided to asked basic question by senior moderator.",
  "We checked the history and found a closed moderator log.",
  "Recruiters reported a case of useless closure design.",
  "Initial evaluation shows the developer decided to downvoted duplicate question by senior moderator.",
  "A review was filed regarding a duplicate score.",
  "Recruiters reported a case of useless duplicate design.",
  "A review was filed regarding a off-topic duplicate.",
  "Scanning candidate profile for closed threads...",
  "Initial evaluation shows the developer decided to asked basic question as off-topic spam.",
  "Alert: The candidate spent three months trying to downvoted code snippet with negative score.",
  "We checked the history and found a downvoted code log.",
  "Warning: System flagged an attempt to downvoted duplicate question without reading details.",
  "A review was filed regarding a simple duplicate.",
  "Alert: The candidate spent three months trying to downvoted code snippet as off-topic spam.",
  "Scanning candidate profile for downvoted duplicates...",
  "Scanning candidate profile for basic threads...",
  "Recruiters reported a case of useless answer design.",
  "Warning: System flagged an attempt to closed thread off-topic violating coding guidelines.",
  "Warning: System flagged an attempt to asked basic question violating coding guidelines.",
  "Recruiters reported a case of basic question design.",
  "Scanning candidate profile for closed duplicates...",
  "Warning: System flagged an attempt to downvoted code snippet with negative score.",
  "We checked the history and found a closed answer log.",
  "Recruiters reported a case of downvoted score design.",
  "Scanning candidate profile for simple duplicates...",
  "Alert: The candidate spent three months trying to flagged useless answer as off-topic spam.",
  "Recruiters reported a case of useless thread design.",
  "We checked the history and found a simple duplicate log.",
  "Recruiters reported a case of basic score design.",
  "A review was filed regarding a basic duplicate.",
  "A review was filed regarding a raw answer.",
  "Initial evaluation shows the developer decided to downvoted duplicate question as off-topic spam.",
  "Recruiters reported a case of off-topic closure design.",
  "We checked the history and found a simple guidelines log.",
  "Alert: The candidate spent three months trying to asked basic question without reading details.",
  "Scanning candidate profile for duplicate closures...",
  "Warning: System flagged an attempt to downvoted code snippet by senior moderator.",
  "Initial evaluation shows the developer decided to flagged useless answer with negative score.",
  "Warning: System flagged an attempt to downvoted code snippet as off-topic spam.",
  "We checked the history and found a basic question log.",
  "Scanning candidate profile for raw scores...",
  "We checked the history and found a basic downvote log.",
  "Alert: The candidate spent three months trying to flagged useless answer with negative score.",
  "Alert: The candidate spent three months trying to closed thread off-topic by senior moderator.",
  "Initial evaluation shows the developer decided to flagged useless answer without reading details.",
  "We checked the history and found a raw duplicate log.",
  "A review was filed regarding a basic answer.",
  "We checked the history and found a raw thread log.",
  "Warning: System flagged an attempt to flagged useless answer by senior moderator.",
  "Recruiters reported a case of raw question design.",
  "Alert: The candidate spent three months trying to closed thread off-topic with negative score.",
  "Initial evaluation shows the developer decided to asked basic question violating coding guidelines.",
  "Initial evaluation shows the developer decided to downvoted code snippet as off-topic spam.",
  "A review was filed regarding a basic code.",
  "Initial evaluation shows the developer decided to downvoted code snippet by senior moderator.",
  "Initial evaluation shows the developer decided to closed thread off-topic without reading details.",
  "Recruiters reported a case of raw code design.",
  "Warning: System flagged an attempt to downvoted duplicate question with negative score.",
  "Alert: The candidate spent three months trying to downvoted duplicate question with negative score."
];

export const findings = [
  "{{github}} contains more off-topic threads than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to downvoted code snippet by senior moderator.",
  "Obtained {{certification}} which apparently teaches how to flagged useless answer as off-topic spam.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to downvoted duplicate question with negative score.",
  "{{github}} contains more duplicate answers than original code.",
  "For {{experience}}, the primary contribution was writing a duplicate config for a answer.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to asked basic question violating coding guidelines.",
  "Obtained {{certification}} which apparently teaches how to flagged useless answer without reading details.",
  "{{achievement}} was highlighted, but the git logs show they only managed to downvoted duplicate question without reading details.",
  "Obtained {{certification}} which apparently teaches how to asked basic question with negative score.",
  "A security audit on {{github}} detected a plain-text database password inside a downvoted downvote.",
  "Listed {{skill}} as a primary competency, but the evidence points to a useless thread.",
  "The candidate claims {{framework}} experience, but their repository is just a off-topic clone that has been abandoned.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to closed thread off-topic as off-topic spam.",
  "{{github}} contains more downvoted codes than original code.",
  "Obtained {{certification}} which apparently teaches how to asked basic question as off-topic spam.",
  "While debugging {{project}}, we found a closed logic loop related to {{language}} features.",
  "{{achievement}} was highlighted, but the git logs show they only managed to asked basic question as off-topic spam.",
  "{{education}} is listed, but they still managed to deploy a useless guidelines to production.",
  "A security audit on {{github}} detected a plain-text database password inside a raw score.",
  "{{github}} contains more duplicate scores than original code.",
  "For {{experience}}, the primary contribution was writing a useless config for a thread.",
  "Failed to configure {{project}} because {{candidateName}} decided to downvoted duplicate question as off-topic spam.",
  "While debugging {{project}}, we found a off-topic logic loop related to {{language}} features.",
  "Listed {{skill}} as a primary competency, but the evidence points to a raw moderator.",
  "{{github}} contains more simple guideliness than original code.",
  "Listed {{skill}} as a primary competency, but the evidence points to a closed duplicate.",
  "{{github}} contains more raw codes than original code.",
  "{{github}} contains more raw duplicates than original code.",
  "{{github}} contains more closed threads than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to flagged useless answer as off-topic spam.",
  "Listed {{skill}} as a primary competency, but the evidence points to a basic guidelines.",
  "{{achievement}} was highlighted, but the git logs show they only managed to downvoted code snippet as off-topic spam.",
  "A security audit on {{github}} detected a plain-text database password inside a basic guidelines.",
  "{{achievement}} was highlighted, but the git logs show they only managed to downvoted duplicate question by senior moderator.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to downvoted code snippet by senior moderator.",
  "Obtained {{certification}} which apparently teaches how to downvoted code snippet violating coding guidelines.",
  "{{education}} is listed, but they still managed to deploy a raw answer to production.",
  "Failed to configure {{project}} because {{candidateName}} decided to downvoted duplicate question without reading details.",
  "Failed to configure {{project}} because {{candidateName}} decided to asked basic question violating coding guidelines.",
  "Listed {{skill}} as a primary competency, but the evidence points to a off-topic guidelines.",
  "{{candidateName}} has spent three weeks optimizing a code while completely ignoring {{missingSection}}.",
  "A security audit on {{github}} detected a plain-text database password inside a closed thread.",
  "{{achievement}} was highlighted, but the git logs show they only managed to asked basic question violating coding guidelines.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to asked basic question without reading details.",
  "Obtained {{certification}} which apparently teaches how to downvoted duplicate question by senior moderator.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to flagged useless answer violating coding guidelines.",
  "A security audit on {{github}} detected a plain-text database password inside a off-topic answer.",
  "{{github}} contains more downvoted downvotes than original code.",
  "Obtained {{certification}} which apparently teaches how to downvoted code snippet with negative score.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to flagged useless answer as off-topic spam.",
  "Failed to configure {{project}} because {{candidateName}} decided to flagged useless answer with negative score.",
  "For {{experience}}, the primary contribution was writing a raw config for a guidelines.",
  "For {{experience}}, the primary contribution was writing a closed config for a score.",
  "{{achievement}} was highlighted, but the git logs show they only managed to asked basic question without reading details.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to flagged useless answer by senior moderator.",
  "{{education}} is listed, but they still managed to deploy a downvoted score to production.",
  "{{github}} contains more duplicate questions than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to asked basic question by senior moderator.",
  "Failed to configure {{project}} because {{candidateName}} decided to flagged useless answer violating coding guidelines.",
  "A security audit on {{github}} detected a plain-text database password inside a simple answer.",
  "A security audit on {{github}} detected a plain-text database password inside a duplicate question.",
  "Obtained {{certification}} which apparently teaches how to closed thread off-topic violating coding guidelines.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to downvoted duplicate question without reading details.",
  "For {{experience}}, the primary contribution was writing a basic config for a moderator.",
  "For {{experience}}, the primary contribution was writing a off-topic config for a duplicate.",
  "Failed to configure {{project}} because {{candidateName}} decided to downvoted code snippet violating coding guidelines.",
  "{{github}} contains more simple threads than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to closed thread off-topic with negative score.",
  "Obtained {{certification}} which apparently teaches how to closed thread off-topic without reading details.",
  "{{github}} contains more useless downvotes than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to asked basic question with negative score.",
  "Failed to configure {{project}} because {{candidateName}} decided to flagged useless answer by senior moderator.",
  "{{achievement}} was highlighted, but the git logs show they only managed to downvoted code snippet with negative score.",
  "{{education}} is listed, but they still managed to deploy a off-topic answer to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to downvoted duplicate question violating coding guidelines.",
  "{{achievement}} was highlighted, but the git logs show they only managed to downvoted duplicate question as off-topic spam.",
  "Listed {{skill}} as a primary competency, but the evidence points to a downvoted answer.",
  "Obtained {{certification}} which apparently teaches how to flagged useless answer violating coding guidelines.",
  "Obtained {{certification}} which apparently teaches how to downvoted duplicate question without reading details.",
  "Obtained {{certification}} which apparently teaches how to closed thread off-topic by senior moderator.",
  "Failed to configure {{project}} because {{candidateName}} decided to downvoted duplicate question by senior moderator.",
  "Obtained {{certification}} which apparently teaches how to downvoted duplicate question violating coding guidelines.",
  "Obtained {{certification}} which apparently teaches how to downvoted duplicate question as off-topic spam.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to downvoted code snippet as off-topic spam.",
  "{{education}} is listed, but they still managed to deploy a duplicate question to production.",
  "Failed to configure {{project}} because {{candidateName}} decided to asked basic question by senior moderator.",
  "For {{experience}}, the primary contribution was writing a simple config for a closure.",
  "{{achievement}} was highlighted, but the git logs show they only managed to flagged useless answer with negative score.",
  "{{achievement}} was highlighted, but the git logs show they only managed to flagged useless answer without reading details.",
  "{{achievement}} was highlighted, but the git logs show they only managed to closed thread off-topic with negative score.",
  "Obtained {{certification}} which apparently teaches how to downvoted code snippet by senior moderator.",
  "Failed to configure {{project}} because {{candidateName}} decided to downvoted duplicate question violating coding guidelines.",
  "Failed to configure {{project}} because {{candidateName}} decided to asked basic question as off-topic spam.",
  "{{github}} contains more simple questions than original code.",
  "{{education}} is listed, but they still managed to deploy a simple downvote to production.",
  "{{github}} contains more simple moderators than original code.",
  "{{github}} contains more downvoted questions than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to asked basic question as off-topic spam.",
  "{{github}} contains more simple answers than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to flagged useless answer violating coding guidelines.",
  "{{achievement}} was highlighted, but the git logs show they only managed to downvoted duplicate question with negative score.",
  "Failed to configure {{project}} because {{candidateName}} decided to downvoted code snippet without reading details.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to downvoted duplicate question as off-topic spam.",
  "{{github}} contains more closed guideliness than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to closed thread off-topic by senior moderator.",
  "Obtained {{certification}} which apparently teaches how to downvoted code snippet without reading details.",
  "Obtained {{certification}} which apparently teaches how to asked basic question without reading details.",
  "Failed to configure {{project}} because {{candidateName}} decided to downvoted code snippet as off-topic spam.",
  "Obtained {{certification}} which apparently teaches how to closed thread off-topic as off-topic spam.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to closed thread off-topic violating coding guidelines.",
  "Obtained {{certification}} which apparently teaches how to downvoted code snippet as off-topic spam.",
  "Obtained {{certification}} which apparently teaches how to downvoted duplicate question with negative score.",
  "Listed {{skill}} as a primary competency, but the evidence points to a simple question.",
  "{{github}} contains more raw closures than original code."
];

export const punchlines = [
  "The only thing memory-safe about this setup is that nobody has ever tried to run it.",
  "Legend says this basic moderator is still running on localhost.",
  "We would deploy it to production, but our SRE team deserves to sleep at night.",
  "The documentation was so empty, I had to use it as a virtual sketchbook.",
  "Even Stack Overflow has marked this score as off-topic.",
  "A junior developer looked at the code and immediately went to touch grass.",
  "It did not optimize our process, but it did make the laptop fan spin like a jet engine.",
  "The compiler requested emotional support after reading the duplicate code.",
  "Legend says this raw closure is still running on localhost.",
  "Legend says this basic closure is still running on localhost.",
  "Legend says this duplicate question is still running on localhost.",
  "Legend says this closed guidelines is still running on localhost.",
  "The compiler requested emotional support after reading the off-topic code.",
  "Legend says this simple code is still running on localhost.",
  "Legend says this off-topic closure is still running on localhost.",
  "Legend says this basic question is still running on localhost.",
  "Legend says this closed thread is still running on localhost.",
  "Legend says this raw score is still running on localhost.",
  "Legend says this raw question is still running on localhost.",
  "Legend says this closed score is still running on localhost.",
  "Legend says this basic duplicate is still running on localhost.",
  "Legend says this duplicate guidelines is still running on localhost.",
  "Legend says this raw answer is still running on localhost.",
  "Legend says this simple duplicate is still running on localhost.",
  "Legend says this duplicate moderator is still running on localhost.",
  "Legend says this duplicate downvote is still running on localhost.",
  "Legend says this duplicate thread is still running on localhost.",
  "Legend says this basic downvote is still running on localhost.",
  "Legend says this raw code is still running on localhost.",
  "Legend says this downvoted answer is still running on localhost.",
  "Legend says this raw moderator is still running on localhost.",
  "Legend says this downvoted moderator is still running on localhost.",
  "Legend says this useless closure is still running on localhost.",
  "Legend says this duplicate code is still running on localhost.",
  "Legend says this closed code is still running on localhost.",
  "Legend says this simple downvote is still running on localhost.",
  "Legend says this simple score is still running on localhost.",
  "Legend says this basic answer is still running on localhost.",
  "Legend says this duplicate answer is still running on localhost.",
  "Legend says this downvoted score is still running on localhost.",
  "Legend says this basic guidelines is still running on localhost.",
  "Legend says this closed downvote is still running on localhost.",
  "Legend says this downvoted thread is still running on localhost.",
  "Legend says this useless guidelines is still running on localhost.",
  "Legend says this simple moderator is still running on localhost.",
  "Legend says this useless answer is still running on localhost.",
  "Legend says this raw duplicate is still running on localhost.",
  "Legend says this downvoted guidelines is still running on localhost.",
  "Legend says this useless score is still running on localhost.",
  "Legend says this closed moderator is still running on localhost.",
  "Legend says this useless moderator is still running on localhost.",
  "Legend says this basic score is still running on localhost.",
  "Legend says this basic thread is still running on localhost.",
  "Legend says this closed question is still running on localhost.",
  "Legend says this simple answer is still running on localhost.",
  "Legend says this closed duplicate is still running on localhost.",
  "Legend says this downvoted duplicate is still running on localhost.",
  "Legend says this duplicate closure is still running on localhost.",
  "Legend says this useless duplicate is still running on localhost.",
  "Legend says this simple question is still running on localhost.",
  "Legend says this raw downvote is still running on localhost.",
  "Legend says this simple closure is still running on localhost.",
  "Legend says this downvoted downvote is still running on localhost.",
  "Legend says this downvoted code is still running on localhost.",
  "Legend says this downvoted closure is still running on localhost.",
  "This is a classic example of a downvoted answer disaster.",
  "This is a classic example of a duplicate score disaster.",
  "This is a classic example of a downvoted downvote disaster.",
  "This is a classic example of a off-topic downvote disaster.",
  "This is a classic example of a closed guidelines disaster.",
  "This is a classic example of a off-topic moderator disaster.",
  "This is a classic example of a downvoted question disaster.",
  "This is a classic example of a raw closure disaster.",
  "This is a classic example of a basic moderator disaster.",
  "This is a classic example of a useless answer disaster.",
  "This is a classic example of a basic guidelines disaster.",
  "This is a classic example of a simple closure disaster.",
  "This is a classic example of a closed downvote disaster.",
  "This is a classic example of a useless score disaster.",
  "This is a classic example of a basic score disaster.",
  "This is a classic example of a downvoted score disaster.",
  "This is a classic example of a simple thread disaster.",
  "This is a classic example of a off-topic duplicate disaster.",
  "This is a classic example of a closed duplicate disaster.",
  "This is a classic example of a raw score disaster.",
  "This is a classic example of a basic answer disaster.",
  "This is a classic example of a raw guidelines disaster.",
  "This is a classic example of a raw downvote disaster.",
  "This is a classic example of a closed moderator disaster.",
  "This is a classic example of a useless moderator disaster.",
  "This is a classic example of a basic closure disaster.",
  "This is a classic example of a basic duplicate disaster.",
  "This is a classic example of a duplicate downvote disaster.",
  "This is a classic example of a closed answer disaster.",
  "This is a classic example of a raw thread disaster.",
  "This is a classic example of a useless guidelines disaster.",
  "This is a classic example of a useless question disaster.",
  "This is a classic example of a downvoted code disaster.",
  "This is a classic example of a basic downvote disaster.",
  "This is a classic example of a duplicate question disaster.",
  "This is a classic example of a downvoted guidelines disaster.",
  "This is a classic example of a simple downvote disaster.",
  "This is a classic example of a simple question disaster.",
  "This is a classic example of a off-topic answer disaster.",
  "This is a classic example of a duplicate thread disaster.",
  "This is a classic example of a duplicate answer disaster.",
  "This is a classic example of a closed question disaster."
];

export const verdicts = [
  "Ship blocked by off-topic check failures.",
  "Needs more commits and fewer explanations.",
  "Rejected on first principles of code organization.",
  "PR downvoted code snippet due to simple implementation.",
  "PR closed thread off-topic due to off-topic implementation.",
  "Closed as useless duplicate.",
  "PR downvoted duplicate question due to simple implementation.",
  "Return after touching actual production servers.",
  "Verdict: Answer is completely unmergeable.",
  "Verdict: Closure is completely unmergeable.",
  "Ship blocked by duplicate check failures.",
  "Verdict: Guidelines is completely unmergeable.",
  "Request changes on the basic downvote.",
  "Rejected on first principles of closure organization.",
  "Rejected on first principles of thread organization.",
  "Closed as duplicate duplicate.",
  "Request changes on the duplicate duplicate.",
  "Request changes on the simple answer.",
  "Rejected on first principles of guidelines organization.",
  "Rejected on first principles of score organization.",
  "Request changes on the off-topic guidelines.",
  "Request changes on the raw question.",
  "Ship blocked by closed check failures.",
  "Rejected on first principles of question organization.",
  "Verdict: Moderator is completely unmergeable.",
  "Request changes on the basic closure.",
  "Closed as off-topic duplicate.",
  "Rejected on first principles of duplicate organization.",
  "Closed as raw duplicate.",
  "Request changes on the off-topic closure.",
  "Ship blocked by raw check failures.",
  "Closed as basic duplicate.",
  "Request changes on the closed moderator.",
  "Verdict: Thread is completely unmergeable.",
  "Ship blocked by basic check failures.",
  "Rejected on first principles of downvote organization.",
  "Request changes on the simple moderator.",
  "PR asked basic question due to downvoted implementation.",
  "Request changes on the basic code.",
  "Rejected on first principles of moderator organization.",
  "PR flagged useless answer due to basic implementation.",
  "Ship blocked by downvoted check failures.",
  "Request changes on the basic guidelines.",
  "Closed as downvoted duplicate.",
  "Request changes on the closed question.",
  "Ship blocked by simple check failures.",
  "Request changes on the downvoted closure.",
  "Request changes on the downvoted score.",
  "PR downvoted code snippet due to off-topic implementation.",
  "PR flagged useless answer due to downvoted implementation.",
  "Verdict: Question is completely unmergeable.",
  "PR flagged useless answer due to raw implementation.",
  "Verdict: Downvote is completely unmergeable.",
  "Verdict: Duplicate is completely unmergeable.",
  "Request changes on the closed thread.",
  "Verdict: Code is completely unmergeable.",
  "Request changes on the useless thread.",
  "Request changes on the useless moderator.",
  "PR downvoted duplicate question due to closed implementation.",
  "PR asked basic question due to simple implementation.",
  "Verdict: Score is completely unmergeable.",
  "Request changes on the off-topic score.",
  "Request changes on the downvoted thread.",
  "Request changes on the raw guidelines.",
  "Request changes on the off-topic code.",
  "Ship blocked by useless check failures.",
  "Rejected on first principles of answer organization.",
  "Closed as simple duplicate.",
  "Request changes on the downvoted question.",
  "PR downvoted duplicate question due to basic implementation.",
  "Request changes on the closed guidelines.",
  "PR downvoted duplicate question due to off-topic implementation.",
  "Request changes on the basic answer.",
  "PR downvoted code snippet due to basic implementation.",
  "Request changes on the useless score.",
  "Request changes on the simple thread.",
  "Request changes on the closed code.",
  "Request changes on the simple code.",
  "PR asked basic question due to closed implementation.",
  "Request changes on the off-topic answer.",
  "PR downvoted code snippet due to closed implementation.",
  "PR asked basic question due to useless implementation.",
  "Request changes on the simple closure.",
  "PR flagged useless answer due to duplicate implementation.",
  "PR downvoted duplicate question due to raw implementation.",
  "Request changes on the off-topic question.",
  "PR downvoted code snippet due to duplicate implementation."
];

export const easterEggs = [
  "Gordon Ramsay Meltdown: 'This downvote is raw! It's absolutely raw!'",
  "Dark Web Resume Auction: Current bid is $0.00, and the buyer is requesting a refund.",
  "NASA Alert: Space mission aborted due to a minor question parsing error.",
  "Gordon Ramsay Meltdown: 'This answer is raw! It's absolutely raw!'",
  "Elon Musk Tweet: 'Just deleted the entire code pipeline, was completely useless.'",
  "FBI Investigation: Suspect was found deploying unencrypted raw codes.",
  "Gordon Ramsay Meltdown: 'This score is raw! It's absolutely raw!'",
  "Steam Achievement Unlocked: Successfully crashed a hello-world app on a $10,000 server.",
  "FBI Investigation: Suspect was found deploying unencrypted off-topic guideliness.",
  "FBI Investigation: Suspect was found deploying unencrypted simple closures.",
  "FBI Investigation: Suspect was found deploying unencrypted useless moderators.",
  "Gordon Ramsay Meltdown: 'This moderator is raw! It's absolutely raw!'",
  "Matrix Glitch: You copy-pasted a template and now the server believes it is a real founder.",
  "FBI Investigation: Suspect was found deploying unencrypted closed duplicates.",
  "Gordon Ramsay Meltdown: 'This code is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted duplicate scores.",
  "Gordon Ramsay Meltdown: 'This duplicate is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This closure is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This guidelines is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This question is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted basic questions."
];
