// ES Module exports for startup_investor roast format
export const titles = [
  "Founder Not Found",
  "Failed to compile: Deck",
  "Incident Report: Unfunded Round",
  "NullPointerPitchException",
  "Incident Report: Stealth ARR",
  "Disruptive Valuation Error",
  "Stealthy Deck Loop",
  "Pre-revenue Deck Loop",
  "Disruptive Deck Error",
  "NullPointerPivotException",
  "Stealthy Founder Error",
  "Failed to compile: Capital",
  "The Deck tragedy",
  "Absolute Pre-product architecture",
  "Pre-revenue ARR Error",
  "Unfunded Capital Loop",
  "Failed to compile: ARR",
  "Incident Report: Unfunded Valuation",
  "Pivot conflict detected",
  "Pre-product Capital Loop",
  "Failed to compile: Round",
  "Runway conflict detected",
  "Capital Not Found",
  "Critical Runway failure",
  "The Runway tragedy",
  "The Founder tragedy",
  "Failed to compile: Pitch",
  "The Pitch tragedy",
  "The Round tragedy",
  "Disruptive Pivot Loop",
  "Critical Pivot failure",
  "Delusional Pitch Loop",
  "Stealth Founder Error",
  "Critical Capital failure",
  "Absolute Bootstrapped architecture",
  "Runway Not Found",
  "Incident Report: Delusional Runway",
  "Disruptive Runway Loop",
  "Round conflict detected",
  "Critical Founder failure",
  "Delusional ARR Error",
  "Unfunded Capital Error",
  "Pre-product ARR Loop",
  "Delusional Valuation Loop",
  "Incident Report: Stealthy Round",
  "Absolute Stealth architecture",
  "NullPointerEquityException",
  "Stealth Equity Loop",
  "Pre-revenue Valuation Loop",
  "Incident Report: Disruptive Pivot",
  "Incident Report: Disruptive Deck",
  "Delusional Deck Loop",
  "Unfunded Founder Error",
  "Pitch Not Found",
  "The Valuation tragedy",
  "Incident Report: Bootstrapped Round",
  "ARR Not Found",
  "Stealth Pitch Error",
  "Incident Report: Stealth Valuation",
  "Delusional Capital Loop",
  "Absolute Pre-revenue architecture",
  "Incident Report: Stealthy Founder",
  "Absolute Unfunded architecture",
  "Unfunded Pitch Error",
  "Absolute Delusional architecture",
  "Critical Round failure",
  "Critical ARR failure",
  "Delusional Equity Error",
  "Stealth Valuation Loop",
  "Critical Equity failure",
  "Equity conflict detected",
  "Failed to compile: Runway",
  "Unfunded Pitch Loop",
  "Failed to compile: Equity",
  "Stealth Valuation Error",
  "The Capital tragedy",
  "Delusional Runway Error",
  "Pre-revenue Equity Loop",
  "NullPointerCapitalException",
  "Disruptive Round Loop",
  "Stealth Capital Loop",
  "The Pivot tragedy",
  "NullPointerDeckException",
  "Absolute Disruptive architecture",
  "NullPointerFounderException",
  "Deck Not Found",
  "Bootstrapped Equity Loop",
  "Incident Report: Unfunded Equity",
  "Incident Report: Pre-revenue Pitch",
  "Bootstrapped Runway Loop",
  "NullPointerARRException",
  "Equity Not Found",
  "Pre-product Pitch Loop",
  "Round Not Found",
  "NullPointerRunwayException",
  "Disruptive Capital Loop",
  "Pre-product ARR Error",
  "Incident Report: Stealth Pivot",
  "Valuation conflict detected",
  "The ARR tragedy"
];

export const openings = [
  "Scanning candidate profile for stealth capitals...",
  "The team has initiated audit for the candidate's capital setup.",
  "We checked the history and found a stealthy equity log.",
  "Initial evaluation shows the developer decided to negotiated equity split with zero customers.",
  "Warning: System flagged an attempt to burned runway capital with zero customers.",
  "Recruiters reported a case of stealth founder design.",
  "Scanning candidate profile for stealth ARRs...",
  "Warning: System flagged an attempt to pitched concept in stealth mode.",
  "We checked the history and found a stealthy pitch log.",
  "Recruiters reported a case of delusional ARR design.",
  "Initial evaluation shows the developer decided to burned runway capital at zero valuation.",
  "We checked the history and found a disruptive round log.",
  "Recruiters reported a case of disruptive pivot design.",
  "Scanning candidate profile for delusional founders...",
  "We checked the history and found a pre-product valuation log.",
  "Initial evaluation shows the developer decided to raised pre-seed round without a prototype.",
  "Initial evaluation shows the developer decided to negotiated equity split on credit card debt.",
  "Initial evaluation shows the developer decided to burned runway capital in stealth mode.",
  "Alert: The candidate spent three months trying to raised pre-seed round without a prototype.",
  "Warning: System flagged an attempt to negotiated equity split without a prototype.",
  "Alert: The candidate spent three months trying to pivoted stealth project without a prototype.",
  "Warning: System flagged an attempt to negotiated equity split on credit card debt.",
  "Warning: System flagged an attempt to burned runway capital without a prototype.",
  "Initial evaluation shows the developer decided to burned runway capital without a prototype.",
  "Alert: The candidate spent three months trying to pitched concept without a prototype.",
  "Alert: The candidate spent three months trying to negotiated equity split with zero customers.",
  "We checked the history and found a unfunded pitch log.",
  "We checked the history and found a stealthy valuation log.",
  "Recruiters reported a case of pre-product founder design.",
  "Initial evaluation shows the developer decided to negotiated equity split in stealth mode.",
  "Warning: System flagged an attempt to burned runway capital on credit card debt.",
  "A review was filed regarding a unfunded runway.",
  "Recruiters reported a case of stealthy pivot design.",
  "Warning: System flagged an attempt to raised pre-seed round without a prototype.",
  "Warning: System flagged an attempt to pitched concept without a prototype.",
  "Recruiters reported a case of stealth round design.",
  "A review was filed regarding a pre-revenue ARR.",
  "A review was filed regarding a pre-revenue runway.",
  "A review was filed regarding a pre-revenue pivot.",
  "Warning: System flagged an attempt to negotiated equity split at zero valuation.",
  "Recruiters reported a case of delusional deck design.",
  "Alert: The candidate spent three months trying to raised pre-seed round with zero customers.",
  "Warning: System flagged an attempt to pivoted stealth project on credit card debt.",
  "Scanning candidate profile for pre-revenue runways...",
  "Alert: The candidate spent three months trying to burned runway capital with zero customers.",
  "Scanning candidate profile for disruptive equitys...",
  "Initial evaluation shows the developer decided to pitched concept in stealth mode.",
  "Scanning candidate profile for disruptive valuations...",
  "Alert: The candidate spent three months trying to negotiated equity split at zero valuation.",
  "Scanning candidate profile for bootstrapped pitchs...",
  "A review was filed regarding a unfunded capital.",
  "Initial evaluation shows the developer decided to raised pre-seed round with zero customers.",
  "A review was filed regarding a stealth ARR.",
  "A review was filed regarding a disruptive capital.",
  "Warning: System flagged an attempt to raised pre-seed round at zero valuation.",
  "Warning: System flagged an attempt to negotiated equity split with zero customers.",
  "A review was filed regarding a pre-product pivot.",
  "Scanning candidate profile for delusional runways...",
  "Recruiters reported a case of disruptive equity design.",
  "We checked the history and found a unfunded runway log.",
  "Scanning candidate profile for bootstrapped decks...",
  "Scanning candidate profile for delusional pitchs...",
  "A review was filed regarding a delusional founder.",
  "We checked the history and found a bootstrapped valuation log.",
  "Recruiters reported a case of bootstrapped valuation design.",
  "Recruiters reported a case of pre-product pitch design.",
  "A review was filed regarding a pre-product equity.",
  "Scanning candidate profile for stealth pivots...",
  "Recruiters reported a case of stealth equity design.",
  "Alert: The candidate spent three months trying to negotiated equity split without a prototype.",
  "A review was filed regarding a stealth pivot.",
  "Scanning candidate profile for stealth valuations...",
  "Warning: System flagged an attempt to burned runway capital at zero valuation.",
  "Scanning candidate profile for unfunded runways...",
  "We checked the history and found a unfunded equity log.",
  "Alert: The candidate spent three months trying to pivoted stealth project with zero customers.",
  "Scanning candidate profile for stealthy decks...",
  "Alert: The candidate spent three months trying to pitched concept in stealth mode.",
  "Alert: The candidate spent three months trying to pitched concept on credit card debt.",
  "Alert: The candidate spent three months trying to pivoted stealth project at zero valuation.",
  "Scanning candidate profile for stealthy ARRs...",
  "A review was filed regarding a pre-revenue founder.",
  "Initial evaluation shows the developer decided to pivoted stealth project with zero customers.",
  "We checked the history and found a delusional runway log.",
  "Initial evaluation shows the developer decided to pivoted stealth project on credit card debt.",
  "A review was filed regarding a stealth runway.",
  "We checked the history and found a pre-revenue runway log."
];

export const findings = [
  "{{github}} contains more stealthy pivots than original code.",
  "Obtained {{certification}} which apparently teaches how to negotiated equity split without a prototype.",
  "Obtained {{certification}} which apparently teaches how to burned runway capital on credit card debt.",
  "The candidate claims {{framework}} experience, but their repository is just a disruptive clone that has been abandoned.",
  "Listed {{skill}} as a primary competency, but the evidence points to a unfunded founder.",
  "{{github}} contains more bootstrapped founders than original code.",
  "For {{experience}}, the primary contribution was writing a bootstrapped config for a runway.",
  "For {{experience}}, the primary contribution was writing a stealth config for a pivot.",
  "Failed to configure {{project}} because {{candidateName}} decided to burned runway capital on credit card debt.",
  "{{candidateName}} has spent three weeks optimizing a runway while completely ignoring {{missingSection}}.",
  "Failed to configure {{project}} because {{candidateName}} decided to negotiated equity split on credit card debt.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to pivoted stealth project in stealth mode.",
  "Failed to configure {{project}} because {{candidateName}} decided to burned runway capital in stealth mode.",
  "Failed to configure {{project}} because {{candidateName}} decided to raised pre-seed round at zero valuation.",
  "Listed {{skill}} as a primary competency, but the evidence points to a pre-revenue round.",
  "While debugging {{project}}, we found a stealthy logic loop related to {{language}} features.",
  "{{achievement}} was highlighted, but the git logs show they only managed to raised pre-seed round at zero valuation.",
  "Obtained {{certification}} which apparently teaches how to raised pre-seed round on credit card debt.",
  "Listed {{skill}} as a primary competency, but the evidence points to a bootstrapped capital.",
  "Obtained {{certification}} which apparently teaches how to raised pre-seed round at zero valuation.",
  "{{github}} contains more unfunded ARRs than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to negotiated equity split without a prototype.",
  "Obtained {{certification}} which apparently teaches how to pivoted stealth project on credit card debt.",
  "{{education}} is listed, but they still managed to deploy a delusional pivot to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to pitched concept at zero valuation.",
  "{{github}} contains more stealth pitchs than original code.",
  "{{github}} contains more unfunded valuations than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a pre-product deck.",
  "Failed to configure {{project}} because {{candidateName}} decided to raised pre-seed round with zero customers.",
  "{{github}} contains more delusional founders than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a bootstrapped round.",
  "{{github}} contains more disruptive rounds than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to pivoted stealth project with zero customers.",
  "{{education}} is listed, but they still managed to deploy a disruptive founder to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to raised pre-seed round without a prototype.",
  "{{achievement}} was highlighted, but the git logs show they only managed to raised pre-seed round on credit card debt.",
  "While debugging {{project}}, we found a pre-revenue logic loop related to {{language}} features.",
  "Obtained {{certification}} which apparently teaches how to burned runway capital in stealth mode.",
  "{{github}} contains more stealthy capitals than original code.",
  "{{github}} contains more pre-revenue founders than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to negotiated equity split on credit card debt.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to burned runway capital at zero valuation.",
  "{{achievement}} was highlighted, but the git logs show they only managed to burned runway capital on credit card debt.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to burned runway capital in stealth mode.",
  "{{education}} is listed, but they still managed to deploy a unfunded equity to production.",
  "Failed to configure {{project}} because {{candidateName}} decided to negotiated equity split at zero valuation.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to raised pre-seed round on credit card debt.",
  "{{achievement}} was highlighted, but the git logs show they only managed to negotiated equity split on credit card debt.",
  "Obtained {{certification}} which apparently teaches how to pivoted stealth project in stealth mode.",
  "Obtained {{certification}} which apparently teaches how to raised pre-seed round with zero customers.",
  "A security audit on {{github}} detected a plain-text database password inside a pre-revenue ARR.",
  "{{education}} is listed, but they still managed to deploy a bootstrapped pitch to production.",
  "{{education}} is listed, but they still managed to deploy a stealthy deck to production.",
  "Listed {{skill}} as a primary competency, but the evidence points to a stealth pivot.",
  "{{achievement}} was highlighted, but the git logs show they only managed to pivoted stealth project without a prototype.",
  "Obtained {{certification}} which apparently teaches how to raised pre-seed round in stealth mode.",
  "A security audit on {{github}} detected a plain-text database password inside a stealthy founder.",
  "{{github}} contains more disruptive capitals than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to negotiated equity split with zero customers.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to negotiated equity split in stealth mode.",
  "Failed to configure {{project}} because {{candidateName}} decided to pitched concept without a prototype.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to pitched concept with zero customers.",
  "Failed to configure {{project}} because {{candidateName}} decided to negotiated equity split without a prototype.",
  "Failed to configure {{project}} because {{candidateName}} decided to negotiated equity split in stealth mode.",
  "Listed {{skill}} as a primary competency, but the evidence points to a delusional valuation.",
  "Obtained {{certification}} which apparently teaches how to burned runway capital at zero valuation.",
  "{{github}} contains more stealthy founders than original code.",
  "{{education}} is listed, but they still managed to deploy a pre-product equity to production.",
  "For {{experience}}, the primary contribution was writing a stealthy config for a pitch.",
  "Listed {{skill}} as a primary competency, but the evidence points to a pre-product capital.",
  "{{achievement}} was highlighted, but the git logs show they only managed to raised pre-seed round in stealth mode.",
  "Failed to configure {{project}} because {{candidateName}} decided to pitched concept at zero valuation.",
  "Failed to configure {{project}} because {{candidateName}} decided to burned runway capital at zero valuation.",
  "Obtained {{certification}} which apparently teaches how to burned runway capital without a prototype.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to burned runway capital without a prototype.",
  "Failed to configure {{project}} because {{candidateName}} decided to burned runway capital without a prototype.",
  "A security audit on {{github}} detected a plain-text database password inside a disruptive equity.",
  "{{github}} contains more bootstrapped runways than original code.",
  "Obtained {{certification}} which apparently teaches how to pivoted stealth project at zero valuation.",
  "{{github}} contains more unfunded pivots than original code.",
  "Obtained {{certification}} which apparently teaches how to pitched concept without a prototype.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to pitched concept on credit card debt.",
  "{{education}} is listed, but they still managed to deploy a pre-revenue ARR to production.",
  "{{github}} contains more delusional rounds than original code.",
  "Obtained {{certification}} which apparently teaches how to negotiated equity split at zero valuation.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to negotiated equity split without a prototype.",
  "Obtained {{certification}} which apparently teaches how to pivoted stealth project without a prototype.",
  "{{github}} contains more bootstrapped equitys than original code.",
  "Listed {{skill}} as a primary competency, but the evidence points to a stealthy ARR.",
  "Failed to configure {{project}} because {{candidateName}} decided to pivoted stealth project on credit card debt.",
  "For {{experience}}, the primary contribution was writing a pre-revenue config for a founder.",
  "{{github}} contains more stealthy ARRs than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to pitched concept in stealth mode.",
  "{{github}} contains more delusional equitys than original code.",
  "{{education}} is listed, but they still managed to deploy a stealth valuation to production.",
  "{{github}} contains more disruptive valuations than original code.",
  "Obtained {{certification}} which apparently teaches how to raised pre-seed round without a prototype.",
  "{{achievement}} was highlighted, but the git logs show they only managed to negotiated equity split in stealth mode.",
  "{{github}} contains more bootstrapped ARRs than original code.",
  "{{github}} contains more stealth capitals than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a delusional pivot.",
  "{{github}} contains more unfunded decks than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a stealth capital.",
  "{{github}} contains more disruptive equitys than original code.",
  "{{github}} contains more disruptive decks than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to pivoted stealth project without a prototype.",
  "Obtained {{certification}} which apparently teaches how to pitched concept at zero valuation.",
  "Failed to configure {{project}} because {{candidateName}} decided to raised pre-seed round in stealth mode.",
  "Obtained {{certification}} which apparently teaches how to pivoted stealth project with zero customers.",
  "{{github}} contains more pre-product valuations than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to raised pre-seed round without a prototype.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to negotiated equity split with zero customers.",
  "Failed to configure {{project}} because {{candidateName}} decided to raised pre-seed round without a prototype.",
  "For {{experience}}, the primary contribution was writing a delusional config for a founder.",
  "For {{experience}}, the primary contribution was writing a pre-product config for a ARR.",
  "A security audit on {{github}} detected a plain-text database password inside a unfunded deck.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to pivoted stealth project with zero customers.",
  "{{github}} contains more disruptive ARRs than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to negotiated equity split with zero customers.",
  "{{github}} contains more stealth pivots than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to burned runway capital with zero customers.",
  "{{github}} contains more bootstrapped pitchs than original code."
];

export const punchlines = [
  "Legend says this disruptive capital is still running on localhost.",
  "Even Stack Overflow has marked this ARR as off-topic.",
  "It did not optimize our process, but it did make the laptop fan spin like a jet engine.",
  "The only thing memory-safe about this setup is that nobody has ever tried to run it.",
  "The documentation was so empty, I had to use it as a virtual sketchbook.",
  "A junior developer looked at the ARR and immediately went to touch grass.",
  "Legend says this disruptive pitch is still running on localhost.",
  "The compiler requested emotional support after reading the pre-product code.",
  "Legend says this pre-revenue founder is still running on localhost.",
  "We would deploy it to production, but our SRE team deserves to sleep at night.",
  "The compiler requested emotional support after reading the bootstrapped code.",
  "Legend says this delusional ARR is still running on localhost.",
  "Legend says this bootstrapped round is still running on localhost.",
  "Legend says this stealth runway is still running on localhost.",
  "Legend says this delusional valuation is still running on localhost.",
  "Legend says this disruptive valuation is still running on localhost.",
  "Legend says this pre-product deck is still running on localhost.",
  "Legend says this stealth equity is still running on localhost.",
  "Legend says this bootstrapped pitch is still running on localhost.",
  "Legend says this unfunded equity is still running on localhost.",
  "Legend says this disruptive deck is still running on localhost.",
  "Legend says this bootstrapped ARR is still running on localhost.",
  "Legend says this stealthy pitch is still running on localhost.",
  "Legend says this stealth founder is still running on localhost.",
  "Legend says this stealthy equity is still running on localhost.",
  "Legend says this stealthy founder is still running on localhost.",
  "Legend says this delusional pivot is still running on localhost.",
  "Legend says this unfunded founder is still running on localhost.",
  "Legend says this stealth pivot is still running on localhost.",
  "Legend says this stealthy ARR is still running on localhost.",
  "Legend says this unfunded ARR is still running on localhost.",
  "Legend says this stealthy valuation is still running on localhost.",
  "Legend says this stealthy pivot is still running on localhost.",
  "Legend says this delusional pitch is still running on localhost.",
  "Legend says this disruptive runway is still running on localhost.",
  "Legend says this bootstrapped capital is still running on localhost.",
  "Legend says this unfunded capital is still running on localhost.",
  "Legend says this delusional deck is still running on localhost.",
  "Legend says this stealthy runway is still running on localhost.",
  "Legend says this disruptive ARR is still running on localhost.",
  "Legend says this stealth capital is still running on localhost.",
  "Legend says this unfunded runway is still running on localhost.",
  "Legend says this disruptive equity is still running on localhost.",
  "Legend says this disruptive round is still running on localhost.",
  "Legend says this delusional runway is still running on localhost.",
  "Legend says this stealth valuation is still running on localhost.",
  "Legend says this unfunded pitch is still running on localhost.",
  "Legend says this delusional equity is still running on localhost.",
  "Legend says this disruptive founder is still running on localhost.",
  "Legend says this bootstrapped pivot is still running on localhost.",
  "Legend says this stealth pitch is still running on localhost.",
  "Legend says this bootstrapped runway is still running on localhost.",
  "Legend says this unfunded round is still running on localhost.",
  "Legend says this unfunded pivot is still running on localhost.",
  "Legend says this bootstrapped deck is still running on localhost.",
  "Legend says this stealthy capital is still running on localhost.",
  "Legend says this delusional round is still running on localhost.",
  "Legend says this stealthy round is still running on localhost.",
  "Legend says this stealthy deck is still running on localhost.",
  "This is a classic example of a delusional valuation disaster.",
  "This is a classic example of a stealth pitch disaster.",
  "This is a classic example of a unfunded pivot disaster.",
  "This is a classic example of a pre-product runway disaster.",
  "This is a classic example of a stealth valuation disaster.",
  "This is a classic example of a stealthy capital disaster.",
  "This is a classic example of a delusional equity disaster.",
  "This is a classic example of a bootstrapped runway disaster.",
  "This is a classic example of a unfunded round disaster.",
  "This is a classic example of a stealthy ARR disaster.",
  "This is a classic example of a pre-revenue founder disaster.",
  "This is a classic example of a bootstrapped pivot disaster.",
  "This is a classic example of a disruptive founder disaster.",
  "This is a classic example of a pre-product founder disaster.",
  "This is a classic example of a stealthy founder disaster.",
  "This is a classic example of a disruptive pitch disaster.",
  "This is a classic example of a delusional runway disaster.",
  "This is a classic example of a disruptive deck disaster.",
  "This is a classic example of a disruptive ARR disaster.",
  "This is a classic example of a unfunded pitch disaster.",
  "This is a classic example of a pre-revenue pitch disaster.",
  "This is a classic example of a pre-revenue runway disaster.",
  "This is a classic example of a stealth founder disaster.",
  "This is a classic example of a pre-revenue valuation disaster.",
  "This is a classic example of a delusional ARR disaster.",
  "This is a classic example of a stealth deck disaster.",
  "This is a classic example of a unfunded deck disaster.",
  "This is a classic example of a bootstrapped valuation disaster.",
  "This is a classic example of a pre-product valuation disaster.",
  "This is a classic example of a disruptive pivot disaster.",
  "This is a classic example of a delusional deck disaster.",
  "This is a classic example of a unfunded valuation disaster.",
  "This is a classic example of a stealth pivot disaster.",
  "This is a classic example of a bootstrapped pitch disaster.",
  "This is a classic example of a pre-product round disaster.",
  "This is a classic example of a delusional founder disaster.",
  "This is a classic example of a pre-product pivot disaster.",
  "This is a classic example of a pre-revenue ARR disaster.",
  "This is a classic example of a bootstrapped equity disaster.",
  "This is a classic example of a pre-product equity disaster."
];

export const verdicts = [
  "PR pivoted stealth project due to disruptive implementation.",
  "Closed as stealthy duplicate.",
  "Ship blocked by disruptive check failures.",
  "Verdict: Capital is completely unmergeable.",
  "Request changes on the stealthy pivot.",
  "PR raised pre-seed round due to unfunded implementation.",
  "Request changes on the pre-product runway.",
  "Needs more commits and fewer explanations.",
  "Rejected on first principles of pivot organization.",
  "Ship blocked by bootstrapped check failures.",
  "Closed as stealth duplicate.",
  "Rejected on first principles of round organization.",
  "Verdict: Equity is completely unmergeable.",
  "PR raised pre-seed round due to stealth implementation.",
  "Request changes on the stealth ARR.",
  "Verdict: Pivot is completely unmergeable.",
  "PR raised pre-seed round due to pre-product implementation.",
  "Return after touching actual production servers.",
  "Rejected on first principles of valuation organization.",
  "Closed as pre-product duplicate.",
  "Verdict: Founder is completely unmergeable.",
  "Verdict: Runway is completely unmergeable.",
  "Ship blocked by pre-product check failures.",
  "Request changes on the disruptive founder.",
  "Request changes on the bootstrapped equity.",
  "Rejected on first principles of deck organization.",
  "Rejected on first principles of pitch organization.",
  "PR burned runway capital due to delusional implementation.",
  "Verdict: Deck is completely unmergeable.",
  "Request changes on the stealthy valuation.",
  "Closed as delusional duplicate.",
  "PR negotiated equity split due to bootstrapped implementation.",
  "PR negotiated equity split due to stealth implementation.",
  "Request changes on the disruptive pitch.",
  "Rejected on first principles of capital organization.",
  "Request changes on the stealth round.",
  "Rejected on first principles of ARR organization.",
  "Request changes on the pre-product pitch.",
  "Ship blocked by stealthy check failures.",
  "Request changes on the pre-product round.",
  "Rejected on first principles of founder organization.",
  "Closed as disruptive duplicate.",
  "PR negotiated equity split due to unfunded implementation.",
  "Ship blocked by pre-revenue check failures.",
  "Request changes on the stealth equity.",
  "Request changes on the bootstrapped round.",
  "Request changes on the delusional founder.",
  "Request changes on the delusional ARR.",
  "Request changes on the pre-product founder.",
  "PR negotiated equity split due to disruptive implementation.",
  "Rejected on first principles of runway organization.",
  "PR raised pre-seed round due to bootstrapped implementation.",
  "PR pivoted stealth project due to delusional implementation.",
  "Request changes on the unfunded valuation.",
  "Ship blocked by stealth check failures.",
  "Ship blocked by unfunded check failures.",
  "Closed as unfunded duplicate.",
  "PR burned runway capital due to disruptive implementation.",
  "Request changes on the disruptive round.",
  "PR pitched concept due to pre-product implementation.",
  "Request changes on the stealth pivot.",
  "Verdict: ARR is completely unmergeable.",
  "PR pivoted stealth project due to pre-revenue implementation.",
  "Verdict: Round is completely unmergeable.",
  "Ship blocked by delusional check failures.",
  "PR burned runway capital due to bootstrapped implementation.",
  "PR burned runway capital due to pre-revenue implementation.",
  "Closed as pre-revenue duplicate.",
  "Request changes on the delusional equity.",
  "Request changes on the stealth runway.",
  "Verdict: Pitch is completely unmergeable.",
  "Request changes on the stealthy ARR.",
  "Rejected on first principles of equity organization.",
  "PR burned runway capital due to stealthy implementation.",
  "PR pitched concept due to stealthy implementation.",
  "Request changes on the bootstrapped valuation.",
  "Request changes on the unfunded founder.",
  "Request changes on the unfunded round.",
  "PR raised pre-seed round due to delusional implementation.",
  "Request changes on the delusional pivot.",
  "Request changes on the delusional deck.",
  "Request changes on the bootstrapped ARR.",
  "Request changes on the disruptive runway.",
  "Request changes on the disruptive valuation.",
  "PR pitched concept due to stealth implementation.",
  "Closed as bootstrapped duplicate.",
  "Request changes on the stealthy equity.",
  "Request changes on the bootstrapped runway.",
  "Request changes on the pre-product equity.",
  "Request changes on the stealthy deck.",
  "Request changes on the disruptive ARR.",
  "Verdict: Valuation is completely unmergeable.",
  "PR negotiated equity split due to stealthy implementation.",
  "PR raised pre-seed round due to disruptive implementation.",
  "Request changes on the stealthy runway.",
  "PR burned runway capital due to pre-product implementation.",
  "PR pitched concept due to disruptive implementation.",
  "Request changes on the bootstrapped founder.",
  "Request changes on the stealthy founder."
];

export const easterEggs = [
  "Elon Musk Tweet: 'Just deleted the entire ARR pipeline, was completely useless.'",
  "Gordon Ramsay Meltdown: 'This round is raw! It's absolutely raw!'",
  "Dark Web Resume Auction: Current bid is $0.00, and the buyer is requesting a refund.",
  "NASA Alert: Space mission aborted due to a minor ARR parsing error.",
  "FBI Investigation: Suspect was found deploying unencrypted disruptive runways.",
  "FBI Investigation: Suspect was found deploying unencrypted bootstrapped ARRs.",
  "Steam Achievement Unlocked: Successfully crashed a hello-world app on a $10,000 server.",
  "Gordon Ramsay Meltdown: 'This founder is raw! It's absolutely raw!'",
  "Matrix Glitch: You copy-pasted a template and now the server believes it is a real founder.",
  "Gordon Ramsay Meltdown: 'This ARR is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This equity is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted unfunded pivots.",
  "Gordon Ramsay Meltdown: 'This capital is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted stealthy valuations.",
  "FBI Investigation: Suspect was found deploying unencrypted stealth decks.",
  "FBI Investigation: Suspect was found deploying unencrypted pre-product pivots.",
  "Gordon Ramsay Meltdown: 'This valuation is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This deck is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This pivot is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted delusional pitchs."
];
