// ES Module exports for therapy_session roast format
export const titles = [
  "Critical Summary failure",
  "Mindset Not Found",
  "Session Not Found",
  "Therapist Not Found",
  "Critical Goals failure",
  "Patient Not Found",
  "NullPointerSessionException",
  "The Goals tragedy",
  "NullPointerSummaryException",
  "Failed to compile: Reality",
  "Absolute High-ego architecture",
  "Delusional Ego Error",
  "Summary conflict detected",
  "Summary Not Found",
  "Failed to compile: Session",
  "Delusion Not Found",
  "Mindset conflict detected",
  "Delusional Reality Loop",
  "Incident Report: Hyperactive Reality",
  "Therapist conflict detected",
  "Reality conflict detected",
  "The Mindset tragedy",
  "Failed to compile: Ego",
  "Empty Session Loop",
  "Critical Reality failure",
  "Critical Therapist failure",
  "Critical Intake failure",
  "Critical Patient failure",
  "Failed to compile: Therapist",
  "Patient conflict detected",
  "Ego Not Found",
  "Confused Summary Error",
  "Incident Report: Standard Goals",
  "Incident Report: Defensive Mindset",
  "Confused Mindset Error",
  "The Therapist tragedy",
  "Confused Goals Loop",
  "Standard Session Loop",
  "Hyperactive Reality Loop",
  "Standard Mindset Error",
  "NullPointerPatientException",
  "Incident Report: Empty Intake",
  "Incident Report: Defensive Delusion",
  "Incident Report: Unrealistic Summary",
  "Unrealistic Session Error",
  "Incident Report: Unrealistic Goals",
  "Incident Report: Hyperactive Patient",
  "Incident Report: Empty Ego",
  "Goals Not Found",
  "Absolute Unrealistic architecture",
  "The Intake tragedy",
  "Absolute Delusional architecture",
  "Absolute Confused architecture",
  "Absolute Standard architecture",
  "The Delusion tragedy",
  "Standard Delusion Error",
  "Failed to compile: Intake",
  "The Summary tragedy",
  "Confused Reality Error",
  "Critical Delusion failure",
  "Unrealistic Mindset Loop",
  "Delusional Patient Loop",
  "Failed to compile: Summary",
  "Incident Report: Delusional Reality",
  "Failed to compile: Patient",
  "Standard Session Error",
  "Empty Intake Loop",
  "Delusional Delusion Loop",
  "Delusional Intake Error",
  "Absolute Defensive architecture",
  "Unrealistic Summary Error",
  "High-ego Delusion Error",
  "Incident Report: Defensive Reality",
  "The Ego tragedy",
  "Delusional Ego Loop",
  "Absolute Hyperactive architecture",
  "Incident Report: Confused Reality",
  "Incident Report: Hyperactive Intake",
  "Unrealistic Intake Error",
  "Reality Not Found",
  "NullPointerGoalsException",
  "Intake conflict detected",
  "NullPointerEgoException",
  "The Patient tragedy",
  "NullPointerDelusionException",
  "Session conflict detected",
  "Incident Report: Unrealistic Delusion",
  "Absolute Empty architecture",
  "High-ego Patient Loop",
  "Confused Patient Error",
  "Intake Not Found",
  "High-ego Reality Error",
  "The Reality tragedy",
  "Delusional Patient Error",
  "Delusional Summary Error",
  "Critical Session failure",
  "Failed to compile: Mindset",
  "Defensive Session Error",
  "NullPointerRealityException",
  "Defensive Summary Error"
];

export const openings = [
  "A review was filed regarding a hyperactive mindset.",
  "Alert: The candidate spent three months trying to shared empty goals in the session.",
  "The team has initiated audit for the candidate's summary setup.",
  "Alert: The candidate spent three months trying to discussed grandiose dreams with zero self-awareness.",
  "Alert: The candidate spent three months trying to avoided professional reality in the session.",
  "Recruiters reported a case of delusional delusion design.",
  "Initial evaluation shows the developer decided to avoided professional reality with zero self-awareness.",
  "Initial evaluation shows the developer decided to evaluated patient mindset in the session.",
  "A review was filed regarding a unrealistic ego.",
  "Warning: System flagged an attempt to evaluated patient mindset in the session.",
  "Recruiters reported a case of high-ego ego design.",
  "We checked the history and found a hyperactive delusion log.",
  "A review was filed regarding a high-ego summary.",
  "Recruiters reported a case of delusional reality design.",
  "Warning: System flagged an attempt to evaluated patient mindset with zero self-awareness.",
  "A review was filed regarding a defensive goals.",
  "Initial evaluation shows the developer decided to defended poor metrics during intake review.",
  "Scanning candidate profile for confused therapists...",
  "Alert: The candidate spent three months trying to shared empty goals with high defensiveness.",
  "Recruiters reported a case of confused session design.",
  "We checked the history and found a unrealistic session log.",
  "Alert: The candidate spent three months trying to evaluated patient mindset in the session.",
  "A review was filed regarding a empty mindset.",
  "Warning: System flagged an attempt to evaluated patient mindset ignoring simple facts.",
  "We checked the history and found a confused intake log.",
  "Initial evaluation shows the developer decided to shared empty goals during intake review.",
  "Recruiters reported a case of delusional mindset design.",
  "Recruiters reported a case of standard reality design.",
  "Alert: The candidate spent three months trying to discussed grandiose dreams ignoring simple facts.",
  "Warning: System flagged an attempt to discussed grandiose dreams with zero self-awareness.",
  "We checked the history and found a high-ego summary log.",
  "A review was filed regarding a empty patient.",
  "Scanning candidate profile for delusional summarys...",
  "Alert: The candidate spent three months trying to discussed grandiose dreams in the session.",
  "Warning: System flagged an attempt to defended poor metrics during intake review.",
  "A review was filed regarding a empty delusion.",
  "We checked the history and found a standard delusion log.",
  "Scanning candidate profile for unrealistic patients...",
  "A review was filed regarding a unrealistic delusion.",
  "We checked the history and found a confused delusion log.",
  "Initial evaluation shows the developer decided to avoided professional reality ignoring simple facts.",
  "A review was filed regarding a standard patient.",
  "Scanning candidate profile for defensive patients...",
  "Alert: The candidate spent three months trying to discussed grandiose dreams with high defensiveness.",
  "Scanning candidate profile for confused delusions...",
  "Scanning candidate profile for standard sessions...",
  "Scanning candidate profile for high-ego delusions...",
  "A review was filed regarding a confused therapist.",
  "Scanning candidate profile for empty patients...",
  "Scanning candidate profile for high-ego sessions...",
  "A review was filed regarding a delusional delusion.",
  "Warning: System flagged an attempt to avoided professional reality during intake review.",
  "Recruiters reported a case of hyperactive therapist design.",
  "We checked the history and found a empty summary log.",
  "Scanning candidate profile for high-ego intakes...",
  "Warning: System flagged an attempt to shared empty goals during intake review.",
  "Scanning candidate profile for standard intakes...",
  "Warning: System flagged an attempt to shared empty goals with high defensiveness.",
  "Alert: The candidate spent three months trying to defended poor metrics with high defensiveness.",
  "Scanning candidate profile for unrealistic sessions...",
  "Alert: The candidate spent three months trying to evaluated patient mindset ignoring simple facts.",
  "Warning: System flagged an attempt to defended poor metrics with high defensiveness.",
  "A review was filed regarding a unrealistic summary.",
  "A review was filed regarding a confused patient.",
  "A review was filed regarding a standard delusion.",
  "Initial evaluation shows the developer decided to discussed grandiose dreams during intake review.",
  "Scanning candidate profile for defensive goalss...",
  "Warning: System flagged an attempt to discussed grandiose dreams ignoring simple facts.",
  "Scanning candidate profile for defensive mindsets...",
  "Initial evaluation shows the developer decided to defended poor metrics with high defensiveness.",
  "Scanning candidate profile for defensive delusions...",
  "Scanning candidate profile for high-ego mindsets...",
  "A review was filed regarding a confused ego.",
  "Initial evaluation shows the developer decided to shared empty goals with high defensiveness.",
  "A review was filed regarding a unrealistic mindset.",
  "Warning: System flagged an attempt to shared empty goals with zero self-awareness.",
  "We checked the history and found a delusional mindset log.",
  "We checked the history and found a delusional patient log.",
  "We checked the history and found a defensive patient log.",
  "Warning: System flagged an attempt to discussed grandiose dreams during intake review.",
  "We checked the history and found a hyperactive intake log.",
  "Recruiters reported a case of confused therapist design.",
  "Initial evaluation shows the developer decided to evaluated patient mindset with high defensiveness.",
  "Initial evaluation shows the developer decided to shared empty goals in the session.",
  "Scanning candidate profile for delusional goalss...",
  "Scanning candidate profile for standard egos...",
  "Warning: System flagged an attempt to avoided professional reality with zero self-awareness.",
  "Warning: System flagged an attempt to shared empty goals in the session."
];

export const findings = [
  "For {{experience}}, the primary contribution was writing a empty config for a mindset.",
  "The candidate claims {{framework}} experience, but their repository is just a empty clone that has been abandoned.",
  "Obtained {{certification}} which apparently teaches how to discussed grandiose dreams during intake review.",
  "Failed to configure {{project}} because {{candidateName}} decided to defended poor metrics in the session.",
  "{{education}} is listed, but they still managed to deploy a defensive delusion to production.",
  "{{education}} is listed, but they still managed to deploy a hyperactive session to production.",
  "{{candidateName}} has spent three weeks optimizing a delusion while completely ignoring {{missingSection}}.",
  "{{achievement}} was highlighted, but the git logs show they only managed to discussed grandiose dreams with zero self-awareness.",
  "While debugging {{project}}, we found a delusional logic loop related to {{language}} features.",
  "{{github}} contains more confused mindsets than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to defended poor metrics in the session.",
  "For {{experience}}, the primary contribution was writing a standard config for a summary.",
  "Listed {{skill}} as a primary competency, but the evidence points to a delusional goals.",
  "{{github}} contains more high-ego mindsets than original code.",
  "{{education}} is listed, but they still managed to deploy a high-ego ego to production.",
  "A security audit on {{github}} detected a plain-text database password inside a delusional summary.",
  "{{achievement}} was highlighted, but the git logs show they only managed to evaluated patient mindset during intake review.",
  "Obtained {{certification}} which apparently teaches how to discussed grandiose dreams in the session.",
  "For {{experience}}, the primary contribution was writing a hyperactive config for a reality.",
  "Obtained {{certification}} which apparently teaches how to evaluated patient mindset ignoring simple facts.",
  "{{achievement}} was highlighted, but the git logs show they only managed to evaluated patient mindset with zero self-awareness.",
  "For {{experience}}, the primary contribution was writing a defensive config for a goals.",
  "{{github}} contains more defensive sessions than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to defended poor metrics during intake review.",
  "Failed to configure {{project}} because {{candidateName}} decided to discussed grandiose dreams with zero self-awareness.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to shared empty goals with zero self-awareness.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to shared empty goals ignoring simple facts.",
  "{{github}} contains more hyperactive summarys than original code.",
  "{{github}} contains more defensive therapists than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to evaluated patient mindset during intake review.",
  "Listed {{skill}} as a primary competency, but the evidence points to a standard reality.",
  "A security audit on {{github}} detected a plain-text database password inside a unrealistic mindset.",
  "{{education}} is listed, but they still managed to deploy a unrealistic goals to production.",
  "Failed to configure {{project}} because {{candidateName}} decided to avoided professional reality during intake review.",
  "Listed {{skill}} as a primary competency, but the evidence points to a confused patient.",
  "For {{experience}}, the primary contribution was writing a high-ego config for a therapist.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to discussed grandiose dreams in the session.",
  "{{achievement}} was highlighted, but the git logs show they only managed to avoided professional reality with high defensiveness.",
  "Obtained {{certification}} which apparently teaches how to discussed grandiose dreams with zero self-awareness.",
  "A security audit on {{github}} detected a plain-text database password inside a empty ego.",
  "Obtained {{certification}} which apparently teaches how to discussed grandiose dreams ignoring simple facts.",
  "For {{experience}}, the primary contribution was writing a unrealistic config for a intake.",
  "{{achievement}} was highlighted, but the git logs show they only managed to evaluated patient mindset ignoring simple facts.",
  "{{achievement}} was highlighted, but the git logs show they only managed to discussed grandiose dreams ignoring simple facts.",
  "Obtained {{certification}} which apparently teaches how to defended poor metrics during intake review.",
  "{{achievement}} was highlighted, but the git logs show they only managed to avoided professional reality ignoring simple facts.",
  "A security audit on {{github}} detected a plain-text database password inside a hyperactive reality.",
  "Obtained {{certification}} which apparently teaches how to defended poor metrics in the session.",
  "A security audit on {{github}} detected a plain-text database password inside a defensive intake.",
  "{{achievement}} was highlighted, but the git logs show they only managed to discussed grandiose dreams in the session.",
  "Failed to configure {{project}} because {{candidateName}} decided to avoided professional reality with high defensiveness.",
  "{{achievement}} was highlighted, but the git logs show they only managed to shared empty goals with zero self-awareness.",
  "While debugging {{project}}, we found a high-ego logic loop related to {{language}} features.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to shared empty goals during intake review.",
  "{{github}} contains more hyperactive egos than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to defended poor metrics during intake review.",
  "{{achievement}} was highlighted, but the git logs show they only managed to defended poor metrics with high defensiveness.",
  "Listed {{skill}} as a primary competency, but the evidence points to a hyperactive delusion.",
  "Failed to configure {{project}} because {{candidateName}} decided to shared empty goals ignoring simple facts.",
  "{{github}} contains more hyperactive mindsets than original code.",
  "{{github}} contains more hyperactive goalss than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to discussed grandiose dreams during intake review.",
  "Listed {{skill}} as a primary competency, but the evidence points to a defensive summary.",
  "{{github}} contains more empty intakes than original code.",
  "{{github}} contains more confused therapists than original code.",
  "Listed {{skill}} as a primary competency, but the evidence points to a high-ego goals.",
  "Obtained {{certification}} which apparently teaches how to avoided professional reality ignoring simple facts.",
  "A security audit on {{github}} detected a plain-text database password inside a standard patient.",
  "Obtained {{certification}} which apparently teaches how to defended poor metrics ignoring simple facts.",
  "A security audit on {{github}} detected a plain-text database password inside a high-ego therapist.",
  "{{github}} contains more standard sessions than original code.",
  "{{github}} contains more confused summarys than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to avoided professional reality in the session.",
  "{{achievement}} was highlighted, but the git logs show they only managed to discussed grandiose dreams during intake review.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to evaluated patient mindset in the session.",
  "A security audit on {{github}} detected a plain-text database password inside a confused session.",
  "For {{experience}}, the primary contribution was writing a confused config for a delusion.",
  "{{github}} contains more unrealistic egos than original code.",
  "{{education}} is listed, but they still managed to deploy a confused summary to production.",
  "Failed to configure {{project}} because {{candidateName}} decided to discussed grandiose dreams with high defensiveness.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to evaluated patient mindset with zero self-awareness.",
  "Failed to configure {{project}} because {{candidateName}} decided to defended poor metrics with zero self-awareness.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to avoided professional reality with high defensiveness.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to defended poor metrics with high defensiveness.",
  "Failed to configure {{project}} because {{candidateName}} decided to discussed grandiose dreams in the session.",
  "{{github}} contains more delusional therapists than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to shared empty goals in the session.",
  "Obtained {{certification}} which apparently teaches how to shared empty goals with zero self-awareness.",
  "Failed to configure {{project}} because {{candidateName}} decided to defended poor metrics ignoring simple facts.",
  "{{achievement}} was highlighted, but the git logs show they only managed to defended poor metrics during intake review.",
  "Failed to configure {{project}} because {{candidateName}} decided to defended poor metrics with high defensiveness.",
  "{{achievement}} was highlighted, but the git logs show they only managed to avoided professional reality with zero self-awareness.",
  "Obtained {{certification}} which apparently teaches how to defended poor metrics with high defensiveness.",
  "Listed {{skill}} as a primary competency, but the evidence points to a unrealistic intake.",
  "Listed {{skill}} as a primary competency, but the evidence points to a empty mindset.",
  "Failed to configure {{project}} because {{candidateName}} decided to evaluated patient mindset with zero self-awareness.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to shared empty goals with high defensiveness.",
  "{{achievement}} was highlighted, but the git logs show they only managed to evaluated patient mindset in the session.",
  "Failed to configure {{project}} because {{candidateName}} decided to evaluated patient mindset in the session.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to avoided professional reality with zero self-awareness.",
  "Obtained {{certification}} which apparently teaches how to avoided professional reality with high defensiveness.",
  "{{github}} contains more standard goalss than original code.",
  "{{github}} contains more unrealistic patients than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to shared empty goals in the session.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to avoided professional reality in the session.",
  "Obtained {{certification}} which apparently teaches how to avoided professional reality with zero self-awareness.",
  "{{education}} is listed, but they still managed to deploy a standard intake to production."
];

export const punchlines = [
  "We would deploy it to production, but our SRE team deserves to sleep at night.",
  "The compiler requested emotional support after reading the standard code.",
  "The only thing memory-safe about this setup is that nobody has ever tried to run it.",
  "A junior developer looked at the reality and immediately went to touch grass.",
  "Even Stack Overflow has marked this session as off-topic.",
  "The documentation was so empty, I had to use it as a virtual sketchbook.",
  "It did not optimize our process, but it did make the laptop fan spin like a jet engine.",
  "Legend says this confused summary is still running on localhost.",
  "Legend says this standard intake is still running on localhost.",
  "Legend says this unrealistic mindset is still running on localhost.",
  "The compiler requested emotional support after reading the high-ego code.",
  "Legend says this confused mindset is still running on localhost.",
  "Legend says this confused reality is still running on localhost.",
  "Legend says this standard patient is still running on localhost.",
  "Legend says this high-ego goals is still running on localhost.",
  "Legend says this confused ego is still running on localhost.",
  "Legend says this delusional summary is still running on localhost.",
  "Legend says this empty goals is still running on localhost.",
  "Legend says this confused session is still running on localhost.",
  "Legend says this empty intake is still running on localhost.",
  "Legend says this hyperactive intake is still running on localhost.",
  "Legend says this empty summary is still running on localhost.",
  "Legend says this hyperactive mindset is still running on localhost.",
  "Legend says this empty session is still running on localhost.",
  "Legend says this defensive summary is still running on localhost.",
  "Legend says this unrealistic summary is still running on localhost.",
  "Legend says this unrealistic therapist is still running on localhost.",
  "Legend says this delusional session is still running on localhost.",
  "Legend says this defensive therapist is still running on localhost.",
  "Legend says this standard goals is still running on localhost.",
  "Legend says this unrealistic reality is still running on localhost.",
  "Legend says this standard session is still running on localhost.",
  "Legend says this empty patient is still running on localhost.",
  "Legend says this confused patient is still running on localhost.",
  "Legend says this delusional intake is still running on localhost.",
  "Legend says this confused delusion is still running on localhost.",
  "Legend says this confused therapist is still running on localhost.",
  "Legend says this defensive intake is still running on localhost.",
  "Legend says this standard delusion is still running on localhost.",
  "Legend says this hyperactive therapist is still running on localhost.",
  "Legend says this hyperactive reality is still running on localhost.",
  "Legend says this standard ego is still running on localhost.",
  "Legend says this empty ego is still running on localhost.",
  "Legend says this delusional delusion is still running on localhost.",
  "Legend says this empty mindset is still running on localhost.",
  "Legend says this hyperactive delusion is still running on localhost.",
  "Legend says this unrealistic ego is still running on localhost.",
  "Legend says this unrealistic goals is still running on localhost.",
  "Legend says this delusional ego is still running on localhost.",
  "Legend says this unrealistic session is still running on localhost.",
  "Legend says this defensive delusion is still running on localhost.",
  "Legend says this delusional goals is still running on localhost.",
  "Legend says this confused intake is still running on localhost.",
  "Legend says this hyperactive patient is still running on localhost.",
  "Legend says this standard summary is still running on localhost.",
  "Legend says this defensive session is still running on localhost.",
  "Legend says this unrealistic delusion is still running on localhost.",
  "Legend says this delusional patient is still running on localhost.",
  "Legend says this delusional mindset is still running on localhost.",
  "Legend says this defensive reality is still running on localhost.",
  "Legend says this hyperactive goals is still running on localhost.",
  "Legend says this empty reality is still running on localhost.",
  "Legend says this delusional therapist is still running on localhost.",
  "This is a classic example of a hyperactive mindset disaster.",
  "This is a classic example of a unrealistic therapist disaster.",
  "This is a classic example of a standard goals disaster.",
  "This is a classic example of a unrealistic reality disaster.",
  "This is a classic example of a defensive therapist disaster.",
  "This is a classic example of a high-ego reality disaster.",
  "This is a classic example of a unrealistic mindset disaster.",
  "This is a classic example of a defensive session disaster.",
  "This is a classic example of a defensive reality disaster.",
  "This is a classic example of a delusional session disaster.",
  "This is a classic example of a delusional patient disaster.",
  "This is a classic example of a standard therapist disaster.",
  "This is a classic example of a defensive intake disaster.",
  "This is a classic example of a confused therapist disaster.",
  "This is a classic example of a standard ego disaster.",
  "This is a classic example of a standard mindset disaster.",
  "This is a classic example of a confused intake disaster.",
  "This is a classic example of a confused session disaster.",
  "This is a classic example of a hyperactive goals disaster.",
  "This is a classic example of a defensive summary disaster.",
  "This is a classic example of a empty patient disaster.",
  "This is a classic example of a delusional ego disaster.",
  "This is a classic example of a delusional mindset disaster.",
  "This is a classic example of a unrealistic goals disaster.",
  "This is a classic example of a empty reality disaster.",
  "This is a classic example of a delusional therapist disaster.",
  "This is a classic example of a empty goals disaster.",
  "This is a classic example of a empty intake disaster.",
  "This is a classic example of a hyperactive delusion disaster.",
  "This is a classic example of a high-ego goals disaster.",
  "This is a classic example of a delusional summary disaster.",
  "This is a classic example of a high-ego mindset disaster.",
  "This is a classic example of a unrealistic delusion disaster.",
  "This is a classic example of a hyperactive intake disaster.",
  "This is a classic example of a defensive goals disaster.",
  "This is a classic example of a confused patient disaster.",
  "This is a classic example of a delusional reality disaster.",
  "This is a classic example of a defensive patient disaster."
];

export const verdicts = [
  "Needs more commits and fewer explanations.",
  "Verdict: Ego is completely unmergeable.",
  "Rejected on first principles of patient organization.",
  "Request changes on the standard goals.",
  "Closed as confused duplicate.",
  "Verdict: Summary is completely unmergeable.",
  "PR evaluated patient mindset due to hyperactive implementation.",
  "Verdict: Goals is completely unmergeable.",
  "Rejected on first principles of intake organization.",
  "Ship blocked by delusional check failures.",
  "Ship blocked by standard check failures.",
  "Verdict: Session is completely unmergeable.",
  "PR defended poor metrics due to unrealistic implementation.",
  "Return after touching actual production servers.",
  "Closed as defensive duplicate.",
  "Closed as standard duplicate.",
  "Closed as high-ego duplicate.",
  "Rejected on first principles of therapist organization.",
  "PR evaluated patient mindset due to standard implementation.",
  "Request changes on the delusional ego.",
  "PR evaluated patient mindset due to confused implementation.",
  "Rejected on first principles of reality organization.",
  "Ship blocked by confused check failures.",
  "Verdict: Therapist is completely unmergeable.",
  "Verdict: Mindset is completely unmergeable.",
  "Closed as empty duplicate.",
  "Ship blocked by empty check failures.",
  "PR discussed grandiose dreams due to unrealistic implementation.",
  "Rejected on first principles of goals organization.",
  "Verdict: Intake is completely unmergeable.",
  "Ship blocked by defensive check failures.",
  "Request changes on the hyperactive patient.",
  "Request changes on the standard mindset.",
  "Request changes on the high-ego session.",
  "Ship blocked by high-ego check failures.",
  "Rejected on first principles of mindset organization.",
  "Request changes on the standard intake.",
  "Rejected on first principles of delusion organization.",
  "PR discussed grandiose dreams due to standard implementation.",
  "PR evaluated patient mindset due to high-ego implementation.",
  "PR evaluated patient mindset due to defensive implementation.",
  "Ship blocked by unrealistic check failures.",
  "Request changes on the confused mindset.",
  "PR defended poor metrics due to empty implementation.",
  "PR discussed grandiose dreams due to confused implementation.",
  "Ship blocked by hyperactive check failures.",
  "Request changes on the delusional therapist.",
  "PR shared empty goals due to standard implementation.",
  "Request changes on the defensive session.",
  "Closed as delusional duplicate.",
  "PR defended poor metrics due to confused implementation.",
  "Request changes on the defensive reality.",
  "PR avoided professional reality due to confused implementation.",
  "Request changes on the confused intake.",
  "Request changes on the hyperactive session.",
  "PR discussed grandiose dreams due to high-ego implementation.",
  "Request changes on the hyperactive mindset.",
  "Request changes on the empty mindset.",
  "Request changes on the delusional delusion.",
  "Verdict: Reality is completely unmergeable.",
  "Request changes on the defensive therapist.",
  "Request changes on the confused session.",
  "Rejected on first principles of session organization.",
  "PR avoided professional reality due to hyperactive implementation.",
  "PR evaluated patient mindset due to delusional implementation.",
  "Request changes on the confused reality.",
  "Rejected on first principles of summary organization.",
  "Request changes on the empty intake.",
  "Request changes on the confused goals.",
  "Closed as hyperactive duplicate.",
  "Request changes on the unrealistic goals.",
  "Verdict: Delusion is completely unmergeable.",
  "Verdict: Patient is completely unmergeable.",
  "Closed as unrealistic duplicate.",
  "Rejected on first principles of ego organization.",
  "PR defended poor metrics due to standard implementation.",
  "Request changes on the standard summary.",
  "PR shared empty goals due to high-ego implementation.",
  "Request changes on the hyperactive ego.",
  "Request changes on the high-ego summary.",
  "PR shared empty goals due to defensive implementation.",
  "PR discussed grandiose dreams due to delusional implementation.",
  "Request changes on the unrealistic therapist.",
  "Request changes on the unrealistic summary.",
  "Request changes on the empty goals.",
  "PR discussed grandiose dreams due to defensive implementation.",
  "PR discussed grandiose dreams due to empty implementation.",
  "PR avoided professional reality due to unrealistic implementation.",
  "Request changes on the confused patient.",
  "Request changes on the high-ego patient.",
  "Request changes on the hyperactive therapist.",
  "PR avoided professional reality due to defensive implementation.",
  "PR defended poor metrics due to defensive implementation.",
  "PR shared empty goals due to unrealistic implementation.",
  "PR avoided professional reality due to empty implementation.",
  "Request changes on the standard ego.",
  "PR defended poor metrics due to hyperactive implementation.",
  "PR avoided professional reality due to delusional implementation.",
  "PR defended poor metrics due to delusional implementation."
];

export const easterEggs = [
  "FBI Investigation: Suspect was found deploying unencrypted standard realitys.",
  "FBI Investigation: Suspect was found deploying unencrypted hyperactive summarys.",
  "Elon Musk Tweet: 'Just deleted the entire mindset pipeline, was completely useless.'",
  "Gordon Ramsay Meltdown: 'This reality is raw! It's absolutely raw!'",
  "Steam Achievement Unlocked: Successfully crashed a hello-world app on a $10,000 server.",
  "Dark Web Resume Auction: Current bid is $0.00, and the buyer is requesting a refund.",
  "Gordon Ramsay Meltdown: 'This session is raw! It's absolutely raw!'",
  "Matrix Glitch: You copy-pasted a template and now the server believes it is a real founder.",
  "NASA Alert: Space mission aborted due to a minor ego parsing error.",
  "FBI Investigation: Suspect was found deploying unencrypted unrealistic therapists.",
  "Gordon Ramsay Meltdown: 'This summary is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted high-ego delusions.",
  "FBI Investigation: Suspect was found deploying unencrypted delusional delusions.",
  "Gordon Ramsay Meltdown: 'This therapist is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This goals is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This delusion is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted defensive goalss.",
  "Gordon Ramsay Meltdown: 'This patient is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted confused sessions.",
  "Gordon Ramsay Meltdown: 'This mindset is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This ego is raw! It's absolutely raw!'"
];
