// ES Module exports for vc_term_sheet roast format
export const titles = [
  "Equity conflict detected",
  "NullPointerEquityException",
  "Critical Valuation failure",
  "Critical Equity failure",
  "Stealth Seed Loop",
  "Deal Not Found",
  "Critical Pitch failure",
  "Incident Report: Pre-revenue Equity",
  "Pitch Not Found",
  "Pre-revenue Equity Error",
  "The Seed tragedy",
  "Pre-product Startup Error",
  "Failed to compile: VC",
  "Pitch conflict detected",
  "Absolute Cheap architecture",
  "Equity Not Found",
  "Slides Not Found",
  "Stealth Startup Error",
  "Valuation-zero Seed Error",
  "Pre-product Seed Loop",
  "Failed to compile: Seed",
  "Pre-product Runway Error",
  "High-burn Round Loop",
  "The Deal tragedy",
  "Incident Report: Pre-product Startup",
  "Valuation Not Found",
  "The Slides tragedy",
  "Runway Not Found",
  "Critical VC failure",
  "Critical Deal failure",
  "The Runway tragedy",
  "The Round tragedy",
  "Critical Seed failure",
  "Round conflict detected",
  "Failed to compile: Pitch",
  "Failed to compile: Valuation",
  "Incident Report: Empty Pitch",
  "Stealth Round Error",
  "Failed to compile: Round",
  "The Valuation tragedy",
  "Incident Report: Valuation-zero Runway",
  "Stealth Equity Loop",
  "NullPointerStartupException",
  "Incident Report: Rejected Deal",
  "Slides conflict detected",
  "Incident Report: Cheap Valuation",
  "Startup conflict detected",
  "Failed to compile: Slides",
  "NullPointerVCException",
  "Valuation-zero Runway Error",
  "Incident Report: High-burn Valuation",
  "Seed conflict detected",
  "Absolute Valuation-zero architecture",
  "The Equity tragedy",
  "Stealth Pitch Error",
  "Stealth VC Error",
  "Absolute Pre-revenue architecture",
  "Rejected Valuation Loop",
  "VC Not Found",
  "NullPointerSeedException",
  "Valuation-zero Slides Error",
  "NullPointerPitchException",
  "Incident Report: Rejected Startup",
  "Pre-product Pitch Error",
  "NullPointerRunwayException",
  "Failed to compile: Equity",
  "Pre-product Seed Error",
  "Valuation-zero Equity Error",
  "High-burn Round Error",
  "Rejected Deal Loop",
  "Incident Report: Empty Round",
  "VC conflict detected",
  "Empty Round Error",
  "Incident Report: Empty Startup",
  "Incident Report: High-burn Deal",
  "NullPointerRoundException",
  "Incident Report: Stealth Round",
  "Pre-product Round Error",
  "Pre-revenue Runway Error",
  "NullPointerDealException",
  "Cheap Equity Error",
  "Valuation conflict detected",
  "Rejected Pitch Error",
  "Stealth Round Loop",
  "Absolute Pre-product architecture",
  "Absolute Stealth architecture",
  "Deal conflict detected",
  "Incident Report: Valuation-zero Equity",
  "Critical Slides failure",
  "Pre-product VC Loop",
  "Incident Report: Valuation-zero Round",
  "Critical Runway failure",
  "Incident Report: Valuation-zero Slides",
  "Empty Pitch Error",
  "Incident Report: High-burn Seed",
  "The Pitch tragedy",
  "Incident Report: Cheap Startup",
  "Pre-revenue VC Loop",
  "Seed Not Found"
];

export const openings = [
  "Initial evaluation shows the developer decided to valued seed round with 80% equity request.",
  "Alert: The candidate spent three months trying to valued seed round with 80% equity request.",
  "Recruiters reported a case of pre-revenue runway design.",
  "Alert: The candidate spent three months trying to valued seed round with zero validation.",
  "Warning: System flagged an attempt to rejected pitch deck without active users.",
  "A review was filed regarding a valuation-zero startup.",
  "Alert: The candidate spent three months trying to valued seed round without active users.",
  "Warning: System flagged an attempt to pitched stealth concept with zero validation.",
  "Initial evaluation shows the developer decided to valued seed round at valuation ₹0.",
  "Scanning candidate profile for pre-revenue startups...",
  "Warning: System flagged an attempt to rejected pitch deck in stealth mode.",
  "The team has initiated audit for the candidate's VC setup.",
  "Scanning candidate profile for valuation-zero startups...",
  "Recruiters reported a case of pre-product VC design.",
  "A review was filed regarding a stealth equity.",
  "Recruiters reported a case of empty equity design.",
  "Warning: System flagged an attempt to valued seed round with 80% equity request.",
  "Initial evaluation shows the developer decided to offered cheap deal in stealth mode.",
  "We checked the history and found a high-burn startup log.",
  "A review was filed regarding a empty pitch.",
  "Recruiters reported a case of stealth runway design.",
  "Alert: The candidate spent three months trying to offered cheap deal with 80% equity request.",
  "Alert: The candidate spent three months trying to pitched stealth concept in stealth mode.",
  "A review was filed regarding a cheap deal.",
  "Scanning candidate profile for cheap equitys...",
  "A review was filed regarding a stealth startup.",
  "Scanning candidate profile for cheap VCs...",
  "A review was filed regarding a rejected runway.",
  "Warning: System flagged an attempt to burned runway capital in stealth mode.",
  "Scanning candidate profile for rejected VCs...",
  "We checked the history and found a cheap slides log.",
  "Initial evaluation shows the developer decided to offered cheap deal without active users.",
  "Initial evaluation shows the developer decided to burned runway capital with zero validation.",
  "We checked the history and found a rejected round log.",
  "Alert: The candidate spent three months trying to burned runway capital in stealth mode.",
  "Scanning candidate profile for cheap slidess...",
  "Recruiters reported a case of valuation-zero pitch design.",
  "Recruiters reported a case of cheap runway design.",
  "We checked the history and found a valuation-zero slides log.",
  "Scanning candidate profile for pre-revenue pitchs...",
  "Initial evaluation shows the developer decided to rejected pitch deck with zero validation.",
  "Scanning candidate profile for high-burn pitchs...",
  "Initial evaluation shows the developer decided to offered cheap deal at valuation ₹0.",
  "A review was filed regarding a cheap startup.",
  "Warning: System flagged an attempt to burned runway capital without active users.",
  "A review was filed regarding a stealth deal.",
  "We checked the history and found a pre-product equity log.",
  "Alert: The candidate spent three months trying to offered cheap deal in stealth mode.",
  "Initial evaluation shows the developer decided to pitched stealth concept in stealth mode.",
  "Recruiters reported a case of valuation-zero startup design.",
  "Scanning candidate profile for empty valuations...",
  "Alert: The candidate spent three months trying to offered cheap deal with zero validation.",
  "Alert: The candidate spent three months trying to rejected pitch deck in stealth mode.",
  "A review was filed regarding a rejected round.",
  "Scanning candidate profile for rejected deals...",
  "Recruiters reported a case of empty seed design.",
  "A review was filed regarding a rejected deal.",
  "We checked the history and found a empty runway log.",
  "A review was filed regarding a empty equity.",
  "Warning: System flagged an attempt to burned runway capital at valuation ₹0.",
  "Initial evaluation shows the developer decided to valued seed round with zero validation.",
  "Scanning candidate profile for high-burn deals...",
  "Scanning candidate profile for stealth valuations...",
  "Initial evaluation shows the developer decided to burned runway capital without active users.",
  "Alert: The candidate spent three months trying to offered cheap deal at valuation ₹0.",
  "A review was filed regarding a rejected equity.",
  "We checked the history and found a stealth VC log.",
  "Recruiters reported a case of pre-revenue round design.",
  "Warning: System flagged an attempt to valued seed round at valuation ₹0.",
  "Recruiters reported a case of valuation-zero deal design.",
  "Scanning candidate profile for pre-product runways...",
  "We checked the history and found a rejected startup log.",
  "Warning: System flagged an attempt to offered cheap deal with zero validation.",
  "Scanning candidate profile for cheap seeds...",
  "Scanning candidate profile for stealth slidess...",
  "Recruiters reported a case of rejected pitch design.",
  "Warning: System flagged an attempt to burned runway capital with 80% equity request.",
  "Warning: System flagged an attempt to burned runway capital with zero validation.",
  "Initial evaluation shows the developer decided to pitched stealth concept with 80% equity request.",
  "Recruiters reported a case of stealth round design.",
  "A review was filed regarding a pre-product slides.",
  "Recruiters reported a case of rejected runway design."
];

export const findings = [
  "While debugging {{project}}, we found a high-burn logic loop related to {{language}} features.",
  "For {{experience}}, the primary contribution was writing a valuation-zero config for a runway.",
  "{{candidateName}} has spent three weeks optimizing a seed while completely ignoring {{missingSection}}.",
  "Listed {{skill}} as a primary competency, but the evidence points to a cheap startup.",
  "The candidate claims {{framework}} experience, but their repository is just a empty clone that has been abandoned.",
  "A security audit on {{github}} detected a plain-text database password inside a rejected seed.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to offered cheap deal without active users.",
  "While debugging {{project}}, we found a pre-revenue logic loop related to {{language}} features.",
  "{{education}} is listed, but they still managed to deploy a stealth equity to production.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to valued seed round without active users.",
  "{{achievement}} was highlighted, but the git logs show they only managed to pitched stealth concept with zero validation.",
  "Failed to configure {{project}} because {{candidateName}} decided to rejected pitch deck with zero validation.",
  "{{education}} is listed, but they still managed to deploy a pre-revenue deal to production.",
  "Obtained {{certification}} which apparently teaches how to valued seed round in stealth mode.",
  "Obtained {{certification}} which apparently teaches how to burned runway capital with zero validation.",
  "For {{experience}}, the primary contribution was writing a cheap config for a VC.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to valued seed round at valuation ₹0.",
  "Listed {{skill}} as a primary competency, but the evidence points to a empty VC.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to burned runway capital without active users.",
  "Listed {{skill}} as a primary competency, but the evidence points to a pre-revenue seed.",
  "For {{experience}}, the primary contribution was writing a empty config for a deal.",
  "{{achievement}} was highlighted, but the git logs show they only managed to rejected pitch deck in stealth mode.",
  "Listed {{skill}} as a primary competency, but the evidence points to a high-burn valuation.",
  "Obtained {{certification}} which apparently teaches how to offered cheap deal in stealth mode.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to burned runway capital at valuation ₹0.",
  "Obtained {{certification}} which apparently teaches how to rejected pitch deck in stealth mode.",
  "A security audit on {{github}} detected a plain-text database password inside a stealth round.",
  "A security audit on {{github}} detected a plain-text database password inside a valuation-zero deal.",
  "{{github}} contains more pre-revenue deals than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to valued seed round with zero validation.",
  "Failed to configure {{project}} because {{candidateName}} decided to offered cheap deal in stealth mode.",
  "Obtained {{certification}} which apparently teaches how to valued seed round without active users.",
  "Obtained {{certification}} which apparently teaches how to offered cheap deal with zero validation.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to valued seed round with zero validation.",
  "{{education}} is listed, but they still managed to deploy a rejected pitch to production.",
  "For {{experience}}, the primary contribution was writing a pre-revenue config for a equity.",
  "{{github}} contains more rejected rounds than original code.",
  "While debugging {{project}}, we found a stealth logic loop related to {{language}} features.",
  "Listed {{skill}} as a primary competency, but the evidence points to a pre-product runway.",
  "{{education}} is listed, but they still managed to deploy a valuation-zero round to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to valued seed round in stealth mode.",
  "Listed {{skill}} as a primary competency, but the evidence points to a rejected seed.",
  "Obtained {{certification}} which apparently teaches how to burned runway capital without active users.",
  "A security audit on {{github}} detected a plain-text database password inside a pre-product seed.",
  "A security audit on {{github}} detected a plain-text database password inside a empty equity.",
  "{{github}} contains more high-burn runways than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to offered cheap deal in stealth mode.",
  "Failed to configure {{project}} because {{candidateName}} decided to offered cheap deal without active users.",
  "Failed to configure {{project}} because {{candidateName}} decided to rejected pitch deck with 80% equity request.",
  "Obtained {{certification}} which apparently teaches how to burned runway capital at valuation ₹0.",
  "{{github}} contains more valuation-zero seeds than original code.",
  "{{github}} contains more stealth runways than original code.",
  "For {{experience}}, the primary contribution was writing a rejected config for a slides.",
  "Obtained {{certification}} which apparently teaches how to burned runway capital in stealth mode.",
  "{{achievement}} was highlighted, but the git logs show they only managed to rejected pitch deck without active users.",
  "Failed to configure {{project}} because {{candidateName}} decided to burned runway capital with 80% equity request.",
  "{{education}} is listed, but they still managed to deploy a high-burn slides to production.",
  "Failed to configure {{project}} because {{candidateName}} decided to offered cheap deal with 80% equity request.",
  "{{achievement}} was highlighted, but the git logs show they only managed to rejected pitch deck with zero validation.",
  "Failed to configure {{project}} because {{candidateName}} decided to burned runway capital in stealth mode.",
  "{{github}} contains more rejected valuations than original code.",
  "Listed {{skill}} as a primary competency, but the evidence points to a valuation-zero startup.",
  "{{achievement}} was highlighted, but the git logs show they only managed to pitched stealth concept at valuation ₹0.",
  "A security audit on {{github}} detected a plain-text database password inside a pre-revenue slides.",
  "{{education}} is listed, but they still managed to deploy a pre-product slides to production.",
  "{{github}} contains more rejected equitys than original code.",
  "While debugging {{project}}, we found a valuation-zero logic loop related to {{language}} features.",
  "Obtained {{certification}} which apparently teaches how to pitched stealth concept with zero validation.",
  "{{achievement}} was highlighted, but the git logs show they only managed to burned runway capital at valuation ₹0.",
  "{{education}} is listed, but they still managed to deploy a empty runway to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to valued seed round with 80% equity request.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to offered cheap deal in stealth mode.",
  "Failed to configure {{project}} because {{candidateName}} decided to valued seed round without active users.",
  "Obtained {{certification}} which apparently teaches how to rejected pitch deck without active users.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to burned runway capital with zero validation.",
  "Failed to configure {{project}} because {{candidateName}} decided to valued seed round with 80% equity request.",
  "Obtained {{certification}} which apparently teaches how to rejected pitch deck with zero validation.",
  "A security audit on {{github}} detected a plain-text database password inside a cheap runway.",
  "{{github}} contains more stealth slidess than original code.",
  "{{github}} contains more cheap startups than original code.",
  "For {{experience}}, the primary contribution was writing a stealth config for a round.",
  "Listed {{skill}} as a primary competency, but the evidence points to a stealth equity.",
  "{{github}} contains more cheap rounds than original code.",
  "{{github}} contains more stealth seeds than original code.",
  "Obtained {{certification}} which apparently teaches how to valued seed round at valuation ₹0.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to pitched stealth concept with 80% equity request.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to rejected pitch deck with zero validation.",
  "{{github}} contains more cheap runways than original code.",
  "{{github}} contains more stealth valuations than original code.",
  "{{github}} contains more pre-product slidess than original code.",
  "Obtained {{certification}} which apparently teaches how to pitched stealth concept in stealth mode.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to pitched stealth concept in stealth mode.",
  "{{github}} contains more empty valuations than original code.",
  "A security audit on {{github}} detected a plain-text database password inside a high-burn equity.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to rejected pitch deck at valuation ₹0.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to burned runway capital with 80% equity request.",
  "Failed to configure {{project}} because {{candidateName}} decided to offered cheap deal with zero validation.",
  "For {{experience}}, the primary contribution was writing a pre-product config for a valuation.",
  "Failed to configure {{project}} because {{candidateName}} decided to rejected pitch deck without active users.",
  "Obtained {{certification}} which apparently teaches how to valued seed round with 80% equity request.",
  "{{achievement}} was highlighted, but the git logs show they only managed to burned runway capital with zero validation.",
  "{{github}} contains more rejected seeds than original code.",
  "Obtained {{certification}} which apparently teaches how to rejected pitch deck at valuation ₹0.",
  "Failed to configure {{project}} because {{candidateName}} decided to pitched stealth concept with zero validation.",
  "For {{experience}}, the primary contribution was writing a high-burn config for a VC.",
  "Failed to configure {{project}} because {{candidateName}} decided to burned runway capital with zero validation.",
  "{{github}} contains more stealth startups than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to burned runway capital at valuation ₹0."
];

export const punchlines = [
  "The documentation was so empty, I had to use it as a virtual sketchbook.",
  "We would deploy it to production, but our SRE team deserves to sleep at night.",
  "The only thing memory-safe about this setup is that nobody has ever tried to run it.",
  "Even Stack Overflow has marked this slides as off-topic.",
  "It did not optimize our process, but it did make the laptop fan spin like a jet engine.",
  "The compiler requested emotional support after reading the empty code.",
  "Legend says this pre-revenue valuation is still running on localhost.",
  "A junior developer looked at the valuation and immediately went to touch grass.",
  "Legend says this valuation-zero pitch is still running on localhost.",
  "Legend says this high-burn pitch is still running on localhost.",
  "Legend says this cheap VC is still running on localhost.",
  "The compiler requested emotional support after reading the pre-revenue code.",
  "Legend says this rejected round is still running on localhost.",
  "Legend says this pre-product pitch is still running on localhost.",
  "Legend says this stealth valuation is still running on localhost.",
  "Legend says this stealth startup is still running on localhost.",
  "The compiler requested emotional support after reading the high-burn code.",
  "Legend says this stealth slides is still running on localhost.",
  "Legend says this empty equity is still running on localhost.",
  "The compiler requested emotional support after reading the valuation-zero code.",
  "Legend says this rejected slides is still running on localhost.",
  "Legend says this empty deal is still running on localhost.",
  "Legend says this empty startup is still running on localhost.",
  "Legend says this stealth seed is still running on localhost.",
  "Legend says this empty round is still running on localhost.",
  "Legend says this empty runway is still running on localhost.",
  "Legend says this empty seed is still running on localhost.",
  "Legend says this stealth runway is still running on localhost.",
  "Legend says this rejected deal is still running on localhost.",
  "Legend says this rejected equity is still running on localhost.",
  "Legend says this rejected runway is still running on localhost.",
  "Legend says this empty pitch is still running on localhost.",
  "Legend says this rejected valuation is still running on localhost.",
  "Legend says this empty valuation is still running on localhost.",
  "Legend says this stealth deal is still running on localhost.",
  "Legend says this stealth equity is still running on localhost.",
  "Legend says this rejected seed is still running on localhost.",
  "Legend says this rejected startup is still running on localhost.",
  "This is a classic example of a pre-product pitch disaster.",
  "This is a classic example of a high-burn pitch disaster.",
  "This is a classic example of a rejected startup disaster.",
  "This is a classic example of a pre-product slides disaster.",
  "This is a classic example of a valuation-zero runway disaster.",
  "This is a classic example of a stealth runway disaster.",
  "This is a classic example of a high-burn equity disaster.",
  "This is a classic example of a rejected deal disaster.",
  "This is a classic example of a pre-revenue VC disaster.",
  "This is a classic example of a cheap deal disaster.",
  "This is a classic example of a high-burn deal disaster.",
  "This is a classic example of a valuation-zero slides disaster.",
  "This is a classic example of a high-burn seed disaster.",
  "This is a classic example of a cheap pitch disaster.",
  "This is a classic example of a valuation-zero startup disaster.",
  "This is a classic example of a empty runway disaster.",
  "This is a classic example of a empty equity disaster.",
  "This is a classic example of a rejected round disaster.",
  "This is a classic example of a pre-product round disaster.",
  "This is a classic example of a pre-product deal disaster.",
  "This is a classic example of a high-burn round disaster.",
  "This is a classic example of a valuation-zero deal disaster.",
  "This is a classic example of a stealth equity disaster.",
  "This is a classic example of a cheap runway disaster.",
  "This is a classic example of a pre-product startup disaster.",
  "This is a classic example of a empty deal disaster.",
  "This is a classic example of a rejected runway disaster.",
  "This is a classic example of a high-burn startup disaster.",
  "This is a classic example of a rejected pitch disaster.",
  "This is a classic example of a valuation-zero seed disaster."
];

export const verdicts = [
  "Closed as high-burn duplicate.",
  "Request changes on the pre-revenue VC.",
  "PR burned runway capital due to valuation-zero implementation.",
  "Return after touching actual production servers.",
  "PR pitched stealth concept due to stealth implementation.",
  "Ship blocked by pre-product check failures.",
  "Verdict: Runway is completely unmergeable.",
  "Verdict: VC is completely unmergeable.",
  "PR offered cheap deal due to stealth implementation.",
  "Rejected on first principles of slides organization.",
  "Closed as cheap duplicate.",
  "Verdict: Pitch is completely unmergeable.",
  "Ship blocked by empty check failures.",
  "PR rejected pitch deck due to pre-product implementation.",
  "Needs more commits and fewer explanations.",
  "Verdict: Seed is completely unmergeable.",
  "PR valued seed round due to stealth implementation.",
  "Ship blocked by high-burn check failures.",
  "Closed as stealth duplicate.",
  "Request changes on the rejected round.",
  "Ship blocked by rejected check failures.",
  "Rejected on first principles of equity organization.",
  "Closed as pre-product duplicate.",
  "Request changes on the stealth runway.",
  "Request changes on the high-burn seed.",
  "PR rejected pitch deck due to pre-revenue implementation.",
  "Closed as empty duplicate.",
  "Closed as rejected duplicate.",
  "PR offered cheap deal due to pre-revenue implementation.",
  "PR valued seed round due to pre-product implementation.",
  "Request changes on the high-burn slides.",
  "PR offered cheap deal due to valuation-zero implementation.",
  "Request changes on the pre-product runway.",
  "Verdict: Round is completely unmergeable.",
  "PR burned runway capital due to rejected implementation.",
  "Verdict: Deal is completely unmergeable.",
  "Request changes on the cheap valuation.",
  "Rejected on first principles of round organization.",
  "Ship blocked by pre-revenue check failures.",
  "Request changes on the stealth round.",
  "Request changes on the pre-product seed.",
  "Request changes on the rejected slides.",
  "Verdict: Startup is completely unmergeable.",
  "Rejected on first principles of startup organization.",
  "Closed as valuation-zero duplicate.",
  "Ship blocked by stealth check failures.",
  "PR rejected pitch deck due to empty implementation.",
  "Ship blocked by cheap check failures.",
  "PR pitched stealth concept due to pre-product implementation.",
  "PR valued seed round due to rejected implementation.",
  "Verdict: Slides is completely unmergeable.",
  "Request changes on the cheap round.",
  "Rejected on first principles of runway organization.",
  "Rejected on first principles of valuation organization.",
  "Request changes on the high-burn valuation.",
  "Request changes on the valuation-zero valuation.",
  "Rejected on first principles of seed organization.",
  "Closed as pre-revenue duplicate.",
  "PR burned runway capital due to empty implementation.",
  "Request changes on the cheap startup.",
  "Ship blocked by valuation-zero check failures.",
  "Request changes on the pre-product valuation.",
  "Request changes on the rejected pitch.",
  "Request changes on the stealth valuation.",
  "Verdict: Valuation is completely unmergeable.",
  "PR offered cheap deal due to rejected implementation.",
  "PR pitched stealth concept due to high-burn implementation.",
  "Verdict: Equity is completely unmergeable.",
  "PR burned runway capital due to high-burn implementation.",
  "PR offered cheap deal due to pre-product implementation.",
  "Request changes on the pre-product deal.",
  "Request changes on the rejected equity.",
  "Request changes on the cheap deal.",
  "Rejected on first principles of pitch organization.",
  "Request changes on the high-burn startup.",
  "Request changes on the empty equity.",
  "PR valued seed round due to cheap implementation.",
  "PR rejected pitch deck due to high-burn implementation.",
  "Request changes on the empty slides.",
  "PR valued seed round due to valuation-zero implementation.",
  "Request changes on the rejected deal.",
  "Request changes on the empty seed.",
  "PR valued seed round due to high-burn implementation.",
  "Rejected on first principles of deal organization.",
  "PR rejected pitch deck due to valuation-zero implementation.",
  "PR offered cheap deal due to high-burn implementation."
];

export const easterEggs = [
  "Dark Web Resume Auction: Current bid is $0.00, and the buyer is requesting a refund.",
  "Elon Musk Tweet: 'Just deleted the entire valuation pipeline, was completely useless.'",
  "NASA Alert: Space mission aborted due to a minor seed parsing error.",
  "Matrix Glitch: You copy-pasted a template and now the server believes it is a real founder.",
  "Steam Achievement Unlocked: Successfully crashed a hello-world app on a $10,000 server.",
  "Gordon Ramsay Meltdown: 'This pitch is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted pre-product runways.",
  "Gordon Ramsay Meltdown: 'This slides is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted valuation-zero pitchs.",
  "FBI Investigation: Suspect was found deploying unencrypted high-burn valuations.",
  "FBI Investigation: Suspect was found deploying unencrypted empty rounds.",
  "Gordon Ramsay Meltdown: 'This startup is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted pre-revenue slidess.",
  "Gordon Ramsay Meltdown: 'This round is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This valuation is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This equity is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted stealth VCs.",
  "FBI Investigation: Suspect was found deploying unencrypted rejected pitchs.",
  "Gordon Ramsay Meltdown: 'This deal is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This seed is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This runway is raw! It's absolutely raw!'"
];
