// ES Module exports for yelp_rant roast format
export const titles = [
  "Expensive Menu Loop",
  "Waiter conflict detected",
  "Critical Menu failure",
  "Absolute Unstyled architecture",
  "Incident Report: Raw Waiter",
  "Bad Design Error",
  "Incident Report: Raw Page",
  "Raw Experience Loop",
  "Manager Not Found",
  "The Menu tragedy",
  "NullPointerPageException",
  "Food conflict detected",
  "Failed to compile: UI",
  "Critical UI failure",
  "Critical Site failure",
  "Absolute Generic architecture",
  "Incident Report: Unstyled Page",
  "The Manager tragedy",
  "The Waiter tragedy",
  "NullPointerFoodException",
  "Absolute Broken architecture",
  "Absolute Slow architecture",
  "Failed to compile: Page",
  "Absolute Bad architecture",
  "Service conflict detected",
  "Broken Experience Error",
  "Page Not Found",
  "Incident Report: Broken Food",
  "Terrible Food Error",
  "Terrible Manager Error",
  "Service Not Found",
  "Experience conflict detected",
  "The Design tragedy",
  "Critical Service failure",
  "Incident Report: Slow Manager",
  "Design Not Found",
  "Site conflict detected",
  "Slow Menu Error",
  "Bad Waiter Loop",
  "Generic Page Error",
  "Slow Experience Loop",
  "Manager conflict detected",
  "Unstyled Food Error",
  "Incident Report: Bad Waiter",
  "Failed to compile: Manager",
  "Failed to compile: Menu",
  "Terrible Experience Error",
  "Incident Report: Generic UI",
  "Critical Manager failure",
  "The Site tragedy",
  "Critical Food failure",
  "Page conflict detected",
  "Waiter Not Found",
  "Incident Report: Raw Design",
  "Raw Waiter Error",
  "Incident Report: Expensive Menu",
  "Raw Waiter Loop",
  "Critical Waiter failure",
  "Absolute Expensive architecture",
  "Broken Design Loop",
  "UI conflict detected",
  "Incident Report: Unstyled Manager",
  "NullPointerManagerException",
  "The UI tragedy",
  "Terrible Waiter Loop",
  "Absolute Raw architecture",
  "Incident Report: Raw Experience",
  "Incident Report: Broken Waiter",
  "Expensive UI Loop",
  "Bad UI Error",
  "The Service tragedy",
  "Critical Design failure",
  "Terrible UI Error",
  "NullPointerSiteException",
  "Incident Report: Terrible Food",
  "Broken Experience Loop",
  "Food Not Found",
  "Failed to compile: Experience",
  "Critical Page failure",
  "Failed to compile: Site",
  "Menu conflict detected",
  "Raw Design Loop",
  "Slow Page Error",
  "Incident Report: Bad Experience",
  "Failed to compile: Design",
  "NullPointerServiceException",
  "Slow Service Loop",
  "UI Not Found",
  "Design conflict detected",
  "Incident Report: Slow Design",
  "The Food tragedy",
  "Slow Food Loop",
  "Incident Report: Slow Waiter",
  "Expensive Site Loop",
  "NullPointerMenuException",
  "Experience Not Found",
  "NullPointerExperienceException",
  "Incident Report: Terrible Waiter",
  "Failed to compile: Service",
  "Incident Report: Unstyled Service"
];

export const openings = [
  "The team has initiated audit for the candidate's experience setup.",
  "Scanning candidate profile for unstyled sites...",
  "Recruiters reported a case of expensive site design.",
  "Scanning candidate profile for slow menus...",
  "Warning: System flagged an attempt to rated one star with zero rating.",
  "Recruiters reported a case of raw page design.",
  "A review was filed regarding a expensive UI.",
  "Warning: System flagged an attempt to comclaimed to manager never returning back.",
  "Alert: The candidate spent three months trying to rated one star after waiting forever.",
  "Alert: The candidate spent three months trying to rated one star never returning back.",
  "We checked the history and found a slow experience log.",
  "Scanning candidate profile for slow waiters...",
  "Warning: System flagged an attempt to waited one hour calling the owner.",
  "We checked the history and found a bad service log.",
  "We checked the history and found a broken UI log.",
  "Initial evaluation shows the developer decided to inspected raw layout never returning back.",
  "Initial evaluation shows the developer decided to rated one star ruining team sprint.",
  "A review was filed regarding a generic experience.",
  "Recruiters reported a case of unstyled experience design.",
  "A review was filed regarding a raw site.",
  "Warning: System flagged an attempt to waited one hour ruining team sprint.",
  "Scanning candidate profile for expensive managers...",
  "Recruiters reported a case of slow food design.",
  "Warning: System flagged an attempt to rated one star after waiting forever.",
  "Recruiters reported a case of unstyled page design.",
  "Initial evaluation shows the developer decided to served static assets with zero rating.",
  "Alert: The candidate spent three months trying to waited one hour with zero rating.",
  "Warning: System flagged an attempt to rated one star calling the owner.",
  "Recruiters reported a case of terrible UI design.",
  "A review was filed regarding a broken site.",
  "We checked the history and found a bad experience log.",
  "Recruiters reported a case of expensive service design.",
  "Scanning candidate profile for expensive designs...",
  "We checked the history and found a expensive service log.",
  "Warning: System flagged an attempt to comclaimed to manager ruining team sprint.",
  "Warning: System flagged an attempt to inspected raw layout ruining team sprint.",
  "Warning: System flagged an attempt to inspected raw layout after waiting forever.",
  "Recruiters reported a case of unstyled food design.",
  "Warning: System flagged an attempt to served static assets calling the owner.",
  "We checked the history and found a raw site log.",
  "A review was filed regarding a slow service.",
  "Initial evaluation shows the developer decided to waited one hour with zero rating.",
  "Alert: The candidate spent three months trying to comclaimed to manager after waiting forever.",
  "Initial evaluation shows the developer decided to served static assets never returning back.",
  "Initial evaluation shows the developer decided to rated one star calling the owner.",
  "Recruiters reported a case of expensive experience design.",
  "A review was filed regarding a raw menu.",
  "Initial evaluation shows the developer decided to comclaimed to manager calling the owner.",
  "We checked the history and found a bad menu log.",
  "Warning: System flagged an attempt to comclaimed to manager after waiting forever.",
  "A review was filed regarding a terrible manager.",
  "A review was filed regarding a slow waiter.",
  "Initial evaluation shows the developer decided to inspected raw layout ruining team sprint.",
  "Scanning candidate profile for bad menus...",
  "A review was filed regarding a terrible experience.",
  "Initial evaluation shows the developer decided to comclaimed to manager after waiting forever.",
  "Recruiters reported a case of generic food design.",
  "A review was filed regarding a generic food.",
  "Alert: The candidate spent three months trying to served static assets with zero rating.",
  "We checked the history and found a slow site log.",
  "Warning: System flagged an attempt to rated one star ruining team sprint.",
  "Recruiters reported a case of unstyled manager design.",
  "We checked the history and found a terrible waiter log.",
  "Initial evaluation shows the developer decided to rated one star never returning back.",
  "Recruiters reported a case of unstyled menu design.",
  "Scanning candidate profile for unstyled pages...",
  "Warning: System flagged an attempt to comclaimed to manager calling the owner.",
  "Recruiters reported a case of generic experience design.",
  "A review was filed regarding a slow design.",
  "Warning: System flagged an attempt to inspected raw layout never returning back.",
  "Alert: The candidate spent three months trying to served static assets ruining team sprint.",
  "Recruiters reported a case of slow waiter design.",
  "Scanning candidate profile for raw waiters...",
  "Scanning candidate profile for slow designs...",
  "A review was filed regarding a bad waiter.",
  "Recruiters reported a case of raw waiter design.",
  "Alert: The candidate spent three months trying to inspected raw layout calling the owner.",
  "Scanning candidate profile for slow services...",
  "Recruiters reported a case of bad manager design.",
  "Scanning candidate profile for expensive pages...",
  "We checked the history and found a slow manager log.",
  "We checked the history and found a unstyled site log.",
  "Warning: System flagged an attempt to served static assets ruining team sprint.",
  "Initial evaluation shows the developer decided to rated one star with zero rating.",
  "We checked the history and found a generic waiter log.",
  "Scanning candidate profile for generic menus...",
  "Scanning candidate profile for terrible managers..."
];

export const findings = [
  "For {{experience}}, the primary contribution was writing a unstyled config for a manager.",
  "{{candidateName}} has spent three weeks optimizing a page while completely ignoring {{missingSection}}.",
  "{{achievement}} was highlighted, but the git logs show they only managed to inspected raw layout with zero rating.",
  "{{education}} is listed, but they still managed to deploy a slow waiter to production.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to comclaimed to manager after waiting forever.",
  "{{github}} contains more bad waiters than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to rated one star after waiting forever.",
  "A security audit on {{github}} detected a plain-text database password inside a expensive menu.",
  "For {{experience}}, the primary contribution was writing a broken config for a design.",
  "{{education}} is listed, but they still managed to deploy a unstyled menu to production.",
  "Obtained {{certification}} which apparently teaches how to rated one star with zero rating.",
  "A security audit on {{github}} detected a plain-text database password inside a terrible waiter.",
  "Failed to configure {{project}} because {{candidateName}} decided to rated one star ruining team sprint.",
  "Failed to configure {{project}} because {{candidateName}} decided to waited one hour with zero rating.",
  "A security audit on {{github}} detected a plain-text database password inside a broken service.",
  "Obtained {{certification}} which apparently teaches how to waited one hour ruining team sprint.",
  "The candidate claims {{framework}} experience, but their repository is just a broken clone that has been abandoned.",
  "Listed {{skill}} as a primary competency, but the evidence points to a slow service.",
  "A security audit on {{github}} detected a plain-text database password inside a unstyled UI.",
  "A security audit on {{github}} detected a plain-text database password inside a raw page.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to rated one star ruining team sprint.",
  "Listed {{skill}} as a primary competency, but the evidence points to a terrible menu.",
  "{{education}} is listed, but they still managed to deploy a broken page to production.",
  "For {{experience}}, the primary contribution was writing a bad config for a site.",
  "Listed {{skill}} as a primary competency, but the evidence points to a bad waiter.",
  "For {{experience}}, the primary contribution was writing a slow config for a menu.",
  "{{github}} contains more unstyled experiences than original code.",
  "While debugging {{project}}, we found a slow logic loop related to {{language}} features.",
  "Obtained {{certification}} which apparently teaches how to rated one star after waiting forever.",
  "For {{experience}}, the primary contribution was writing a raw config for a service.",
  "Failed to configure {{project}} because {{candidateName}} decided to waited one hour calling the owner.",
  "Obtained {{certification}} which apparently teaches how to inspected raw layout after waiting forever.",
  "{{github}} contains more bad designs than original code.",
  "Obtained {{certification}} which apparently teaches how to inspected raw layout ruining team sprint.",
  "Failed to configure {{project}} because {{candidateName}} decided to served static assets calling the owner.",
  "A security audit on {{github}} detected a plain-text database password inside a generic site.",
  "Obtained {{certification}} which apparently teaches how to comclaimed to manager after waiting forever.",
  "Failed to configure {{project}} because {{candidateName}} decided to served static assets with zero rating.",
  "Failed to configure {{project}} because {{candidateName}} decided to inspected raw layout ruining team sprint.",
  "{{github}} contains more raw foods than original code.",
  "Listed {{skill}} as a primary competency, but the evidence points to a broken experience.",
  "Obtained {{certification}} which apparently teaches how to served static assets never returning back.",
  "Failed to configure {{project}} because {{candidateName}} decided to comclaimed to manager never returning back.",
  "Listed {{skill}} as a primary competency, but the evidence points to a raw food.",
  "A security audit on {{github}} detected a plain-text database password inside a bad food.",
  "Obtained {{certification}} which apparently teaches how to waited one hour after waiting forever.",
  "{{education}} is listed, but they still managed to deploy a expensive service to production.",
  "{{achievement}} was highlighted, but the git logs show they only managed to rated one star never returning back.",
  "{{github}} contains more expensive experiences than original code.",
  "{{github}} contains more slow managers than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to rated one star after waiting forever.",
  "{{education}} is listed, but they still managed to deploy a generic site to production.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to served static assets with zero rating.",
  "{{achievement}} was highlighted, but the git logs show they only managed to comclaimed to manager after waiting forever.",
  "Failed to configure {{project}} because {{candidateName}} decided to rated one star calling the owner.",
  "{{achievement}} was highlighted, but the git logs show they only managed to waited one hour ruining team sprint.",
  "For {{experience}}, the primary contribution was writing a terrible config for a food.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to waited one hour calling the owner.",
  "{{achievement}} was highlighted, but the git logs show they only managed to served static assets calling the owner.",
  "{{github}} contains more expensive UIs than original code.",
  "{{github}} contains more generic menus than original code.",
  "Obtained {{certification}} which apparently teaches how to rated one star never returning back.",
  "{{achievement}} was highlighted, but the git logs show they only managed to served static assets never returning back.",
  "{{github}} contains more expensive waiters than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to inspected raw layout ruining team sprint.",
  "{{github}} contains more raw menus than original code.",
  "Obtained {{certification}} which apparently teaches how to rated one star ruining team sprint.",
  "{{achievement}} was highlighted, but the git logs show they only managed to inspected raw layout ruining team sprint.",
  "{{github}} contains more broken services than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to comclaimed to manager with zero rating.",
  "Obtained {{certification}} which apparently teaches how to served static assets after waiting forever.",
  "Failed to configure {{project}} because {{candidateName}} decided to inspected raw layout after waiting forever.",
  "Failed to configure {{project}} because {{candidateName}} decided to served static assets after waiting forever.",
  "{{achievement}} was highlighted, but the git logs show they only managed to comclaimed to manager calling the owner.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to waited one hour ruining team sprint.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to rated one star never returning back.",
  "{{github}} contains more unstyled designs than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to waited one hour calling the owner.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to inspected raw layout with zero rating.",
  "Failed to configure {{project}} because {{candidateName}} decided to waited one hour never returning back.",
  "Obtained {{certification}} which apparently teaches how to rated one star calling the owner.",
  "{{education}} is listed, but they still managed to deploy a terrible experience to production.",
  "{{github}} contains more expensive foods than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to waited one hour after waiting forever.",
  "Failed to configure {{project}} because {{candidateName}} decided to comclaimed to manager ruining team sprint.",
  "{{achievement}} was highlighted, but the git logs show they only managed to rated one star calling the owner.",
  "{{achievement}} was highlighted, but the git logs show they only managed to waited one hour never returning back.",
  "{{github}} contains more slow services than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to comclaimed to manager ruining team sprint.",
  "{{github}} contains more terrible menus than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to rated one star with zero rating.",
  "Obtained {{certification}} which apparently teaches how to waited one hour with zero rating.",
  "Failed to configure {{project}} because {{candidateName}} decided to rated one star with zero rating.",
  "{{github}} contains more broken pages than original code.",
  "{{github}} contains more generic managers than original code.",
  "{{github}} contains more unstyled foods than original code.",
  "Failed to configure {{project}} because {{candidateName}} decided to waited one hour ruining team sprint.",
  "{{github}} contains more slow pages than original code.",
  "Obtained {{certification}} which apparently teaches how to inspected raw layout calling the owner.",
  "Obtained {{certification}} which apparently teaches how to waited one hour never returning back.",
  "{{achievement}} was highlighted, but the git logs show they only managed to inspected raw layout after waiting forever.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to comclaimed to manager calling the owner.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to served static assets after waiting forever.",
  "{{github}} contains more bad menus than original code.",
  "{{achievement}} was highlighted, but the git logs show they only managed to waited one hour with zero rating.",
  "{{github}} contains more terrible foods than original code.",
  "Listed {{skill}} as a primary competency, but the evidence points to a expensive page.",
  "Failed to configure {{project}} because {{candidateName}} decided to served static assets never returning back.",
  "{{achievement}} was highlighted, but the git logs show they only managed to served static assets ruining team sprint.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to inspected raw layout never returning back.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to inspected raw layout calling the owner.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to waited one hour with zero rating.",
  "{{github}} contains more unstyled waiters than original code.",
  "The resume completely lacks {{missingSection}}, probably because they were busy trying to waited one hour never returning back.",
  "Obtained {{certification}} which apparently teaches how to comclaimed to manager calling the owner.",
  "{{github}} contains more broken experiences than original code."
];

export const punchlines = [
  "We would deploy it to production, but our SRE team deserves to sleep at night.",
  "The documentation was so empty, I had to use it as a virtual sketchbook.",
  "It did not optimize our process, but it did make the laptop fan spin like a jet engine.",
  "A junior developer looked at the waiter and immediately went to touch grass.",
  "The compiler requested emotional support after reading the slow code.",
  "The only thing memory-safe about this setup is that nobody has ever tried to run it.",
  "Legend says this bad page is still running on localhost.",
  "Legend says this slow manager is still running on localhost.",
  "Even Stack Overflow has marked this manager as off-topic.",
  "Legend says this expensive service is still running on localhost.",
  "Legend says this generic food is still running on localhost.",
  "Legend says this raw UI is still running on localhost.",
  "Legend says this broken waiter is still running on localhost.",
  "Legend says this expensive page is still running on localhost.",
  "Legend says this unstyled experience is still running on localhost.",
  "Legend says this slow experience is still running on localhost.",
  "Legend says this expensive site is still running on localhost.",
  "Legend says this terrible UI is still running on localhost.",
  "Legend says this generic menu is still running on localhost.",
  "Legend says this unstyled manager is still running on localhost.",
  "Legend says this bad design is still running on localhost.",
  "Legend says this expensive waiter is still running on localhost.",
  "Legend says this unstyled waiter is still running on localhost.",
  "Legend says this expensive manager is still running on localhost.",
  "Legend says this broken manager is still running on localhost.",
  "Legend says this unstyled site is still running on localhost.",
  "Legend says this slow page is still running on localhost.",
  "Legend says this slow service is still running on localhost.",
  "Legend says this unstyled design is still running on localhost.",
  "Legend says this generic waiter is still running on localhost.",
  "Legend says this unstyled menu is still running on localhost.",
  "Legend says this broken menu is still running on localhost.",
  "Legend says this expensive design is still running on localhost.",
  "Legend says this slow site is still running on localhost.",
  "Legend says this bad manager is still running on localhost.",
  "Legend says this expensive experience is still running on localhost.",
  "Legend says this broken service is still running on localhost.",
  "Legend says this unstyled food is still running on localhost.",
  "Legend says this bad waiter is still running on localhost.",
  "Legend says this bad site is still running on localhost.",
  "Legend says this bad food is still running on localhost.",
  "Legend says this generic manager is still running on localhost.",
  "Legend says this expensive food is still running on localhost.",
  "Legend says this generic design is still running on localhost.",
  "Legend says this broken design is still running on localhost.",
  "Legend says this generic service is still running on localhost.",
  "Legend says this broken page is still running on localhost.",
  "Legend says this slow design is still running on localhost.",
  "Legend says this bad service is still running on localhost.",
  "Legend says this expensive menu is still running on localhost.",
  "Legend says this broken site is still running on localhost.",
  "Legend says this unstyled page is still running on localhost.",
  "Legend says this broken experience is still running on localhost.",
  "Legend says this generic page is still running on localhost.",
  "Legend says this generic site is still running on localhost.",
  "Legend says this slow menu is still running on localhost.",
  "Legend says this generic experience is still running on localhost.",
  "This is a classic example of a bad food disaster.",
  "This is a classic example of a unstyled experience disaster.",
  "This is a classic example of a generic site disaster.",
  "This is a classic example of a broken menu disaster.",
  "This is a classic example of a terrible UI disaster.",
  "This is a classic example of a bad experience disaster.",
  "This is a classic example of a bad page disaster.",
  "This is a classic example of a slow site disaster.",
  "This is a classic example of a raw service disaster.",
  "This is a classic example of a bad menu disaster.",
  "This is a classic example of a raw site disaster.",
  "This is a classic example of a generic waiter disaster.",
  "This is a classic example of a generic manager disaster.",
  "This is a classic example of a unstyled page disaster.",
  "This is a classic example of a unstyled waiter disaster.",
  "This is a classic example of a slow page disaster.",
  "This is a classic example of a unstyled menu disaster.",
  "This is a classic example of a broken food disaster.",
  "This is a classic example of a broken design disaster.",
  "This is a classic example of a unstyled manager disaster.",
  "This is a classic example of a bad site disaster.",
  "This is a classic example of a bad waiter disaster.",
  "This is a classic example of a raw page disaster.",
  "This is a classic example of a slow waiter disaster.",
  "This is a classic example of a broken site disaster.",
  "This is a classic example of a expensive service disaster.",
  "This is a classic example of a slow manager disaster.",
  "This is a classic example of a unstyled food disaster.",
  "This is a classic example of a raw waiter disaster.",
  "This is a classic example of a generic experience disaster."
];

export const verdicts = [
  "Verdict: UI is completely unmergeable.",
  "Rejected on first principles of service organization.",
  "PR rated one star due to generic implementation.",
  "Needs more commits and fewer explanations.",
  "Return after touching actual production servers.",
  "Ship blocked by raw check failures.",
  "Ship blocked by broken check failures.",
  "Verdict: Waiter is completely unmergeable.",
  "Verdict: Menu is completely unmergeable.",
  "Ship blocked by slow check failures.",
  "PR waited one hour due to broken implementation.",
  "PR inspected raw layout due to raw implementation.",
  "Ship blocked by unstyled check failures.",
  "Verdict: Food is completely unmergeable.",
  "Request changes on the bad experience.",
  "Closed as expensive duplicate.",
  "Rejected on first principles of site organization.",
  "PR waited one hour due to unstyled implementation.",
  "Request changes on the slow experience.",
  "Request changes on the raw UI.",
  "PR served static assets due to terrible implementation.",
  "Verdict: Design is completely unmergeable.",
  "Closed as broken duplicate.",
  "Request changes on the terrible manager.",
  "Closed as terrible duplicate.",
  "Ship blocked by terrible check failures.",
  "Ship blocked by generic check failures.",
  "PR comclaimed to manager due to slow implementation.",
  "Rejected on first principles of page organization.",
  "Closed as raw duplicate.",
  "Rejected on first principles of waiter organization.",
  "Verdict: Page is completely unmergeable.",
  "Verdict: Service is completely unmergeable.",
  "Verdict: Site is completely unmergeable.",
  "Request changes on the expensive service.",
  "PR served static assets due to slow implementation.",
  "Request changes on the broken service.",
  "Closed as bad duplicate.",
  "Rejected on first principles of food organization.",
  "PR rated one star due to unstyled implementation.",
  "PR waited one hour due to generic implementation.",
  "Request changes on the unstyled manager.",
  "Request changes on the slow manager.",
  "Request changes on the bad service.",
  "Closed as slow duplicate.",
  "Closed as generic duplicate.",
  "Closed as unstyled duplicate.",
  "PR served static assets due to bad implementation.",
  "Verdict: Manager is completely unmergeable.",
  "Request changes on the expensive page.",
  "PR rated one star due to raw implementation.",
  "Request changes on the unstyled service.",
  "Request changes on the generic experience.",
  "Ship blocked by bad check failures.",
  "Ship blocked by expensive check failures.",
  "PR rated one star due to expensive implementation.",
  "PR served static assets due to generic implementation.",
  "Request changes on the unstyled menu.",
  "Rejected on first principles of manager organization.",
  "Request changes on the terrible page.",
  "Request changes on the terrible service.",
  "Request changes on the broken page.",
  "Rejected on first principles of design organization.",
  "PR rated one star due to slow implementation.",
  "Request changes on the expensive design.",
  "PR comclaimed to manager due to generic implementation.",
  "PR waited one hour due to bad implementation.",
  "PR comclaimed to manager due to bad implementation.",
  "Rejected on first principles of experience organization.",
  "Request changes on the broken waiter.",
  "PR comclaimed to manager due to broken implementation.",
  "Rejected on first principles of menu organization.",
  "Request changes on the terrible waiter.",
  "Request changes on the broken manager.",
  "Request changes on the expensive site.",
  "Request changes on the generic design.",
  "Request changes on the slow design.",
  "PR waited one hour due to raw implementation.",
  "Request changes on the terrible menu.",
  "Request changes on the unstyled site.",
  "PR waited one hour due to terrible implementation.",
  "Request changes on the slow food.",
  "PR served static assets due to broken implementation.",
  "Request changes on the expensive food.",
  "Verdict: Experience is completely unmergeable.",
  "Request changes on the broken menu.",
  "Request changes on the generic page.",
  "Request changes on the generic site.",
  "PR served static assets due to unstyled implementation.",
  "Request changes on the generic service.",
  "Request changes on the bad food."
];

export const easterEggs = [
  "NASA Alert: Space mission aborted due to a minor experience parsing error.",
  "Gordon Ramsay Meltdown: 'This food is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This experience is raw! It's absolutely raw!'",
  "Gordon Ramsay Meltdown: 'This site is raw! It's absolutely raw!'",
  "Steam Achievement Unlocked: Successfully crashed a hello-world app on a $10,000 server.",
  "Gordon Ramsay Meltdown: 'This service is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted terrible pages.",
  "Elon Musk Tweet: 'Just deleted the entire service pipeline, was completely useless.'",
  "Gordon Ramsay Meltdown: 'This manager is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted bad sites.",
  "Matrix Glitch: You copy-pasted a template and now the server believes it is a real founder.",
  "Gordon Ramsay Meltdown: 'This waiter is raw! It's absolutely raw!'",
  "Dark Web Resume Auction: Current bid is $0.00, and the buyer is requesting a refund.",
  "FBI Investigation: Suspect was found deploying unencrypted raw designs.",
  "FBI Investigation: Suspect was found deploying unencrypted slow waiters.",
  "Gordon Ramsay Meltdown: 'This menu is raw! It's absolutely raw!'",
  "FBI Investigation: Suspect was found deploying unencrypted expensive UIs.",
  "FBI Investigation: Suspect was found deploying unencrypted unstyled managers.",
  "FBI Investigation: Suspect was found deploying unencrypted broken foods.",
  "Gordon Ramsay Meltdown: 'This design is raw! It's absolutely raw!'"
];
